### ISSUE TITLE
latest build throws z/VM 6.3 into PROG004 crash when starting TCPIP

### ISSUE THREAD

**Issue by moshix** [SDL-Hercules-390/hyperion#134]
I am on Debian and Ubuntu Linux. 

I have a clean new install of z/VM 6.3 1701. Latest build of this repository. When I start TCPIP, z/VM goes into PROG004, reliably each time. 

I use hercules 3.13 works just fine and doesn't cause PROG004. 

Also, I discovered that my NUMA related problems disappear when using Hercules 3.13.

Thanks.

**Comment by ivan-w** [comment]
Please provide the z/VM DUMP file

**Comment by ivan-w** [comment]
Define a 3480 device, create a HET file, from OPERATNS do a DUMPLOAD and then dump the file in VMFPLC2 format to the HET file

**Comment by ivan-w** [comment]
Still waiting for more info (I can't reproduce this)

**Comment by ivan-w** [comment]
Moshe,

Please give your hercules config details and your FAL stack config so that I can see if I can reproduce it.

--Ivan

**Comment by moshix** [comment]
Sorry Ivan, I am traveling for work and only have my laptop with me. 

I know that with 3.13 I have not had any issues at all, but with Hyperion of this repository I have had all kinds of issues. I would say that something is seriously borked in this repository. 

I will get back to this at the end of next week. 

thanks a lot
