### ISSUE TITLE
Random Hercules crash ... while using Rexx?

### ISSUE THREAD

**Issue by Vf58** [SDL-Hercules-390/hyperion#139]
Hello

Hercules crashed and I suspect it is during Rexx execution.
My automation involve the use of a small Rexx which is used +/- 6 times a day on a daily basis.
I would say that 2 days on 3 Hercules crashed while executing the Rexx.
You will notice in the log Rexx executes 14 times(find "HHC01603I exec Mount#scr.rex") before crashing.

Please find dump & others informations in the zip file sended to the ftp server.

Thank you for your help

Ph.

**Comment by Fish-Git** [comment]
https://github.com/Fish-Git/AskForHelp

**Comment by Vf58** [comment]
Hi FIsh,

my apologies for my unclear explanations.
The dump and all the files specified in the attached $$readme.txt are resend now to 'incoming' folder of www.softdevlabs.com.
You will find print screen of Windows, Hercules level, license.

Sorry for the disagreement,

Philippe


[$readme.txt](https://github.com/SDL-Hercules-390/hyperion/files/2335062/readme.txt)

**Comment by Fish-Git** [comment]
FYI: Issue #140 ("Random Hercules crash using OORexx with HAO") was created by the user to replace this one.
