### ISSUE TITLE
Build failure on Mageia v6 X64

### ISSUE THREAD

**Issue by vbcoen** [SDL-Hercules-390/hyperion#144]
Using distro **Mageia v6 X86** with **gcc v5.5.0-1** and **clang v3.9.1** installed, the build fails after having built the extpkgs using the readme instructions for such and using scripting:

&nbsp;
util/bldlvlck:
```
OK      autoconf requires 2.64, found 2.69
OK      automake requires 1.9, found 1.15.1
OK      flex requires 2.5, found 2.6.1
OK      gawk requires 3.0, found 4.1.4
OK      gcc requires 3, found 5.5.0
OK      grep requires 1, found 3.0
OK      m4 requires 1.4.6, found 1.4.18
OK      make requires 3.79, found 4.1
OK      perl requires 5.6, found 5.22.3
OK      sed requires 3.02, found 4.2.2
```

&nbsp;
autogen.sh:
```
./configure --enable-extpkgs=extpkgs
make > build.log 2>build.err
```

&nbsp;
Contents of build.err: 
```
cckdutil.c: In function ‘cckd_chkdsk’:
cckdutil.c:1267:33: warning: operation on ‘empty_l2[i].L2_size’ may be undefined [-Wsequence-point]
             empty_l2[i].L2_size = empty_l2[i].L2_size = cdevhdr.nullfmt;
                                 ^
ckddasd.c: In function ‘ckddasd_init_handler’:
ckddasd.c:233:17: warning: variable ‘kw’ set but not used [-Wunused-but-set-variable]
 char           *kw = NULL;              /* Argument keyword          */
                 ^
ckddasd.c: In function ‘ckddasd_purge_cache’:
ckddasd.c:708:17: warning: variable ‘trk’ set but not used [-Wunused-but-set-variable]
 int             trk;                    /* Cached track              */
                 ^
In file included from hercules.h:62:0,
                 from dasdutil.c:17:
dasdutil.c: In function ‘data_dump’:
hmacros.h:137:30: warning: typedef ‘assertion_failed_dasdutil_c174’ locally defined but not used [-Wunused-local-typedefs]
 typedef char _CASSERT_PASTE( assertion_failed_ ## file, line )[ 2 * !!(cond) - 1 ]
                              ^
hmacros.h:135:41: note: in definition of macro ‘_CASSERT_PASTE’
 #define      _CASSERT_PASTE( a, b )     a ## b
                                         ^
hmacros.h:134:41: note: in expansion of macro ‘_CASSERT_LINE’
 #define       CASSERT( cond, file )     _CASSERT_LINE( cond, __LINE__, file )
                                         ^
dasdutil.c:174:5: note: in expansion of macro ‘CASSERT’
     CASSERT( MAX_DD == ROUND_UP( MAX_DD, DD_BPL ), dasdutil_c );
     ^
In file included from hercules.h:62:0,
                 from crypto.c:14:
crypto.c: In function ‘renew_wrapping_keys’:
hmacros.h:137:30: warning: typedef ‘assertion_failed_crypto_c390’ locally defined but not used [-Wunused-local-typedefs]
 typedef char _CASSERT_PASTE( assertion_failed_ ## file, line )[ 2 * !!(cond) - 1 ]
                              ^
hmacros.h:135:41: note: in definition of macro ‘_CASSERT_PASTE’
 #define      _CASSERT_PASTE( a, b )     a ## b
                                         ^
hmacros.h:134:41: note: in expansion of macro ‘_CASSERT_LINE’
 #define       CASSERT( cond, file )     _CASSERT_LINE( cond, __LINE__, file )
                                         ^
crypto.c:390:5: note: in expansion of macro ‘CASSERT’
     CASSERT( sizeof( sysblk.wkvpaes_reg ) >= sizeof( cpuid ) + sizeof( lparname ) + 1, crypto_c );
     ^
hmacros.h:137:30: warning: typedef ‘assertion_failed_crypto_c391’ locally defined but not used [-Wunused-local-typedefs]
 typedef char _CASSERT_PASTE( assertion_failed_ ## file, line )[ 2 * !!(cond) - 1 ]
                              ^
hmacros.h:135:41: note: in definition of macro ‘_CASSERT_PASTE’
 #define      _CASSERT_PASTE( a, b )     a ## b
                                         ^
hmacros.h:134:41: note: in expansion of macro ‘_CASSERT_LINE’
 #define       CASSERT( cond, file )     _CASSERT_LINE( cond, __LINE__, file )
                                         ^
crypto.c:391:5: note: in expansion of macro ‘CASSERT’
     CASSERT( sizeof( sysblk.wkvpdea_reg ) >= sizeof( cpuid ) + sizeof( lparname ) + 1, crypto_c );
     ^
gcc: error: extpkgs/lib/libcrypto64.a: No such file or directory
gcc: error: extpkgs/lib/libdecNumber64.a: No such file or directory
gcc: error: extpkgs/lib/libSoftFloat64.a: No such file or directory
gcc: error: extpkgs/lib/libtelnet64.a: No such file or directory
make[2]: *** [libherc.la] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

&nbsp;
&nbsp;
Contents of build.log:
```
make  all-recursive
make[1]: Entering directory '/home/vince/Installed-SW/hyperion-SDL-master'
Making all in m4
make[2]: Entering directory '/home/vince/Installed-SW/hyperion-SDL-master/m4'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/vince/Installed-SW/hyperion-SDL-master/m4'
Making all in util
make[2]: Entering directory '/home/vince/Installed-SW/hyperion-SDL-master/util'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/vince/Installed-SW/hyperion-SDL-master/util'
Making all in html
make[2]: Entering directory '/home/vince/Installed-SW/hyperion-SDL-master/html'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/vince/Installed-SW/hyperion-SDL-master/html'
Making all in man
make[2]: Entering directory '/home/vince/Installed-SW/hyperion-SDL-master/man'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/vince/Installed-SW/hyperion-SDL-master/man'
Making all in .
make[2]: Entering directory '/home/vince/Installed-SW/hyperion-SDL-master'
  CC       hsys.lo
  CCLD     libhercs.la
  CC       codepage.lo
  CC       hdl.lo
  CC       hexdumpe.lo
  CC       hostinfo.lo
  CC       hscutl.lo
  CC       hscutl2.lo
  CC       hsocket.lo
  CC       hthreads.lo
  CC       logger.lo
  CC       logmsg.lo
  CC       memrchr.lo
  CC       parser.lo
  CC       pttrace.lo
  CC       version.lo
  CC       ltdl.lo
  CCLD     libhercu.la
  CC       hetlib.lo
  CC       ftlib.lo
  CC       sllib.lo
  CCLD     libherct.la
  CC       cache.lo
  CC       cckddasd.lo
  CC       cckdutil.lo
  CC       ckddasd.lo
  CC       dasdtab.lo
  CC       dasdutil.lo
  CC       fbadasd.lo
  CC       shared.lo
  CCLD     libhercd.la
  CC       _archdep_templ.lo
  CC       archlvl.lo
  CC       assist.lo
  CC       bldcfg.lo
  CC       cgibin.lo
  CC       channel.lo
  CC       chsc.lo
  CC       clock.lo
  CC       cmdtab.lo
  CC       cmpsc_2012.lo
  CC       cmpscdbg.lo
  CC       cmpscdct.lo
  CC       cmpscget.lo
  CC       cmpscmem.lo
  CC       cmpscput.lo
  CC       config.lo
  CC       control.lo
  CC       cpu.lo
  CC       crypto.lo
  CC       dat.lo
  CC       decimal.lo
  CC       dfp.lo
  CC       diagmssf.lo
  CC       diagnose.lo
  CC       dyn76.lo
  CC       ecpsvm.lo
  CC       esame.lo
  CC       external.lo
  CC       facility.lo
  CC       fillfnam.lo
  CC       float.lo
  CC       general1.lo
  CC       general2.lo
  CC       general3.lo
  CC       hao.lo
  CC       hconsole.lo
  CC       hdiagf18.lo
  CC       history.lo
  CC       hRexx.lo
  CC       hRexx_o.lo
  CC       hRexx_r.lo
  CC       hsccmd.lo
  CC       hscemode.lo
  CC       hscloc.lo
  CC       hscmisc.lo
  CC       hscpufun.lo
  CC       httpserv.lo
  CC       ieee.lo
  CC       impl.lo
  CC       io.lo
  CC       ipl.lo
  CC       loadmem.lo
  CC       loadparm.lo
  CC       losc.lo
  CC       machchk.lo
  CC       opcode.lo
  CC       panel.lo
  CC       pfpo.lo
  CC       plo.lo
  CC       qdio.lo
  CC       scedasd.lo
  CC       scescsi.lo
  CC       script.lo
  CC       service.lo
  CC       sie.lo
  CC       sr.lo
  CC       stack.lo
  CC       strsignal.lo
  CC       timer.lo
  CC       trace.lo
  CC       transact.lo
  CC       vector.lo
  CC       vm.lo
  CC       vmd250.lo
  CC       xstore.lo
  CCLD     libherc.la

*** Warning: Linking the shared library libherc.la against the
*** static library extpkgs/lib/libcrypto64.a is not portable!

*** Warning: Linking the shared library libherc.la against the
*** static library extpkgs/lib/libdecNumber64.a is not portable!

*** Warning: Linking the shared library libherc.la against the
*** static library extpkgs/lib/libSoftFloat64.a is not portable!

*** Warning: Linking the shared library libherc.la against the
*** static library extpkgs/lib/libtelnet64.a is not portable!
Makefile:1712: recipe for target 'libherc.la' failed
make[2]: Leaving directory '/home/vince/Installed-SW/hyperion-SDL-master'
Makefile:2106: recipe for target 'all-recursive' failed
make[1]: Leaving directory '/home/vince/Installed-SW/hyperion-SDL-master'
Makefile:1529: recipe for target 'all' failed
```

&nbsp;
A serious improvement now that I found the notes for installing extpkgs.

Can I suggest that as you also maintain these extra elements, that they be included with the hyperion sources and a build script created to build them prior to building hyperion? Doing so would save a lot of heartache!

I realize that some of the o/p in the `build.err` log relates to unused fields, but that nevertheless might still be an issue.

Personally I do not like having _any_ warnings during a compile phase, but then again, I am old school too. (*)
___
(*) ok, _very_ old school, as I have got to 71 years!&nbsp;`;-)`

**Comment by Fish-Git** [comment]
Your CASSERT and other warning are likely due to the version of gcc/clang you are using. I'm using gcc 4.4.7 20120313 and clang 3.4.2 on my CentOS 6.10 x64 system (which are older than the versions you are using) and I'm not seeing any of the warnings you're seeing.

I'll see if maybe I can upgrade each of them to a newer version that is greater than or equal to the versions you're currently using so I can maybe come up with a way to either fix the warnging or suppress them somehow.

In the mean time however, ignore them; they're nothing to worry about.

&nbsp;
> *** Warning: Linking the shared library libherc.la against the
> *** static library extpkgs/lib/libcrypto64.a is not portable!

These can be safely ignored as well since all EXTPKGs are always built using -fPIC. I have not yet found a way to suppress/filter this warning.

&nbsp;
> gcc: error: extpkgs/lib/libcrypto64.a: No such file or directory
> gcc: error: extpkgs/lib/libdecNumber64.a: No such file or directory
> gcc: error: extpkgs/lib/libSoftFloat64.a: No such file or directory
> gcc: error: extpkgs/lib/libtelnet64.a: No such file or directory

This is the heart of your problem: Hercules is not finding any of the External Package static libraries that you presumably built. This is because you did not specify your --enable-extpkgs=DIR configure option correctly:
```
    ./configure --enable-extpkgs=extpkgs       # WRONG!
```
There is no 'extpkgs' directory in the Hercules source tree. Check your ./configure output. I'm certain you will find an error indicating that the 'extpkgs' directory was not found.

You probably _should_ have instead specified:
```
    ./configure  --enable-extpkgs=../extpkgs    # RIGHT!
```
 This is of course presuming your 'extpkgs' directory is at the same level as your Hercules source code (repo) directory.

When you specify a directory on your ./configure command, you need to take into consideration what your _current directory_ is. Otherwise it's best to specify an absolute directory instead, e.g.:
```
    ./configure  --enable-extpkgs=/home/vince/hercules/extpkgs
```
Personally, I prefer to define a permanent `LIBRARY_PATH` environment variable that points to my extpkgs/lib directory (e.g. /home/fish/hercules/extpkgs/lib). That way I don't need to specify any --enable-extpkgs=DIR option on my configure command at all (unless I want to override it).

Hercules looks in your '--enable-extpkgs=DIR' lib subdirectory first. That option overrides everything. If the '--enable-extpkgs=DIR' option is not specified, then it looks in each of the directories listed in your LIBRARY_PATH environment variable until it finds the static lib it's looking for. If it still can't find the static lib there, then it defaults to its own internal set of static libraries within its own source tree (i.e. the default static libs that come distributed with Hercules).

Fix your ./configure command and I'm sure your build will succeed this time (presuming all of your External Packages got built and installed correctly beforehand of course!).

&nbsp;
> Can I suggest that as you also maintain these extra elements, that they be included with the hyperion sources

They are!

But sometimes the provided default versions, for one reason or another, do not work on a given system, thereby requiring you to build them for yourself (so as to ensure they're compatible with your system).

> and a build script created to build them prior to building hyperion? Doing so would save a lot of heartache!

That is an _excellent_ idea, Vince! (Thank you) I'm working on it right now. I'll let you know when it's ready. You can be my first guinea pig!&nbsp;`;-)`

**Comment by vbcoen** [comment]
Hi;

Thanks,  now fixed the configure cmd line to :

./configure --enable-extpkgs=/home/vince/Installed-SW/hyperion-SDL-master/extpkgs

However there is still an issue - here is results of ls -la extpkgs and yes extpkgs along with repo and work is in the herc source dir.

```
[vince@applewood hyperion-SDL-master]$ ll /home/vince/Installed-SW/hyperion-SDL-master/extpkgs
total 1432
-rw-r--r-- 1 vince vince    4349 Aug  5 12:47 crypto.LICENSE.txt
-rw-r--r-- 1 vince vince    1416 Aug  5 12:47 crypto.README.txt
-rw-r--r-- 1 vince vince    2231 Aug  5 12:47 decnumber.ERRATA
-rw-r--r-- 1 vince vince    1977 Aug  5 12:47 decnumber.ICU-license.html
-rw-r--r-- 1 vince vince 1416382 Aug  5 12:47 decnumber.pdf
-rw-r--r-- 1 vince vince    2801 Aug  5 12:47 decnumber.readme.txt
drwxr-xr-x 2 vince vince    4096 Sep  1 16:34 doc/
drwxr-xr-x 2 vince vince    4096 Sep  1 16:34 include/
drwxr-xr-x 2 vince vince    4096 Sep  1 16:34 lib/
-rw-r--r-- 1 vince vince    1720 Aug  2 16:45 softfloat.LICENSE.txt
-rw-r--r-- 1 vince vince    1253 Aug  2 16:45 softfloat.README.html
-rw-r--r-- 1 vince vince     797 Aug  2 16:45 softfloat.README.txt

``` 

Next for lib :

```
ll /home/vince/Installed-SW/hyperion-SDL-master/extpkgs/lib
total 6280
-rw-r--r-- 1 vince vince  283636 Sep  1 16:33 libcryptomaster32.a
-rw-r--r-- 1 vince vince   89062 Sep  1 16:33 libcryptomaster32d.a
-rw-r--r-- 1 vince vince  161600 Sep  1 16:33 libcryptomaster64.a
-rw-r--r-- 1 vince vince   99984 Sep  1 16:33 libcryptomaster64d.a
-rw-r--r-- 1 vince vince  630808 Sep  1 16:34 libdecNumbermaster32.a
-rw-r--r-- 1 vince vince  414566 Sep  1 16:33 libdecNumbermaster32d.a
-rw-r--r-- 1 vince vince  933824 Sep  1 16:34 libdecNumbermaster64.a
-rw-r--r-- 1 vince vince  514712 Sep  1 16:34 libdecNumbermaster64d.a
-rw-r--r-- 1 vince vince  772220 Sep  1 16:34 libSoftFloatmaster32.a
-rw-r--r-- 1 vince vince  663896 Sep  1 16:34 libSoftFloatmaster32d.a
-rw-r--r-- 1 vince vince 1040124 Sep  1 16:34 libSoftFloatmaster64.a
-rw-r--r-- 1 vince vince  801276 Sep  1 16:34 libSoftFloatmaster64d.a

```

As you can see the lib name include 'master' within but compile is excluding this.

Note the name of the top level dir as hyperion-SDL-master (I added the 'SDL-' bit) to seperate it from the std hyperion sources.

From the repo dir :

```
/home/vince/Installed-SW/hyperion-SDL-master/repo
[vince@applewood repo]$ ls -la
total 1716
drwxr-xr-x  6 vince vince   4096 Sep  1 16:30 ./
drwxr-xr-x 24 vince vince  20480 Sep  4 15:22 ../
drwxr-xr-x  6 vince vince   4096 Sep  1 16:09 crypto-master/
-rw-rw-r--  1 vince vince  93493 Sep  1 16:06 crypto-master.zip
drwxr-xr-x  6 vince vince   4096 Aug  5 12:47 decNumber-master/
-rw-rw-r--  1 vince vince 819373 Sep  1 16:06 decNumber-master.zip
drwxr-xr-x  7 vince vince   4096 Aug  2 16:45 SoftFloat-master/
-rw-rw-r--  1 vince vince 716901 Sep  1 16:07 SoftFloat-master.zip
drwxr-xr-x  5 vince vince   4096 Aug  5 12:48 telnet-master/
-rw-rw-r--  1 vince vince  77278 Sep  1 16:07 telnet-master.zip

```

As you will notice all of the zip files as well as the pkgs dirs have '-master' but again the herc compile is NOT looking with that name extension.

Have me a feeling that grabbing the sources using the zip'd files for all was NOT a good idea?

Vince

**Comment by Fish-Git** [comment]
Your directory structure is rather confusing to me.

Please post the output of a `cd /home/vince/Installed-SW/hyperion-SDL-master && tree -d -o tree.txt` command. Thanks.

**Comment by Fish-Git** [comment]
> As requested:
> 
> * tree.txt

I don't suppose I could get you to do it again, but specifying the `-n` option this time?
```
   tree -d -n -o tree.txt
```
Thanks.

**Comment by Fish-Git** [comment]
Try this:
```
cd /home/vince/Installed-SW/hyperion-SDL-master

cd extpkgs
cd lib
rm *.a
cd ..
cd ..

cd work
rm -rf  crypto  decNumber  SoftFloat  telnet
mkdir   crypto  decNumber  SoftFloat  telnet

cd crypto
../../repo/crypto-master/build    --rebuild --pkgname . --all --install ../../extpkgs > crypto.log 2>&1
cd ..

cd decNumber
../../repo/decNumber-master/build --rebuild --pkgname . --all --install ../../extpkgs > decNumber.log 2>&1
cd ..

cd SoftFloat
../../repo/SoftFloat-master/build --rebuild --pkgname . --all --install ../../extpkgs > SoftFloat.log 2>&1
cd ..

cd telnet
../../repo/telnet-master/build    --rebuild --pkgname . --all --install ../../extpkgs > telnet.log 2>&1
cd ..
```

&nbsp;
Followed by:
```
cd /home/vince/Installed-SW/hyperion-SDL-master
./configure --enable-extpkgs=extpkgs   --other-options-here...   > configure.log 2>&1
make -j 4 > make.log 2>&1
```

&nbsp;
_**Note #&#8288;1:**_ adjust the above `./configure` command's options and the `make` command's options as needed/desired. My own system (VMware virtual machine) has 4 processors defined, thus I personally use `make -j 4` for faster builds.

_**Note #&#8288;2:**_ you will still get the same previously mentioned warnings during your build, _but ..._ your build _should_ succeed. That's all I'm interested in right now. I'll try to take care of the warnings later.

Please let me know if the above works okay for you.

**Comment by vbcoen** [comment]
I have now done as per your instructions with the results attached from make.log for which I notice a lot of static library not portable for all four ext libs multi times but it seems to have finished this time.
[make.log](https://github.com/SDL-Hercules-390/hyperion/files/2361237/make.log)

As well as I can see anyway.

Do you agree ?

Vincent

**Comment by Fish-Git** [comment]
> ... but it seems to have successfully finished this time (as best as I can tell anyway):
> 
> * make.log
> 
> Do you agree?

Yep! It looks good to me!

I'll try to see what I can do to maybe fix (or silence) the other warnings you're seeing, but that may take a while longer.

In the mean time however, it's looks like you are good to go!

I am going to close this issue as "Invalid (i.e. user-error) since it doesn't appear to be a bug in Hercules.
