### ISSUE TITLE
get rid of the HDL_USE_LIBTOOL ltdl.c ltdl.h

### ISSUE THREAD

**Issue by ghost** [SDL-Hercules-390/hyperion#146]
done, testing in progress, 
almost ready for a pull request
cheers
e

**Comment by ivan-w** [comment]
What the problem that needs solving ?

**Comment by herc4mac** [comment]
get rid of useless crap

**Comment by ivan-w** [comment]
You mean we now have to reinvent the wheel for every possible instance of dynamic loading while there are people more capable than us that know how to handle it ?

**Comment by Fish-Git** [comment]
I'm confused as well. What problem is libtool causing that compels you to conclude it's "useless crap"?

**Comment by Fish-Git** [comment]
It seems Enrico has gone away in a huff and deleted his github account so we cannot talk to him anymore. Sheesh. What is with that guy?&nbsp;`:(`

Marking issue as "Invalid" and closing.
