### ISSUE TITLE
Incorrect guest IP address on hercifc-created tun0 interface

### ISSUE THREAD

**Issue by RenaudGiot** [SDL-Hercules-390/hyperion#148]
The `tun0` network interface created by `hercifc` upon Hercules startup is showing an incorrect guest IP address.

Extract from the Hercules  configuration file:

    0E20-0E21   CTCI  -n /dev/tun0 10.0.0.70 10.0.0.5

Output of `ifconfig tun0` after Hercules startup:
```
tun0: flags=8851<UP,POINTOPOINT,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	inet 10.0.0.5 --> 129.255.255.255 netmask 0xff000000 
	open (pid 670)
```
The guest IP address is matching the one defined in the config file, but the host IP address is not!

As suggested by Peter Jansen, the problem can be circumvented by modifying the tun device after Hercules startup (but prior to IPL-ing the guest OS) by issuing a `sudo ifconfig guestip/8 hostip`

&nbsp;
Hercules version:

* Hercules version 4.0.0.0-SDL (4.0.0.0)

Build information:
```
Build date: Oct  9 2018 at 16:53:01
Built with: Apple Clang 10.0.0 (clang-1000.10.44.2)
Build type: Mac OS X x86_64 host architecture build
```

Host system:

* Mac OS X 10.14

Tun/Tap driver:

* tuntap_20150118 from: http://tuntaposx.sourceforge.net

**Comment by mcisho** [comment]
I've had a quick look at the source code for the mentioned tuntap driver and the only ioctl requests it supports to set tun or tap interface parameters are SIOCSIFFLAGS, SIOCSIFADDR and SIOCSIFMTU, plus SIOCSIFLLADDR for tap interfaces. All other set requests get an EOPNOTSUPP return code. Hence Hercules cannot set the guest IP address or the netmask, and Peters circumvention is the only solution, until the author improves the tuntap driver.

**Comment by Fish-Git** [comment]
> Hence Hercules cannot set the guest IP address or the netmask, and Peters circumvention is the only solution, until the author improves the tuntap driver.

Thank you for looking into this, Ian.

Given the results of your analysis I am going to go ahead and close this issue at this time.

When/IF Mac's tuntap driver is updated in the future to allow proper Hercules resolution of this problem, it can be re-opened at that time (or else a new Issue created).

Thanks again for your help.
