### ISSUE TITLE
LCS Checksum take 2 : LCS advertises ICMP checksum offload but doesn't actually calculate it

### ISSUE THREAD

**Issue by ivan-w** [SDL-Hercules-390/hyperion#153]
It's an issue in netsupp.[ch] - The ICMP case is not taken into account.

A correction is in the works (a little more complicated than TCP or UDP since ICMP has *TWO* checksums).

--Ivan

**Comment by mcisho** [comment]
Ivan, are you sure about this? How does LCS advertise ICMP checksum offload? I have never heard of checksum offload for ICMP, or any of the other minor protocols come to that, only for TCP and UDP.

**Comment by ivan-w** [comment]
Since the LCS outbound frame IP assist support is not documented, it's possible it doesn't support ICMP checksums (but I very much doubt it). But there is no reason not to support ICMP, ICMPv6 and others.. If we don't support any of these, then we don't support any of them or we support all of them...

**Comment by mcisho** [comment]
You've obviously got the bit between your teeth, but I think you're wasting your time. Except for the stack you are writing, there isn't a stack anywhere that expects an LCS to support checksum offload, for any protocol. Even IBM changed from LCS to CLAW when they added the support to the 3172 model 3.

The benefits of checksum offload have to outweigh the complexity added to the stack when the support is added. For TCP and UDP the benefit is no doubt measurable, for ICMP et al the benefit is so marginal no one has ever bothered to implement.

**Comment by mcisho** [comment]
My point was that when IBM added Offload support to the 3172 model 3, the host system that sent data to or received data from the 3172 no longer considered the 3172 to be an LCS, the host considered the 3172 to be a CLAW. Hence, I'm not quite sure I understand your point?

**Comment by ivan-w** [comment]
The LCS CCW protocol has provision for IP/UDP/TCP/ICMP checksum, TCP segmentation and multicast filtering offload.

The X'B2' command/response frame indicates which of those are available and/or enabled.

If the LCS reports it supports such and such offload feature, then it should implement them correctly.

LCS offload may be something implemented by something else than a 3172 running ICP Lan Gateway.

LCS is not necessarily a 3172 (although LCS is provided by a 3172 running ICP as a LAN Gateway), and LCS is not CLAW, and CLAW is not always a 3172 !

**Comment by ivan-w** [comment]
The way I understand it, the 3172 running offload basically handles the entire TCP/IP stack and uses CLAW to communicate.. The Offload server is basically a socket proxy server, offloading the ENTIRE stack on a workstation.

Found this guy : http://www.danzig.jct.ac.il/tcp-ip-lab/ibm-tutorial/3376c51.html#3172

--Ivan

**Comment by ivan-w** [comment]
Closed by https://github.com/SDL-Hercules-390/hyperion/commit/ccabc1082f4a0c8bbfa40e1062cb155e3200e51c

**Comment by mcisho** [comment]
I agree with all that you say. However, I still contend that there is not, and never has been, an LCS that supports any kind of offload.

**Comment by ivan-w** [comment]
Now there is one ! (Didn't the Cisco implementation of LCS support it ?)

**Comment by ivan-w** [comment]
Actually, the 3172 LCS at least supported the multicast filtering offload for IGMP support.
