### ISSUE TITLE
Not getting Console after NIP

### ISSUE THREAD

**Issue by Rakeshreddy11** [SDL-Hercules-390/hyperion#155]
I am using Hyperion(Hercules-4.0.0-rc0-win-x64)

I am using Mocha TN3270 emulator. As soon as i load the OS, the NIP console comes up. So far good.

But once NIP messages finished, i am getting the VTAM logon screen, not the Console.

I used to get Console after NIP messages when i used Mocha TN3270 with other Hercules product.

Any one facing thing issue? please help.

**Comment by Fish-Git** [comment]
> I am using Hyperion (Hercules-4.0.0-rc0-win-x64)

Then you are posting your question to the wrong forum.

As I already explained in my offline email reply to you:

> That is NOT my product.  That is someone else's product, not mine.
> 
> The "Hercules-4.0.0-rc0-win-x64" product is a VERY OLD (Dec 16, 2016) version of the abandoned (very dead) Hercules 4.0 Hyperion product, which no one is currently working on.
> 
> MY product is the "SDL" version of Hercules 4.1 Hyperion, which is very much alive (very active, i.e. there are many developers working on it) and is the most current version of Hercules in existence.  You can download it from either of the following URLs:

* https://github.com/SDL-Hercules-390/hyperion/releases
* http://www.softdevlabs.com/hyperion#prebuilt
