### ISSUE TITLE
SDL Latest with CCKD64 z/VM often fails and Hercules freezes

### ISSUE THREAD

**Issue by moshix** [SDL-Hercules-390/hyperion#158]
Fish, Ivan

Ok, I am getting a problem I didn't see in a long time with z/VM 6.2. I am sending you both an email with the screen shot.

This time SDL latest completely freezes. I can't even switch from log view to hardware console view. Only kill -9 helps.

Thanks.

M

I managed to extract only the below log information from Hercules. I could be wrong, but looks like an SIE problem to me.

```
11:28:51 HCPDMP908I SYSTEM FAILURE ON CPU 0001, CODE - IFI004 +
11:28:51 HCPDMP908I 2018-12-08 SYSTEM ZVM62
11:28:54 HCPDMP9252I DUMPING TO DASD
11:29:07 HCPDMP9260I 25% OF THE DUMP HAS BEEN COMPLETED
11:29:13 HCPDMP9260I 50% OF THE DUMP HAS BEEN COMPLETED
11:29:21 HCPDMP9260I 75% OF THE DUMP HAS BEEN COMPLETED
11:29:25 HCPDMP9261I DUMP COMPLETE ON 2018-12-08, CODE IFI004
11:29:25 HCPWRP963I SHUTDOWN STEP CKPSH - TAKE A CHECKPOINT
11:29:25 HCPWRP963I SHUTDOWN STEP OPRCK - SAVE OPERATOR CONSOLE LIST
11:29:26 HCPWRP963I SHUTDOWN STEP MCWMD - DETERMINE MACHINE CHECK STATUS
11:29:26 HCPWRP963I SHUTDOWN STEP SDVRS - RESET IBM DASD CU CHARACTERISTICS
11:29:27 HCPWRP963I SHUTDOWN STEP SGQXX - RESET OTHER PROCESSORS
HHC00814I Processor CP01: SIGP CPU reset (0C) CP00, PARM 0000000000346E40: CC 0
11:29:27 HCPWRP9277I SYSTEM TERMINATION COMPLETE, ATTEMPTING RESTART
11:29:27 HCPWRP9277I 2018-12-08 SYSTEM ZVM62
11:29:27 HCPWRP963I SHUTDOWN STEP SVADV - DEACTIVATE TERMINATION SAVE AREAS
HHC00814I Processor CP01: SIGP Set architecture mode (12) CP01, PARM 0000000000000000: CC 0
HHC00811I Processor CP01: architecture mode ESA/390
HHC00814I Processor CP01: SIGP Set architecture mode (12) CP01, PARM 00000001: CC 0
HHC00811I Processor CP01: architecture mode z/Arch
HHC00814I Processor CP01: SIGP Initial CPU reset (0B) CP00, PARM 0000000000000000: CC 0
HHC00814I Processor CP01: SIGP Set prefix (0D) CP00, PARM 00000000009BA000: CC 0
HHC00814I Processor CP01: SIGP Initial CPU reset (0B) CP00, PARM 000000000000E658: CC 0
HHC00814I Processor CP01: SIGP Set prefix (0D) CP00, PARM 00000000009BA000: CC 0
HHC00814I Processor CP01: SIGP Restart (06) CP00, PARM 00000000000E43F8: CC 0
HHC00814I Processor CP01: SIGP Restart (06) CP00, PARM 0000000000075410: CC 2
HHC00814I Processor CP00: SIGP Stop (05) CP00, PARM 0000000000000000: CC 0
HHC00814I Processor CP01: SIGP Restart (06) CP00, PARM 0000000000075410: CC 0
HHC00004I Control program identification: type VM, name ZVM62, sysplex , level 2006110100000000
HHC00004I Control program identification: type VM, name ZVM62, sysplex , level 2006110101000000
HHC00822I Processor IE00: machine check due to host error: User defined signal 1
HHC02324I SIE: CP00: PSW=0404400180000000 0000000001880FB0 INST=E350D3980004 LG 5,920(0,13) lo
HHC02326I SIE: CP00: V:0000000002342908:A:0000000125911908:K:0E=00000000 02342400 00000000 00FC0380 .......
HHC02269I CP00: R0=000000003F11E010 R1=FFFFFFFFFFFFF000
HHC02269I CP00: R2=00000000019DD538 R3=000000003F00E000
HHC02269I CP00: R4=0000000000FC4780 R5=0000000002342400
HHC02269I CP00: R6=00000000019B8110 R7=00000000019DD538
HHC02269I CP00: R8=00000000019B7718 R9=00000000023A7000
HHC02269I CP00: RA=0000000000000000 RB=000000007F7FB118
HHC02269I CP00: RC=00000000018820C0 RD=0000000002342570
HHC02269I CP00: RE=0000000000FC0380 RF=00000000023A7000
HHC00814I Processor CP00: SIGP CPU reset (0C) CP00, PARM 000000000000E000: CC 0
HHC00814I Processor CP01: SIGP CPU reset (0C) CP00, PARM 0000000000346E40: CC 0
HHC00101I Thread id 00007f8afff7c700, prio 2, name 'Processor CP00' ended
```

**Comment by moshix** [comment]
Ivan

As requested some dump analysis data:

z/VM Version 6 Release 2.0, service level 1101 (CP 64-BIT)                     
Generated at 11/02/11 18:54:31.000000, IPLd at 12/08/18 11:14:24.224344        
Date 12/08/18 Time 11:28:51.466778                                             
                                                                               
CPUID = 001132EF 20970000                                                      
                                                                               
CPU address is 0001    Prefix register is 009BC000   (failing)                 
CPU address is 0000    Prefix register is 00032000                             
7FB21780 11:28:51  IFI004 Hard Abend svc 00 at HCPIFI+19F4                     
                   opsw 04040000_001D1084 svcilc 0002                          
                                                                               
Summary of CP exits                                                            
      0 Pre-defined exits found                                                
      0 Dynamic exits found                                                    
      0 Diagnose exits found                                                   
                                                                               
IFI004 HCPIFIIN was attempting to do one of the following: 1) Transfer control 
       to the interrupt response address specified in the IORBK field IORIRA,  
       but it contained zeros. 2) Call the emergency error recovery procedure, 
       but was unable to resolve its address.    



>>> symptom                                                               
Symptom Record for Incident D559582E 0561ASYM                             
                                                                          
TOD Clock . . D559582E0561A026         Date. . . . . 12/08/18             
Time Zone . . -05.00.00                Time. . . . . 11:28:51.466778      
CPU model . . 2097                     Base SCP. . . 5741                 
CPU Serial. . 1132EF                   NodeID. . . . ZVM62                
Dump Name . . SIEPROB DUMP0001 A1      Dump Type . . CPDUMP               
Comp ID . . . 5741A07                  Ver/Rel/Mod . V06R02M0             
Dump format . 64-BIT                                                      
------------------------------------------------------------              
Primary Symptom Strings                                                   
              PIDS/5741A0702           (Component ID)                     
              AB/SIFI004               (Abend Code)                       
              RIDS/IFI                 (Failing Module)                   
              REGS/FFFFF               (Register/PSW Info)                
------------------------------------------------------------              
Section 5 Data:                                                           
              USERID DUMPED: SYSTEM                                       
              DUMP RECEIVER: OPERATNS                                     
              SPOOLID: 0004                                               
------------------------------------------------------------              
Last trace entry on abending processor                                    
7FB21780 11:28:51  IFI004 Hard Abend svc 00 at HCPIFI+19F4                
                   opsw 04040000_001D1084 svcilc 0002                     

>>> lasttran                                                         
Analysis of  00000000_00895304 translated on ASCE 00000000_0000A007  
Table type Table address     + displ  contains                       
---------- ----------------- -------- -----------------              
Region 1st (not applicable)                                          
Region 2nd (not applicable)                                          
Region 3rd 00000000_0000A000 00000000 00000000_80000007              
Segment    00000000_80000000 00000040 00000000_8000F000              
Page       00000000_8000F000 000004A8 00000000_00895000              
           (translation was successful)                              

>>> trace for 1                                                                     
7FB21780 11:28:51  IFI004 Hard Abend svc 00 at HCPIFI+19F4 opsw 04040000_001D108    

>>> dts reg map                                                         
complete                                                                
>>> greg                                                                
R0 4A81005A_00000043                 R8 C0000000_00B0CD10               
R1 00000000_00002000 HCPSYSVM        R9 00000000_001D0690 HCPIFI+1000   
R2 00000000_00B6E000                 RA 00000000_00B86008               
R3 00000000_0C000000                 RB C0000000_00002000 HCPSYSVM      
R4 00000000_00800000 HCWPA2+1CA30    RC 00000000_001CF690 HCPIFI        
R5 00000000_00000000                 RD 00000000_00000038               
R6 00000000_00B0CDC0                 RE 00000000_801CFF9E HCPIFI+90E    
R7 00000000_00000518                 RF 00000000_00000000               
                                                                        
>>> callers 00000038                                                              
---> CPEBK at 00000038                                                            
CPEXFPNT 00000000 CPEXBPNT 00000000 CPEXSFQP 00000000 CPEXCPRQ 00000000           
CPEXSCHC 00 CPEXCALC 00 CPEXFORM 00 CPEXRETN 00000000 (32-bit)                    
  Bits  defined in CPEXSCHC         (00)                                          
  Bits  defined in CPEXCALC         (00)                                          
R0 00000000                   R8 00000000                                         
R1 00000000                   R9 00000000                                         
R2 00000000                   RA 00000000                                         
R3 00000000                   RB 00000000                                         
R4 00000000                   RC 0001D000 HCPWRKPC                                
R5 00000000                   RD 00001202                                         
R6 00000000                   RE 00020000 HCPWRKSS                                
R7 00000000                   RF 00060016 HCPACV+5E6                              
CPEXWRK0-4 00000000 00000000 00000000 00000000 09000001 *....................*    
CPEXWRK5-9 00000000 00000000 00ECD000 00000000 00000000 *..........}.........*    
---> R13 has the wrong boundary to be a CPEBK                                     

I am keeping the dump if further questions arise. 

Since yesterday this happened 2 more times on z/VM 6.2 on different machines. 

Hope this helps

thanks

M

**Comment by ivan-w** [comment]
This doesn't look like a SIE problem.. This looks like a device got the same I/O interrupt twice !

You should use the trace command to try to determine how it got there !

**Comment by Fish-Git** [comment]
> This looks like a device got the same I/O interrupt twice !

Where do you see that? Educate me please! I'm unfamiliar with VM dumps and have no idea what I'm looking at! What part of the dump indicates an I/O interrupt occurred twice for the same device?

**Comment by moshix** [comment]
I don’t know Z/VM control blocks either. I sent Ivan an email yesterday with login info to connect to it system and look at the dump with vmdumptl . I tried email Ivan the dump but it’s too big, even when compressed 

Ivan did you get the logon info ?

**Comment by ivan-w** [comment]
I wouldn't be able to read the dump anyway ;) (I don't have z/VM 6.2... only z/VM 6.3)
I can't connect to the system with the information provided (connect time out)
Let's find a way to debug this ;) (there is also a possibility this a z/VM 6.2 bug !)

**Comment by Fish-Git** [comment]
@moshix : is this truly a CCKD64 issue? Did this problem only start happening after converting to CCKD64? Does it happen (has it _ever_ happened) with z/VM 6.3? Or does it only seem to happen with 6.2?

Also, have you seen my recent comments in the #20 thread? (where I discovered a bug?) Could this bug explain your problem? Did you do at any time do a level-3 or level-4 cckdcdsk64 on any of your z/VM 6.2 dasds?

> Let's find a way to debug this! `;-)`

I agree, Ivan! &nbsp; But _how?!_

**Comment by moshix** [comment]
Fish

I am not implying it’s a CCKD64 issue. I am merely remarking that this strange total freeze of Hercules has never happened before CCKD64 to me in 15 years of being a Hercules user. But correlation is not causation.  That’s clear. 

Yes, I did have a crashed VM before with CCKD64. I did convert a zOS dasd to 64bit and the underlying z/VM 6.2 has creasse once and I restarted it. I didn’t pay attention but one can surmise that some
Recovery might have been needed for the failed guest z/OS dasds. But again, I didn’t see it wirh my eyes and I had to reboot the underlying Linux because it was so badly frozen 

Yes, this only happened to me with z/VM 6.2 and not with 6.3 but then I didn’t have yet the exact same constellation of issues leading to the freeze on the z/VM 6.3 machine 

Sorry to not offer more help. However Ivan does have access to the dump of that failed z/VM 6.2. I assume he’s studying it. 

Thanks 

M

**Comment by Fish-Git** [comment]
> I am merely remarking that this strange total freeze of Hercules has never happened before CCKD64 to me in 15 years of being a Hercules user.

Hmmm...  That's quite suspicious in and of itself!

&nbsp;
> But correlation is not causation. That’s clear.

True, but since as you said, it had never occurred _before_ having converted to CCKD64, then I have to agree that it sure _smells_ like a CCKD64 issue!&nbsp;`:(`

&nbsp;
> Yes, I did have a crash of VM before with CCKD64. I did convert a zOS dasd to 64bit and the underlying z/VM 6.2 has crashed once and I restarted it.

Hmmm... I want to be certain I fully understand what happened. You had z/VM 6.2 up and running using CCKD64 dasd and it was running fine. Then you converted your z/OS dasd to CCKD64 and then attached them to your already running z/VM 6.2 system? Is that right? And then afterwards, after they were attached to Hercules and your running z/VM 6.2 saw them, you then tried to IPL your z/OS system (under your already running z/VM 6.2 system), and z/VM 6.2 itself crashed? (i.e. the IPL of your z/OS guest never got off the ground because z/VM itself crashed?)

Was this the "frozen solid" issue that required you to do the `kill -9` to recover? (i.e. _this_ very issue we're conversing in right now? i.e. issue #158 that we're posting our comments to right now?)

&nbsp;
> But again, I didn’t see it with my own eyes since I had to reboot the underlying Linux because it was so badly frozen.

_Wait!_ What are you saying?! Are you saying that _after_ doing the `kill -9` to kill Hercules that your _Linux host system_ ended up being so badly frozen that you had to reboot it? Am I understanding you correctly? Wow. That doesn't sound good.&nbsp;`:(`

**Question:** Since having discovered and fixed [the CCKD64 bug documented in the #20 thread](https://github.com/SDL-Hercules-390/hyperion/issues/20#issuecomment-447203935), can I get you to try again? Would that be asking too much? Would it be possible for you to:

&nbsp;
1. Run `cckdcdsk -3` on all of your original 32-bit cckd z/VM 6.2 dasd and let it repair any problems it finds. (This is of course presuming your original z/VM 6.2 dasds were compressed cckd dasd and not regular uncompressed ckd dasd.)

2. If your original z/VM 6.2 dasds were regular _uncompressed_ ckd dasd, then re-run `dasdcopy64 -o c cckd64` on them again to recreate the new _compressed_ cckd64 format dasds, using the _now fixed_ version of Hercules (with the [#20 bug](https://github.com/SDL-Hercules-390/hyperion/issues/20#issuecomment-447203935) fixed).

3. _**OR,**_ _optionally,_ use the new `convto64` utility to simply convert your original _non_-compressed ckd z/VM 6.2 dasds to _non_-compressed cckd64 format.

4.  Then convert your z/OS dasd to the new cckd64 format either however you did that before (`dasdcopy64?`) or optionally  using the new `convto64` utility.

5. Bring up z/VM 6.2, attach the cckd64 z/OS dasd to Hercules (and thus to z/VM), and then try to IPL your z/OS guest under z/VM.

&nbsp;
I'm asking too much, aren't I?&nbsp;`:(` &nbsp;  I'm sure I probably am.

But if it's in any way possible, I'd _really_ appreciate it!

My concern here is, due to the nature of the [bug I found](https://github.com/SDL-Hercules-390/hyperion/issues/20#issuecomment-447203935), I want to be sure that it gets completely eliminated as a suspect in the current problem. I'm worried that, due to the bug, that your current dasds might still be damaged somehow and maybe that's what's causing the weirdness you're currently experiencing. So let's eliminate that possibility by starting over fresh using a version of Hercules that _doesn't_ have the bug.

Make sense?

**Comment by moshix** [comment]
> > I am merely remarking that this strange total freeze of Hercules has never happened before CCKD64 to me in 15 years of being a Hercules user.
> 
> Hmmm... That's quite suspicious in and of itself!
> 
>  
> 
> > But correlation is not causation. That’s clear.
> 
> True, but since as you said, it had never occurred _before_ having converted to CCKD64, then I have to agree that it sure _smells_ like a CCKD64 issue! `:(`
> 
I agree, so that's why I opened this issue under CCKD64

 
> > Yes, I did have a crash of VM before with CCKD64. I did convert a zOS dasd to 64bit and the underlying z/VM 6.2 has crashed once and I restarted it.
> 
> Hmmm... I want to be certain I fully understand what happened. You had z/VM 6.2 up and running using CCKD64 dasd and it was running fine. Then you converted your z/OS dasd to CCKD64 and then attached them to your already running z/VM 6.2 system? Is that right? And then afterwards, after they were attached to Hercules and your running z/VM 6.2 saw them, you then tried to IPL your z/OS system (under your already running z/VM 6.2 system), and z/VM 6.2 itself crashed? (i.e. the IPL of your z/OS guest never got off the ground because z/VM itself crashed?)

No, let me explain better:

I converted a zOS 1.13 instance (the RES volume and and a few other volumes, but not all) to CCKD64. Then I IPLd z/VM 6.2 and started a VM wiht z/OS 1.13.  After a few hours I noticed that z/VM 6.2 had a PROG004 or PROG005 (don't remember anymore which) and restarted on it's own. This means it killed the VM with z/OS 1.13 in it ungracefully, of course. So, I shut down z/VM 6.2, exited Hercules, restarted Hercules and IPLd z/VM 6.2 again. 

Then I started a few VMs, including the previously creashed z/OS 1.13 instance (and in this case some repair might have been attempted as I started Hercules, but I didn't watch as Hercules started, so I didn't see anything myself). 

About half an hour later Hercules froze solid. I sent you the screen shots and a dump was produced in z/VM 6.2 which is still there for Ivan to analyze. 


> 
> Was this the "frozen solid" issue that required you to do the `kill -9` to recover? (i.e. _this_ very issue we're conversing in right now? i.e. issue #158 that we're posting our comments to right now?)

I couldn't kill it with SIGKILL (-9). I opened a new terminal session on that host ( I always run all my sessions under "screen" to have multiple virtual sessions) and after a long while it did open a new session but the keyboard was so slow to respond, that I simply rebooted the machine (which itself is a VMware ESXi VM). Since, then this has not happened anymore. 

And yes, that's the very same issue. 

> 
>  
> 
> > But again, I didn’t see it with my own eyes since I had to reboot the underlying Linux because it was so badly frozen.
> 
> _Wait!_ What are you saying?! Are you saying that _after_ doing the `kill -9` to kill Hercules that your _Linux host system_ ended up being so badly frozen that you had to reboot it? Am I understanding you correctly? Wow. That doesn't sound good. `:(`

Yes, as mentioned above the machine took 3-4 seconds to respond to a keystroke at the Linux terminal, so I had to restart. 

HOWEVER: back around may with the current SDL-hyperion back then, I did see a few times something a bit similar: I was starting Hercules and it would take 4-5 minutes to come up all the way, and during that time the keyboard of the Linux underneath it was very slow to respond, too. Not sure that's related, but it's definitely not the first time that HErcules causes keyboard to respond very slow and the machine seeming very busy with something. In those cases "top" or "htop" show Hercules running at 101% CPU or so .

> 
> **Question:** Since having discovered and fixed [the CCKD64 bug documented in the #20 thread](https://github.com/SDL-Hercules-390/hyperion/issues/20#issuecomment-447203935), can I get you to try again? Would that be asking too much? Would it be possible for you to:

Fish, yes of course. I did update all my SDLs today and recompiled and it's now running on the very same machine I gave access Ivan to. So far, so good. 
 
> 
>  
> 
> 1. Run `cckdcdsk -3` on all of your original 32-bit cckd z/VM 6.2 dasd and let it repair any problems it finds. (This is of course presuming your original z/VM 6.2 dasds were compressed cckd dasd and not regular uncompressed ckd dasd.)

Will do later today

> 2. If your original z/VM 6.2 dasds were regular _uncompressed_ ckd dasd, then re-run `dasdcopy64 -o c cckd64` on them again to recreate the new _compressed_ cckd64 format dasds, using the _now fixed_ version of Hercules (with the [#20 bug](https://github.com/SDL-Hercules-390/hyperion/issues/20#issuecomment-447203935) fixed).

Ok, sure. I have a script for this conversion in the mean-time for unattended conversion. 

> 3. _**OR,**_ _optionally,_ use the new `convto64` utility to simply convert your original _non_-compressed ckd z/VM 6.2 dasds to _non_-compressed cckd64 format.

will skip this, due to somewhat short of disk space on that VM. 

> 4. Then convert your z/OS dasd to the new cckd64 format either however you did that before (`dasdcopy64?`) or optionally  using the new `convto64` utility.


ok, will do 

> 5. Bring up z/VM 6.2, attach the cckd64 z/OS dasd to Hercules (and thus to z/VM), and then try to IPL your z/OS guest under z/VM.

roger. will do. 


> 
>  
> I'm asking too much, aren't I? `:(`   I'm sure I probably am.

No, I am determined to see Hercules support for z/VM be as good as it is for z/OS. 

> 
> But if it's in any way possible, I'd _really_ appreciate it!
> 
> My concern here is, due to the nature of the [bug I found](https://github.com/SDL-Hercules-390/hyperion/issues/20#issuecomment-447203935), I want to be sure that it gets completely eliminated as a suspect in the current problem. I'm worried that, due to the bug, that your current dasds might still be damaged somehow and maybe that's what's causing the weirdness you're currently experiencing. So let's eliminate that possibility by starting over fresh using a version of Hercules that _doesn't_ have the bug.
> 
> Make sense?

yes, it does!

thanks

M

**Comment by Fish-Git** [comment]
> 3\. _**OR,**_ _optionally,_ use the new `convto64` utility to simply convert your original _non_-compressed ckd z/VM 6.2 dasds to _non_-compressed cckd64 format.

_**(ACK!)**_ That was dumb of me!

`convto64` only converts _compressed_ (CCKD) dasd to the new _compressed_ CCKD64 format! It _doesn't_ convert regular _non_-compressed CKD dasd!

The only way to convert regular _non_-compressed ckd dasd to the new cckd64 format is to use `dasdcopy64`.

Sorry for the confusion!

**Comment by Fish-Git** [comment]
@moshix : _Ping!_

Have you had a chance to recreate all of your CCKD64 dasds again for z/VM as I suggested in my earlier comment? Has this z/VM freeze/crash of course happened again since then? Does this problem still exist? Or has it been fixed?

Thanks!

**Comment by moshix** [comment]
Fish

Sorry, I was traveling and now I have been sick with pneumonia the last 5 days. 

I did recreate all the CCKD64s again with the fixed CCKD64 support and I have not had problems with it on my laptop. But over the last six to nine months, z/VM problems have rarely surfaced on my laptop. Problems usually happened when I ran big instances on my server. 

I have been running a huge z/VM instance on my server for the last 5 days without problems so far, though. 

thanks

M

**Comment by ivan-w** [comment]
Hold your horses with this one !
This could very well be related to... TADA.... surprise ! a LCS issue !
I did run ONCE into an IFI004 issue (z/VM 6.3 - no CCKD64 at the time) (but for some awkward reason, no dump)... 
However, seeing how erratic LCS is behaving - especially when trying to HSCH to it - it COULD be related !
More research is needed !

**Comment by ivan-w** [comment]
I can reproduce the z/VM IFI004 abend on z/VM 6.3 at will now. It is obviously related to the HSCH/CSCH handling of the LCS and is a Heisenbug (time dependent - when CCW and I/O tracing is active, the problem goes away).
- #156 is a strong duplicate candidate
- #163 is a possible duplicate candidate

**Comment by moshix** [comment]
Ivan 

That’s progress!

What does VMDUMPTL say is the symptom ?

Thanks 

M

**Comment by Fish-Git** [comment]
> It is obviously related to the `HSCH`/`CSCH` handling of the LCS and is a Heisenbug (time dependent - when CCW and I/O tracing is active, the problem goes away).

Please see my comment in issue #156 "[LCS is broken for zLinux guest](https://github.com/SDL-Hercules-390/hyperion/issues/156#issuecomment-449841222)" regarding use of PTT trace to try and get around the Heisenbug problem.

**Comment by Fish-Git** [comment]
> Please see my comment in issue #156 "[LCS is broken for zLinux guest](https://github.com/SDL-Hercules-390/hyperion/issues/156#issuecomment-449841222)" regarding use of PTT trace to try and get around the Heisenbug problem.

(Oops!) Never mind! It looks like you've already seen it (and even commented on it).&nbsp;`:)`

**Comment by ivan-w** [comment]
Try with 082b69c5b764782afae24fa3483b930b7f2aa7d0 (should fix z/VM IFI004)

**Comment by Fish-Git** [comment]
@moshix:

Recent changes were made to SDL Hyperion (see "[Release Notes](https://sdl-hercules-390.github.io/html/hercrnot.html)" and commit b76163a6646abef539e6800df3fbdb6adaed9a9d) to prevent `HHC00822I Processor IE00: machine check due to host error: User defined signal 1` from occurring. Instead, Hercules should now crash and create a core dump file that can then, theoretically, be analyzed to determine exactly where Hercules is going wrong.

If possible, please do a git pull or clone to pick up the latest version of Hercules and then rebuild and retest to see whether the problem still occurs or not. If it does (and a crash dump ("core" file) is created), please compress the core file (crash dump) and attach it to your GitHub comment so one of us can try to analyze it.

Thanks.

p.s. Depending on how you have your system (host) configured, you might need to enter the `ulimit -c unlimited` or similar command before performing your test. Please refer to the new GitHub Discussion Issue #199 that I have created regarding Linux Crash dumps: "[HELP! How to analyze a Linux "core" file? (crash dump)](https://github.com/SDL-Hercules-390/hyperion/issues/199)" for more information.

**Comment by moshix** [comment]
it's been much more stable with the build as of last week. I am closing this issue for now. 

thank

M
