### ISSUE TITLE
SDL latest core dumps very early upon starting

### ISSUE THREAD

**Issue by moshix** [SDL-Hercules-390/hyperion#159]
I have this:

```
oot@zvm63test:/root/hyperion# uname -a
Linux zvm63test 4.15.0-1025-gcp #26~16.04.1-Ubuntu SMP Wed Nov 21 10:13:20 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

And when I do this:

```
root@zvm63test:/root/hyperion# 
root@zvm63test:/root/hyperion# hercules
```

I get this: 

```
Illegal instruction (core dumped)
```

I am building hyperion freshly on this system from a clean SDL source tree. Not sure what's going on here. 

Thanks.

M

**Comment by ivan-w** [comment]
Without information about : 
- How the binary was obtained
- How the binary was built (version of the compiler, which compiler, flags used, etc..)

This is going to be hard to track down.
--Ivan

**Comment by moshix** [comment]
Well, I got the source from this GitHub repo. Then I comipiled it with the same compilers like I did on mh other system (same versions of gcc, and all other dependencies). 

Then I built it wirh:
./autogen.sh
./configure
make
make install. 

Nothing out of the ordinary. 

Thanks 

M

**Comment by ivan-w** [comment]
Without the PATH specification, and configuring from source directory is bound to conflicts and mishaps.
You should always : 
Build out of source 
Install from outside the build directory
Run from outside the install directory 
If you run into a core dump situation, set ulimit to get a core dump and examine the core dump to determine where the exception happened !

**Comment by Fish-Git** [comment]
I myself am not a Linux person and so am not very familiar with `gdb`. However, I _do_ know that using it can be unfamiliar territory even for people who _are_ Linux people. (Regardless of what operating system one uses, not everyone is necessarily "geeky" enough to be able to debug crash dumps!)

With that in mind, I thought I'd pass along the following helpful(?) information I found to help get you started just in case you _are_ one of those non-geeky types who are unfamiliar with `gdb`:

* [How to analyse a crash dump file using GDB](https://stackoverflow.com/questions/1482061/how-to-analyse-a-crash-dump-file-using-gdb)

The output of a `where` and/or `bt` (backtrace) command appears to be the ones that would provide the most help to us in this particular case.

Finally, if you _are_ already geeky enough to already know how to use `gdb`, then please _do_ accept my sincerest apologies. I realize that having an amateur offer advice to someone much more skilled can seem very insulting to someone, so if that's the case, I do sincerely apologize. I don't wish to insult anyone. I'm only trying to help.

**Comment by moshix** [comment]
Thank you Fish. I know gdb well from my development work.

I found the reason: moved to an older CPU platform. 

Recompiled everything (incl C lib) and now it runs fine. 

Closing this now. 

Thanks 

M
