### ISSUE TITLE
SDL does not compile with commit 8194b34 (Improved performance for string instructions)

### ISSUE THREAD

**Issue by mcisho** [SDL-Hercules-390/hyperion#160]
I had earlier compiled on a Windows 10 virtual machine using VS2017, apparently successfully, but zLinux hung during start-up. I then attempted to compile on Fedora 29 x64 with gcc version 8.2.1 20181105 (Red Hat 8.2.1-5) (GCC), but the compile failed with the following:-

 gcc -DHAVE_CONFIG_H -I. -I . -I . -I ./crypto/include -I ./decNumber/include -I ./SoftFloat/include -I ./telnet/include -D DYNAMIC_VERSION=\"4.2.0.0-SDL-g8194b349-modified\" -D VERS_MAJ=4 -D VERS_INT=2 -D VERS_MIN=0 -D VERS_BLD=0 -DPKGDATADIR=\"/***/Hercules.run/share/hercules\" -DMODULESDIR=\"/***/Hercules.run/lib/hercules\" -DHERC_LOCALEDIR=\"/***/Hercules.run/share/locale\" -O2 -Wall -W -pthread -D_GNU_SOURCE -MT general1.lo -MD -MP -MF .deps/general1.Tpo -c general1.c  -fPIC -DPIC -o .libs/general1.o
In file included from hercules.h:62,
                 from general1.c:39:
general1.c: In function 's370_compare_logical_string':
hmacros.h:156:27: error: expected '(' before '__builtin_expect'
     #define unlikely(_c)  __builtin_expect((_c),0)
                           ^~~~~~~~~~~~~~~~
general1.c:3137:8: note: in expansion of macro 'unlikely'
     if unlikely(CROSSPAGEL(addr1,cpu_length) | CROSSPAGEL(addr2,cpu_length))
        ^~~~~~~~
hmacros.h:156:27: warning: statement with no effect [-Wunused-value]
     #define unlikely(_c)  __builtin_expect((_c),0)
                           ^~~~~~~~~~~~~~~~~~~~~~~~
general1.c:3137:8: note: in expansion of macro 'unlikely'
     if unlikely(CROSSPAGEL(addr1,cpu_length) | CROSSPAGEL(addr2,cpu_length))
        ^~~~~~~~
general1.c:3138:5: error: expected ';' before '{' token
     {
     ^
general1.c:3112:9: warning: unused variable 'usable' [-Wunused-variable]
 int     usable;                         /* usable length to page end */
         ^~~~~~
In file included from hercules.h:62,
                 from general1.c:39:
general1.c: In function 's390_compare_logical_string':
hmacros.h:156:27: error: expected '(' before '__builtin_expect'
     #define unlikely(_c)  __builtin_expect((_c),0)
                           ^~~~~~~~~~~~~~~~
general1.c:3137:8: note: in expansion of macro 'unlikely'
     if unlikely(CROSSPAGEL(addr1,cpu_length) | CROSSPAGEL(addr2,cpu_length))
        ^~~~~~~~
hmacros.h:156:27: warning: statement with no effect [-Wunused-value]
     #define unlikely(_c)  __builtin_expect((_c),0)
                           ^~~~~~~~~~~~~~~~~~~~~~~~
general1.c:3137:8: note: in expansion of macro 'unlikely'
     if unlikely(CROSSPAGEL(addr1,cpu_length) | CROSSPAGEL(addr2,cpu_length))
        ^~~~~~~~
In file included from general1.c:5953:
general1.c:3138:5: error: expected ';' before '{' token
     {
     ^
general1.c:3112:9: warning: unused variable 'usable' [-Wunused-variable]
 int     usable;                         /* usable length to page end */
         ^~~~~~
In file included from general1.c:5959:
general1.c: In function 'z900_branch_and_link_register':
general1.c:426:25: warning: cast between incompatible function types from 'func' {aka 'int (*)()'} to 'U64 (*)(int,  U64,  REGS *)' {aka 'long unsigned int (*)(int,  long unsigned int,  struct REGS *)'} [-Wcast-function-type]
         regs->CR(12) = ((ARCH_DEP(trace_br_func))regs->trace_br)
                         ^
general1.c: In function 'z900_branch_and_save_register':
general1.c:500:25: warning: cast between incompatible function types from 'func' {aka 'int (*)()'} to 'U64 (*)(int,  U64,  REGS *)' {aka 'long unsigned int (*)(int,  long unsigned int,  struct REGS *)'} [-Wcast-function-type]
         regs->CR(12) = ((ARCH_DEP(trace_br_func))regs->trace_br)
                         ^
In file included from hercules.h:62,
                 from general1.c:39:
general1.c: In function 'z900_compare_logical_string':
hmacros.h:156:27: error: expected '(' before '__builtin_expect'
     #define unlikely(_c)  __builtin_expect((_c),0)
                           ^~~~~~~~~~~~~~~~
general1.c:3137:8: note: in expansion of macro 'unlikely'
     if unlikely(CROSSPAGEL(addr1,cpu_length) | CROSSPAGEL(addr2,cpu_length))
        ^~~~~~~~
hmacros.h:156:27: warning: statement with no effect [-Wunused-value]
     #define unlikely(_c)  __builtin_expect((_c),0)
                           ^~~~~~~~~~~~~~~~~~~~~~~~
general1.c:3137:8: note: in expansion of macro 'unlikely'
     if unlikely(CROSSPAGEL(addr1,cpu_length) | CROSSPAGEL(addr2,cpu_length))
        ^~~~~~~~
In file included from general1.c:5959:
general1.c:3138:5: error: expected ';' before '{' token
     {
     ^
general1.c:3112:9: warning: unused variable 'usable' [-Wunused-variable]
 int     usable;                         /* usable length to page end */
         ^~~~~~
general1.c: In function 's370_compare_logical_character':
general1.c:2776:20: warning: this statement may fall through [-Wimplicit-fallthrough=]
                 if (sizeof( unsigned int ) >= 8)
                    ^
general1.c:2785:13: note: here
             default:
             ^~~~~~~
In file included from general1.c:5953:
general1.c: In function 's390_compare_logical_character':
general1.c:2776:20: warning: this statement may fall through [-Wimplicit-fallthrough=]
                 if (sizeof( unsigned int ) >= 8)
                    ^
general1.c:2785:13: note: here
             default:
             ^~~~~~~
In file included from general1.c:5959:
general1.c: In function 'z900_compare_logical_character':
general1.c:2776:20: warning: this statement may fall through [-Wimplicit-fallthrough=]
                 if (sizeof( unsigned int ) >= 8)
                    ^
general1.c:2785:13: note: here
             default:
             ^~~~~~~
make[2]: *** [Makefile:2322: general1.lo] Error 1
make[2]: Leaving directory '/***/Hercules.SDL/hyperion'
make[1]: *** [Makefile:2372: all-recursive] Error 1
make[1]: Leaving directory '/***/Hercules.SDL/hyperion'
make: *** [Makefile:1734: all] Error 2

**Comment by wably** [comment]
It seems that GCC is choking on the following:

       if unlikely(....

Even though VS2012 is handling it just fine.  Just a few minutes ago I did a fresh clone from the master SDL repo and compiled it on a Raspberry Pi (to use its GCC) and I encountered the same errors you reported.  Removing the 'unlikely' keyword in the code for CLST and SRST in general1.c and general2.c fixed the problems.

I will remove those keywords (they are not important enough to be worth all this) and quickly recompile and re-test and re-commit the change.

**Comment by ivan-w** [comment]
The "unlikely" statement is important (for branch optimization).. There is no reason it shouldn't work. If it's not working, then the "unlikely" macro is broken and should be fixed.

**Comment by ivan-w** [comment]
If you don't mind, do not remove the unlikely() statements just yet.. It could be simple mishap !

**Comment by wably** [comment]
it might be a coding error; I did not have 'unlikely' inside parenthesis even though VS2012 buys it.

I had   if unlikely(...) when I should probably have  if (unlikely(...)) 

testing...

**Comment by wably** [comment]
Yes, that was problem.  The correct form is:

          if (unlikely(....))

I'll get you fixed up asap.

**Comment by ivan-w** [comment]
Ah ah.. not my patch to start with - but if it works, nice catch !

**Comment by wably** [comment]
fixed by commit 3be4641

my apologies for the hassles!

**Comment by ivan-w** [comment]
Compile works for me now (fixed a typo in another file in the process)

**Comment by mcisho** [comment]
Compile works on Fedora, and zLinux starts on Windows 10 vm. Thanks.
