### ISSUE TITLE
Wrong CC for AR/AGR/SR/SGR instructions on Mac

### ISSUE THREAD

**Issue by Peter-J-Jansen** [SDL-Hercules-390/hyperion#173]
Thanks to Fish's excellent investigation and test script, a Mac compiler optimization bug was discovered.  It was discovered in the "Add overflow" thread discussion over the AR instruction on the *hercules-390* forum, but it affects -all- Hercules variants : SDL-Hyperion 4.2 as well as Hyperion 4.0.0 and Spinhawk 3.13.  The only practical problem it caused was when trying to run the VM IPSF/PDF application, which then generated this error message :

   DMSFRR161E Invalid free storage release call from 01135FFE, error code 6 

The only workaround at that time was to build Hercules on the Mac without optimization for all of the Hercules versions.  This problem was caused by the very same Mac compiler optimization bug now uncovered.

Fish correctly assumed something wrong with the compiler for the "add_signed" function inside "inline.h".  At first it was verified that by disabling the compiler optimization the problems went away.  Then Fish's suggestion to add more parentheses to explicitly make the operator precedence obvious was attempted, but this was unsuccessful, even after many many attempts, including reverting to the more explicit if .. else statements.  Finally the logic in the return statement was turned around, and that turned out to be successful.  This is the code that works :    

```diff
diff -w inline.h SDL-hyperion/inline.h

141,146d140
< /*
< #if defined(__APPLE__)
<     __attribute__((optnone)) // Workaround for an Apple compiler bug !
<                              // Needed for the original return stmt.
< #endif
< */
150d143
< /*
156,162d148
< */
< 
<     return  ((S32)*result <  0) ?
<                 ((S32)op1 <  0 || (S32)op2 <  0) ? 1 : 3 :
<             ((S32)*result >  0) ?
<                 ((S32)op1 >= 0 || (S32)op2 >= 0) ? 2 : 3 :
<                 ((S32)op1 >= 0 || (S32)op2 >= 0) ? 0 : 3;
pjvmojave:~ hercules$ 
```

This is a compiler optimization bug workaround only.  I think the AR instruction now deserves a complete set test for all of the six possible return values (1, 2, 0 and three times 3.)  I'll try learning how to write those test cases.  I don't know how or where to correctly report the GCC / Clang compiler bug for the Mac.

Cheers,

Peter

**Comment by srorso** [comment]
Hi Peter,

Here are the beginnings of a comprehensive test case for ADD, with only the AR variant implemented.  There is room in the test case for the remaining variants.  Two sets of test data are envisioned, a 32-bit and a 64-bit.  

I developed these as examples/discussion tools when Bob P. was doing test cases for MVST _et al_.  

With luck, you will find them helpful as a starting point or as an example for your own code.  

Best Regards,
Steve Orso

[bim-001.zip](https://github.com/SDL-Hercules-390/hyperion/files/2752557/bim-001.zip)

**Comment by srorso** [comment]
Thinking about this further, I will have to give this a try on FreeBSD 11, as that uses clang, albeit a different version.

**Comment by Fish-Git** [comment]
@Peter-J-Jansen Peter,

1. Your patch (diff) appears (to me) to be _bass-ackwards._ It appears to be deleting code (less than sign '<') that doesn't exist. I believe greater than signs '>' are nomally used for _inserting_ new code. Yes?

2. You might find the [README](https://github.com/SDL-Hercules-390/hyperion/blob/master/tests/README) document in the 'tests' subdirectory helpful. It explains the various .tst file directives used in runtest test cases (scroll down about 1/2 way).

3. The line endings in @srorso Steve's "**bim-001-add.tst**" test are inconsistent. You need to convert them to all Windows line endings or all Unix line endings. If you don't, then you might have a hard time making sense of the test (e.g. the `r` commands followed by the `*Want` statements).

4. I highly recommand installing and using [Harold's excellent SATK (Stand Alone Tool Kit)](https://github.com/s390guy/SATK) product for developing test cases, It's ASMA product (A Small Mainframe Assembler) makes it trivially easy to create .core files that runtest test cases (.tst files) can then `loadcore` and immediately use.

5. I'm also curious about:

> Then Fish's suggestion to add more parentheses to explicitly make the operator precedence obvious was attempted, but this was unsuccessful, even after many many attempts, including reverting to the more explicit if .. else statements.

I haven't tried adding any parentheses myself yet. Instead, my approach was to first investigate upgrading to a new version of `clang`, which I'm still trying to do. (My inexperience with Mac is slowing me down greatly, and I'm trying to work on other things at the same time too, which is slowing me down even more.)

I'll try adding some parentheses myself to see if I can get it to work right. If I can, I'll go ahead and commit the change.

If I'm _not_ successful however, I'll go ahead and commit _your_ workaround instead.

_**Thank you**_ guys, for keeping on top of things! It almost makes me cry each time when I think about how great of a team we have!&nbsp;

**Comment by ivan-w** [comment]
Before calling off a compiler bug... Let's make sure the code is actually proper ! Especially "casting" (not promotion) will get you the invariable answer from the C language community (per whatever standard they choose) : Undefined behavior, you're on your own !

**Comment by ivan-w** [comment]
We already got stung with this (especially because hercules is an emulation processor)... when trying to copy unaligned integers (which is by the C standard an undefined behavior) (this led to MVC & al to crash hercules because the compiler started using type strict aligned (vector) instructions). The conversion from unsigned to signed is a bit awkward though ! These should be purely language constructs and should be handled by the compiler.... I need to check the standards and/or the the community here !
I do however understand  the fact that the 'No Optimize' statement is a workaround (not a solution).

**Comment by Fish-Git** [comment]
> We already got stung with this (especially because hercules is an emulation processor)... when trying to copy unaligned integers (which is by the C standard an undefined behavior) (this led to MVC et al. to crash hercules because the compiler started using type strict aligned (vector) instructions).

Yes, our `OPTION_STRICT_ALIGNMENT` build option (which I forgot to make permanent; I'll have to go back and do that).

> The conversion from unsigned to signed is a bit awkward though! These should be purely language constructs and should be handled by the compiler....

Well, during my brief few minutes researching I discovered that gcc has some helpful compiler built-ins we might be able to leverage:

* [6.55 Built-in Functions to Perform Arithmetic with Overflow Checking](https://gcc.gnu.org/onlinedocs/gcc/Integer-Overflow-Builtins.html)

Unfortunately I have yet to find anything similar for Microsoft's C compiler.&nbsp;`:(`

> I need to check the standards and/or the the community here!

* [C Programming Language (C99, FINAL, TC3, 2007)](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf)
* [C Programming Language (C11, DRAFT, N1570, 2011)](https://web.cs.dal.ca/~vlado/pl/C_Standard_2011-n1570.pdf)

**Comment by Peter-J-Jansen** [comment]
Aha, indeed not a compiler bug then ! I never realized that overflow on signed integer additions is _undefined behavior_, and indeed, the smallest source correction to the "add_signed" routine I just verified appears to be this one, just omitting the (S32) casts : 

```
pjvmojave:~ hercules$ diff -w inline.h SDL-hyperion/inline.h
142,145c142
< 
< /*  *result = (S32)op1 + (S32)op2; */
<     
<     *result = op1 + op2;
---
>     *result = (S32)op1 + (S32)op2;
pjvmojave:~ hercules$ 
```

The diff command was run on MacOS, the "<" lines are from the leftmost diff file (i.e. my changes), the ">" from the rightmost (original) "inline.h".

I'm going to try using Steve's "bim-001".

Cheers,

Peter

**Comment by Fish-Git** [comment]
> The diff command was run on MacOS, the "<" lines are from the leftmost diff file (i.e. my changes), the ">" from the rightmost (original) "inline.h".

1. You're not requesting a unifed diff (`-u` option).
2. You're specifying the files in the wrong order. The first file is the "old" file. The second file is the "new" file.

A diff creates a patch file showing the changes that are needed to change FILE1 into FILE2 (source, destination, from, to, old, new, etc).

I would prefer to see the `-u` option being used too. I'm expecting lines being deleted to be red and lines being inserted to be green, just like how they're displayed in GitHub:

* [Example of unified diff as show by GitHub commit](https://github.com/SDL-Hercules-390/hyperion/commit/e7e64e66c3cde70a3c76291c2dcb5f2cd25563dd)

Unified diffs use `+` and `-` so there's no question as to which lines are being inserted and which are being removed:

* [Understanding of diff output](https://unix.stackexchange.com/questions/81998/understanding-of-diff-output)

It's up to you whether you want to create unified diffs or not, but IMO you should at least correct the order your files (first=old, second=new). Even if you don't create unified diffs, at least the `<` and `>` will be colorized correctly if you specify the files in the correct order.

> I'm going to try using Steve's "bim-001"

I haven't tried it yet myself, but I'm about to. Just be sure to fix the line endings beforehand! As my mentioned in my earlier comment Steve's .tst file contains inconsistent line endings. All lines should use either Windows line endings or all Unix line endings, but not both. When a file contains mixed line endings it kind of confuses things.

**Comment by Fish-Git** [comment]
Here are my own versions of the four inline.h functions:

```C
/*-------------------------------------------------------------------*/
/* Add two signed fullwords giving a signed fullword result          */
/* and return the condition code for the A or AR instruction         */
/*-------------------------------------------------------------------*/
static inline int add_signed( U32* result, U32 op1, U32 op2 )
{
    S32 sop1, sop2, res;

    sop1 = (S32) op1;
    sop2 = (S32) op2;

    res = sop1 + sop2;
    *result = (U32) res;

    return
    (0
        || (sop1 > 0 && sop2 > (INT_MAX - sop1))
        || (sop1 < 0 && sop2 < (INT_MIN - sop1))
    )
    ? 3 : (res < 0 ? 1 : (res > 0 ? 2 : 0));
}


/*-------------------------------------------------------------------*/
/* Add two signed doublewords giving a signed doubleword result      */
/* and return the condition code for the AG or AGR instruction       */
/*-------------------------------------------------------------------*/
static inline int add_signed_long( U64* result, U64 op1, U64 op2 )
{
    S64 sop1, sop2, res;

    sop1 = (S64) op1;
    sop2 = (S64) op2;

    res = sop1 + sop2;
    *result = (U64) res;

    return
    (0
        || (sop1 > 0 && sop2 > (LLONG_MAX - sop1))
        || (sop1 < 0 && sop2 < (LLONG_MIN - sop1))
    )
    ? 3 : (res < 0 ? 1 : (res > 0 ? 2 : 0));
}


/*-------------------------------------------------------------------*/
/* Subtract two signed fullwords giving a signed fullword result     */
/* and return the condition code for the S or SR instruction         */
/*-------------------------------------------------------------------*/
static inline int sub_signed( U32* result, U32 op1, U32 op2 )
{
    S32 sop1, sop2, res;

    sop1 = (S32) op1;
    sop2 = (S32) op2;

    res = sop1 - sop2;
    *result = (U32) res;

    return
    (0
        || (sop1 < 0 && sop2 > (INT_MAX + sop1))
        || (sop1 > 0 && sop2 < (INT_MIN + sop1))
    )
    ? 3 : (res < 0 ? 1 : (res > 0 ? 2 : 0));
}


/*-------------------------------------------------------------------*/
/* Subtract two signed doublewords giving signed doubleword result   */
/* and return the condition code for the SG or SGR instruction       */
/*-------------------------------------------------------------------*/
static inline int sub_signed_long( U64* result, U64 op1, U64 op2 )
{
    S64 sop1, sop2, res;

    sop1 = (S64) op1;
    sop2 = (S64) op2;

    res = sop1 - sop2;
    *result = (U64) res;

    return
    (0
        || (sop1 < 0 && sop2 > (LLONG_MAX + sop1))
        || (sop1 > 0 && sop2 < (LLONG_MIN + sop1))
    )
    ? 3 : (res < 0 ? 1 : (res > 0 ? 2 : 0));
```
The existing multiply/divide functions appear to be okay so no fix is needed to any of them. The add/subtract _logical_ functions also appear to be okay. Only the add/subtract _signed_ functions need to be fixed.

**Comment by Peter-J-Jansen** [comment]
Thanks Fish for the diff help, I'll start using the correct options and file order. My preferred diff-style utilities are WinMerge and SUPERC, hence my beginner's mistakes using diff.

Cheers,

Peter

**Comment by Fish-Git** [comment]
_**EDIT:** My original proposed replacement functions were bad! I have edited the above comment with the updated/**corrected** versions!_

**Comment by Fish-Git** [comment]
@Peter-J-Jansen: I see you committed your "bim-001-add-sub" test. Are you also going to commit the fix to the actual instructions themselves in `inline.h` too? Or are you waiting for me to do that?

Thanks!

**Comment by Peter-J-Jansen** [comment]
Hi Fish !
I was going to send you a message requesting that you indeed commit the fixes to "add_signed" and the 3 related ones, as I think you are more than entitled to have your preferred code fixes in SDL Hercules. Would that be OK ?
Thanks,
Peter

**Comment by Fish-Git** [comment]
Done!

Commit f2946690d24d0da7715b8effa6a99a862b292480 is the fix.

Commit 3a1546c29d067a98fe09b9c440e5f645171bab48 adds the test files to the VC project files and \*Nix Makefile (which you forgot to do but don't worry about it since I can usually quite easily take care of such things for you myself).

Issue now finally closed!&nbsp;`:)`

Thanks Peter! (and everyone else too!)
