### ISSUE TITLE
SDL latest on Intel Nehalem CPU core-dumps

### ISSUE THREAD

**Issue by moshix** [SDL-Hercules-390/hyperion#176]
Hello everybody.

I am starting the SDL latest (as of Jan 23 2019) and it reliably core dumps after fresh build. Previous versions (e.g. Dec 26 2018) work fine. 

```
# hercules
HHC01536W HDL: WARNING: '' is not a valid directory
HHC00007I Previous message from function 'hdl_checkpath' at hdl.c(759)
HHC00100I Thread id 00007f4333867740, prio 5, name 'impl_thread' started
HHC00100I Thread id 00007f43313c2700, prio 4, name 'logger_thread' started
HHC01413I Hercules version 4.2.0.0-SDL-g172b5a48-modified (4.2.0.0)
HHC01414I (C) Copyright 1999-2019 by Roger Bowler, Jan Jaeger, and others
HHC01417I ** The SoftDevLabs version of Hercules **
HHC01415I Build date: Jan 23 2019 at 08:48:17
HHC01417I Built with: GCC 7.3.0
HHC01417I Build type: GNU/Linux x86_64 host architecture build
HHC01417I Modes: S/370 ESA/390 z/Arch
HHC01417I Max CPU Engines: 64
HHC01417I Using   shared libraries
HHC01417I Using   setresuid() for setting privileges
HHC01417I Using   POSIX threads Threading Model
HHC01417I Using   Error-Checking Mutex Locking Model
HHC01417I With    Shared Devices support
HHC01417I With    Dynamic loading support
HHC01417I With    External GUI support
HHC01417I With    IPV6 support
HHC01417I With    HTTP Server support
HHC01417I With    sqrtl support
HHC01417I With    SIGABEND handler
HHC01417I With    CCKD BZIP2 support
HHC01417I With    HET BZIP2 support
HHC01417I With    ZLIB support
HHC01417I With    Regular Expressions support
HHC01417I Without Object REXX support
HHC01417I With    Regina REXX support
HHC01417I With    Automatic Operator support
HHC01417I Without National Language Support
HHC01417I With    CCKD64 Support
HHC01417I Machine dependent assists: cmpxchg1 cmpxchg4 cmpxchg8 hatomics=C11
HHC01417I Running on: 203zVM63 (Linux-4.15.0-43-generic x86_64) MP=6
HHC01417I Built with decNumber external package version 3.68.0.79-g53f2512
HHC01417I Built with SoftFloat external package version 3.5.0.82-g1c66591
HHC01417I Built with telnet external package version 1.0.0.41-ged0ddec
HHC00018I Hercules is running in elevated mode
Illegal instruction (core dumped)
```

Here is my CPU info from `/proc`:

```
more /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 46
model name      : Intel(R) Xeon(R) CPU           X7560  @ 2.27GHz
stepping        : 6
microcode       : 0xa
cpu MHz         : 2261.013
cache size      : 24576 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 11
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx r
dtscp lm constant_tsc arch_perfmon pebs bts nopl xtopology tsc_reliable nonstop_tsc cpuid aperfmperf pni ssse3 cx16 sse4_1 sse4_2 x2api
c popcnt tsc_deadline_timer hypervisor lahf_lm epb pti tsc_adjust dtherm ida
bugs            : clflush_monitor cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
bogomips        : 4522.02
clflush size    : 64
cache_alignment : 64
address sizes   : 42 bits physical, 48 bits virtual
power management:
```

What info can I send you to help debug this?

Thanks.

M

**Comment by Fish-Git** [comment]
Hmmm... This sounds familiar... Ah yes! Here it is:

* [#159: SDL latest core dumps very early upon starting](https://github.com/SDL-Hercules-390/hyperion/issues/159) (opened on Dec 10, 2018, closed on Dec 11, 2018)

Could this maybe be the same problem yet again? (i.e. a mistake on your part?)

If it's _not_ the same problem, then could you please:

1. Provide a "gdb backtrace" so we can see _where_ it's crashing?
2. Try building again, but with different otimization flags? (e.g. `-O2` or `-O1` or even `-O0` to completely disable optimizations altogether)

An "Illegal instruction" crash is usually indicative of a compiler bug. It shouldn't be generating intructions that are illegal for your processor unless you purposely (or accidentally) told it to via a potentially incorrect `-march=xxx` compiler option.

Thanks.

**Comment by moshix** [comment]
-O0 fixes it. I then went back to previous stable version of gcc and that fixed it. 

It seems the latest gcc has issues on Nehalem. I posted a bug report with gcc. 

thanks

M

**Comment by ivan-w** [comment]
Reverting to -O0 and the issue going away is NOT a correction ! It probably mean there is an underlying bug !... DO NOT CLOSE the issue (it is most probably an alignment issue - whereas hercules is assuming you can make unaligned stores.. (no you can't per C standard))

**Comment by ivan-w** [comment]
C89 (I think) states that the result of loading or storing a value from a rvalue that is not aligned with the size of the type of the value is undefined, and the other way around too.. (loading a non aligned lvalue).. Optimization WILL take that into account and this may lead to bizarre results (especially with processors that make use of vector instructions)

**Comment by ivan-w** [comment]
So basically, if reducing the optimization level makes a problem go away usually means : there is something wrong with the code !

**Comment by moshix** [comment]
Ivan, 

yes, I understand all that, but if I go back a gcc version and then run with -O2 and there is no more illegal instruction problem, then it surely must be a gcc problem and not an alignment problem.

**Comment by ivan-w** [comment]
-O3 is very agressive (in respect to C standard)... but yields the best results ! Especially the use of vector instructions and whatnot (which are very alignment sensitive)... Basically - if your code is assuming something that the C standard says is "undefined" will actually result in a "undefined" result when going -O3 (and will probably break at some point or another)

**Comment by ivan-w** [comment]
And this yields for any target architecture (Intel, Power, s390x, ARM, etc..)

**Comment by Fish-Git** [comment]
> it is most probably an alignment issue - whereas hercules is assuming you can make unaligned stores.

I seriously doubt it's an alignment issue. Commit be67880ca4eea4f4d8c4725cfcb2c386e584e230 made the `OPTION_STRICT_ALIGNMENT` build option permanent.

If something is not being aligned properly I doubt it's Hercules's fault. Rather, I highly suspect it's actually a bonafide compiler optimization bug. The fact that the problem goes away when the optimization level is reduced is strong evidence for this IMO.

**Comment by Fish-Git** [comment]
I will wait a day or two to give Ivan a chance to object if he wants before closing this issue as a non-Hercules-bug (likely compiler bug).

**Comment by Fish-Git** [comment]
Closing as compiler bug.
