### ISSUE TITLE
Low speed disk access

### ISSUE THREAD

**Issue by bencz** [SDL-Hercules-390/hyperion#177]
Hi!!

I'm doing tests with Ubuntu running on Hyperion, when I performed disk access tests, I got some bad results....

Here some results:

> bencz@ubuntu-s390:~$ dd if=/dev/zero of=test bs=64k count=16k conv=fdatasync
> 16384+0 records in
> 16384+0 records out
> 1073741824 bytes (1.1 GB, 1.0 GiB) copied, 63.6609 s, 16.9 MB/s

> bencz@ubuntu-s390:~$ dd if=/dev/zero of=/root/testfile bs=1G count=1 oflag=direct
> 1+0 records in
> 1+0 records out
> 1073741824 bytes (1.1 GB, 1.0 GiB) copied, 99.8951 s, 10.7 MB/s

When creating DASD to install linux, I used the following command line:

> dasdinit -lfs -linux ubuntu.disk 3390-3 LIN120 32000

**Comment by bencz** [comment]
A good tutorial about how to install Ubuntu on Hercules: https://astr0baby.wordpress.com/2018/06/03/installing-ubuntu-18-04-server-s390x-in-hercules-mainframe-simulator/

**Comment by bluecmd** [comment]
I'm not an author or anything, but I'd imagine you'll have to provide some more information of what you'd expect to see in terms of performance :-). A benchmark towards the host system would be useful as well of course.

**Comment by Fish-Git** [comment]
@bluecmd is correct: _much_ more detailed information is needed before this "problem" can be properly looked into. We need to know things such as the _exact_ git revision of SDL-Hyperion you are using, what real host you are running on (which Linux, which Windows, etc), the exact version of S390 ubuntu you are running under Hercules, what type of real host dasd you are using, a comparative benchmark on your real host, etc, etc, etc...

I am going to close this issue as Unknown/Unresolved for now. Feel free to re-open it after providing more information.
