### ISSUE TITLE
BIG difference in execution speed with SDL-Hyperion vs. Spinhawk

### ISSUE THREAD

**Issue by FanDjango** [SDL-Hercules-390/hyperion#180]
I am alternately using Spinhawk and SLD-Hyperion from 29.1.2019 am slightly disgruntled because of very visible speed differences between the two. IPL'ing on one, and then on the other - you really notice the difference.

I was only using SDL-hyperion originally for some important tests when I became suspicious about the bad performance - that then prompted me to get Spinhawk and compare.

I also picked up SDL-Hyperions from November 2018, July 2018 and so on to see if going back in commits/in time would change anything - it didn't.

Remembering previous threads on this topic, there were never differences beyond, say, 40% or so. If that were the case here, I would not have asked for your help in finding out what the heck is going on here. 

I realize that the two different versions (Spinhawk, SDL-Hyperion) do have slightly different base values on the compile (like MAXCPU) or whatever, but this here can't account for this discrepancy.

Same host (linux-px), same underlying operating system, exact same config file (except for different syntax for feature enable of ASN_AND_LX_REUSE). Same everything.

The REXX tests were not I/O bound so the new I/O subsystem logic shouldn't be the root cause?

For both: 
```
wget [spinhawk or hyperion]
unzip it, cd into basedir
./autogen.sh
./configure
make
make install
```
and then
```
hercules -f configfile [-r hercules.rc]   (3.13 does not support -r, 4.2 needs it)
```
Some timing information:

```
IPL up to start of JES2 cold start
Hercules 3.13:		1m 40sec
SDL-Hyperion 4.2:	2m 45sec
```

Each test, fresh IPL, wait for system to settle down, then:

```
MAKCOAN (REXX Program, few IOs):
Hercules 3.13:		4m 15sec
SDL-Hyperion:		13m 26sec
```

```
TIMTST1 (REXX Program, no IOs at all, just MUL and DIV in a loop):
Hercules 3.13:		6.05sec
SDL-Hyperion:		18.39sec
```

I really have no idea what is happening here, there SHOULD NOT be such a big difference between the two (or should there?)

**Comment by FanDjango** [comment]
My gcc is:
```
gcc (Debian 4.9.2-10+deb8u2) 4.9.2
```
In **configure.ac**(hyperion) there is a check, which is not in spinhawk:
```
#------------------------------------------#
#  Check for broken '-O3' version of GCC   #
#------------------------------------------#

if test "$GCC" = "yes"; then

    AC_CACHE_CHECK( [if this is GCC with broken '-O3' option],

        [hc_cv_broken_gcc_O3],
        [
            AS_VERSION_COMPARE( $hc_gcc_level, "4.9.2",
                                [hc_cv_broken_gcc_O3=no],
                                [hc_cv_broken_gcc_O3=yes],
                                [hc_cv_broken_gcc_O3=no] )
        ]
    )
else
    hc_cv_broken_gcc_O3=no
fi
```
This check causes ./configure to **not** use **-O3** etc.

Although spinhawk works fine being compiled with **-O3**, I must assume this check is legit and that spinhawk **will** fail in some unspecified way (although it runs ok, looks like).

I will close this issue tomorrow after some more tests.

**Comment by Fish-Git** [comment]
I don't recall what the issue was, but if there's a specific test for a specific version of gcc that's purpose disabling optimizations, it's probably there for a very good reason.

You might consider upgrading to a different version of gcc or building with clang instead.

**Comment by FanDjango** [comment]
Yes, I agree, thank you. I am evaluating the possibilites right now. 
Sadly, upgrading gcc only is more work/danger on that system than upgrading it totally (Debian 8 -> Debian 9).
Investigating clang and also perhaps cross-compiling on another system.

**Comment by FanDjango** [comment]
Ok. Compiled with gcc (Debian 6.3.0-18+deb9u1) 6.3.0.
Timing results are now:
TIMTST1 (REXX Program, no IOs at all, just MUL and DIV in a loop):
Hercules 3.13: 6sec
SDL-Hyperion: 10sec
I suppose that's the most I can expect.

**Comment by Fish-Git** [comment]
> Ok. Compiled with gcc (Debian 6.3.0-18+deb9u1) 6.3.0.

Did ./configure add `-O3` to the optimization flags?

> MAKCOAN (REXX Program, few IOs):
> Hercules 3.13: 4m 15sec
> SDL-Hyperion: 7m 38sec
> 
> TIMTST1 (REXX Program, no IOs at all, just MUL and DIV in a loop):
> Hercules 3.13: 6sec
> SDL-Hyperion: 10sec

Wow. That sucks! Something's not right. I'm going to re-open this issue so we can research it to see what the frick is going on.

In the mean time, what kind of results do you get if you build using the same optimization flags that spinhawk (3.13) is using? (i.e. `-O3 -march=k8 -fomit-frame-pointer -fno-strict-aliasing`)

Also, would it be possible to post a copy of your `MAKCOAN` and `TIMTST1` Rexx scripts so we try it for ourselves? Thanks!

(grumbleweshouldn'tbegoingbackwardsinperformancegrumble)

**Comment by ivan-w** [comment]
It's possible to go backward in performance when fixing architectural compliance.

**Comment by Fish-Git** [comment]
> It's possible to go backward in performance when fixing architectural compliance.

But not by that much! Sheesh! According to his numbers we're a good 50% or more slower! That doesn't seem right! Does it? Because it doesn't to me!

**Comment by ivan-w** [comment]
Ensuring Block update consistency can be taxing on a system that doesn't guarantee it !

**Comment by ivan-w** [comment]
I just wouldn't consider this as a "bug"... just something that needs being addressed ! (nothing is broken)

**Comment by Fish-Git** [comment]
> Ensuring Block update consistency can be taxing on a system that doesn't guarantee it!

Hmmm... You might be onto something... As I recall one of my recent changes was to make `OPTION_STRICT_ALIGNMENT` permanent (commit be67880ca4eea4f4d8c4725cfcb2c386e584e230). I wonder what kind of performance would result if that particular commit were backed out? (and made into a ./configure option instead?) (with the default being _no_ strict alignment so as to get the best performance but still allow specifying it for people whose compiler/cpu happens to be incompatible with it)

@FanDjango ? Give me a few minutes and I'll whip up a patch for you, or you can just backout that particular commit yourself and rebuild if you know to do that.

**Comment by Fish-Git** [comment]
> I just wouldn't consider this as a "bug"... just something that needs being addressed! (nothing is broken)

Yes, technically you're right: nothing is technically broken, BUT... In my opinion such an unexpected _(and undesirable!)_ drop in performance _should_ be considered a "bug" or sorts!  (Our performance should be getting _better_, not worse!)

**Comment by ivan-w** [comment]
The OPTION_STRICT_ALIGNMENT is to overcome an issue with -O3 (because accessing an "int" that is not aligned with sizeof(int) is an "undefined behavior" in C standard). It was previously designed for architectures that didn't support it.. But with -O3, even on x86_64 it becomes a problem (when gcc starts using SSEx instructions & such which require alignement).

**Comment by FanDjango** [comment]
Using `-O3 -march=k8 -fomit-frame-pointer -fno-strict-aliasing` I get:

TIMTST1 (REXX Program, no IOs at all, just MUL and DIV in a loop):
Hercules 3.13: 6sec
SDL-Hyperion: 11sec

which boils down to a small worsening of the execution times.

TIMTST1:
```
/* REXX */   
t = Time('R')
a = 17       
Do 100000    
 a = a*6     
 a = a / 3   
 a = a / 2   
End          
t = Time('E')
Say t        
```
Primitive, like a code-fart, I know, but definitely no I/O.

Current performance is good enough for me - I would probably not even have felt prompted to do the direct comparison at this level.

**Comment by Fish-Git** [comment]
@FanDjango: Can you try again with commit be67880ca4eea4f4d8c4725cfcb2c386e584e230 backed out to see if that makes any difference? Thanks!

**Comment by FanDjango** [comment]
@Fish, willco re backing out be67880, gimme a moment.

**Comment by ivan-w** [comment]
PLEASE DONT !!! You are breaking EVERYTHING by doing this !!!!

**Comment by ivan-w** [comment]
It will break a LOT of builds !!!!

**Comment by ivan-w** [comment]
By backing out this patch, you are re-introducing a behavior that is defined by the C standard as "undefined"... any compliler with any optimization level MAY break hercules if this patch is backed out !

**Comment by FanDjango** [comment]
Maybe, but won't it at least prove that cause of the performance hit?

**Comment by ivan-w** [comment]
The performance hit is ONE thing... breaking hercules to the point it goes into a segfault... NOT !

**Comment by FanDjango** [comment]
I promise to put it back in after one short quick test. :-)

**Comment by ivan-w** [comment]
You are using an antiquated version of gcc (4.9)... The current version is gcc 8 !
You can change it locally of course ! But I ask that it not be backed out in the repository here ... that's all !

**Comment by Fish-Git** [comment]
RELAX, Ivan! I'm just trying to determine whether or not this is the root of the problem! If it is, THEN I'll weigh our options regarding how we should best address the issue. (I'm sure there's _something_ we could do to ensure compliance while at the same time getting better performance!)

**Comment by ivan-w** [comment]
I'll cool down ;) (anyway - things can always backtrack, be rolled backed, etc..) (You know me.. I'm passionate..)

**Comment by Fish-Git** [comment]
> You know me.. I'm passionate..

As am I!!! &nbsp;`:)`

**Comment by ivan-w** [comment]
Anyway.. Seeing if reducing the Strict Alignment on his build using gcc 4.9.2 gets performance back to what it is in Hercules 3.13... I'll be happy to look into it... But as I was saying - it's quite possible such a change could lead hercules to segfault under newer versions of gcc - or that enforcing alignement may lead to better performance in newer versions of gcc.

**Comment by Fish-Git** [comment]
OH YEAH! @FanDjango ? After backing out that commit, you'll also need to delete the statements:

```C
/* Per C11 standard, unaligned storage accesses have an undefined behavior so...  */
#define OPTION_STRICT_ALIGNMENT
```

in `machdep.h` near line 525. If you don't, nothing will change. You'll still get shitty performance. You need to _disable_ (#undef or comment out) the `OPTION_STRICT_ALIGNMENT` option.

**Comment by Fish-Git** [comment]
> But as I was saying - it's quite possible such a change could lead hercules to segfault under newer versions of gcc - or that enforcing alignement may lead to better performance in newer versions of gcc.

Excellent point. I wonder if we could code a `configure.ac` test to determine whether or not it was "safe" to disable strict alignment? (just thinking out loud)

**Comment by ivan-w** [comment]
Remember.. The bad performance issue may be due to an issue with the optimizer in gcc 4.9.2 !

**Comment by ivan-w** [comment]
A compiler version which was already flagged for having a fault optimizer ;)

**Comment by FanDjango** [comment]
There is also no #define OPTION_STRICT_ALIGNMENT in the current machdep.h either. You've got me confused now.

**Comment by Fish-Git** [comment]
Here's the patch that should be applied against the _current_ repository:

* [noalign.zip](https://github.com/SDL-Hercules-390/hyperion/files/2824621/noalign.zip)

It _should_, ideally, (unless I missed something) default to _NO_ strict alignment, thereby restoring performance (I hope).

**Comment by Fish-Git** [comment]
> There is also no #define OPTION_STRICT_ALIGNMENT in the current machdep.h either. You've got me confused now.

I'm not sure what you mean.

**Comment by FanDjango** [comment]
To be safe I have now done a git-clone.
I have three subdirectories:
spinhawk-master <- current
hyperion-master <- current 
hyperion-master-be   <- this one is JAN 13 pre be67880
only the spinhawk-master's machdep.h contains such an option in file machdep.h. I cannot find this string anywhere in hyperion.

But, I will now use your patch and see where that gets me.

**Comment by Fish-Git** [comment]
> I cannot find this string anywhere in hyperion.

Then something is _very wrong_ somewhere! You are not building / running what you think you are! Prior to JAN 13 pre be67880, `machdep.h` has tests for `OPTION_STRICT_ALIGNMENT` all over the place!

Perhaps you mean you don't see the option being _set_ (#defined) anywhere? If so, that's to be expected! As designed the option is purposely _not_ set, so as to _not_ enable strict alignment! It's when the option gets set that causes the performance hit.

**Comment by FanDjango** [comment]
I understand all that. I searched for "OPTION_STRICT", is all. I will clear this up and report back. Please stand down for now.

**Comment by Fish-Git** [comment]
10-4. I need to go to bed anyway. I'll catch up with you later tonight/tomorrow.

**Comment by FanDjango** [comment]
I cleared up all the problems (misunderstandings). My backout was not far enough back. But your patch on the current repo worked, and I get a seg fault just as @ivan-w prophecied.

Back to the drawing board :-)

**Comment by Fish-Git** [comment]
> and I get a seg fault just as @ivan-w prophecied.

Which is probably why we:

1. Have that special test for gcc version 4.9.2 in `configure.ac` that removes the compiler optimization flags.

2. Why the `OPTION_STRICT_ALIGNMENT` build option was made permanent in SDL Hyperion.

I wish there was some way to get better unaligned fetch/store performance without causing undefined behavior (i.e. without violating the standard).

Right now we're using `memcpy` to copy the data to be fetched/stored to an aligned work variable where we then do the real fetch/store from. I suspect some compilers may be generating code to perform an actual function call to `memcpy`, instead of treating it as a compiler intrinsic like Microsoft's Visual Studio does (which then just generates the one or two machine instructions neccessary to perform the _equivalent_ of a memcpy, thereby eliminating the overhead of an actual call to a runtime library function.) I'll have think about this. (Low priority of course.)

**Comment by Fish-Git** [comment]
@FanDjango:

LOW PRIORITY

Just out of curiosity, does the following patch help any?

* [align.zip](https://github.com/SDL-Hercules-390/hyperion/files/2825210/align.zip)

Basically I just added a one instruction alignment check to all of the fetch_xx_noswap and store_xx_noswap functions in machdep.h so they'd only use memcpy if needed (if the source or target address was actually unaligned). Otherwise they use the same (faster?) direct fetch/store technique that 3.13 is presumably using.

Be sure to specify the -O3 flag too if needed. With the way the patch is designed it shouldn't segfault and should hopefully improve performance a bit (he said optimistically).

Thanks.

(again, LOW PRIORITY)

**Comment by FanDjango** [comment]
Using the second patch:

TIMTST1 (REXX Program, no IOs at all, just MUL and DIV in a loop):
SDL-Hyperion:   12.2sec

Consistantly about one second longer.

This test shows that you are probing around in an area that reflects very directly on performance, which seems obvious and is no surprise given the central importance of machdep.

> I am re-closing this issue and removing the "Bug" label per Ivan's suggestion since, as he correctly states, this is not an actual bug but rather just "undesirable behavior" (which, at the moment, we can unfortunately do nothing about).

On my "other" machine, I need to add a zero to the loop count of TIMTST1 in order to get any significant  digits at all on the elapsed time message, so 6secs vs. 10secs is like deciding to fly to Alpha Centauri or to hit for Barnard's Star. Both way out of scale.

And now to my Sunday job: Shovel some snow...

**Comment by Fish-Git** [comment]
> Using the second patch:
> [...]
> Consistantly about one second longer.

Dang!&nbsp;`:(`

Oh well. It was a valiant try but I can see I'm not going to get anywhere with this so I think it's time for me to stop trying and give up.

> And now to my Sunday job: Shovel some snow...

Where you at? What's the temp?
