### ISSUE TITLE
DASDLOAD error: HHC90020W 'hthread_setschedparam()' failed

### ISSUE THREAD

**Issue by pjfarleyiii** [SDL-Hercules-390/hyperion#181]
Subject error message appears twice for every DASDLOAD execution.  Full text is:

HHC90020W 'hthread_setschedparam()' failed at loc=cckddasd.c:1748: rc=22: Invalid argument

I do not (yet) know if the created DASD file is good or not, will reply if I find it is not.

System is Win10 Pro Build 1803.  DASDLOAD version is:

HHC01413I Hercules utility dasdload - Build DASD from TSO XMIT files; version 4.1.0.9426-SDL-g42b533fa (4.1.0.9426)

Regards,

Peter

**Comment by Fish-Git** [comment]
This bug has already been identified and fixed:

* "[Don't attempt to set thread priority in batch mode](https://github.com/SDL-Hercules-390/hyperion/commit/c8addaafe1133427607280a46536844284f4e974)"

and will apear in the next snapshot for version 4.2 once version 4.2 is eventually officially released.

Closing as resolved.

> I do not (yet) know if the created DASD file is good or not...

Your created dasd is fine.

**Comment by pjfarleyiii** [comment]
Yes, I found that the created DASD was in fact fine.

Thank you for the prompt response. 

Regards,

Peter
