### ISSUE TITLE
QETH Manual page outdated

### ISSUE THREAD

**Issue by bluecmd** [SDL-Hercules-390/hyperion#182]
Hi,

I'm playing around with QETH and it seems the [page](https://sdl-hercules-390.github.io/html/hercconf.html#QETH) is outdated and contradictory.

One example is that it says:

> For technical reasons, the iface, ipaddr and netmask parameters are required parameters for both Windows and *nix. All other parameters however, are optional.

and then goes on to say:

> Optional for both Windows and *nix: iface  device

However, I know from https://github.com/SDL-Hercules-390/hyperion/issues/89 that iface is a perfectly acceptable parameter for L2 mode.

Let me know if you want me to write you a PR for it, or if you prefer to update it yourself. The latter would probably be more accurate and faster, but I'm not shy of pulling my weight.

**Comment by Fish-Git** [comment]
Simple DOC bug.  Thanks for reporting it. 

As far as you creating a PR (Pull Request) for this, it's entirely up to you.  Yes, I could  quickly and easily fix it myself, but a PR has the advantage of logging the commit under your name, not mine.

**Comment by Fish-Git** [comment]
Christian (@bluecmd): are you going to create the PR (Pull Request) for this?

**Comment by bluecmd** [comment]
Sure, I can do that. It might take some time but you can assign it to me.
