### ISSUE TITLE
QETH crashes on unknown packet

### ISSUE THREAD

**Issue by bluecmd** [SDL-Hercules-390/hyperion#184]
Hi,

In one of my workloads I'm loading a virtualized Ubuntu. As it is initializes the interfaces, the host system crashes. I'm using head as of today (7703dda3).

This is the part of the log that I think is relevant, I have filtered out `HHC02269I|HHC00801I|HHC02324I|HHC02326I|HHC02270I` messages as they are spamming the log.

```
19:28:05 HHC00910D 0:0E22 QETH: Send IPv4 packet of size 110 bytes to device zvmip0
19:28:05 HHC00979D QETH: Packet: +0000< 4500006E 58780000 3C064E6E 0A00FB82  E..nXx..<.Nn.... ...>......+>...b
19:28:05 HHC00979D QETH: Packet: +0010< 0A00C821 0017C5F7 1806AD85 82DFBF47  ...!...........G ..H...E7..[eb...
19:28:05 HHC00979D QETH: Packet: +0020< 50187FFF B2C60000 01C21100 CC284100  P............(A. &."..F...B......
19:28:05 HHC00979D QETH: Packet: +0030< 284200F8 4BF84BF8 4BF82800 00111ADF  (B..K.K.K.(..... ...8.8.8.8......
19:28:05 HHC00979D QETH: Packet: +0040< 1D601119 9F290342 004100C0 C1111ACB  .`...).B.A...... .-.........{A...
19:28:05 HHC00979D QETH: Packet: +0050< 29034200 4100C060 D9E4D5D5 C9D5C740  ).B.A..`.......@ ......{-RUNNING
19:28:05 HHC00979D QETH: Packet: +0060< 4040C3D4 C4E9E5D4 40401D60 FFEF      @@......@@.`..     CMDZVM  .-..
19:28:05 HHC00913D 0:0E22 QETH: Receive IPv4 packet of size 40 bytes from device zvmip0
19:28:05 HHC00979D QETH: Packet: +0000> 45000028 68734000 7E06BCB8 0A00C821  E..(hs@.~......! ...... .=.....H.
19:28:05 HHC00979D QETH: Packet: +0010> 0A00FB82 C5F70017 82DFBF47 1806ADCB  ...........G.... ...bE7..b.....[.
19:28:05 HHC00979D QETH: Packet: +0020> 501003FE 062B0000                    P....+..         &.......
19:28:05 HHC00910D 0:0E22 QETH: Send IPv4 packet of size 126 bytes to device zvmip0
19:28:05 HHC00979D QETH: Packet: +0000< 4500007E 58790000 3C064E5D 0A00FB82  E..~Xy..<.N].... ...=.`....+)...b
19:28:05 HHC00979D QETH: Packet: +0010< 0A00C821 0017C5F7 1806ADCB 82DFBF47  ...!...........G ..H...E7..[.b...
19:28:05 HHC00979D QETH: Packet: +0020< 50187FFF 29950000 01C21101 40284100  P...).......@(A. &."..n...B.. ...
19:28:05 HHC00979D QETH: Packet: +0030< 284200F8 4BF84BF8 4BF84040 28000011  (B..K.K.K.@@(... ...8.8.8.8  ....
19:28:05 HHC00979D QETH: Packet: +0040< 01E02841 00284200 40402800 00111ADF  ..(A.(B.@@(..... .\......  ......
19:28:05 HHC00979D QETH: Packet: +0050< 1D601119 9F290342 004100C0 C1111ACB  .`...).B.A...... .-.........{A...
19:28:05 HHC00979D QETH: Packet: +0060< 29034200 4100C060 D9E4D5D5 C9D5C740  ).B.A..`.......@ ......{-RUNNING
19:28:05 HHC00979D QETH: Packet: +0070< 4040C3D4 C4E9E5D4 40401D60 FFEF      @@......@@.`..     CMDZVM  .-..
19:28:05 HHC00913D 0:0E22 QETH: Receive IPv4 packet of size 40 bytes from device zvmip0
19:28:05 HHC00979D QETH: Packet: +0000> 45000028 69384000 7E06BBF3 0A00C821  E..(i8@.~......! ...... .=..3..H.
19:28:05 HHC00979D QETH: Packet: +0010> 0A00FB82 C5F70017 82DFBF47 1806AE21  ...........G...! ...bE7..b.......
19:28:05 HHC00979D QETH: Packet: +0020> 501003FE 05D50000                    P.......         &....N..
19:28:05 HHC00910D 0:0E22 QETH: Send ???? packet of size 90 bytes to device zvmip0
19:28:05 HHC00979D QETH: Packet: +0000< 33330000 00160200 00000003 86DD6000  33............`. ............f.-.
19:28:05 HHC00979D QETH: Packet: +0010< 00000024 00010000 00000000 00000000  ...$............ ................
19:28:05 HHC00979D QETH: Packet: +0020< 00000000 0000FF02 00000000 00000000  ................ ................
19:28:05 HHC00979D QETH: Packet: +0030< 00000000 00163A00 05020000 01008F00  ......:......... ................
19:28:05 HHC00979D QETH: Packet: +0040< 6F870000 00010400 0000FF02 00000000  o............... ?g..............
19:28:05 HHC00979D QETH: Packet: +0050< 00000000 0001FF00 0003               ..........       ..........
19:28:05 HHC00911E 0:0E22 QETH: Error writing to device zvmip0: 22 Invalid argument
19:28:05 HHC00007I Previous message from function 'write_packet' at qeth.c(2749)
19:28:05 HHC00809I Processor CP02: disabled wait state 0002000000000000 0000000000009005
19:28:05 HHC00809I Processor CP00: disabled wait state 0002000000000000 0000000000009005
19:28:05 HHC00809I Processor CP01: disabled wait state 0002000000000000 0000000000009005
19:28:05 HHC00913D 0:0E22 QETH: Receive IPv4 packet of size 84 bytes from device zvmip0
19:28:05 HHC00979D QETH: Packet: +0000> 45000054 6ABA0000 7E01FA4A 0A00C821  E..Tj...~..J...! ....|...=.....H.
19:28:05 HHC00979D QETH: Packet: +0010> 0A00FB82 0800781D 0A4E0965 34CA5D5C  ......x..N.e4.]\ ...b.....+....)*
19:28:05 HHC00979D QETH: Packet: +0020> 00000000 0C360F00 00000000 10111213  .....6.......... ................
19:28:05 HHC00979D QETH: Packet: +0030> 14151617 18191A1B 1C1D1E1F 20212223  ............ !"# ................
19:28:05 HHC00979D QETH: Packet: +0040> 24252627 28292A2B 2C2D2E2F 30313233  $%&'()*+,-./0123 ................
19:28:05 HHC00979D QETH: Packet: +0050> 34353637                             4567             ....
19:28:05 HHC00913D 0:0E22 QETH: Receive IPv4 packet of size 84 bytes from device zvmip0
19:28:05 HHC00979D QETH: Packet: +0000> 45000054 6ABE0000 7E01FA46 0A00C821  E..Tj...~..F...! ....|...=.....H.
19:28:05 HHC00979D QETH: Packet: +0010> 0A00FB82 08003D9C 0B7804B6 34CA5D5C  ......=..x..4.]\ ...b..........)*
19:28:05 HHC00979D QETH: Packet: +0020> 00000000 4A3C0F00 00000000 10111213  ....J<.......... ................
19:28:05 HHC00979D QETH: Packet: +0030> 14151617 18191A1B 1C1D1E1F 20212223  ............ !"# ................
19:28:05 HHC00979D QETH: Packet: +0040> 24252627 28292A2B 2C2D2E2F 30313233  $%&'()*+,-./0123 ................
19:28:05 HHC00979D QETH: Packet: +0050> 34353637                             4567             ....
19:28:06 HHC00913D 0:0E22 QETH: Receive IPv4 packet of size 84 bytes from device zvmip0
19:28:06 HHC00979D QETH: Packet: +0000> 45000054 6AC10000 7E01FA43 0A00C821  E..Tj...~..C...! ....|A..=.....H.
19:28:06 HHC00979D QETH: Packet: +0010> 0A00FB82 0800C619 0A4E0966 35CA5D5C  .........N.f5.]\ ...b..F..+....)*
19:28:06 HHC00979D QETH: Packet: +0020> 00000000 BD380F00 00000000 10111213  .....8.......... ....]...........
19:28:06 HHC00979D QETH: Packet: +0030> 14151617 18191A1B 1C1D1E1F 20212223  ............ !"# ................
19:28:06 HHC00979D QETH: Packet: +0040> 24252627 28292A2B 2C2D2E2F 30313233  $%&'()*+,-./0123 ................
19:28:06 HHC00979D QETH: Packet: +0050> 34353637                             4567             ....
19:28:06 HHC00913D 0:0E22 QETH: Receive IPv4 packet of size 84 bytes from device zvmip0
19:28:06 HHC00979D QETH: Packet: +0000> 45000054 6AC40000 7E01FA40 0A00C821  E..Tj...~..@...! ....|D..=.. ..H.
19:28:06 HHC00979D QETH: Packet: +0010> 0A00FB82 0800429A 0B7804B7 35CA5D5C  ......B..x..5.]\ ...b..........)*
19:28:06 HHC00979D QETH: Packet: +0020> 00000000 443D0F00 00000000 10111213  ....D=.......... ................
19:28:06 HHC00979D QETH: Packet: +0030> 14151617 18191A1B 1C1D1E1F 20212223  ............ !"# ................
19:28:06 HHC00979D QETH: Packet: +0040> 24252627 28292A2B 2C2D2E2F 30313233  $%&'()*+,-./0123 ................
19:28:06 HHC00979D QETH: Packet: +0050> 34353637                             4567             ....
19:28:07 HHC00913D 0:0E22 QETH: Receive IPv4 packet of size 84 bytes from device zvmip0
19:28:07 HHC00979D QETH: Packet: +0000> 45000054 6AC70000 7E01FA3D 0A00C821  E..Tj...~..=...! ....|G..=.....H.
19:28:07 HHC00979D QETH: Packet: +0010> 0A00FB82 0800FC16 0A4E0967 36CA5D5C  .........N.g6.]\ ...b.....+....)*
19:28:07 HHC00979D QETH: Packet: +0020> 00000000 863A0F00 00000000 10111213  .....:.......... ....f...........
19:28:07 HHC00979D QETH: Packet: +0030> 14151617 18191A1B 1C1D1E1F 20212223  ............ !"# ................
19:28:07 HHC00979D QETH: Packet: +0040> 24252627 28292A2B 2C2D2E2F 30313233  $%&'()*+,-./0123 ................
19:28:07 HHC00979D QETH: Packet: +0050> 34353637                             4567             ....
19:28:07 HHC00913D 0:0E22 QETH: Receive IPv4 packet of size 84 bytes from device zvmip0
19:28:07 HHC00979D QETH: Packet: +0000> 45000054 6AC90000 7E01FA3B 0A00C821  E..Tj...~..;...! ....|I..=.....H.
19:28:07 HHC00979D QETH: Packet: +0010> 0A00FB82 08005698 0B7804B8 36CA5D5C  ......V..x..6.]\ ...b...q......)*
19:28:07 HHC00979D QETH: Packet: +0020> 00000000 2F3E0F00 00000000 10111213  ..../>.......... ................
19:28:07 HHC00979D QETH: Packet: +0030> 14151617 18191A1B 1C1D1E1F 20212223  ............ !"# ................
19:28:07 HHC00979D QETH: Packet: +0040> 24252627 28292A2B 2C2D2E2F 30313233  $%&'()*+,-./0123 ................
19:28:07 HHC00979D QETH: Packet: +0050> 34353637                             4567             ....
19:28:08 HHC03991D 0:0E20 QETH: Halting read device
19:28:08 HHC03991D 0:0E20 QETH: Read device halted
19:28:08 HHC03991D 0:0E22 QETH: Halting data device
19:28:08 HHC03991D 0:0E22 QETH: Activate Queues: QDSIG_HALT received
19:28:08 HHC03991D 0:0E22 QETH: Activate Queues: Exit
19:28:08 HHC03991D 0:0E22 QETH: Data device halted
19:28:27 HHC00814I Processor CP03: SIGP CPU reset                        (0C) CP00, PARM 00000000002DA5F8: CC 0
19:28:27 HHC00814I Processor CP03: SIGP CPU reset                        (0C) CP01, PARM 00000000002DA5F8: CC 0
19:28:27 HHC00814I Processor CP03: SIGP CPU reset                        (0C) CP02, PARM 00000000002DA5F8: CC 0
19:28:27 HHC00814I Processor CP03: SIGP Set architecture mode            (12) CP03, PARM 0000000000000000: CC 0
19:28:27 HHC00811I Processor CP03: architecture mode ESA/390
```

My guess: It looks like the VM is trying to send something Hercules does not know what to do with. Instead of dropping it, it seems to try to send it out the wire and that failes with Invalid argument, causing the whole system to go down.

Let me know if you need more data.

EDIT: Everything is running in Layer-3 mode.

Thanks,

**Comment by ivan-w** [comment]
I'm having a problem understanding the setup ! 
What is the host system ? What is the guest system ? Is there other virtualization layers ? Are you running z/Linux ubuntu under z/VM under hercules ? Are you using a z/VM VSWITCH ?

**Comment by bluecmd** [comment]
Definitely a good question :-).

So the full setup is:
- Intel NUC running VMware vSphere ESXi
- A Debian 9 as a VM running SDL Hyperion
- Hyperion running an OS that is not unlike older z/VM (so let's assume it is, say z/VM 5.3)
- z/VM running a VSWITCH in L-3 as well as running Ubuntu Bionic

On the vswitch:
- The VSWITCH has an QETH/OSA adapter attached as a physical adapter.
- The VM OS's TCP/IP stack is attached to the VSWITCH.
- The Ubuntu VM has a NIC on the VSWITCH as well and is being told to use it in Layer-3 mode.

Let me know if you require more details.

**Comment by bluecmd** [comment]
Fwiw, this patch resolved the issue for me - but I doubt it's the proper solution :-). At minimum it should log that a packet was dropped I guess.

```patch
diff --git a/qeth.c b/qeth.c
index aab6fe80..fe12a458 100644
--- a/qeth.c
+++ b/qeth.c
@@ -3402,7 +3402,7 @@ static QRC write_buffered_packets( DEVBLK* dev, OSA_GRP *grp,
 
                      if (iPktVer == 4) STRLCPY( cPktType, " IPv4" );
                 else if (iPktVer == 6) STRLCPY( cPktType, " IPv6" );
-                else                   STRLCPY( cPktType, " ????" );
+                else                   return 0;
 
                 // HHC00910 "%1d:%04X %s: Send%s packet of size %d bytes to device %s"
                 WRMSG( HHC00910, "D", LCSS_DEVNUM,
```

**Comment by bluecmd** [comment]
Digging some more, the above patch only works when having debug enabled (doh!), but when fixing that I found this part:

https://github.com/SDL-Hercules-390/hyperion/blob/26e18fe3a17b5bb955d06d509be4cd7ee2c39c2e/qeth.c#L3340-L3377

This seems like what is happening, so maybe somebody else found this issue but for whatever the reason that fix is not triggering in my case.

**Comment by Fish-Git** [comment]
> As it is initializes the interfaces, the host system crashes.

Can you tell us _where?_ (gdb backtrace?)

**Comment by bluecmd** [comment]
Sorry Fish, in this case the "host system" is z/VM. It dumps and re-IPLs. Hercules itself chuggs along fine.

**Comment by Fish-Git** [comment]
> Sorry Fish, in this case the "host system" is z/VM. It dumps and re-IPLs. Hercules itself chuggs along fine.

Ah. Okay. Never mind then. I misunderstood. Sorry. My bad.

**Comment by Fish-Git** [comment]
It appears to me the root of our problem is the following:

> ... However, after  the guest has received an NA with a link local address every IPv6   packet from the guest is an Ethernet frame containing the IPv6 packet. Perhaps that's how OSD's actually work?

and:

> ```
> 12:09:00 HHC00911E 0:0E22 QETH: Error writing to device zvmip0: 22 Invalid argument                            
> 12:09:00 HHC00007I Previous message from function 'write_packet' at qeth.c(2749)
> ```

Based on the QETH Debugging packet trace it's obvious the packet is actually an _Ethernet Frame_, not an IP Packet. Thus the reason behind the unsurprising `Invalid argument` error: you can't write Ethernet Frames to tun devices! (Duh!) Only _IP Packets_ can be written to tun devices. Ethernet Frames must be written to _tap_ devices, not tun devices.

Thus it would seem to me that in order to properly support Layer 3, we need to _also_ have a corresponding _tap_ device too, so we can write Ethernet Frames to it when we need to? (like in this case)

Or am I off track here?

**Comment by Fish-Git** [comment]
Does the following seem to be a reasonable replacement for the above mentioned problematic code segment?

```C
/*                      PROGRAMMING NOTE                              */
/*                                                                    */
/* I know the following looks pretty weird but it seems to be         */
/* necessary when using IPv6 over layer 3. IPv6 uses ICMPv6 Neighbor  */
/* Solicitation (NS) & Neighbor Advertisment (NA) to determine the    */
/* link layer address (i.e. Ethernet MAC) for an IPv6 address. When   */
/* the guest sends out a NS, this function sends the packet over the  */
/* tun to the host, whereupon the host duly ignores the packet. Hence */
/* this function, and function process_l3_icmpv6_packet, responds to  */
/* the NS with a NA. It seems that the NA must contain a link local   */
/* address, otherwise the guest ignores the packet. However, after    */
/* the guest has received an NA with a link local address every IPv6  */
/* packet from the guest is an Ethernet frame containing the IPv6     */
/* packet. Perhaps that's how OSD's actually work? IPv6 packets to    */
/* the guest don't need to be Ethernet frames.                        */
/*                                                                    */
/* Originally the whole of this section of code was surrounded by an  */
/* '#if defined(ENABLE_IPV6)' and '#endif'. However, implementing     */
/* zLinuz layer 3 support showed that zLinux emmitted IPv4 ARP        */
/* frames, which if sent to the tun interface, upset the tun, hence   */
/* the following special handling.                                    */
/*                                                                    */
if (grp->l3)
{
  /* Might this be a L2 IPv6 Ethernet Frame? (and not an L3 IP packet?)
    (Refer to PROGRAMMING NOTE just above regarding IPv6 over layer 3)
  */
  if (HDR_ID_LAYER2 == hdr_id)
  {
    eth = (ETHFRM*) pkt;
    FETCH_HW( hwEthernetType, eth->hwEthernetType );
    if (1
        && ETH_TYPE_IP   != hwEthernetType
        && ETH_TYPE_IPV6 != hwEthernetType
    )
    {
      /* Can't write L2 Ethernet frame to L3 tun device! */
      dev->qdio.dropcnt++;
      if (grp->debugmask & DBGQETHDROP)
      {
        // "%1d:%04X %s: %s: Output dropped: %s"
        WRMSG( HHC03811, "W", LCSS_DEVNUM,
          dev->typname, grp->ttifname, "L2 frame on tun device" );
      }
      continue; /* (don't write this packet) */
    }

    /* Bump past L2 Ethernet header to actual L3 IP packet */
    pkt    += sizeof( ETHFRM );
    pktlen -= sizeof( ETHFRM );
  }
}
```

After studying the code is occurred to me that perhaps the reason Ian's (@mcisho) attempted fix wasn't working was maybe because: 1) he wasn't checking if it was an actual Ethernet Frame before testing to see where it was coming from, and 2) he was only dropping it if the source MAC was the OSA interface MAC.

1 was easy enough to test for, and 2 doesn't make any sense to me at all. Why should we care _where_ the frame says it came from? It's something the guest specifically (purposely) placed into its output buffer to be written to the device (network) so we should make our best effort to try and do that. We shouldn't care where (from what MAC) the guest says the frame came from. It's allowed to lie! It can "spoof" packets if it wants! Thus the test for the source MAC is bogus in my opinion so I removed it.

I'd be very curious as to whether the above works any better for you or not.

Thanks.

Feedback encouraged and appreciated.

**Comment by bluecmd** [comment]
That would work, but might be easier to just do a tap always regardless of the layer mode and construct the L2 header for the cases where it's missing (L3 + IPv4 it seems).

Alternatively, handle the L3 + IPv6 case by dropping the Ethernet header. Surely sending IPv6 is fine on a tun device if properly configured.

Having *both* interfaces seems like a really hard thing to get working correctly and will probably result in people having weird L2 partitions.

**Comment by Fish-Git** [comment]
> Thus it would seem to me that in order to properly support Layer 3, we need to _also_ have a corresponding _tap_ device too, so we can write Ethernet Frames to it when we need to? (like in this case)

Which, upon further reflection might not be true! (Refer to my [comment above](https://github.com/SDL-Hercules-390/hyperion/issues/184#issuecomment-462362859) where I offered a possible fix/workaround)

**Comment by Fish-Git** [comment]
> That would work, but might be easier to just do a tap always regardless of the layer mode and construct the L2 header for the cases where it's missing

Actually that's _not_ easier since we'd then have to deal with routing in order to determine which destination MAC to put into the Ethernet header.

> Having _both_ interfaces seems like a really hard thing to get working correctly on the end-user side and will probably result in people having weird L2 partitions.

I agree, which is why afterwards, after thinking about it some more, I decided maybe the best approach was the one I then proposed afterwards instead: just fix Ian's code by, as you suggested, simply dropping the Ethernet header (or the entire L2 frame if it's not an IP packet).

> The code linked above does look sane from a passing glance. I'm more than happy to test it if that adds value to the discussion.

Well _DUH!_ &nbsp;`:)`

_You're_ the one with the problem. I'm just trying to help you out by offering a possible fix for it. If you're no longer interested in getting it fixed then by all means feel free to ignore my offering and live with your problem. (sheesh!)&nbsp;`;-)`

**Comment by bluecmd** [comment]
@Fish-Git Hah, I didn't mean it like that -- more like I wasn't sure if the code was at a stage where it would even compile or of it was a pseudo-code-esque.

I'll test in a bit, I'll do a bit of traveling in the coming days but should have time to give it a spin.

**Comment by mcisho** [comment]
> After studying the code is occurred to me that perhaps the reason Ian's (@mcisho) attempted fix wasn't working was maybe because: 1) he wasn't checking if it was an actual Ethernet Frame before testing to see where it was coming from, and 2) he was only dropping it if the source MAC was the OSA interface MAC.

At the time a new and unexpected situation had arisen, so I wrote a specific solution until such time as information became available that would suggest what the more general solution should be.

> I'd be very curious as to whether the above works any better for you or not.

So will I! At the time I wasn't sure whether these ethernet frames had a qeth layer2 or a layer3 header (and I'm still not, as we only trace what we send out to the tun/tap, not what comes out of (or goes into?) the qeth device (that's what the DBGQETHDATA mask was intended for)).

**Comment by mcisho** [comment]
p.s. I also wan't sure whether any other protocols, e.g. ARP, might appear, which is why I didn't drop the packets, but let them through so that there contents would be traced. I also didn't expect it would bring down the guest OS!

**Comment by bluecmd** [comment]
I managed to put in some time to do a quick test. I applied the @Fish-Git's code above on my dirty workspace, but the dirty parts should not change the outcome.
```
HHC00910D 0:0E22 QETH: Send ???? packet of size 90 bytes to device zvmip0                                
HHC00979D QETH: Packet: +0000< 33330000 00160200 00000003 86DD6000  33............`. ............f.-.    
HHC00979D QETH: Packet: +0010< 00000024 00010000 00000000 00000000  ...$............ ................    
HHC00979D QETH: Packet: +0020< 00000000 0000FF02 00000000 00000000  ................ ................    
HHC00979D QETH: Packet: +0030< 00000000 00163A00 05020000 01008F00  ......:......... ................    
HHC00979D QETH: Packet: +0040< 6F870000 00010400 0000FF02 00000000  o............... ?g..............    
HHC00979D QETH: Packet: +0050< 00000000 0001FF00 0003               ..........       ..........          
HHC00979D QETH: Packet: +0050< 00000000 0001FF00 0003               ..........       ..........                  
HHC00911E 0:0E22 QETH: Error writing to device zvmip0: 22 Invalid argument                                       
HHC00007I Previous message from function 'write_packet' at qeth.c(2749)                                          
HHC00809I Processor CP02: disabled wait state 0002000000000000 0000000000009005                                  
HHC00809I Processor CP01: disabled wait state 0002000000000000 0000000000009005                                  
HHC00809I Processor CP00: disabled wait state 0002000000000000 0000000000009005                                  
HHC03991D 0:0E20 QETH: Halting read device                                                                       
HHC03991D 0:0E20 QETH: Read device halted                                                                        
HHC03991D 0:0E22 QETH: Halting data device                                                                       
HHC03991D 0:0E22 QETH: Activate Queues: QDSIG_HALT received                                                      
HHC03991D 0:0E22 QETH: Activate Queues: Exit                                                                     
HHC03991D 0:0E22 QETH: Data device halted                                                                        
```

So no cigar :-(. The final diff looked like [this](https://gist.github.com/bluecmd/65da56bfa5dc78a2a8964a5539fd58e7).

**Comment by mcisho** [comment]
Hmm... having added the bit of code to display the data coming out of the qeth, in this example (a ping reply) we have a layer3 header (32 bytes), followed by the ethernet header (12 bytes), followed by the IPv6 packet (104 bytes).

18:44:04 HHC00981D 0:2328 QETH: Accept data of size 150 bytes from guest
18:44:04 HHC00979D QETH: data: +0000< 01960000 00000000 00760000 00000000  .........v...... .o..............
18:44:04 HHC00979D QETH: data: +0010< FD000000 00000002 00000000 02500222  .............P." .............&..
18:44:04 HHC00979D QETH: data: +0020< AA2B92AA 5E400200 5E94EAD1 86DD600D  .+..^@..^.....`. ..k.; ..;m.Jf.-.
18:44:04 HHC00979D QETH: data: +0030< 7CF40040 3A40FD00 00000000 00020000  |..@:@.......... @4. . ..........
18:44:04 HHC00979D QETH: data: +0040< 00000250 0221FD00 00000000 00020000  ...P.!.......... ...&............
18:44:04 HHC00979D QETH: data: +0050< 00000250 02228100 A0A77A4B 000364B4  ...P."....zK..d. ...&..a..x:.....
18:44:04 HHC00979D QETH: data: +0060< 615C0000 0000D7C2 04000000 00001011  a\.............. /*....PB........
18:44:04 HHC00979D QETH: data: +0070< 12131415 16171819 1A1B1C1D 1E1F2021  .............. ! ................
18:44:04 HHC00979D QETH: data: +0080< 22232425 26272829 2A2B2C2D 2E2F3031  "#$%&'()*+,-./01 ................
18:44:04 HHC00979D QETH: data: +0090< 32333435 3637                        234567           ......        

 Sorry Fish, your proposed solution won't work. However, all might not be lost. When outbound IPv6 packets without the ethernet header are seen, the layer3 header has only the HDR3_FLAGS_IPV6 flag on, whereas when outbound IPv6 packets with the ethernet header are seen, the layer3 header has 
both the HDR3_FLAG_IPV6 and the HDR3_FLAG_PASSTHRU flags on. Adding the following to the earlier case HDR_ID_LAYER3: might be the solution:-
    if ((o3hdr->flags & HDR3_FLAG_IPV6) && (o3hdr->flags & HDR3_FLAG_PASSTHRU))
    {
        pkt += sizeof(ETHFRM);
        pktlen -= sizeof(ETHFRM);
     }

Cheers, Ian

**Comment by mcisho** [comment]
Fish, I've changed my proposal, but I've tested it and it works, would you like me to commit my changes? They include the display of the data accepted from the qeth device. At some point I will add the display of the data presented to the qeth device.

**Comment by Fish-Git** [comment]
> ```
> 18:44:04 HHC00981D 0:2328 QETH: Accept data of size 150 bytes from guest
> 18:44:04 HHC00979D QETH: data: +0000< 01960000 00000000 00760000 00000000  .........v...... .o..............
> 18:44:04 HHC00979D QETH: data: +0010< FD000000 00000002 00000000 02500222  .............P." .............&..
> 18:44:04 HHC00979D QETH: data: +0020< AA2B92AA 5E400200 5E94EAD1 86DD600D
> (...snipped...)
> ```

Ah. Yes! Interesting...

> Adding the following to the earlier `case HDR_ID_LAYER3:` might be the solution:

Yep! As soon as I saw your above debug trace I had the exact same thought! _Thank you_, Ian! Your patch seems much more reasonable (i.e. correct) than mine. I say go with it!

**Comment by Fish-Git** [comment]
> Would you like me to commit my changes?

_**Abso-fricking-lutely!** Duh!_ Why do you even have to ask? _You're a developer for crying out loud!_&nbsp;`:)`

Team members (developers with commit access to the repository) should be free to commit whatever fricking change they feel is correct/proper and shouldn't need to ask for my permission beforehand(*). Sheesh! You're as bad as Jürgen.&nbsp;`;-)`
___
(*) The only time you _might_ want to "ask for permission" would be if your change happened to be controversial in some unusual way, which isn't the case here. Besides, if a developer's change was felt to be somewhat controversial in nature, then they shouldn't be asking _just me_ for permission to commit it. Rather, they should be asking _all_ team members for constructive feedback regarding, not just for my feedback. Okay? Are we cool? I don't want my fellow team members being afraid to make commits and feeling they need to ask for my permission beforehand! Sheesh. Just do it!&nbsp;`:)`

**Comment by mcisho** [comment]
See commit 6b2dccfc

I wasn't asking permission as such, I was just clarifying that I wasn't going to clash with something that you might have been in the process of working on.

The change you suggested earlier included code to drop the packet with a message. I haven't implemented anything like that, I would like to see what happens for a while.

**Comment by Fish-Git** [comment]
> See commit [6b2dccf](https://github.com/SDL-Hercules-390/hyperion/commit/6b2dccfc1dae2ed9e3b26f76ecac27f84c07e244)

Thanks, Ian! Much appreciated.

> I wasn't asking permission as such, I was just clarifying that I wasn't going to clash with something that you might have been in the process of working on.

Ah. Okay. Sorry for the misunderstanding. (And no, for the record, I'm not working on anything in that area.)

> The change you suggested earlier included code to drop the packet with a message. I haven't implemented anything like that, I would like to see what happens for a while.

Sounds fine to me!

(p.s. Christian? (@bluecmd) Please let us know whether Ian's above commit resolves your problem or not. If it does, I'd like to close this issue. Thanks!)

**Comment by bluecmd** [comment]
Looks good! The debugging output seems much more useful now as well on a first glance, nice work!

Tried it out and IPv6 packets are coming in and out. IPv6 doesn't work over the L3 interfaces due to broken neighbor discovery (I confirmed that it works over L2 however) but that's maybe a separate issue? At least nothing crashes now :-). It certainly didn't work with my patch that just dropped the packets, so it's definitely an improvement.

Fwiw, this is how tshark looks like on the TUN interface from z/VM (and the Ubuntu VM indirectly). Ubuntu VM has fd00:1::2/64 and the Hercules host system has fd00:1::1/64:

```
   83 62.974693138    fd00:1::2 → ff02::1:ff00:1 ICMPv6 72 Neighbor Solicitation for fd00:1::1 from 02:00:00:00:00:03
   84 62.974713202    fd00:1::1 → fd00:1::2    ICMPv6 64 Neighbor Advertisement fd00:1::1 (rtr, sol, ovr)
```

From inside the VM:

```
   41 59.398134357    fd00:1::2 → ff02::1:ff00:1 ICMPv6 86 Neighbor Solicitation for fd00:1::1 from 02:00:00:00:00:03
```

I.e. the reply is not seen.

I also have a case of IPv4 DUPs over the L3 interface, but that has "always" been the case:
```
bluecmd@y:~$ ping 10.0.251.140 # Ubuntu VM inside z/VM over L3 and VSWITCH
PING 10.0.251.140 (10.0.251.140) 56(84) bytes of data.
64 bytes from 10.0.251.140: icmp_seq=1 ttl=64 time=1.38 ms
64 bytes from 10.0.251.140: icmp_seq=1 ttl=64 time=2.28 ms (DUP!)
64 bytes from 10.0.251.140: icmp_seq=2 ttl=64 time=1.24 ms
64 bytes from 10.0.251.140: icmp_seq=2 ttl=64 time=2.15 ms (DUP!)
--- 10.0.251.140 ping statistics ---
2 packets transmitted, 2 received, +2 duplicates, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 1.242/1.767/2.288/0.462 ms
bluecmd@y:~$ ping 10.0.251.130 # z/VM
PING 10.0.251.130 (10.0.251.130) 56(84) bytes of data.
64 bytes from 10.0.251.130: icmp_seq=1 ttl=60 time=4.40 ms
64 bytes from 10.0.251.130: icmp_seq=2 ttl=60 time=7.10 ms
```

Anyway, these are most likely follow-up issues so I'll close this bug for now.

**Comment by Fish-Git** [comment]
> Looks good! ...

> ... so I'll close this bug for now.

Thanks, Christian!
