### ISSUE TITLE
POLL: Should CTCT support also be dropped?

### ISSUE THREAD

**Issue by Fish-Git** [SDL-Hercules-390/hyperion#19]
Hercules currently supports many different networking device types: 
&nbsp;
&nbsp;

Type | Description
------------ | -------------
2703 | Binary Synchronous (BSC/Bisync) communication line
_**3088**_ | _(generic type used in old/deprecated format device statements)_
3705 | Communications Controller running NCP
CTCE | Enhanced Channel to Channel Emulation via TCP connection (true CTCA)
CTCI | Channel to Channel link to host TCP/IP stack
_**CTCT**_ | _Channel to Channel Emulation via TCP connection_
LCS | LAN Channel Station Emulation
OSA | _(synonym for QETH)_
OSD | _(synonym for QETH)_
PTP | MPCPTP and/or MPCPTP6 Point-To-Point (PTP)
QETH | OSA Express
_**VMNET**_ | _SLIP (Serial Line Internet Protocol)_

&nbsp;
&nbsp;
Support for 3088 and  VMNET are definitely going to be dropped, but what about, for example, CTCT? Does anyone actually use CTCT today?

As I recall it was created in an attempt to provide pseudo Channel-to-Channel support, i.e. the ability for two (or more??) Hercules systems to be able to directly communicate with one another just as a true CTC device did.

Unfortunately, as I also recall, it never did work right, and has since been replaced with CTCE, which **_does_** provide _true_ CTC support, allowing you to connect multiple Hercules systems together in a sysplex.
&nbsp;

_**Q1:** &nbsp; Which Hercules networking communication device types do you personally still use?_

_**Q2:** &nbsp; Would anyone mind if support for CTCT were to be dropped?_

&nbsp;
Thanks!

**Comment by Peter-J-Jansen** [comment]
A1: I use CTCE (of course, I’m slightly prejudiced !), LCS, QETH, and CTCI

A2: No I wouldn’t mind (but then again I don’t really understand what CTCT would be used for)

 

Cheers,

Peter J.

**Comment by Fish-Git** [comment]
Support for 3088, CTCI-W32, CTCT and VMNET has been dropped.

Issue closed by commit 8946111985a2ec3b0ff92db87ec48ed91a4ad727.

**Comment by Juergen-Git** [comment]
Hi Fish

Apparently, I'm a little late to answer this question. I must have overlooked it back then. Nonetheless:

A1: I'm using CTCE, LCS, QETH and **CTCT**
A2: Yes, I do mind. The TK4- MVS 3.8j distribution comes with MVSDDT pre-installed and ready to use. MVSDDT is _the_ debugger of choice for MVS 3.8j systems and relies heavily on the CTCT device.

I've asked Peter whether the CTCE would be able to provide that specific functionality (simply driving a static TCP connection for READ and WRITE), in which case I'd of course go down this road. But if that's not feasible (what I'm assuming) I'd really appreciate getting the CTCT back...

Cheers
Jürgen

**Comment by Fish-Git** [comment]
> A1: I'm using CTCE, LCS, QETH and **CTCT**
> A2: Yes, I do mind. The TK4- MVS 3.8j distribution comes with MVSDDT pre-installed and ready to use. MVSDDT is _the_ debugger of choice for MVS 3.8j systems and relies heavily on the CTCT device.

Since from the sound of things you obviously very much need it, I would have absolutely no problem whatsoever with you bringing it back again!

**Comment by Juergen-Git** [comment]
CTCT has been reinstated.
Issue closed by commit [6eeb551](https://github.com/SDL-Hercules-390/hyperion/commit/6eeb5518bc97419bd87540608054b937d29149d2)
