### ISSUE TITLE
z/VM 6.3 and 6.2 crash (along with Hyperion) when IPLing two or more  guest machines at the same time

### ISSUE THREAD

**Issue by moshix** [SDL-Hercules-390/hyperion#190]
I have SDL latest (as of this morning). z/VM comes up normal, and then when I IPL two z/OS guests at the same time, quite reliably Hercules will crash hard. The CP00 indicator is pegged at full use (********** all the way) but the MIPS indicator shows 0. Only kill -9 makes hercules come down again. 

I sent by email a video I took with my phone of the Hercules panel so you can see for yourselves:

* [IMG_0713.zip](https://github.com/SDL-Hercules-390/hyperion/files/2911436/IMG_0713.zip)

Thanks

m

**Comment by moshix** [comment]
And just had another crash again. Second in 2 hours:

12:16:28 HCPWRP963I SHUTDOWN STEP SVACV - ACTIVATE TERMINATION SAVE AREAS                                                                 +
12:16:29 HCPWRP963I SHUTDOWN STEP CHMOF - DISABLE CHANNEL MEASUREMENT
12:16:29 HCPWRP963I SHUTDOWN STEP ISHDA - DISABLE ALL DEVICES
12:16:30 HCPWRP963I SHUTDOWN STEP DMPDK - TAKE DUMP
12:16:27 HCPDMP908I SYSTEM FAILURE ON CPU 0000, CODE - IFI004
12:16:27 HCPDMP908I 2019-02-16 SYSTEM ZVM63
12:16:30 HCPDMP9252I DUMPING TO DASD
12:16:39 HCPDMP9260I 25% OF THE DUMP HAS BEEN COMPLETED
12:16:44 HCPDMP9260I 50% OF THE DUMP HAS BEEN COMPLETED
12:16:48 HCPDMP9260I 75% OF THE DUMP HAS BEEN COMPLETED
12:16:54 HCPDMP9261I DUMP COMPLETE ON 2019-02-16, CODE IFI004
12:16:54 HCPWRP963I SHUTDOWN STEP CKPSH - TAKE A CHECKPOINT
12:16:54 HCPWRP963I SHUTDOWN STEP OPRCK - SAVE OPERATOR CONSOLE LIST
12:16:55 HCPWRP963I SHUTDOWN STEP MCWMD - DETERMINE MACHINE CHECK STATUS
12:16:55 HCPWRP963I SHUTDOWN STEP SDVRS - RESET IBM DASD CU CHARACTERISTICS
12:16:56 HCPWRP963I SHUTDOWN STEP SGQXX - RESET OTHER PROCESSORS
HHC00814I Processor CP00: SIGP CPU reset                        (0C) CP01, PARM 00000000004C7AD0: CC 0
12:16:56 HCPWRP9277I SYSTEM TERMINATION COMPLETE, ATTEMPTING RESTART
12:16:56 HCPWRP9277I 2019-02-16 SYSTEM ZVM63

**Comment by moshix** [comment]
another core dump of hercules right now. this time with this output. something is not quite right in the land of SDL Hyperion:

**Comment by moshix** [comment]
Some more color to this problem:
z/VM 6.3 and 6.2 crash now almost reliably if I IPL two guest machines with OS/390 or z/OS guests (31  bit or 64 bit, doesn't matter). You can try by IPLing two or three guest VMs at the same time. PROG04 almost every time. 

with SDL hyperion of ca. early December 2018 I had far fewer crashes, so it seems to me there is a regression in Hyperion in the last two months. 

thanks a lot

M

**Comment by ivan-w** [comment]
Don't get me wrong, not dismissing the issue ;)
..
but
...
There is not much to chew on with this... Sorry... I'm going to need a bit more information... 
- There is no such thing as a PROG04 Abend (but I presume you mean PRG004 - Protection Exception in CP)
- Is this IFI004 or PRG004 ? (IFI004 is an unexpected I/O completion interrupt while there was no outstanding I/O)
- Is this about hercules crashing ?
- Any dump ? Does the OPERATNS user have a dump file ? Did you load it and looked at the dump ? (If you need help with IPCS, DUMPLOAD and VMDMPTL, you can ask)...
- What is the host system (Linux I am assuming here, but which distro ?) ? What is the compiler version ?
- Do you have any crash that doesn't involve using a MVS style guest ? (Just asking.. I am OS blind)
- If you have a CP Dump, can you transfer it using VMFPLC2 to a HET file and put the relevant file in some place I can retrieve it ? (privately if it contains sensitive information).
- Apparently you did a "make dist-strip" - so all references to any hercules symbols where lost... can you run a version of hercules which do not have the symbols stripped (it doesn't affect performance, just the file sizes).

I'm interested as to why you are getting those kind of issues ! 

--Ivan

**Comment by moshix** [comment]
Replies below:


> Don't get me wrong, not dismissing the issue ;)
> ..
> but
> ...
> There is not much to chew on with this... Sorry... I'm going to need a bit more information...
> 
> * There is no such thing as a PROG04 Abend (but I presume you mean PRG004 - Protection Exception in CP)

ok, sorry, I misquoted PRG004. 

> * Is this IFI004 or PRG004 ? (IFI004 is an unexpected I/O completion interrupt while there was no outstanding I/O)

IFI004 mostly, sometimes PRG004

> * Is this about hercules crashing ?

first z/VM crashes, and then Hercules gets stuck hard, as expained below

> * Any dump ? Does the OPERATNS user have a dump file ? Did you load it and looked at the dump ? (If you need help with IPCS, DUMPLOAD and VMDMPTL, you can ask)...

Will send you instructions how to get  a binary download of the dump by seperate email. 

> * What is the host system (Linux I am assuming here, but which distro ?) ? What is the compiler version ?

Linux Ubuntu 16.04 64bit, gcc version 5.4.0 
> * Do you have any crash that doesn't involve using a MVS style guest ? (Just asking.. I am OS blind)

excellent question: the crashes happen only with MVS style OSs

> * If you have a CP Dump, can you transfer it using VMFPLC2 to a HET file and put the relevant file in some place I can retrieve it ? (privately if it contains sensitive information).

see seperate email on how to obtain the dump

> * Apparently you did a "make dist-strip" - so all references to any hercules symbols where lost... can you run a version of hercules which do not have the symbols stripped (it doesn't affect performance, just the file sizes).

will do. 
> 
> I'm interested as to why you are getting those kind of issues !
> 
> --Ivan

**Comment by ivan-w** [comment]
Can't promise anything ! But will look into it when I can !

**Comment by moshix** [comment]
Thank you Ivan. 

I definitely see more crashes with the SDLs of the last two months than the ones from November 2018 to December 2018. 

Circumstantial evidence points to SDL and thru it z/VM crashing more often the slower the disks drives in Linux are. On my laptop with NVME disk, i have not yet managed to make SDL and z/VM crash. But on my NAS /NFS/iSCSI based disks, the crashes happen more often. So, it could be a timing, or pending channel command answer issue. 

thanks

**Comment by moshix** [comment]
Ivan

You probably didn't have the chance to study the dumps I sent you. But I think the SYMPTOM comand of the z/VM dump analysis tool is giving already very good indications. Here is what it says:

IFI004 HCPIFIIN was attempting to do one of the following: 1) Transfer control  
       to the interrupt response address specified in the IORBK field IORIRA,   
       but it contained zeros. 2) Call the emergency error recovery procedure,  
       but was unable to resolve its address.                                   
                                                                                
>>> symptom                                                                     
Symptom Record for Incident D51AA4B5 B3C09SYM                                   
                                                                                
TOD Clock . . D51AA4B5B3C09062         Date. . . . . 10/19/18                   
Time Zone . . -05.00.00                Time. . . . . 14:35:47.799049            
CPU model . . 2097                     Base SCP. . . 5741                       
CPU Serial. . 1132EF                   NodeID. . . . ZVM63                      
Dump Name . . PRB00001 MDMP0001 T1     Dump Type . . CPDUMP                     
Comp ID . . . 5741A07                  Ver/Rel/Mod . V06R03M0                   
Dump format . 64-BIT                                                            
------------------------------------------------------------                    
Primary Symptom Strings                                                         
              PIDS/5741A0702           (Component ID)                           
              AB/SIFI004               (Abend Code)                             
              RIDS/IFI                 (Failing Module)                         
              REGS/FFFFF               (Register/PSW Info)                      
------------------------------------------------------------                    
Section 5 Data:                                                                 
              USERID DUMPED: SYSTEM                                             
              DUMP RECEIVER: OPERATNS                                           
              SPOOLID: 0004                                                     
------------------------------------------------------------                    
Last trace entry on abending processor                                          
7FBE1E00 14:35:47  IFI004 Hard Abend svc 00 at HCPIFI+1C00                      
                   opsw 04040000_0030FAD0 svcilc 0002                           
------------------------------------------------------------                    
Abend  Description                                                              
IFI004 HCPIFIIN was attempting to do one of the following: 1) Transfer control  
       to the interrupt response address specified in the IORBK field IORIRA,   
       but it contained zeros. 2) Call the emergency error recovery procedure,  
       but was unable to resolve its address.                                   
====>                                                                           
1=help 2=inpt 3=file 4=cmd- 5=cmd+ 6=xed 7=scb 8=sf 9=del 10=   11=ret 12=?     

REGS command:

>>> regs                                                                        
R0-3 4A80005D_00000049 00000000_00100000 00000000_00F0E000 00000000_0C000001    
R4-7 00000000_00800000 00000000_00000000 00000000_00E4C7D0 00000000_00000518    
R8-B 00000001_00E4C720 00000000_0030EED0 00000000_00F3E558 00000000_00100000    
RC-F 00000000_0030DED0 00000000_00000038 00000000_8030E8F6 00000000_00000000    
                                                                                
C0-3 00000000_9404EE60 00000000_00108007 00000000_005030C0 00000000_00000000    
C4-7 00000000_00000000 00000000_7FF79000 00000000_C0000000 00000000_00106101    
C8-B 00000000_00000000 00000000_00000000 00000000_00000000 00000000_00000000    
CC-F 00000000_7FBE1E21 00000000_00108007 00000000_1F000000 00000000_00000000    
                                                                                
A0-7  00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000   
A8-15 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000   
                                                                                
Floating Point Control Register 07E61000                                        
F0-3   0000000000000000  0000000000000000  0000000000000000  0000000000000000   
F4-7   0000000000000000  0000000000000000  0000000000000000  0000000000000000   
F8-B   0000000000000000  0000000000000000  0000000000000000  0000000000000000   
FC-F   0000000000000000  0000000000000000  0000000000000000  0000000000000000   
                                                                                
TOD Clock D51AA4B5 B3C09062   Clock Comparator D51AA4B7 985DD800                
                                                                                
CPU Timer 7FFFFFFC EB421700                                                     
                                                                                
PFX VALUE 00B60000                                                              
                                                                                
Restart  Old 00000000 00000000 00000000 00000000                                
         New 04F4F000 80000000 00000000 005616E0 HCPSVF@1                       
External Old 07064000 80000000 00000000 00000000                                
         New 0404C000 80000000 00000000 00292AD0 HCPEXTEX                       
SVC      Old 04040000 80000000 00000000 0030FAD0 HCPIFI+1C00                    
         New 0404C000 80000000 00000000 005615B8 HCPSVF@0                       
Program  Old 04041000 80000000 00000000 005678AC HCPSVR+25EC                    
         New 0404C000 80000000 00000000 004964A0 HCPPRGIN                       
Machine  Old 00000000 00000000 00000000 00000000                                
         New 00000000 80000000 00000000 003A1690 HCPMCHIN                       
I/O      Old 07064000 80000000 00000000 00000000                                
         New 0404C000 80000000 00000000 0030DF90 HCPIFIIN             

DTQ command (logical addresses):

>>> dtq                                                                        
ABEND    set to IFI004                                                         
ABLIB    set to HCQAB630                                                       
ABSOLUTE set to OFF                                                            
ADDRESS  set to LOGICAL                                                        
ASCE     set to 00000000 00000020                                              
BITS     set to ON                                                             
BLKLIBS  set to HCQD8630 HCQB8630                                              
DEBUG    set to OFF                                                            
DVFMACRO set to OFF                                                            
FILES    set to 1                                                              
FRTRACE  set to  3                                                             
HIWORD   set to FULL                                                           
IMPDVF   set to OFF                                                            
INDENT   set to   0                                                            
INTBLOCK set to ON                                                             
LEVEL    set to 630                                                            
LINESIZE set to 80                                                             
MACLVL   set to   0                                                            
MNEMLIB  set to HCQMN630                                                       
PREFIX   set to ON                                                             
RECORDS  set to 43664                                                          
REGS     set to NOMAP    LONG                                                  
SEPARATE set to OFF                                                            
TRACE    set to ADDRESS CPU/TIME NOCODE DATA NOSLASH ASSERT                    
    LIB  set to Default> HCQTR630                                              
    TERM set to ADDRESS  ASCBK    ASTE     CARBK    CCTBK    COMBK    CPEBK    
                DUMPCODE ESW      EXTCODE  FCTBK    FRMTE    HASHID   IACCODE  
                IORBK    IPARML   IUCVB    IXBLK    JOINEVNT LATBK    LDEVNO   
                LNKBK    LOCBK    LOCK     LOCTHRED LSCH     MBHBK    MBRLONG  
                MBRSTATE MDEBK    MEMLONG  MODULE   MSGBK    NODBK    PARM     
                PATH     PGMBK    PGMCODE  PLMSYABO PLMSYSOC PTHBK    PXMACTN  
                PXMRQTY  PXMRQTYP RDEV     RDEVNO   RSCH     SCKBK    SID      
                SNABK    SSIMODE  SUBCH    SVCCODE  SYSSVCCD TCHBK    TCHKEY   
                TCHTKFMT TSKBK    USRBCSF  VDEV     VDEVNO   VMDBK    VOTERESP 
                VSCH     WEIBK    XCRBK    XITBK                               
    TYPE set to ACQUIRE  APPC     CALL     CCALL    CCS      CHANGE   CONTROL  
                EXIT     EXT      EXTERNAL FAILED   FREE     GLOBALLY HCPXLKUU 
                I/O      IO       ISFC     IUCV     LGRMM    LI/O     LIO      
====>                                                                          
1=help 2=inpt 3=file 4=cmd- 5=cmd+ 6=xed 7=scb 8=sf 9=del 10=   11=ret 12=?              


and finally the trace command:

>>> trace for 1                                                                
7FBE1E00 14:35:47  IFI004 Hard Abend svc 00 at HCPIFI+1C00                     
                   opsw 04040000_0030FAD0 svcilc 0002                          
>>> trace for 2                                                                
7FBE1E00 14:35:47  IFI004 Hard Abend svc 00 at HCPIFI+1C00                     
                   opsw 04040000_0030FAD0 svcilc 0002                          
7FBE1DE0 14:35:47  Obtain 73 dw (IOR) at 00F3E558 by HCPIFI+E48 vmdbk 00100000 
                   SYSTEM                              


As you had mentioned at some point, it seems I/O related somehow. 

thanks
M

**Comment by Fish-Git** [comment]
&nbsp;
> ... then when I IPL two z/OS guests at the same time, quite reliably Hercules will crash hard. The CP00 indicator is pegged at full use (********** all the way) but the MIPS indicator shows 0. Only kill -9 makes hercules come down again.

&nbsp;

> z/VM 6.3 and 6.2 crash now almost reliably if I IPL two guest machines with OS/390 or z/OS guests (31 bit or 64 bit, doesn't matter). You can try by IPLing two or three guest VMs at the same time. PROG04 almost every time.

&nbsp;
@moshix:

Recent changes were made to SDL Hyperion (see "[Release Notes](https://sdl-hercules-390.github.io/html/hercrnot.html)" and commit b76163a6646abef539e6800df3fbdb6adaed9a9d) to prevent `HHC00822I Processor IE00: machine check due to host error: User defined signal 1` from occurring. Instead, Hercules should now crash and create a core dump file that can then, theoretically, be analyzed to determine exactly where Hercules is going wrong.

If possible, please do a git pull or clone to pick up the latest version of Hercules and then rebuild and retest to see whether the problem still occurs or not. If it does (and a crash dump ("core" file) is created), please compress the core file (crash dump) and attach it to your GitHub comment so one of us can try to analyze it.

Thanks.

p.s. Depending on how you have your system (host) configured, you might need to enter the `ulimit -c unlimited` or similar command before performing your test. Please refer to the new GitHub Discussion Issue #199 that I have created regarding Linux Crash dumps: "[HELP! How to analyze a Linux "core" file? (crash dump)](https://github.com/SDL-Hercules-390/hyperion/issues/199)" for more information.

**Comment by moshix** [comment]
testing. 

will let you know and close this bug if it seems to fix the issue. 

thanks a lot!

**Comment by moshix** [comment]
I have been IPLing guests, up and down for a week now. This build seems very stable so far. I am closing this issue. 

thanks a lot Fish and Ivan.
