### ISSUE TITLE
SDL Hercules 4.2 segmentation fault on linux when connecting Hercprt32

### ISSUE THREAD

**Issue by rgschmi** [SDL-Hercules-390/hyperion#196]
Hercules segmentation faults when connecting Hercprt32.  It happens both before and after IPLing a guest host.  Linux is openSUSE Leap 15.0 and the Hercules version is  Hercules version 4.2.0.0-SDLg8c38cc83-modified (4.2.0.0).   If it matters, I'm using a bridged ethernet port.  A remote shared disk works ok. 

The same vintage of Hercules works under Windows.
___
_**Editor's note:** this bug is a duplicate of bug #195._

_**Editor's note:** this is a report of a bug that was already found and fixed by commit 20f4c3a98d4a9d23bc6942832a08866647ed4a73 long before this GitHub Issue was created._

**Comment by Fish-Git** [comment]
Please see my [GitHub comment](https://github.com/SDL-Hercules-390/hyperion/issues/195#issuecomment-468399944) in Issue #195.

Closing as Invalid.
