### ISSUE TITLE
HHC00136E opening OSA on Linux 

### ISSUE THREAD

**Issue by rgschmi** [SDL-Hercules-390/hyperion#205]
This appears to be a duplicate of #87.  Running as root fixes the problem.  You may close as duplicate.

Environment is openSUSE linux LEAP 15.0
HHC01413I Hercules version 4.2.0.0-SDL-g0928346b-modified (4.2.0.0)  

My OSA configuration:
3000.3   QETH Ifname tun0 ipaddr 192.168.10.12/24 MTU 1500 chpid 20

Im getting the following error opening OSA:
HHC00901I 0:3001 QETH: Interface tun0, type TUN opened                                                                                                
HHC00136E Error in function execlp(): No such file or directory

Followed by a page of misaligned output and then: 
 [0;49;39mHHC03997I 0:3001 QETH: tun0: using MAC address 02:00:5e:f9:0d:6f                                                                            
HHC03997I 0:3001 QETH: tun0: using IP address 192.168.10.12                                                                                           
HHC03997I 0:3001 QETH: tun0: using MTU 1500                                                                                                           
HHC03997I 0:3001 QETH: tun0: using drive MAC address 62:ae:12:fd:2c:a1                                                                                
HHC03997I 0:3001 QETH: tun0: using drive IP address fe80::62ae:12ff:fefd:2ca1                                                                         
HHC03805I 0:3001 QETH: tun0: Register guest IP address 192.168.10.12                                                                                  
HHC00911E 0:3002 QETH: Error writing to device tun0: 5 Input/output error                                                                             
HHC00007I Previous message from function 'write_packet' at qeth.c(2783)                                                                               
HHC00911E 0:3002 QETH: Error writing to device tun0: 5 Input/output error                                                                             
HHC00007I Previous message from function 'write_packet' at qeth.c(2783)                                                                               
HHC00911E 0:3002 QETH: Error writing to device tun0: 5 Input/output error                                                                             
HHC00007I Previous message from function 'write_packet' at qeth.c(2783)                                                                               
HHC00911E 0:3002 QETH: Error writing to device tun0: 5 Input/output error                                                                             
HHC00007I Previous message from function 'write_packet' at qeth.c(2783)     

My Hercules OSA definition is:

NETDEV /dev/net/tun

3000.3   QETH Ifname tun0 ipaddr 192.168.10.12/24 MTU 1500 chpid 20

The Hercules device display shows devices 3000 and 3001 owned by IDX but 3002 is owned by tun0.

Hercules  log:

HHC00901I 0:3001 QETH: Interface tun0, type TUN opened                                                                                                
HHC00136E Error in function execlp(): No such file or directory                                                                                       
HHC00007I Previous message from function 'IFC_IOCtl' at tuntap.c(1118)                                                                                
 [0;49;39m [2J [1;1H [0;49;39m
 HHC00100I Thread id 00007f5994603700, prio 1, name 'cckd_gcol' started                                                  
ted=1, max=2                                                   [3;1H [0;49;39mHHC00100I Thread id 00007f5994502700, prio 1, name 'cckd_writer thread 2
identification: type MVS, name NUI1, sysplex NUINET, level FFFFFFFFEF7FA002                                    [5;1H [0;49;39HHC00130W PGMPRDOS LICEN
       [6;1H [0;49;39mHHC00007I Previous message from function 'losc_check' at losc.c(49)                                                             
                                                       [8;1H [0;49;39mHHC00811I Processor CP01: architecture mode z/Arch                              
tial CPU reset                (0B) CP01, PARM 0000000000F58258: CC 0                                   [10;1H [0;49;39mHHC00814I Processor CP00: SIGP 
[11;1H [0;49;39mHHC00814I Processor CP00: SIGP Restart                          (06) CP01, PARM 0000000000000000: CC 0                                
00000C000: CC 0                                   [13;1H [0;49;39mHHC00814I Processor CP01: SIGP Initial CPU reset                (0B) CP00, PARM 0000
 prio 2, name 'Processor CP00' ended                                                                [15;1H [0;49;39mHHC00100I Thread id 00007f59961787
;1H [0;49;39mHHC00811I Processor CP00: architecture mode z/Arch                                                                                       
F58258: CC 0                                   [18;1H [0;49;39mHHC00814I Processor CP01: SIGP Set prefix                       (0D) CP00, PARM 0000000
                        (06) CP00, PARM 0000000000000000: CC 0                                   [20;1H [0;49;39mHHC01315I 0:0025 CHAN: ccw 03300001 1
 [0;49;39mHHC01312I 0:0025 CHAN: stat 0200, count 0001                                                                                             [22
0000000                                     [23;1H [0;49;39mHHC01314I 0:0025 CHAN: sense INTREQ                                                       
0                                                                                             [25;1H [0;49;39mHHC01312I 0:0025 CHAN: stat 0200, count 
;49;39mHHC01313I 0:0025 CHAN: sense 40000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000                                     [27;1H
                                         [28;1H [0;49;39mHHC01315I 0:0025 CHAN: ccw 05200090 2148D2B7=>7E7E7E6E 40C595A3 8599407F D3D6C7D6 ===> Enter 
                                                                                           [30;1H [0;49;39mHHC01313I 0:0025 CHAN: sense 40000000 00000
;39mHHC01314I 0:0025 CHAN: sense INTREQ                                                                                                      [32;1H [0
                                      [33;1H [0;49;39mHHC01312I 0:0026 CHAN: stat 0200, count 0001                                                    
000000 00000000 00000000 00000000 00000000 00000000                                     [35;1H [0;49;39mHHC01314I 0:0026 CHAN: sense INTREQ           
mHHC01315I 0:0026 CHAN: ccw 03200001 00000000                                                                                             [37;1H [0;49
                                   [38;1H [0;49;39mHHC01313I 0:0026 CHAN: sense 40000000 00000000 00000000 00000000 00000000 00000000 00000000 0000000
                                                                                     [40;1H [0;49;39mHHC01315I 0:0026 CHAN: ccw 05200090 2148D057=>7E7
C01312I 0:0026 CHAN: stat 0200, count 0000                                                                                             [42;1H [0;49;39
                                [43;1H [0;49;39mHHC01314I 0:0026 CHAN: sense INTREQ                                                                   
                                                                                  [45;1H [0;49;39mHHC01312I 0:0027 CHAN: stat 0200, count 0001        
313I 0:0027 CHAN: sense 40000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000                                     [47;1H [0;49;39mHH
                             [48;1H [0;49;39mHHC01315I 0:0027 CHAN: ccw 03200001 00000000                                                             
                                                                               [50;1H [0;49;39mHHC01313I 0:0027 CHAN: sense 40000000 00000000 00000000
I 0:0027 CHAN: sense INTREQ                                                                                                      [52;1H [0;49;39mHHC01
                          [53;1H [0;49;39mHHC01312I 0:0027 CHAN: stat 0200, count 0000                                                                
000 00000000 00000000 00000000 00000000                                     [55;1H [0;49;39mHHC01314I 0:0027 CHAN: sense INTREQ                       
 [0;49;39mHHC03997I 0:3001 QETH: tun0: using MAC address 02:00:5e:f9:0d:6f                                                                            
HHC03997I 0:3001 QETH: tun0: using IP address 192.168.10.12                                                                                           
HHC03997I 0:3001 QETH: tun0: using MTU 1500                                                                                                           
HHC03997I 0:3001 QETH: tun0: using drive MAC address 62:ae:12:fd:2c:a1                                                                                
HHC03997I 0:3001 QETH: tun0: using drive IP address fe80::62ae:12ff:fefd:2ca1                                                                         
HHC03805I 0:3001 QETH: tun0: Register guest IP address 192.168.10.12                                                                                  
HHC00911E 0:3002 QETH: Error writing to device tun0: 5 Input/output error                                                                             
HHC00007I Previous message from function 'write_packet' at qeth.c(2783)                                                                               
HHC00911E 0:3002 QETH: Error writing to device tun0: 5 Input/output error                                                                             
HHC00007I Previous message from function 'write_packet' at qeth.c(2783)                                                                               
HHC00911E 0:3002 QETH: Error writing to device tun0: 5 Input/output error                                                                             
HHC00007I Previous message from function 'write_packet' at qeth.c(2783)                                                                               
HHC00911E 0:3002 QETH: Error writing to device tun0: 5 Input/output error                                                                             
HHC00007I Previous message from function 'write_packet' at qeth.c(2783)

**Comment by Fish-Git** [comment]
Your copy & paste of the messages from your Hercules logfile appears to be garbled, making it very difficult to read!

I'm seeing lots of `[11;1H [0;49;39m` and similar type strings, etc.  These appear to be ANSI screen attributes, which should _never_ appear in the Hercules logfile. The Hercules logfile should always contain _only plain text._

Perhaps the problem is the fault of the editor you were copying the text _from?_ What editor were you using? Try using a different editor, such as gedit? (i.e. an editor as simplistic as, and as similar to, Windows notepad.)

**Comment by Fish-Git** [comment]
> This appears to be a duplicate of #87.  ...

_**Eh?!**&nbsp;&nbsp;&nbsp;&nbsp;I think you have the wrong issue number!_

GitHub Issue 87 deals with "PER G register alteration events" and has nothing to do with networking or root or Linux at all.

**Comment by rgschmi** [comment]
That garble is EXACTLY how it looked on the Hercules log!

**Comment by rgschmi** [comment]
This is the issue I was referring to.  It may be in the 'official' Hercules repository


Problem with tun/tap networking #87

Open
sjcr https://github.com/sjcr opened this issue on Dec 19, 2015 · 9 comments

>

**Comment by Fish-Git** [comment]
Okay, it's GitHub doing it.

When you use the string "pound" sign (or "hash" sign) followed immediately by a number, GitHub presumes you're referencing a Issue for the _current repository_ (which for SDL Hyperion is https://github.com/SDL-Hercules-390/hyperion/issues).

If you want to reference a GitHub Issue in a _different_ repository, you need to use a different syntax: _repository name,_ pound sign, number:

* SDL Hyperion issue #87: "PER G" register alteration event...
* Original 4.0 Hyperion issue hercules-390#87: "Problem with tun/tap networking"

&nbsp;
_Or..._ You can of course simply specify the full URL of the issue itself:

* SDL Hyperion issue 87: `https://github.com/SDL-Hercules-390/hyperion/issues/87`
* Original 4.0 Hyperion issue 87: `https://github.com/hercules-390/hyperion/issues/87`

Hope that helps!

**Comment by Fish-Git** [comment]
> That garble is EXACTLY how it looked on the Hercules log!

Hmmm... Weird. Must be something unique to Linux I guess.&nbsp;&nbsp;_&lt;shrug&gt;_

But getting back to the actual issue at hand however...

> Running as root fixes the problem.

That's good to know. Thanks.

> You may close as duplicate.

Done. Thanks.&nbsp;`(*)`

___
`(*)`&nbsp; _But you of course already knew **you** could have done so just as easily yourself, right?_
