### ISSUE TITLE
Three replies to each ping request using OSA multiple IP support and CTCI-WIN 3.7

### ISSUE THREAD

**Issue by rgschmi** [SDL-Hercules-390/hyperion#206]
Each ping results in three replies as shown in the attached Wireshark trace printout.
There is only one OSA and no VIPA defined.  I first noticed the trace output when I had two OSAs and a VIPA defined.  I restarted TCPIP with a single OSA and got the same results.

[pingtrace.txt](https://github.com/SDL-Hercules-390/hyperion/files/3133669/pingtrace.txt)

 trace the trace

**Comment by rgschmi** [comment]
Researching.  I may have a routing issue.

**Comment by rgschmi** [comment]
No routing issue that I can find.

Results from testing so far:

Configuration:  host ethernet adapter address  192.168.20.1
z/OS OSA address 192.168.20.12
IP address of pinging station  192.168.30.1
All addresses have a /24 mask

I see three responses to each ping as seen in the trace.  Pinging the host ethernet adapter 192.168.20.1 show a normal single response to each ping.  Pinging the OSA address from the host (source address 192.168.20.1) also shows a single response to each ping.  Testing on a linux host with an LCS interface sows normal responses to pings both from the host source address and the cross-subnet source address.  TN3270 traces also show duplicate packets being sent from the OSA address.

Note, that TN3270 works fine (as does ping if you don't mind multiple responses) from a user point of view.  TCP apparently (for 3270) discards the duplicate packets.

This appears to be specific to cross-subnet traffic and only for OSA and/or CTCI-WIN traffic.  I will try to change my configurations to have an OSA on linux and LCS on Windows and post the results, when time allows.

**Comment by Fish-Git** [comment]
I suspect this might be caused by your having IP Routing enabled on your Windows host. You shouldn't need IP Routing and I suspect it's the cause of the multiple responses. Your Windows host believes it's in charge of routing but so does network router too.

I suspect if you disable IP Routing on your Windows host this problem will go away.

**Comment by rgschmi** [comment]
The multiple responses to ping are gon as are the extra packets in the TN3270 data stream.  Problem solved!  I must have turned IP routing on in the distant past, as I have no recollection of doing it, on bothh my WindowsPCs.

**Comment by Fish-Git** [comment]
_FANTASTIC!_

Closing this issue as resolved.&nbsp;`:)`
