### ISSUE TITLE
Diagnose F08 Improvement

### ISSUE THREAD

**Issue by davekreiss** [SDL-Hercules-390/hyperion#211]
Currently this diagnose returns a 32 bit count but it tends to wrap quickly and if interval is too long one doesn't know how many wraps occurred.  How about returning a 64 bit number in z/Arch mode?

Another issue is determining which processor the count is for.  I do a store CPU id (STAP) before and after and assume if both same that is processor the count is associated with.  Maybe the diagnose can return another value in a second register identifying the processor?

Just ideas.
Dave

**Comment by Fish-Git** [comment]
Both requests seem reasonable enough. Let me see what I can do...

**Comment by Fish-Git** [comment]
I decided not to change the functionality of our existing Diagnose F08 and to code a brand new Diagnose F09 instead, which I have implemented in commit 86a135d3eb773d1c5059131c4ad1500672511719 as follows:

>### Diagnose F09:
>
> Operand-1 register r1 bits 32-47 specify the option code and bits 48-63 specify the CPU Address for option code 1. For option code 0, operand-1 register r1 bits 48-63 are ignored. Bits 0-31 of operand-1 register r1 are ignored. Any option code other than 0 or 1 causes a Specification Exception Program Interrupt.
>
> Option 0 = instruction count for entire system (all CPUs together). Option 1 = instruction count for specific CPU identified in bits 48-63 of r1.
>
> The register and bits that the 64-bit instruction count is returned in depends on: 1) whether z/Architecture mode is active or not, and 2) whether or not the operand-3 r3 register specifies an even numbered register or not.
>
> If r3 is an even numbered register, then the high-order bits 0-31 of the 64-bit instruction count is returned in bits 32-63 of the even numbered register, the low-order bits 32-63 the 64-bit instruction count is returned in bits 32-63 of the r3+1 odd numbered register, and bits 0-31 of each register remains unmodified.
>
> If r3 specifies an odd numbered register however, then the entire 64-bit instruction count is returned in bits 0-63 of the specified r3 register in z/Architecture mode, whereas a Specification Exception Program Check Interrupt occurs in both ESA/390 and System/370 architecture modes as 64-bit registers don't exist in either architecture.
>
> Precluding a Specification Exception Program Interrupt, Condition Code 0 is returned for option 0, whereas for option 1, Condition Code 0 is only returned if the CPU specified in bits 48-63 of the operand-1 r1 register is currently valid and online. Otherwise if the specified CPU is offline or does not exist in the configuration, Condition Code 3 is returned and the r3 or r3 and r3+1 return value register(s) is/are not modified.

_**Please let me know** if this is acceptable to you (as well as whether or not it works okay for you), since **I have not tested it.**_

_(I believe I have coded it correctly but I did not bother to test it.)_

Thanks.

**Comment by davekreiss** [comment]
I have a STC that records the count for each COU at specifABKE intervals along with the MAXRATES I/O and MIPS just for the fun of it to SMF user record. However I am on vacation for a time and am not even close to proficient at building (no experience!).   

I have been running the CLCL fix version of Hercules for some time. 

I do like the give me all processors instruction though I have been recording all online processor counts using a probe technique. 

I’ll modify my code when I get a chance to use me the F09 interface. 

Thanks for the quick response. 

Dave

**Comment by Fish-Git** [comment]
### _**CORRECTION!**_

_(Oops!)_ I had my operand register use _backwards_ (reversed) in my original design/commit! Operand-1 register r1 is the _output_ register (where the instruction count is placed) and it is the _operand-3_ register r3 that specifies the option code and cpu address. Sorry about that.

Commit abca30641cfe967033c39ed5a937ad3aed2d77f7 contains the fix.

The following is the _CORRECTED_ version of the instruction's description:

>### Diagnose F09:
>
> Operand register r3 bits 32-47 specify the option code and bits 48-63 specify the CPU Address for option code 1. For option code 0, operand register r3 bits 48-63 are ignored. Bits 0-31 of operand register r3 are also always ignored. Any option code other than 0 or 1 causes a Specification Exception Program Interrupt to occur.
> 
> Option 0 = instruction count for entire system (all CPUs together). Option 1 = instruction count for specific CPU identified in bits 48-63 of r3.
> 
> The register and bits that the 64-bit instruction count is returned in depends on: 1) whether z/Architecture mode is active or not, and 2) whether the specified operand-1 r1 register number is even or odd.
> 
> If operand-1 register r1 is an even numbered register, then the high-order bits 0-31 of the 64-bit instruction count is returned in bits 32-63 of the even numbered register, the low-order bits 32-63 the 64-bit instruction count is returned in bits 32-63 of the r1+1 odd numbered register and bits 0-31 of each register remain unmodified.
> 
> If operand-1 register r1 specifies an odd numbered register however, then the 64-bit instruction count is returned in bits 0-63 of register r1 in z/Architecture mode, whereas a Specification Exception Program Check Interrupt occurs in both ESA/390 and System/370 architecture modes as 64-bit registers don't exist in either of those architectures.
> 
> Precluding a Specification Exception Program Interrupt, Condition Code 0 is returned for option 0, whereas for option 1, Condition Code 0 is only returned if the CPU specified in bits 48-63 of the operand-3 register r3 is currently valid and online. Otherwise if the specified CPU is offline or does not exist in the configuration, Condition Code 3 is returned and the r1 or r1 and r1+1 return value register(s) is/are not modified.

**Comment by Fish-Git** [comment]
@davekreiss Dave,

This has been fixed in [Release 4.2](https://github.com/SDL-Hercules-390/hyperion/releases). &nbsp; [(https://github.com/SDL-Hercules-390/hyperion/releases)](https://github.com/SDL-Hercules-390/hyperion/releases)

Please let us know if you have any problems with it.

Thanks.
