### ISSUE TITLE
Bug in "bfp*" Binary Floating Point implementation.

### ISSUE THREAD

**Issue by Fish-Git** [SDL-Hercules-390/hyperion#214]
I came across code (in many places) in ieee.c similar to the following:

https://github.com/SDL-Hercules-390/hyperion/blob/0cb7ae037ff232503ba2b5296a6838e1d7f86c27/ieee.c#L1534-L1540

&nbsp;

https://github.com/SDL-Hercules-390/hyperion/blob/0cb7ae037ff232503ba2b5296a6838e1d7f86c27/ieee.c#L1757-L1762

&nbsp;

https://github.com/SDL-Hercules-390/hyperion/blob/0cb7ae037ff232503ba2b5296a6838e1d7f86c27/ieee.c#L3395-L3401

&nbsp;

This is wrong. _**Very** wrong!_

The `FEATURE_037_FP_EXTENSION_FACILITY` build option only determines whether support for the given facility will be _generated_ or not for the given version of Hercules that you are building, but says _nothing_ about whether or not that particular facility is _enabled_ (i.e. "available") or not _**at run time**_ (i.e. at the moment the instruction is being executed).

Rather, the runtime macro `FACILITY_ENABLED(...)` should be used to determine whether or not the given facility is currently enabled or not. Recall that z/Architecture facilities can be dynamically enabled or disabled at will at runtime (i.e. before the guest is IPLed). If someone starts Hercules and disables the Floating Point Extension Facility, incorrect results will occur.

As a test to prove this point, build Hercules as normal (with the `FEATURE_037_FP_EXTENSION_FACILITY` build option #defined like normal) and then do a runtest for all "bfp*" tests. All 22 tests will pass with flying colors.

Then, add the statement `facility disable 037_FP_EXTENSION` immediately before each `runtest` statement in each of the `bfp*.tst` runtest test files:

```
...
loadcore "$(testpath)/bfp-(whatever).core"
facility disable 037_FP_EXTENSION
runtest 1.0
...
```

And run the same set of runtests again. You will notice that 18 of the 22 tests now _**FAIL!** (and rightfully so since each of the instructions in question are incorrectly coded)._

The code in question should instead be changed to something similar to:

```C
    bool fpx = FACILITY_ENABLED( 037_FP_EXTENSION, regs );
    if (fpx)
    {
        /* Enabled case... */
    }
    else
    {
        /* Disabled case... */
    }
```

This is the correct way to check for a facility at runtime.

_PLEASE NOTE_ that I seriously doubt anyone who is running a guest operating system where the facility is normally enabled by default would purposely be disabling the facility before IPLing their guest and thus this particular bug will likely impact very few people (if any at all), so please consider this to be a _low priority_  issue.

But _technically_ it _**is**_ a bug and _should_ be fixed ...

_... eventually!_ &nbsp; `;-)`

**Comment by Fish-Git** [comment]
p.s. All of the bfp*.tst loadcore tests themselves (e.g. bfp-001-divtoint.tst, bfp-002-loadr.tst, etc) _might_ also need to be changed as well, I don't know.

_OR..._ perhaps what might be easier _(I don't know; I haven't bothered to examine the assembler source code of any of the bfp loadcore test programs)_ is to instead simply code a new set of `.tst` runtest tests for the "facility disabled" case. E.g.:

* bfp-001-divtoint.tst (existing enabled case)
* bfp-001-fpx-disabled-divtoint.tst (new disabled test)
* bfp-002-loadr.tst (existing enabled case)
* bfp-002-fpx-disabled-loadr.tst (new disabled test)
* etc...

I leave that to you.

@srorso ? I have assigned this to you since I believe it was you that coded the code in question (and developed all of the bfp runtests), but it doesn't have to be you that does it. You can give it to someone else or someone else can volunteer to do it for you if they're willing to. I don't want to appear "bossy" by assigning work to you!&nbsp;`:)`

**Comment by Fish-Git** [comment]
More information:

The following are comments that I proposed be added to ieee.c:

```C
    // ----------------------------------------------------------------
    //
    //              SUPPRESSION OF INEXACT EXCEPTION
    //
    // From: "SA22-7832-11" (Principles of Operation) page 19-23:
    //
    //   When the floating-point extension facility IS installed,
    //   bit 1 of the M4  field is the IEEE-inexact-exception
    //   control (XxC).  Bits 0, 2, and 3 are ignored.  If XxC is
    //   ZERO, recognition of IEEE-inexact exception is NOT sup-
    //   pressed (i.e. IS allowed to occur); if XxC is ONE, rec-
    //   ognition of IEEE-inexact exception is SUPPRESSED (i.e.
    //   does NOT occur).
    //
    //   When the floating-point extension facility is NOT in-
    //   stalled and if bits 20-23 of the instruction are ZEROS,
    //   recognition of IEEE-inexact exception is NOT suppressed;
    //   when the floating-point extension facility is NOT in-
    //   stalled and if bits 20-23 of the instruction contain a
    //   NONZERO value, it is UNPREDICTABLE whether recognition
    //   of IEEE-inexact exception is suppressed or not.
    //
    //   SUMMARY:
    //
    //    FPX installed    M4 bit 1    Inexact
    //    -------------    --------    ------------------------
    //
    //        n/a             0        Exception DOES occur
    //                                 (i.e. is NOT suppressed)
    //
    //        Yes             1        Exception does NOT occur
    //                                 (i.e. is SUPPRESSED)
    //
    //        No              1        Exception is UNPREDICTABLE,
    //                                 but SUPPRESSED for consistency.
    //
    // ----------------------------------------------------------------
```

Notice the handling of the "not installed" (i.e. disabled) case: If the Floating Point Extension Facility is _not_ installed (but the M4 "suppress inexact exception" bit is on (non-zero)), the inexact exception handling can be made to be _identical_ to the way it is handled when the Floating Point Extension Facility _**is**_ installed without violating the architecture.

I would like to therefore recommend (propose) that we do exactly that. Doing so will greatly simplify the logic by completely eliminating the need to test whether the facility is installed or not! That is to say, we can legitimately suppress or not suppress an inexact exception based on the setting of the M4 field's bit _regardless_ of whether the Floating Point Extension Facility is installed or not and still be 100% compliant with the architecture.

Does this sound good to everyone?

**Comment by srorso** [comment]
Hi Fish,

The comments make sense; feel free to add them.  

With respect to the FEATURE_037... matter, my last visit to the code continued the use of the static macros FEATURE_FPS_EXTENSIONS and FEATURE_ESAME.  The "037" changes were made by your commit 76acfb9 in late 2017, so I am not as familiar with that as I would like to be. 

I will be happy to take a look at the issues; feel free to leave it assigned as you have it.  

Best Regards,
Steve

**Comment by Fish-Git** [comment]
> With respect to the FEATURE_037... matter, my last visit to the code continued the use of the static macros FEATURE_FPS_EXTENSIONS and FEATURE_ESAME. The "037" changes were made by your commit [76acfb9](https://github.com/SDL-Hercules-390/hyperion/commit/76acfb981c5e62dae5b308f916a0409eada6db58) in late 2017, so I am not as familiar with that as I would like to be.

Understood. _HOWEVER..._ As far as I know the `FACILITY_ENABLED()` macro has been around forever (i.e. pre-dates my commit), so technically my commit didn't change anything in that area. That is to say, if the code wasn't already using the `FACILITY_ENABLED()` macro before my commit, then it was already broken and my commit had no impact in that regard.

I'm working on a fix right now for the M4 right now (_as well as for the M3 field too!_ see next github comment further below). But don't worry: I'm _not_ going to commit anything. Rather I will simply pass on my proposed fix(es) to you for review and then let _you_ decide where to go from there. (I'd much rather _you_ implement/commit the fix than me! I'm just trying (hoping) to try and help you, that's all! Give you a jump start so to speak.)

**Comment by Fish-Git** [comment]
More information:

```C
// --------------------------------------------------------------------
//
//                HANDLING OF BFP ROUNDING MODE
//                 (The M3 instruction field)
//
// From: "SA22-7832-11" (Principles of Operation) page 19-19,20:
//
//   When the floating-point extension facility IS installed, the
//   converted result is rounded as specified BY THE MODIFIER IN
//   THE M3 FIELD.
//
//   An M3 modifier other than 0, 1, or 3-7 is invalid.  The M3
//   field must designate a valid modifier; otherwise, a specifi-
//   cation exception is recognized.
//
//   When the M3 modifier field is ZERO, rounding is controlled
//   BY THE CURRENT BFP ROUNDING MODE specified in the FPC register.
//
//   When the field is NOT ZERO, rounding is performed AS SPECIFIED
//   BY THE MODIFIER, regardless of the current BFP rounding mode.
//
//   When the floating-point extension facility is NOT installed
//   and bits 16-19 of the instruction contain a value of ZERO,
//   the converted result is rounded ACCORDING TO THE CURRENT BFP
//   ROUNDING MODE.
//
//   When the floating-point extension facility is NOT installed
//   and bits 16-19 of the instruction contain a nonzero value,
//   it is UNDEFINED whether a specification exception is recog-
//   nized or an unpredictable rounding method is performed.
//
//   SUMMARY:
//
//    FPX installed    M3 field    Rounding
//    -------------    --------    ------------------------------
//
//        Yes           (zero)     According to FPC Rounding mode
//        Yes          (nonzero)   According to M3 field
//
//        No            (zero)     According to FPC Rounding mode
//        No           (nonzero)   Undefined/unpredictable, but
//                                 according to M3 for consistency.
//
// --------------------------------------------------------------------
```

Also, as far as the handling of a specification exception if the M3/M4 fields are non-zero when the Floating Point Extension Facility is not installed goes (which is the way it's code right now), the Principles of Operation manual states quite clearly:

> Instruction fields shown [...] as containing slashes (/) are currently unassigned.  These fields in an instruction should contain zeros; otherwise,  the  program  may  not  operate compatibly in the future.

So for those instructions where the code is currently throwing a specification exception if m3 or m4 is non-zero should be able to be safely removed as well while still remaining compatible with the architecture. That is to say, the specification exception that is currently being thrown, while valid, probably _shouldn't_ be thrown and instead simply handled the same way as for the Floating Point Extension Facility installed case (as written in my proposed comments for ieee.c above).

**Comment by Fish-Git** [comment]
> I'm working on a fix for the M4 right now _(as well as for the M3 field too! see next github comment further below)_. But don't worry: I'm _not_ going to commit anything. Rather I will simply pass on my proposed fix(es) to you for review and then let _you_ decide where to go from there. (I'd much rather _you_ implement/commit the fix than me! I'm just trying (hoping) to try and help you, that's all! Give you a jump start so to speak.)

Well, I'm done with my fix:

* [bfp37.patch.txt](https://github.com/SDL-Hercules-390/hyperion/files/3269919/bfp37.patch.txt)

Unfortunately, even with the patch, all 18 of the 22 tests still fail whenever the Floating Point Extension Facility is disabled. (When the facility is left enabled like normal, all 22 tests pass just fine with or without the patch.)

All of the 18 tests that are failing (when the Floating Point Extension Facility is disabled) are failing due to an "unexpected wait state" causing all storage compares to fail ("Storage compare mismatch"). Given that all 18 of the failing tests appear to be using the `SRNMB` (Set BFP Rounding Mode) instruction and that the SRNMB instruction itself is simply only one of the many new instructions introduced by the Floating Point Extension Facility, such should come as no surprise.

I did _not_ bother to check to see how much effort it would take to modify (fix) each of the tests (i.e. the .asm assembler source code and rebuild each test to create a corrected .core runtest file). Doing that would take more effort than I'm prepared to expend on this issue right now, so I'll leave doing that to you, Steve. I've given you all the help I can give you at the moment.

Please let me know what you think of my patch. I believe it's a good fix even though I'm currently unable to prove it due to the way the current bfp runtest tests are designed.

Thanks.

**Comment by Fish-Git** [comment]
Additional thoughts regarding how best to address (fix) the bfp runtest failures...

Currently, the `redtest.rexx` script -- an integral part of our runtest harness -- sets a bunch of Rexx variables based on current Hercules settings and build options (e.g. `$platform`, `$ptrsize`, `$can_s370_mode`, etc, including `$HET_BZIP2`, `$ZLIB`, `$rexx_supported`, `$rexx_VERSION` and `$rexx_package` variables for example) which certain .tst test scripts currently use to select which test they're going to run or whether to run any test at all _(see the `hetbsf.tst` and `3211.tst` test scripts for two (good?) examples)_.

I'm thinking maybe I should devise a new Rexx variable (or variables) to be set by `redtest.rexx` that a .tst script could then use to determine whether support for a given architectural facility was installed and/or enabled or not. If such a variable (or variables) existed then the "fix" for the 18 bfp tests that are currently failing (when facility 37 isn't enabled) would then become a simple matter of simply wrapping each test within a `*If $fac[37]`, `*Else`, `*Fi` or similar set of statements to allow choosing to either run or skip the given test depending on whether the given facility was enabled or not.

That might be much easier to implement than having you modify the .asm assembler source code and resulting .core files for each of the 18 tests that are failing.

What do you (and others?) think? Does that sound reasonable?

(I'm thinking we could easily come across a similar situation as this one at some point in the future so I want to try and address it now rather than later.)

**Comment by Fish-Git** [comment]
Here's the patch for the runtest harness:

* [bfp-tst.patch](https://github.com/SDL-Hercules-390/hyperion/files/3271146/bfp-tst.patch.txt)

The previous [bfp37.patch](https://github.com/SDL-Hercules-390/hyperion/files/3269919/bfp37.patch.txt) along with this one, together, should completely resolve this issue. @srorso Steve, please confirm.  (And please let me know what you think about my ieee.c patch further above.)

Thanks.

p.s. What's up with PFPO?

**Comment by srorso** [comment]
Hi Fish, sorry for the delays....I have been traveling with limited access to my tools.  I should have some time later this week.  

Some of the BFP tests are a mix of basic functionality tests and M3/M4 tests; I think the .asm's will need to be updated to include a STFL(E) to determine if features are enabled and to selectively skip the M3/M4 tests, and the scripts modified in the manner you have to skip the *Compare/*Want sections when those tests are disabled.  

I also like the approach of separate tests.  Because each test can set the conditions of execution, including enablement of 37, there should be no issue with a test "knowing" if a feature is available.  The separate test would verify correct operation in the absence of feature enablement.

Re PFPO, I haven't heard from Bob offline; I presume he's still working on that.  

Best, 
Steve

**Comment by srorso** [comment]
I have identified the identified points of non-conformance with the PoOp in the current ieee.c.  Page references are from SA22-7832-08, the first edition to describe the Floating Point Extensions Facility, with cross-references to SA22-7832-11.

1.  There is no validation of the rounding mode encoded in the m3 field of the Divide To Integer instruction.  An invalid value may exceed the bounds of the map_m3_to_sf_rm array and will result in an unpredictable rounding mode being selected.  (Actually, the chosen rounding mode can be predicted and will be wrong.)

The conforming action is to generate a specification exception for rounding modes 2 and 8-15.  If the Floating Point Extension Facility is not installed, a specification exception should be generated for rounding mode 3 (SA22-7832-08 p. 19-27; verbiage unchanged in -11 on p. 19-28).

2.  There is limited PoOp support for generating a specification exception when the Floating Point Extension Facility is not installed/enabled and bits 16-23 of the following instructions are non-zero:
>>>
        Convert From Fixed
        Load Rounded

While SA22-7832-08 p. 19-19 says the result in this case might be a specification exception or use of an unpredictable rounding method, Figure 9-15 on p. 9-17 says the result is rounded by the two-bit BFP Rounding Mode in the Floating Point Control Register (Entries for Convert From Fixed and Load Rounded, both with Rounding Action MBB).  Verbiage unchanged in SA22-7832-11 (p. 19-20 and 9-17 respectively).

P. 9-17 of -08 also matches the behavior of this instruction on z/Architecture models prior to z196/z114, the model documented in -08 and the first to have the Floating Point Extension Facility available.

Other instructions affected by the Floating Point Extensions Facility are coded in ieee.c to operate as defined in SA22-7832-07 if the Facility is not installed, namely:
>>>
    Load FP Integer
    Convert To Fixed

The PoOp appears to have an internal conflict: p. 19-19 states that non-zero bits 16-19 generates unpredictable results, while Figure 9-15 specifies a predictable result that ignores bits 16-23 and is consistent with prior z/Architecture models.  It may be that the two chapters had different editors.  It is also possible that the Internal Use Only version of the PoOp addresses the conflict.

I suspect that the language in -11 p. 19-20 and p. 19-36 is there to give a z/Architecture implementer some flexibility in how they code the Facility, with perhaps some of it in the base z/Arch coding and some in a separate hardware/microcode/millicode file.  It may also be a way to edit an architecture document without introducing a description of model-specific behaviors.  

To resolve the apparent PoOp internal conflict, I like using the definition of the Floating Point Extension Facility on p. 1-12 of SA22-7832-08 (unchanged in SA22-7832-11 p. 1-14).  That definition does not change the z/Architecture from prior editions if the Facility is not installed. It seems reasonable to assume that in the absence of the Facility, the changes enabled by the facility do not exist and the system operates in a manner consistent with that defined in SA22-7832-07.

It would be helpful to know if the Facility is a standard addition to all z/196/z114 and newer models or if it is a separately-installable optional feature.  Based on my understanding of what the Facility added, my guess is that the Facility is a standard feature.  (Rounding is not hard, especially Round for Shorter Precision, exception suppression should not be hard, and addition of the BFP<->unsigned  int instructions is mostly a clone of BFP<->signed int functionality.)

As I read the patch, it has the effect of making ieee.c behave as if it is always emulating Binary Floating Point operations on a z196/z114 or newer system with the Floating Point Extension Facility installed and
enabled.  There does not seem to be any means to turn off the Facility for BFP operations.

This is certainly a reasonable approach; older programming for z/Architecture BFP will work as expected provided programmers and compiler writers follow IBM's recommendation that unused bit positions in instructions should be set to zero.  It also simplifies test case development, as there should be no need to develop test cases specific to emulation with the Floating Point Extensions Facility disabled.

The Floating Point Extensions Facility also affected Decimal Floating Point and Floating Point Support instructions, and for consistency's sake DFP and FPS should be treated the same way.

Equally reasonable would be to correct the code for the instructions affected by the PoOp non-conformance.  Whether the corrections include testing the feature bit at run time, using preprocessor macros to include and enable the Facility, or both requires further thought.

I have wondered why there is so much feature-related pre-processor code in Hercules and thought about how much simpler it would be if each emulated architecture just emulated the most recent model of that architecture.  I do not understand the use case for being able to build Hercules such that it precisely emulates, say, a zServer eSeries 990 as defined in SA22-7832-04, omiting all functionality added later.  Perhaps it was a coding style appropriate to much slower and smaller personal computers ca. 1999.  

I still need to review the test case patch and consider how much of commit https://github.com/hercules-390/hyperion/commit/bec74e3a3dc26acb251eb820b3aeafcee0576b88 (Convert HFP <-> BFP and related tests) and https://github.com/hercules-390/hyperion/commit/5c081ec6dbb2b7abe83ca221f8a53218acc5752e (ieee.c code refactor) I would like to port to SDL.

More out of pocket for the next two weeks...

**Comment by Fish-Git** [comment]
Steve, &nbsp; (@srorso)

Last comment made to this issue (yours, above) was almost 2 years ago.

Do you still have your patch handy? Can it be committed? I'd like to close this issue if possible! Thanks!

**Comment by Fish-Git** [comment]
Closing due to lack of response.
