### ISSUE TITLE
SIE performance perf enhancement - Request for Comments

### ISSUE THREAD

**Issue by ivan-w** [SDL-Hercules-390/hyperion#218]
In an hypervisor environment (z/VM or QEMU KVM HV), the proposal would be to avoid using concurrent safe loads/stores/copies when the virtual environment is actually a single processor even if the host is multi processor. Consequently a virtual multi-processor environment in a host single processor rig would also benefit from bypassing those.

As a test case, (bypassing all concurrent safe accesses - in a controlled environment) I get a 10% performance enhancement.

The basis of my working theory is as follows: When the SIE instruction is executed, the `SIEBK`/`SIEBK2` includes information about the presence of any sibling virtual CPUs: `sie_scao` in the `REGS` which contains a bitmap of vCPUS. If the population count is 1, then we are a virtual uniprocessor configuration and we don't have to use fancy concurrent access protected fetches and stores.

My first question is as follows... gcc and MSVC have builtins to do a population count of an int... How should this be treated to be safe, portable, etc?

**Comment by Fish-Git** [comment]
> the proposal would be to avoid using concurrent safe loads/stores/copies when the virtual environment is actually a single processor even if the host is multi processor.

That sounds dangerous to me. Due to the heavily multithreaded design of Hercules, on a multiprocessor host it is entirely possible for more than one Hercules thread to be accessing/updating the same guest storage area at the same time. This is true regardless of how many virtual processors the guest has.

> Consequently a virtual multi processor environment in a host single processor rig would also benefit from bypassing those.

The same would apply for this situation too, no?

Perhaps it's only me (perhaps I'm missing something), but if either the host _**-or-**_ the guest has multiple processors (meaning two things can be happening at once) then access/updating of guest storage _must_ be done in some type of controlled fashion. Unless, as I said, I'm missing something.

> ... `sie_scao` in the `REGS` which contains a bitmap of vCPUS.

Where? I'm not seeing that.

**Comment by Fish-Git** [comment]
> As a test case, (bypassing all concurrent safe accesses - in a controlled environment) I get a 10% performance enhancement.

Can we see your patch?

**Comment by ivan-w** [comment]
Nothing to see yet. The mods I made to check were perfectly non canon, and where just to test whether there was an actual performance impact.

I am working on the same assumption as there are times when we do this :
 if(regs->cpubit == regs->sysblk->started_mask) - and then proceed to perform perform non atomic load/stores since we only have a single CPU running.

My proposal is that when a SIE guest Virtual CPU is running and has no siblings then it should be treated as a uniprocessor configuration and we could then bypass atomic operations.

The SCA Block Origin is part of the SIEBK/SIEBK2 descriptor (+64 SIEBK and +5C and +64 for SIEBK2). It points to a memory location (it's a SIE host absolute address). This block contains a bitmap of the virtual configuration virtual CPUS (as well as references to  addresses of the SIEBK/SIEBK2 for each sibling).

If the configuration only contains a single virtual CPU, it is in effect a single processor configuration while dispatching this virtual CPU.

This is just food for thought and tests are ongoing !

**Comment by ivan-w** [comment]
I might be on a wild goose chase... Just looking !

**Comment by Fish-Git** [comment]
@ivan-w Ivan,

Any news or progress on this issue? &nbsp; _(No rush! Just curious is all)_

**Comment by Fish-Git** [comment]
Closing due to non-response/inactivity.
