### ISSUE TITLE
CODE IFI004 failures with VM/ESA and z/VM 6.4

### ISSUE THREAD

**Issue by moshix** [SDL-Hercules-390/hyperion#224]
I started having issues again with IFI004 system failures:

```
 12:14:39 HCPDMP908I SYSTEM FAILURE ON CPU 0002, CODE - IFI004  
 HCPDMP9250E SYSTEM DUMP FAILURE; NO DUMP DEVICE AVAILABLE      
 HCPWRP9025W SYSTEM TERMINATION COMPLETE, ENTERING WAIT STATE   
```

The interesting thing is that the failures occur both with z/VM 6.4 as well as with ancient VM/ESA 2.4. 

The other interesting thing is that it occurs on X84-64 Linux as well as on Raspberry 3 and Raspberry 4 Linux. 

I am compiling with gcc 7.4.0 on X86-64 and with gcc 8.3.0 on Raspberry.

Thanks

**Comment by Fish-Git** [comment]
I wish there was something I could do myself to help you Moshix, but unfortunately my z/VM debugging skills are non-existent.&nbsp;`:(`

I'm adding the "Help!" label to this issue in the hope that maybe @ivan-w Ivan or someone else with the requisite z/VM debugging skills can come to the rescue and analyze your z/VM system dump to see what's going on.

**Comment by moshix** [comment]
Fish

with the SDL updates from August 2-August 10, most of the crashes have disappeared. In particualr, z/VM 6.4 with QDIO now finally works. Before it wouldn't stay up more than a few minutes once TCPIP on QDIO was started. 

So, as far as I am concenred, huge improvement. 

thanks a lot

**Comment by moshix** [comment]
So, I am closing this for now

**Comment by Fish-Git** [comment]
> So, I am closing this for now

Fine by me!&nbsp;`:)`
