### ISSUE TITLE
Remove configure and intermediate files from the *SOURCE*

### ISSUE THREAD

**Issue by ivan-w** [SDL-Hercules-390/hyperion#227]
At this point, with the current situation, even a single 1 line change to a source may generate a 1 Million lines change if one decides to regenerate the automagic/cmake/external packages files (and don't get me going with this horror), whatnot... and make it impossible to determine the actual cause of a bug introduced by a change.

Source is *SOURCE* - NOT Generated files !

Please keep Source files as SOURCE files - not generated scripts, binaries or any kind of magic.

**Comment by ivan-w** [comment]
If a "package" has no other purpose to be used but within hercules, it should be IN the hercules source, NOT as a separate source tree. Please re-include "crypto", "Decnumber" "Softfloat" and "telnet" as an integral part of hercules. Those being "external" is useless and a complication for everyone.

**Comment by Fish-Git** [comment]
@ivan-w Ivan (and all others too),

This issue basically already exists as GitHub Issue #76 "[Externalize non-engine related Hercules components](https://github.com/SDL-Hercules-390/hyperion/issues/76)". As a result, I am closing this issue as "Duplicate".  Please direct all of your comments to Issue #76 instead. Thanks.

**Comment by ivan-w** [comment]
You are correct ! Thanks :)
