### ISSUE TITLE
Curtailing GCC warnings - WORK IN PROGRESS

### ISSUE THREAD

**Issue by ivan-w** [SDL-Hercules-390/hyperion#231]
Ladies & Gents,

I am implementing a series of patches that are intended to curtail a bunch of GCC warnings. I "believe" they should be innocuous (mostly some reformatting, maybe a bit of refactoring). Each small change is applied individually (should the change cause an issue). At most a couple of files at a time.

I ask from you guys if possible to test the changes as they occur and notify if there is something that breaks.

Thanks!

--Ivan

**Comment by ivan-w** [comment]
the intent is that there should be NO functionality or logic change in any of my patches - if this occurs, please notify ASAP

**Comment by ivan-w** [comment]
One thing I am seeing is the use of "strncpy" in the form strncpy(outbfr,Literal,length of literal -1) - gcc complains it won't be able to copy the trailing 0... OF COURSE IT WON'T ! use memcpy in that case (besides memcpy is VERY well optimized in most modern compilers).

**Comment by Fish-Git** [comment]
> I ask from you guys if possible to test the changes as they occur and notify if there is something that breaks.

> The intent is that there should be NO functionality or logic change in any of my patches. If this occurs, please notify ASAP.

10-4!

Thank you for taking the time and effort to help cleanup Hercules code.

**Comment by ivan-w** [comment]
:) That's what we do !

Any and all breakage will be addressed !

**Comment by Fish-Git** [comment]
Closing due to both inactivity and the fact that curtailing compiler warnings should _always_ be an ongoing effort for _all_ of us, and thus does not merit even being a GitHub Issue in the first place IMHO.
