### ISSUE TITLE
Possible spinloop running zOS 2.3 under z/VM 6.4 

### ISSUE THREAD

**Issue by fbi-ranger** [SDL-Hercules-390/hyperion#232]
Hercules version | **4.2.0.0-SDL-gf8e1fa5b-modified (4.2.0.0)**
------------ | -------------
Host OS | **openSUSE 15.0**
Guest OS | **z/VM 6.4**
z/VM guest | **z/OS 2.3**

This issue is related to #233.

Under some unknown condition, Hercules seems to get into a (spin?) loop, causing problems with the guest.

Two of the four CPs are running at maximum (100%). (The other two appear to be idle)

Hercules commands can still be entered, but SCP commands are not honored any more. The same is true for the guest.

A screenshot of the Hercules console shows that two of the four CPs are completely busy (100%):

![Hercules cnsl](https://user-images.githubusercontent.com/4795000/62444358-91f36600-b75d-11e9-8536-8f0ad2a6b62c.png)

**Comment by fbi-ranger** [comment]
I observed several occurrences also on ONE processor only. It runs at 100% speed. 
This happened during a FORCE of a z/OS guest. During cleanup processing the processor goes into a loop and does not complete the FORCE. Maybe due to a missing interrupt? 
The guest remains in FORCE/LOGOFF PENDING state.

**Comment by Fish-Git** [comment]
This honestly sounds like a z/VM bug, not a Hercules bug:

* [VM65776: VARY PROC LOCK HANG PREVENTS MCW002 ABEND](https://www-01.ibm.com/support/docview.wss?uid=isg1VM65776)

You also don't mention whether or not you are using an OSA (QETH) device or not, but if you are, I also found the following:

* [VM66280: VSWITCH OSA RDEV BLOCKED WITH POSSIBLE ABEND MCW002 OR MPC008](https://www-01.ibm.com/support/docview.wss?crawler=1&uid=isg1VM66280)

Both of these issues point to a bug in IBM code related to z/VM and/or OSAs.

Closing.
