### ISSUE TITLE
Code MCW002 during z/VM shutdown

### ISSUE THREAD

**Issue by fbi-ranger** [SDL-Hercules-390/hyperion#233]
Hercules version | **4.2.0.0-SDL-g9a332aa3-modified (4.2.0.0)**
------------ | -------------
Host OS | **openSUSE 15.0**
Guest OS | **z/VM 6.4**
z/VM guest | **z/OS 2.3**

This issue is related to #232.

During testing of patch related to #226 sometimes a (spin) loop occurs where z/VM and its guest do not respond to commands any more. 

In this case at 13:34:28 to following messages are sent from z/VM 

```
13:34:28 13:34:28 HCPMPG9152E Processor 02 is being restarted because it is not responsive.
13:34:28 13:34:28 HCPMPG9152E Processor 03 is being restarted because it is not responsive.
```

and z/VM tries a shutdown and re-IPL. 

During this processing on CPU 0000, a CODE - MCW002 happened and  and a dump was taken by z/VM. The following is from the VMDUMP tool: 

```
VM Dump Tool - z/VM 6.4.0 -  MCW002 - PRB00002 MDMP0001 D1

z/VM Version 6 Release 4.0, service level 1802 (CP 64-BIT)                     
Generated at 12/31/18 23:06:10.000000, IPLd at 08/05/19 13:26:10.816547        
Date 08/05/19 Time 13:34:38.139258                                             
                                                                               
CPUID = 0001A2EF 28270000                                                      
                                                                               
CPU address is 0000    Prefix register is 00132000   (failing)                 
CPU address is 0001    Prefix register is 00B2E000                             
CPU address is 0002    Prefix register is 00B30000                             
CPU address is 0003    Prefix register is 00B32000                             
7FE60800 13:34:38  MCW002 Hard Abend svc 00 at HCPMCW+FC opsw 04040000_003BCAEC
                   svcilc 0002                                                 
                                                                               
Summary of CP exits                                                            
      0 Pre-defined exits found                                                
      0 Dynamic exits found                                                    
      0 Diagnose exits found                                                   
                                                                               
MCW002 A processor that was doing system work was reset.                       
```

The complete log is attached: 
                                                                               
* [run-pat03.log](https://github.com/SDL-Hercules-390/hyperion/files/3467743/run-pat03.log)

**Comment by fbi-ranger** [comment]
Today this situation happened again during z/VM shutdown. 
Before there was a FORCE of the z/OS guest, which did not complete. The guest remained in HCPUS0361E LOGOFF/FORCE PENDING state and did not logoff.

Doing a shutdown of z/VM resulted in the MCW002 abend and an automatic re-IPL. 

Hereby the excerpt from the Hercules console log:

[hercules.log](https://github.com/SDL-Hercules-390/hyperion/files/3501357/hercules.log)

13:41:49 13:41:49 HCPWRP963I SHUTDOWN STEP ISHDA - DISABLE ALL DEVICES                   
13:41:49 13:41:49 HCPWRP963I SHUTDOWN STEP DMPDK - TAKE DUMP              

Seems that this happens during step DISABLE ALL DEVICES.

**Comment by moshix** [comment]
fbi-ranger can confirm same behavior with Hercules version 4.3.0.0-SDL-g1f8fa07-modified (4.3.0.0) and z/VM 6.4 on Ubuntu 16.04. I have only seen it twice so far, but exact same behavior when it happens. 

M

**Comment by fbi-ranger** [comment]
It seems that during FORCE of a z/OS guest, one processor gets into a spin loop. 
When a shutdown of z/VM is entered and the processor loops, then the MCW002 abend happens.

**Comment by Fish-Git** [comment]
This honestly sounds like a z/VM bug, not a Hercules bug:

* [VM65776: VARY PROC LOCK HANG PREVENTS MCW002 ABEND](https://www-01.ibm.com/support/docview.wss?uid=isg1VM65776)

You also don't mention whether or not you are using an OSA (QETH) device or not, but if you are, I also found the following:

* [VM66280: VSWITCH OSA RDEV BLOCKED WITH POSSIBLE ABEND MCW002 OR MPC008](https://www-01.ibm.com/support/docview.wss?crawler=1&uid=isg1VM66280)

Both of these issues point to a bug in IBM code related to z/VM and/or OSAs.

Closing.
