### ISSUE TITLE
CTCI and LCS read errors following commit 9bb68b4

### ISSUE THREAD

**Issue by mcisho** [SDL-Hercules-390/hyperion#234]
I've just updated to commit 9bb68b4 ( Fix exit/quit hang when no tuntap traffic: Closes #226. ) and now I'm getting read errors on CTCI and LCS interfaces.

The following are using a **zLinux** guest:

```
19:31:02 Booting default (Fedora (5.1.20-300.fc30.s390x) 30 (Thirty)) 
19:31:02 HHC00912E 0:0600 CTCI: Error reading from device tun141: 4 Interrupted system call
19:31:02 HHC00007I Previous message from function 'CTCI_ReadThread' at ctc_ctci.c(1039)
[...]
19:33:50 HHC00942I CTC: lcs device tap143 using mac 8E:A3:9E:1A:8A:E9
19:33:50 HHC00944E CTC: lcs device read error from port 00: Interrupted system call
19:33:50 HHC00007I Previous message from function 'LCS_PortThread' at ctc_lcs.c(2050)
```

and the following are using a **z/VM** guest:

```
19:33:04 HHC00912E 0:1C60 CTCI: Error reading from device tun10: 4 Interrupted system call
19:33:04 HHC00007I Previous message from function 'CTCI_ReadThread' at ctc_ctci.c(1039)
```

Presumably the error is from the `select()` in function `read_tuntap()` rather than the actual `read()`. My limited experience is that "Interrupted system call" is returned from `select()` quite often under Linux.

**Comment by Fish-Git** [comment]
> My limited experience is that "Interrupted system call" is returned from select() quite often under Linux.

_(Doh!)_

Yes, of course it is.  My bad.  I forgot all about that.  I apologize profusely.  I'll get that fixed for you right away.

_&lt;grumbleihateitwhenimakecarelessmistakeslikethatgrumble&gt;..._

**Comment by Fish-Git** [comment]
Should be fixed now by commit d7e8644c2a05ef8f8f654f9768e5ba00dc30f784.

Please confirm.

Thanks.

**Comment by mcisho** [comment]
Fixed. Thanks.

**Comment by Fish-Git** [comment]
> Fixed. Thanks.

Thanks. Closing.
