### ISSUE TITLE
Console 3215/1052 devices (via telnet) stop responding under SDL Hyperion 4.2

### ISSUE THREAD

**Issue by cjar1950** [SDL-Hercules-390/hyperion#237]
If console device 3215 or 1052 (rather than 3215-c or 1052-c) are set up for telnet access, they stop responding.

OS360/MFT the console stops after the second command.
OS360/MVT the console doesn't accept any command entered.

They worked correctly with build "SDL_TEMP_4.2_PVT_X64_VS2008", but not build "R4.2.0.9708-SDL-x64".

Chris

**Comment by Juergen-Git** [comment]
Fixed by [ea1e518]https://github.com/SDL-Hercules-390/hyperion/commit/ea1e51808e00b714cbaeb54d1a03cbc199190d51
