### ISSUE TITLE
4.2.1 "Fix" release?

### ISSUE THREAD

**Issue by Fish-Git** [SDL-Hercules-390/hyperion#240]
Folks,

I was thinking, due to the importance of some recent fixes that have been committed (e.g. the [SIE fix](https://github.com/SDL-Hercules-390/hyperion/issues/222), the [hercifc fix](https://github.com/SDL-Hercules-390/hyperion/issues/236), and [other recent fixes](https://sdl-hercules-390.github.io/html/hercnew.html)), should we maybe release our first interim version _**4.2.1 "Fix" release**_ while we continue to work on version 4.3?

Note that I would like to fix [Florian's `hercifc` crash](https://github.com/SDL-Hercules-390/hyperion/issues/239) before we do, but once it has been resolved, do you think maybe we should release a 4.2.1 fix release?

What do you think?

**Comment by ivan-w** [comment]
Sure.. It's important for people that "can't/won't/don't want to" build hercules themselves.

**Comment by Juergen-Git** [comment]
Yes, I think too that we should provide a fix release. However, as I'm away until mid September, the two issues (#235 and #237) Fish just assigned to me are probably not going to get fixed until then. On the other hand they might be irrelevant to the release cycle, given that only the rarely used 1052/3215 consoles seem to be affected.

**Comment by Fish-Git** [comment]
Once Ivan (@ivan-w) feels [we've waited long enough](https://github.com/SDL-Hercules-390/hyperion/issues/222#issuecomment-522318454) for issue #222 to be safely closed, then I'll go ahead and do the release. But I want to get #222 out of the way first.

Thanks to Ian, #239 is now closed, so it's only #222 that we're now waiting on.

Unless, of course, there are any other issues any of you feel we should also wait for first?

**Comment by Juergen-Git** [comment]
#235 and #237 are closed in the meantime, so from my point of view everything is good to go.

**Comment by Fish-Git** [comment]
@ivan-w 

From my point of view we're good to go too. All we need now is for Ivan (who may now be too busy with his new job to spend much time working on Hercules) to agree we've waited "long enough" and that #222 can now be safely closed. Once that happens I'll begin the process of creating the fix release (tag current commit, build pre-builts, create github release pages, etc).

Ivan? Can #222 be closed?

**Comment by ivan-w** [comment]
Done !

**Comment by Fish-Git** [comment]
@davide125

Fix Release 4.2.1 in progress...

(And already I screwed up! I forgot to add `dasdser` to .gitignore! Sorry Dave! I'll get that fixed in a subsequent commit and try to remember that from now on.)

**Comment by Fish-Git** [comment]
DONE!

(I hope I did it right)
