### ISSUE TITLE
z/OS 2.3 IEA367A Multiple Console Support Inoperative without Multiple console support

### ISSUE THREAD

**Issue by sford1950** [SDL-Hercules-390/hyperion#246]
Running Fedora 30 server - 5.2.13-200.fc30.x86_64

Ipled Hercules , using CA ACF2 R16 ..

```
HHC02324I CP02: PSW=0704500080000000 00000000038C3744 INST=B218A000     PC    0(10)                  program_call
HHC02326I CP02: V:0000000000000B00:K:0E=00000000 00000000 00000000 00000000  ................
HHC02269I CP02: R0=0000000000000004 R1=000000007F6BF9C8
HHC02269I CP02: R2=0000000000FD91E0 R3=0000000000000008
HHC02269I CP02: R4=000000007F6C02D0 R5=0000000000FF3BF0
HHC02269I CP02: R6=000000000000020C R7=0000000000000003

HHC02269I CP03: RA=000000001F805790 RB=000000001F807DB0                                                                                                      +
HHC02269I CP03: RC=000000001F808DAF RD=000000001F807DB0
HHC02269I CP03: RE=000000007F6BCF78 RF=0000000000000B02
HHC02271I CP03: C0=00800002DF98EE20 C1=00000000FB51C007
HHC02271I CP03: C2=000000007EB99E80 C3=0000000180400009
HHC02271I CP03: C4=0000000100010009 C5=0000000002D38240
HHC02271I CP03: C6=00000000FE000000 C7=00000000FB51C007
HHC02271I CP03: C8=0000000000000000 C9=0000000000000000
HHC02271I CP03: CA=0000000000000000 CB=0000000000000000
HHC02271I CP03: CC=00000001004171DF CD=00000000FB51C007
HHC02271I CP03: CE=00000000DF882D3A CF=000000007FF87010
HHC00006I SCLP console interface active
*00 IEA367A MULTIPLE CONSOLE SUPPORT INOPERATIVE
            ERROR CODE = F0D6
            REPLY WITH ANY CHARACTER TO CONTINUE
            WITHOUT MULTIPLE CONSOLE SUPPORT
HHC00801I Processor CP00: LSX-translation exception code 0027  ilc 4
HHC02324I CP00: PSW=0704500080000000 00000000038C3744 INST=B218A000     PC    0(10)                  program_call
HHC02326I CP00: V:0000000000000B00:K:0E=00000000 00000000 00000000 00000000  ................
HHC02269I CP00: R0=0000000000000004 R1=000000007F6BF9C8
HHC02269I CP00: R2=0000000000FD91E0 R3=0000000000000008
HHC02269I CP00: R4=000000007F6C02D0 R5=0000000000FF3BF0
HHC02269I CP00: R6=000000000000020C R7=0000000000000003
HHC02269I CP00: R8=0000000000000000 R9=0000000000000001
HHC02269I CP00: RA=0000000000000B00 RB=000000007F6C02D0
HHC02269I CP00: RC=00000000038C4DA0 RD=000000007F6BE228
HHC02269I CP00: RE=000000007F6C02EC RF=00000000000000B4
HHC02271I CP00: C0=00800002DF98EE20 C1=00000000FB51C007
HHC02271I CP00: C2=000000007DA4CF00 C3=0000000180400009
HHC02271I CP00: C4=0000000100010009 C5=0000000002D38240
```
                                                                                       
Recursive loop ...

Let me know what you need to help resolve or review ...

Scott

**Comment by Fish-Git** [comment]
How did you get this to happen?  What do you have to do to enable Multiple Console Support in z/OS?  (I don't know z/OS that well)

I've been IPLing various different versions of z/OS for years (including 2.3) and have _never_ seen this happen!  Can you help me to reproduce the problem?  I can't fix it if I can't reproduce it!

**Comment by sford1950** [comment]
Fish,

We support RACF, which is IBM’s security system, CA Top-Secret and CA-ACF2 which are both developed by Broadcom.
I was able IPL all three, but ACF2 is the one that died . Multiple console support is a new one on me , been around z/OS long time.
Let me dig through IBM and CA doc and update you sometime next week

**Comment by sford1950** [comment]
Fish:

Here is my config and log of the failure. You might need the ACF2 volumes, if so I will have to talk to my management...

Scott




[hercules.txt](https://github.com/SDL-Hercules-390/hyperion/files/3614502/hercules.txt)

[hercules.log](https://github.com/SDL-Hercules-390/hyperion/files/3614501/hercules.log)
Fish:

I am attaching the full Hercules failing log and hercules.cnf used. The z/OS 2.3 was RSU 1709 ..

**Comment by Fish-Git** [comment]
> The z/OS 2.3 was RSU 1709 ..

I have no idea what that means.&nbsp;`:(`

(I know almost nothing about z/OS! Yes I can IPL it and logon and submit jobs, etc, and even do basic network configuring, but anything beyond that is questionable. I have no real practical experience wit it, so please treat me as someone who pretty much know _nothing_ about z/OS!)

**Comment by sford1950** [comment]
Fish:

This is the IBM manual for abend reference..

https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.1.0/com.ibm.zos.v2r1.ieah700/m014959.htm  pointing to the 0D6 abend with a condition code or reason code of 27 ..

27
Linkage second index translation exception. Start of changeThis can be caused by using a PC number which is no longer valid.End of change

Frankly this is going on inside z/OS and looks like "program call" that's not valid. The same Hercules 
and z/OS version are working on standard IBM RACF system, my thoughts are there is something going  on with CA ACF2 that is causing this issue. I think maybe a incapability. I will look on the CA ( Computer Associates - now Broadcom website ) and let you know

**Comment by Fish-Git** [comment]
I also found this too:

* [z/OS - Version 2 Release 3 - _MVS Planning: Operations_](https://www-01.ibm.com/servers/resourcelink/svc00100.nsf/pages/zOSV2R3SA231390/$file/ieag300_v2r3.pdf) &nbsp; (SA23-1390-30)

(last paragraph on page 2):

> **Multiple console support and the MVS environment**
> 
>  &nbsp;.&nbsp;&nbsp;.&nbsp;&nbsp;.
> 
> Defining  a console configuration  is an important part of your MVS operations planning. You define  a console configuration  by defining  the devices you want to use as consoles and their console attributes, in the `CONSOLxx` parmlib member. In `CONSOLxx`, these console attributes control important console functions like the types of commands operators can enter from the console, routing information for messages and commands, and how to use the console. `CONSOLxx` and the MCS and SMCS console attributes that you can control are described in _"Summary of `CONSOLxx` and commands to change values"_ on page 153.

Maybe your parmlib `CONSOL00`(?) member has been customized to specify multiple consoles and the expected second console isn't attached? Maybe you need to connect a tn3270 console to whatever the defined second  console device address is?

**Comment by sford1950** [comment]
Fish,

I found an address at x'908' for a console I will give it a whirl and see what happens.

Thanks,
Scott

**Comment by sford1950** [comment]
Fish ,

This was a bad disk volume. I tried another backup volume and everything came up fine.
Sorry for the trouble my friend.

Scott

**Comment by Fish-Git** [comment]
> This was a bad disk volume. I tried another backup volume and everything came up fine.

(Whew!) That's actually good to hear! It's a relief to learn the problem we originally thought existing doesn't actually exist. Thanks for letting us know.

> Sorry for the trouble my friend.

Not a problem! While I normally "hate" spending time and effort on a non-problem (chasing ghosts), in this particular case not a lot of time nor effort was involved. Just a few minutes was spent over the course of a few days sending a few messages back and forth, so the time "wasted" and effort involved wasn't very much.

Take care.
