### ISSUE TITLE
Process listing in LINUX shows some strange thread names

### ISSUE THREAD

**Issue by agadsby** [SDL-Hercules-390/hyperion#249]
Doing a "ps -T" or "top" with H options shows some very strange thread names. The issue is in hthreads.c  hthread_create_thread() where name points to a location specified by the caller BUT in some cases this is on the stack and not the heap. This means that name field will subsequently point at the wrong data.

The fix is trivial to strdup the name and use that in hthread_create_thread() instead:
Change line 815 from
    \*(arg2+2) = (void*) name;
To
    \*(arg2+2) = (void*) strdup(name);

I wonder if this may also explain other issues with threads as name doesn't always point to the expected string, or even a nul terminated string at all.

Andy Gadsby

**Comment by agadsby** [comment]
Related to this is that in top and ps listing Hercules is listed by its primary thread name
       impl_thread. 
This is explicitly set but I'm wondering if there is a reason why this name is used and also why this is explicitly set in impl.c:
    SET_THREAD_NAME( IMPL_THREAD_NAME );

This could be confusing for users who'd expect to Hercules listed and not impl_thread.

**Comment by Fish-Git** [comment]
> ... BUT in some cases this is on the stack and not the heap.

Andy, can you point to an example of this? IMO this is the bug that needs to be fixed!

I also consider it quite odd that Linux doesn't make its own private copy of the thread name. That sounds like a serious bug to me! What version of what Linux are you using?

And since I'm not a Linux person (but I do have CentOS 6.10 installed in a VMware virtual machine), can you explain how to recreate the incorrect behavior you're seeing?

**Comment by agadsby** [comment]
Hi Fish,

Just fire up Hercules on any LINUX box with MVS, or any other live system. This will create a thread for each device etc. if you then do a "ps -T" you then see all of the threads but instead I see some thread names correctly shown but some of them are blank or show  random characters. So that's the issue I chased down.

LINUX does keep its own copy of the thread name which is set by Hercules via this macro

    SET_THREAD_NAME( BOOTSTRAP_NAME );

which ultimately calls

DLL_EXPORT int nix_set_thread_name( pthread_t tid, const char* name )

The problem is that name as used is not always passed as a pointer into the heap but rather sometimes exists on the callers stack. Now here is the tricky part - hthread_create is called to create the new thread but the usage of name is after the new thread has been created and started so the calling stack, in the calling thread, is no longer valid. Therefore, a dereference is made to what is now other data on the stack. This links to your previous comments about the complexity of the hthreads.c code

Some threads do show the correct name but in those cases name is pointing to a constant e.g.

    #define BOOTSTRAP_NAME          "bootstrap"

but in some case the caller build up on the name on its stack e.g. from printer.c (which hints at an issue ! )

    /* Fix thread name */
    {
        char    thread_name[16];
        MSGBUF( thread_name, "spthread %1d:%04X", LCSS_DEVNUM );
        SET_THREAD_NAME( thread_name );
    }

The trivial solution is in hthreads.c / hthread_create_thread  to strdup() to copy the name to the heap and use that reference, which is now thread safe. In testing on my system this now works correctly and shows proper thread names.

I have raised this as a change so you can see how simple it is.

I'm now pondering if some of the mallocs() in the hthreads.c code are going to lead to memory leakage, especially if different OSs are iIPLed without quitting Hercules between ipls. 

I can send some screen shots if that would help show the problem but it will occur on any system - it's down to timing of the thread_start and the usage of the name parameter that determines what you see for certain thread names.

Andy

**Comment by Fish-Git** [comment]
Andy,

Your analysis is correct, but your fix is bad (incomplete).

I have rejected you pull request with the comment to please resubmit it with the `free` fix shown in my comment. If you do that then I will be happy to accept your pull request. Thanks!

&nbsp;
_**P.S.** I would appreciate it if you would post your comments/responses (replies) to this GitHub Issue _DIRECTLY_ via the GitHub web page user interface (`https://github.com/SDL-Hercules-390/hyperion/issues/249`), and _**not**_ via email. **(\*)**_

_Thanks._

___
_**(\*)** GitHub does not handle email replies very well, making it impossible for me to fix the formatting of your replies for readability. Thanks for understanding._

**Comment by Fish-Git** [comment]
Fix by Pull Request commit 04654299843f00b08ef6da4d9c3562b37690d88f.

Closing.
