### ISSUE TITLE
Date in the timestamp

### ISSUE THREAD

**Issue by rvanspaa** [SDL-Hercules-390/hyperion#260]
Hi,

As mentioned previously, it would be nice to have the date included in the timestamp when Hyperion is run in daemon mode. Because there are many date formats, and these vary by country, I thought perhaps you might consider a standard format such as ISO 8601?

**Comment by Fish-Git** [comment]
We'll see what we can do! Thanks for the suggestion!

**Comment by Fish-Git** [comment]
Fixed by commit 0719fe7a2b2ac147b31dbfcd8399fba4ed4a8004.

Closing.
