### ISSUE TITLE
HHC90013E 'obtain_lock(&sysblk.mainlock)' failed: rc=35: deadlock;

### ISSUE THREAD

**Issue by mcisho** [SDL-Hercules-390/hyperion#261]
Host is: &nbsp; _**Fedora 30 x86_64**_.

Hercules version: **`4.3.9999.0-SDL-ga6ae8c00-modified (4.3.9999.0)`**.

Problem description:

```
HHC90013E 'obtain_lock(&sysblk.mainlock)' failed: rc=35: deadlock; tid=00007f01be8bd700, loc=general2.c:404
HHC00007I Previous message from function 'loglock' at hthreads.c(83)
HHC90014I lock &sysblk.mainlock was obtained by thread 00007f01be8bd700 at general2.c:404
```

**`general2.c:404`** is the **`OBTAIN_MAINLOCK_UNCONDITIONAL( regs );`** statement in function **`DEF_INST(perform_locked_operation)`**.

The lock messages appear at regular intervals _(every 20 or 30 seconds)_ for various thread ids until the running system _(z/OS 1.13 under z/VM 6.1)_ eventually grinds to a halt. `PLO` obviously isn't used by VM as it runs fine alone.

&nbsp;
_(Added 20 minutes later):_

z/OS can be started and shut down successfully. The lock messages only appear when doing compiles or assemblies. _(Unsure whether it's either or both.)_

&nbsp;
_(Added several hours later):_

Nothing to do with compiles or assemblies:

* Running z/OS 1.13 _natively_ the problem does _not_ occur.
*  Running z/OS 1.13 _**under z/VM 6.1**_ the problem _**is reproducible**_.

**Comment by Peter-J-Jansen** [comment]
Sorry to hear about this problem. 

Question : What does the "HHC01417I Machine dependent assists:" message say when you issue a Hercules version command please ? E.g. something like :  

```
HHC01417I Machine dependent assists: cmpxchg1 cmpxchg4 cmpxchg8 cmpxchg16 hatomics=C11
```

Are all cmpxchg1/4/8/16 and the C11 atomics available ? If that would not be the case, then I have a suspicion what could cause it (and perhaps how to fix it).

Cheers,

Peter

**Comment by mcisho** [comment]
Here are the Hercules version and host CPU information.

HHC01603I version
HHC01413I Hercules version 4.3.9999.0-SDL-ga6ae8c00-modified (4.3.9999.0)
HHC01414I (C) Copyright 1999-2019 by Roger Bowler, Jan Jaeger, and others
HHC01417I ** The SoftDevLabs version of Hercules **
HHC01415I Build date: Oct  5 2019 at 12:03:44
HHC01417I Built with: GCC 9.2.1 20190827 (Red Hat 9.2.1-1)
HHC01417I Build type: GNU/Linux x86_64 host architecture build
HHC01417I Modes: S/370 ESA/390 z/Arch
HHC01417I Max CPU Engines: 64
HHC01417I Using   shared libraries
HHC01417I Using   setresuid() for setting privileges
HHC01417I Using   POSIX threads Threading Model
HHC01417I Using   Error-Checking Mutex Locking Model
HHC01417I With    Shared Devices support
HHC01417I With    Dynamic loading support
HHC01417I With    External GUI support
HHC01417I With    IPV6 support
HHC01417I With    HTTP Server support
HHC01417I With    sqrtl support
HHC01417I With    Signal handling
HHC01417I With    CCKD BZIP2 support
HHC01417I With    HET BZIP2 support
HHC01417I With    ZLIB support
HHC01417I With    Regular Expressions support
HHC01417I Without Object REXX support
HHC01417I Without Regina REXX support
HHC01417I With    Automatic Operator support
HHC01417I Without National Language Support
HHC01417I With    CCKD64 Support
HHC01417I Machine dependent assists: cmpxchg1 cmpxchg4 cmpxchg8 cmpxchg16 hatomics=C11
HHC01417I Running on: mcisho (Linux-5.2.17-200.fc30.x86_64 x86_64) MP=4
HHC01417I Built with crypto external package version 1.0.0.27-ga3e07b5
HHC01417I Built with decNumber external package version 3.68.0.80-gdb5c456
HHC01417I Built with SoftFloat external package version 3.5.0.83-g3da230f
HHC01417I Built with telnet external package version 1.0.0.45-g2d9f219-modified

$ sudo lshw -C cpu
  *-cpu                     
       description: CPU
       product: Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz
       vendor: Intel Corp.
       physical id: 4
       bus info: cpu@0
       version: Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz
       serial: To Be Filled By O.E.M.
       slot: LGA1155
       size: 2957MHz
       capacity: 3800MHz
       width: 64 bits
       clock: 100MHz
       capabilities: lm fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp x86-64 constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 popcnt tsc_deadline_timer xsave avx lahf_lm epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm arat pln pts md_clear flush_l1d cpufreq
       configuration: cores=2 enabledcores=1 threads=2

**Comment by Peter-J-Jansen** [comment]
Thanks for the speedy feedback.

So cmpxchg1/4/8/16 and C11 atomics are all present, which means that OBTAIN_ / RELEASE_MAINLOCK_UNCONDITIONAL as a result of commit e0052fd closing Issue #247, is the only MANLOCK present; all others are effectively nullified. So effectively, the PLO instruction was _not_ changed by this recent commit, as this now MAINLOCK_UNCONDITIONAL is identical to the pervious MAINLOCK; it was merely renamed.

So the next question is if this worked correctly prior to this commit. If it did, then we have a mystery. However, looking at the code implementing the PLO instruction, I do see a possibility for a MAINLOCK not being RELEASEd as a specification exception program interruption may have come prior to the RELEASE. But that too looks odd.

Therefore : did this work prior to this recent commit ?

Thanks,

Peter

**Comment by mcisho** [comment]
The preceding commit 1c542317 titled "Mostly cosmetic tweaks for upcoming #247 commit." works. Commit e0052fd9 introduces the problem.

I cannot see an PLO exceptions in the Herc log.

**Comment by Peter-J-Jansen** [comment]
Thanks for your reply !

OK, I must have overlooked something, and I will try my best to find and correct the issue.

I am already reviewing commit e0052fd but have not found anything yet. Perhaps I can reproduce the problem. I do not have z/OS 1.13 or z/VM 6.1, but perhaps z/OS 2.3 and z/VM 6.3 (which I use to test my stuff) exhibit the same problem. Are there some compiles / assemblies I could try ? Would you perhaps have a ready to run batch job for that ? Please also feel free to comment on my commit.

Another possibility is also if you'd be willing to rebuild whilst the variable MAINLOCK_ALWAYS is defined, and then see if the problem disappears. With that variable defined, the regular, i.e. non-conditional MAINLOCK macros are not nullified, and the resulting code is then identical to the preceding commit 1c54231 status (apart from the fact that the new cmpxchg## hardware assists remain present; but these by themselves do not use MAINLOCK).

Ian, I'm sorry about these problems; my apologies.

Peter

**Comment by mcisho** [comment]
The first time I saw the lock messages I was running compiles/assemblies and I thought the messages were being caused by them. Subsequent testing has shown they aren't involved, just starting z/OS with the common or garden address spaces provokes the messages.

Once I've found where MAINLOCK_ALWAYS is defined I'll have a go. I will be later today, I'm currently in the process (using commit 1c54231) of doing those compiles/assemblies I wanted to do yesterday.

**Comment by Peter-J-Jansen** [comment]
I think to have corrected an oversight of mine, and would be thankful if you could please verify if the fix works, and let me know the results.

Thanks,

Peter

**Comment by mcisho** [comment]
Yes, that seems to have fixed the problem.

Thanks.

**Comment by Peter-J-Jansen** [comment]
Thanks for the positive news ! I think we can close this now.

Cheers,

Peter
