### ISSUE TITLE
Serious bug in CMPSC (Compression Call) instruction

### ISSUE THREAD

**Issue by Fish-Git** [SDL-Hercules-390/hyperion#264]
_(This issue is closely related to issue #265 "CMPSC Compression Call test")_
___

Reported by @rwoodpd (Bob Wood):

> There is a major bug in the support for the CMPSC instruction.    I discovered it when testing SMP/E.

> There is a utility called `GIMCPTS` (located in `SYS1.MIGLIB` on z/OS) than compacts and expands PTFs.   &nbsp; It uses CMPSC to do the compression, and in some cases it is not even close to being right.   I am attaching the expanded data, and the correct and incorrect compressed data.   I will run Hercules through the Visual Studio debugger to try and capture the dictionary being used, and the contents of R0.     I can work on this if you like, or try to send you the needed doc.

>R0 = 0x00000000 0x00005200

> I did verify it on real hardware.  Also, if I compress and then reexpand the data, the reexpanded data does not match the original data.  On real hardware it does match.  I will gather the data and  ...

> I was able to recreate the error with a simple program that uses the CMPSC instruction just once.    I ran the program on Hercules and on a real machine using the same dictionary and the same input file.   The output (compressed) files are not the same.   When the correct compressed file (from the real machine) is expanded, the result matches the original input file.   Expanding the compressed file from Hercules results in a file that does not match the original.   Expanding the correct file works fine on both Hercules and the real machine, so the problem must just be with compression. I am attaching a zip file that contains the following files:

* [cmpsc_files.zip](https://github.com/SDL-Hercules-390/hyperion/files/3814832/cmpsc_files.zip)

> *  `cmpsctst.asm`: source for my assembler test program.  It just reads the input file and dictionary into buffers, invokes CMPSC, then writes out the result from the output buffer.  A four byte length is prefixed to the compressed  data.
> *  `cmpsctst.jcl`: JCL to run the program.
> *  `asmcmpts.jcl`: JCL to assemble the test program (only requires standard system macros).
> *  `cmpsctst_in.bin`: input data to compress
> *  `cmpsctst_out_ok.bin`: correct compressed output from the real machine
> *  `cmpsctst.out.err.bin`: incorrect compressed output from hercules.
> *  `cmpsctst_compress_dict.bin`: compression dictionary
> *  `cmpsctst.expand.dict.bin`: expansion dictionary

> You should be able to recreate the issue with the files above.   I don't think an instruction trace is needed, because you have access to the source. The input file consists of four records.   If you upload the files to z/OS, the .bin files should be transferred in binary, and the others using
ASCII-EBCDIC translation.    All files are RECFM=FB (fixed block).   The dictionary files should be uploaded with record length (LRECL) 64, all others record length 80.
>
> Please let me know if there is anything else you need.
>
>  Bob Wood

**Comment by Fish-Git** [comment]
Files received.  Thank you.  I am actively looking into the problem and will get back to you as soon as I can.  This issue is currently my #&#8203;1  priority right now.

It might take me a short(?) while before I can report anything however, as I must first update my [cmpsctst test program](https://github.com/Fish-Git/cmpsctst) to reflect the changes that have been made to SDL Hyperion over the years. Once that is done however, I am hoping the bug should be fairly easy to recreate, identify and of course fix.

(I just hope it doesn't have anything to do with the new Entropy-Encoding-Compression Facility, which I haven't added support for yet! If it does, then the fix is obviously going to take a bit longer!)

QUESTION: Can you confirm whether or not facility 54 (Entropy-Encoding-Compression Facility) is enabled or not on the real machine you tested with? If so, is there a way to disable it and run the test again without it?

**Comment by rwoodpd** [comment]
Facility bit 54 is not set on the machine I was testing on.

 

  Bob

**Comment by Fish-Git** [comment]
Bug found! Fix coming.

**Comment by ivan-w** [comment]
You rock !

**Comment by Fish-Git** [comment]
@rwoodpd Bob,

Bug is fixed by commit 6e3749700900c0555ac891e4c98cd422e6955db3.

Please pull, rebuild, and re-test with your own test program to verify.(*)

(*) With me being too inexperienced with z/OS I was to unable to test using your test program (don't know hot to create the datasets, etc!), BUT... I did add your input file and dictionaries to my [cmpsctst testing tool](https://github.com/Fish-Git/cmpsctst) and now all tests complete with 100% success rate (whereas before they weren't due to the bug).

**Comment by Fish-Git** [comment]
> You rock!

Thank you for the sentiment Ivan, but no, I definitely _don't_ rock. &nbsp; It was **_me_** that _introduced_ (caused) the damn bug: a seemingly innocent cosmetic-type change by commit 771dccae92b8508c4a2ee327b51cd8b3a782a2a6.

By adding the `#define _CMPSC_C_` statement at the beginning of the file, I inadvertently caused the `g_nDictSize` table to never get built (because it was guarded with #ifdefs for \_CMPSC_C\_), thereby causing the CMPSC instruction to use undefined dictionary size values, leading to unpredictable results. &nbsp;_(Oops!)_&nbsp; `(:-(`

And what's worse, _this bug has been in SDL Hercules for **almost 2 years**. &nbsp;(Yikes!)_&nbsp;`(:-o`

Definitely _not_ good. &nbsp; `:(`

**Comment by ivan-w** [comment]
Do we have a CI action on Github ?

**Comment by rwoodpd** [comment]
verified

 

  Bob

**Comment by Fish-Git** [comment]
> verified
>
> Bob

Thank you!

Closing.

**Comment by Fish-Git** [comment]
> Do we have a CI action on Github? (unrelated to the problem at hand)

If by "CI" you mean "Continuous integration", then Yes! Of course!  It's called "Travis CI", and we've been using it for quite some time now:

* [`.travis.yml`](https://github.com/SDL-Hercules-390/hyperion/blob/master/.travis.yml)

Notice the little green checkmarks next to most commits:

* https://github.com/SDL-Hercules-390/hyperion/commits/master

Clicking on the checkmark display a dialog with a "Details" link. Click on the "Details" link and it will show you the `make test` results for that commit for all of the configured configurations (as controlled by the above `.travis.yml` file).

We also provide a nice Travis CI "build: passing" link:

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; [![image](https://user-images.githubusercontent.com/1486786/68504872-e43f9980-021a-11ea-99a4-afdc4094228a.png)](https://travis-ci.org/SDL-Hercules-390/hyperion)

at the top of our main repository README.md page at the bottom of our main github repository web page:

* https://github.com/SDL-Hercules-390/hyperion

(scroll down to the bottom and you should see the Travis CI "build: passing" image/link at the top of the ReadMe.)

I created a [GitHub Issue for updating it to include one or more Apple Mac platforms](https://github.com/SDL-Hercules-390/hyperion/issues/200), but so far no one has stepped forward to help us out with that. (*) &nbsp;`:(`

___
(*) I'd do it myself but I know next to _NOTHING_ about the Apple Mac.&nbsp; `:(`

**Comment by Fish-Git** [comment]
> > Do we have a CI action on Github? (unrelated to the problem at hand)
> 
> If by "CI" you mean "Continuous integration", then Yes! Of course! It's called "Travis CI", and we've been using it for quite some time now

FYI: that's why I told you (quite some time ago) why, for _simple_ "cosmetic" type commits (such as commits that just update our documentation or just fix a typo in a comment or something, i.e. something that doesn't actually change any of the actual 'C' code anywhere), you should always be sure to include the magic string "[skip travis]" somewhere in your git commit log message. Otherwise each commit kicks off a Travis CI build (which I hope you'll agree is silly for .html or README documentation changes!).

Hope that helps!
