### ISSUE TITLE
VTAM CTC Using Hyperion 4.2

### ISSUE THREAD

**Issue by TheBaronBradley** [SDL-Hercules-390/hyperion#269]
I am trying to get CTC between to LPARS active using VTAM Channel to Channel but when I try and activate PU I get INTREQ.

First question is does VTAM to VTAM via CTC work on CTCE connection under Windows?

**Comment by ivan-w** [comment]
If you are getting INTREQ chances are you have a configuration issue. SSCP to SSCP should work with CTCE (regardless of the OS hosting hercules).

Try issuing a t+cuu (on the hercules panel on both sides) and show us what gives.

--Ivan

**Comment by TheBaronBradley** [comment]
Hello Ivan,

Thank you for responding. I just wanted to confirm what I was trying was possible. I have done further work and now have the link active. I had to tune the MAXBFRU in the CTC major node. I do have some issues working cross domain but I am working on those. However the CDRMS are now active and paths work between the two systems. I need to play with VTAM start options to get application access issues rectified.

**Comment by ivan-w** [comment]
So you are getting there. I did manage do get cross CDRM working accross multiple VM/VTAM systems (even 3.2 to 4.2) using CTCE... but not even sure if you are using OS VTAM, VM VTAM or VSE VTAM !

**Comment by TheBaronBradley** [comment]
Yes it is working just need to get the cross domain sessions initiating. It is OS VTAM to OS VTAM. I am getting 089d0001 when session tries to init but I believe with some start option tweaking I will be able to get them working.

**Comment by Peter-J-Jansen** [comment]
I am working on CTCE improvements for recovery purposes (such as when restarting CTCE links), and my development GitHub (https://github.com/Peter-J-Jansen/SDL-hyperion/tree/personal-extras) contains additional CTCE information showing also some of the VTAM CTC definitions I use; these might be useful to you.

Cheers,

Peter

**Comment by ivan-w** [comment]
For some reason, this didn't get through.. Are you sure your VTAM instance is CDRM capable ?

**Comment by ivan-w** [comment]
https://www.ibm.com/support/knowledgecenter/SSLTBW_2.1.0/com.ibm.zos.v2r1.cs3cod0/sc089d.htm
089D0001 looks like a configuration error.

**Comment by ivan-w** [comment]
Looks to me you either don't have CDRM capabilities on both sides or both sides are using the same SSCP SUBAREA number or you have an error in your VR (Virtual Routes) or PR (Physical Routes).

**Comment by TheBaronBradley** [comment]
Thanks Peter for the info will look at that. 

Ivan I agree the 089d001 is config and I think if I play with the start options enhaddr= and also check path tables I have setup I should be ok. Both systems are CDRM capable and I actually get both CDRMs active and subareas are 01 and 06. Once I have done some more analysis and have the cross domain logon working I will share the setup so anyone else trying this has a chance of getting it working. GTF trace next step if the config changes don't work.

CTCE definitely works it is just a little flaky on recovery but will allow me to do what I need to. :-) Once the VTAM piece is in place I am also going to setup XCF properly between my two systems. 

Thank you both your comments so far.

**Comment by Fish-Git** [comment]
> ... and my development GitHub (https://github.com/Peter-J-Jansen/SDL-hyperion/tree/personal-extras) contains additional CTCE information showing also some of the VTAM CTC definitions I use; these might be useful to you.

You are referring to the additional CTCE information that you added to your [README.NETWORKING](https://github.com/Peter-J-Jansen/SDL-hyperion/blob/personal-extras/readme/README.NETWORKING.md) document in your repository, yes?

If so, and if the additional information applies to SDL Hyperion as well, then please update current SDL Hyperion's [README.NETWORKING](https://github.com/SDL-Hercules-390/hyperion/blob/master/readme/README.NETWORKING.md) document the same way too!&nbsp; Your changes look very nice!!

**Comment by Peter-J-Jansen** [comment]
My [CTCE development repo](https://github.com/Peter-J-Jansen/SDL-hyperion) containing various corrections and improvements, especially when restarting or recovering CTCE based connections, is now ready for testing. If all goes well, the intent is to commit this in a few weeks time.

Cheers,

Peter

**Comment by Fish-Git** [comment]
Thanks for the update, Peter! That's fantastic news! I look forward to your commit!

**Comment by TheBaronBradley** [comment]
Just as a quick update I have actually got this working between two ZOS LPARs. It works well once active. I will be using you rnew build Peter to see if it makes startup and recovery easiwer for the CTCE. Once that is done I will share my configs here.

**Comment by Peter-J-Jansen** [comment]
Please note that the announced CTCE v2 corrections and improvements were just made available via commit a575524. I believe this Issue can therefore be closed.

Cheers,

Peter
