### ISSUE TITLE
ECKD X'E7' Locate Record may return incorrect status when using CCKD(?) and/or CCKD64 media

### ISSUE THREAD

**Issue by ivan-w** [SDL-Hercules-390/hyperion#271]
Traces indicate an issue where a X'E7' Locate Record returns an empty SCSW/CSW status when jumping track.... The same CCW works fine under the original CKD/AWS (or something is different in the RDC data returned...)

Study in progress... More details to come. (Issue opened for tracking purposes.)

**Comment by Fish-Git** [comment]
Might it have something/anything to do with the following (and subsequent) change(s), which, while mostly related to Read Count handling, nonetheless _did_, I believe, _also_ impact E7 Locate Record handling as well:

> Revision: 4a8ad33dba76221d0e9fa56595d85aa7c13ef29b
> Author: Bob Wood <rwoodpd@gmail.com>
> Date: 12/28/2018 8:31:39 PM
> Message: Fix CKD suffixed Read Count bug
> 
> Modified: ckddasd.c
> Modified: dasdtab.c
> Modified: hstructs.h

**See also** the GitHub Issue #166 thread [**"z/VM 6.4 Issues FILE PROTECT errors on DASD"**](https://github.com/SDL-Hercules-390/hyperion/issues/166), which I believe had to do with the above mentioned commit. _Specifically,_ the following three comments of mine that appear in said thread (although it wouldn't hurt to read through the entire thread in detail):

* [Fish-Git commented on Dec 28, 2018](https://github.com/SDL-Hercules-390/hyperion/issues/166#issuecomment-450459064)
* [Fish-Git commented on Jan 7, 2019](https://github.com/SDL-Hercules-390/hyperion/issues/166#issuecomment-451954353)
* [Fish-Git commented on Jul 11, 2019](https://github.com/SDL-Hercules-390/hyperion/issues/166#issuecomment-510507376)

Bob Wood (now one of our fellow Hercules developers) is the person mentioned in the first of the above referenced comments.

The second above referenced comment mentions Mark's claims that Bob's initial implementation failed to pass his (Mark's) QA tests.

The third above referenced comment mentions that the problem _might_ be related possibly incorrect RDC/RCD data being returned by Hercules (which we've always had trouble with).

I realize that might not help you resolve your problem but felt it should at least be mentioned if only for, as you say, "tracking" (heh!) purposes.

**Comment by Fish-Git** [comment]
> Traces indicate ...

Can we _see_ them? &nbsp; `:)`

> More details to come.

Still waiting! &nbsp; `:)`

p.s. some guidance regarding how one might try to recreate the problem for themselves would be helpful as well (such as the traces you supposedly have). That way you don't have to work on this issue yourself. That way others could maybe jump in to try and figure it out and fix it themselves too, instead of only you!

Just sayin'

**Comment by Fish-Git** [comment]
I believe this issue (bug) was finally identified by issue [#464 ("z/VM 7.2 doesn't work with compressed DASDs")](https://github.com/SDL-Hercules-390/hyperion/issues/464) and was fixed by commit 120c28b8559f822d8bbe01a46652359933b0a3bb.

Closing.
