### ISSUE TITLE
Non-intercepted STFLE in SIE doesn't return correct running architecture

### ISSUE THREAD

**Issue by ivan-w** [SDL-Hercules-390/hyperion#272]
If a STFLE instruction is issued from a z/Architecture hypervisor and in a SIE environment and STFLE is not intercepted AND the SIE is a S/390 architecture virtual machine, STFLE still indicates that z/Architecture is active.

On IBM built machines, the results will be that z/Architecture is not active. On Hercules STFLE indicates z/Architecture is active although the SIE environment is S/390.

**Comment by ivan-w** [comment]
Fixed by https://github.com/SDL-Hercules-390/hyperion/commit/a2a810adeb67cdabb0c565f723c8463afd406207 - Please review

**Comment by ivan-w** [comment]
Note : the fix determines if STFLE is being issued from a S/390 SIE guest - in which case Byte 0 bit 2 of STFLE should be 0. Some hypervisors intercept STFLE and fix set the bit right, some rely on the underlying infrastructure. This fix ensures STFLE works in this case.

**Comment by Fish-Git** [comment]
> If more symbolic names could be used instead of hardcoded values....

Fixed in commit 0912933aad590767fee63f3708a1a31ec5a0bbcc.

(You're welcome)

**Comment by Fish-Git** [comment]
(p.s. Good catch!)

**Comment by ivan-w** [comment]
Thank you :)

**Comment by ivan-w** [comment]
This can be put under wrap I guess ;)
