### ISSUE TITLE
DASDCOMP Message HHC02424E against 3380 created volume

### ISSUE THREAD

**Issue by davekreiss** [SDL-Hercules-390/hyperion#278]
I created a 3380 dasd volume using DASDINIT then immediately did a DASDCOMP and received message HHC02424E.

PC OS is Windows 10 and the commands issued were DASDINIT and DASDCOMP from command line. Those commands and resulting messages follow.

```
C:\Program Files\Hercules\Hercules>DASDINIT -a "C:/Program Files/Hercules/Dasd/RES380.3380" 3380-J RES380
HHC02499I Hercules utility dasdinit - DASD image file creation program - version 4.2.0.9708-SDL-gdc7243b2
HHC01414I (C) Copyright 1999-2019 by Roger Bowler, Jan Jaeger, and others
HHC01417I ** The SoftDevLabs version of Hercules **
HHC01415I Build date: Jul 8 2019 at 12:19:44
HHC00467W Maximum cylinders supported is 65536
HHC00007I Previous message from function 'create_ckd' at dasdutil.c(1848)
HHC00462I 0:0000 CKD file C:/Program Files/Hercules/Dasd/RES380.3380: creating 3380 volume RES380: 886 cyls, 15 trks/cyl, 47616 bytes/track
HHC00460I 0:0000 CKD file C:/Program Files/Hercules/Dasd/RES380.3380: 886 cylinders successfully written
HHC02423I DASD operation completed
```

```
C:\Program Files\Hercules\Hercules>CCKDCOMP -3 "C:/Program Files/Hercules/Dasd/RES380.3380"
HHC02499I Hercules utility cckdcomp - CCKD compress program - version 4.2.0.9708-SDL-gdc7243b2
HHC01414I (C) Copyright 1999-2019 by Roger Bowler, Jan Jaeger, and others
HHC01417I ** The SoftDevLabs version of Hercules **
HHC01415I Build date: Jul 8 2019 at 12:19:44
HHC02424E Dasd image file format unsupported or unrecognized: C:/Program Files/Hercules/Dasd/RES380.3380
HHC00007I Previous message from function 'main' at cckdcomp.c(99)
C:\Program Files\Hercules\Hercules>
```

Hopefully that is sufficient to determine what is happening. Note that I tried variations of 3380-J -E and -K with and without specifying alternate tracks with same results.

Let me know if there is any more info you might need.

Dave Kreiss

**Comment by davekreiss** [comment]
Oops wrong place - soooo sooooorry

**Comment by davekreiss** [comment]
So sorry to be ping ponging this issue.

**Comment by Fish-Git** [comment]
_[**PEBKAC**](https://www.google.com/search?q=define+PEBKAC)_

> DASDINIT -a "C:/Program Files/Hercules/Dasd/RES380.3380" 3380-J RES380

This command creates an ordinary <i><b>non-</b>compressed</i> "CKD" dasd image file.

> CCKDCOMP -3 "C:/Program Files/Hercules/Dasd/RES380.3380"

This command is attempting to "compress" a <i><b>non-</b>compressed</i> "CKD" dasd image file. This will _**NEVER WORK**_ and will always result in the error message you are seeing.

The `cckdcomp` command _(notice the first 4 characters of the command itself!! "**cckd**comp"!!)_ only works on _compressed_ "_**CCKD**_" dasd image files. It cannot magically convert an ordinary <i><b>un</b>compressed</i> "CKD" dasd image file into a compressed "CCKD" dasd image file.

(Ref: "**[Compressed Dasd Emulation - Utilities](https://sdl-hercules-390.github.io/html/cckddasd.html#utilities)**")

You can either use the `dasdcopy` utility to convert your existing CKD image into a CCKD image _(being sure to specify the **`-o CCKD`** output option)_:

<pre>
HHC02499I Hercules utility dasdcopy - DASD copy/convert - version 4.3.9999.9877-SDL-gc67ac2ee
HHC01414I (C) Copyright 1999-2019 by Roger Bowler, Jan Jaeger, and others
HHC01417I ** The SoftDevLabs version of Hercules **
HHC01415I Build date: Feb  1 2020 at 02:35:52
HHC02594E Syntax error: missing input-file specification
HHC00007I Previous message from function 'syntax' at dasdcopy.c(646)
HHC02439I Usage: dasdcopy [-options] ifile [sf=sfile] ofile
HHC02439I Copy a dasd file to another dasd file
HHC02439I   ifile    input dasd file   (required)
HHC02439I   sfile    input shadow file (optional) (see note)
HHC02439I   ofile    output dasd file  (required)
HHC02439I Options:
HHC02439I   -h       display this help and quit
HHC02439I   -q       quiet mode, don't display status
HHC02439I   -r       replace the output file if it exists
HHC02439I   -z       compress using zlib [default]
HHC02439I   -bz2     compress using bzip2
HHC02439I   -0       don't compress output
HHC02439I   -blks n  size of output fba file
HHC02439I   -cyls n  size of output ckd file
HHC02439I   -a       output ckd file will have alt cyls
HHC02439I   -lfs     create single large output file
<b>HHC02439I   -o type  output file type (CKD, CCKD, FBA, CFBA)</b>
HHC02439I
HHC02439I Note: input shadow files will, as part of the copy
HHC02439I operation, have their data automatically merged into
HHC02439I the resulting output file.
</pre>

&nbsp;
Or, _**even easier**_, simply _**create**_ your compressed CCKD image from the get-go by simply specifying the necessary **`-z`, `-bz2`** or **`-0`** option on your `dasdinit` command:

<pre>
HHC02499I Hercules utility dasdinit - DASD image file creation program - version 4.3.9999.9877-SDL-gc67ac2ee
HHC01414I (C) Copyright 1999-2019 by Roger Bowler, Jan Jaeger, and others
HHC01417I ** The SoftDevLabs version of Hercules **
HHC01415I Build date: Feb  1 2020 at 02:35:52
HHC02448I Usage: dasdinit [-options] filename devtype[-model] [volser] [size]
HHC02448I Builds an empty dasd image file
HHC02448I options:
HHC02448I
<b>HHC02448I   -z        build compressed dasd image file using zlib
HHC02448I   -bz2      build compressed dasd image file using bzip2
HHC02448I   -0        build compressed dasd image file with no compression</b>
HHC02448I   -lfs      build a large (uncompressed) dasd file (if supported)
HHC02448I   -a        build dasd image file that includes alternate cylinders
HHC02448I             (option ignored if size is manually specified)
HHC02448I   -r        build 'raw' dasd image file
HHC02448I             (no VOL1 or IPL track)
HHC02448I   -b        make wait PSW in IPL1 record a BC-mode PSW
HHC02448I             (default is EC-mode PSW)
HHC02448I   -m        enable wait PSW in IPL1 record for machine checks
HHC02448I             (default is disabled for machine checks)
HHC02448I   -linux    null track images will look like Linux dasdfmt'ed images
HHC02448I             (3390 device type only)
HHC02448I
HHC02448I   filename  name of dasd image file to be created
HHC02448I   devtype   CKD: 2305, 2311, 2314, 3330, 3340, 3350, 3375, 3380, 3390, 9345
HHC02448I             FBA: 0671, 3310, 3370, 9313, 9332, 9335, 9336
HHC02448I
HHC02448I   model     device model (implies size) (opt)
HHC02448I   volser    volume serial number (1-6 characters)
HHC02448I             (specified only if '-r' option not used)
HHC02448I   size      number of CKD cylinders or 512-byte FBA sectors
HHC02448I             (required if model not specified else optional)
</pre>

&nbsp;
Closing issue as Invalid (User Error).
