### ISSUE TITLE
Issues building new version on Windows

### ISSUE THREAD

**Issue by TheBaronBradley** [SDL-Hercules-390/hyperion#281]
Well I have downloaded the new version but get the following when trying to install:

```
F:\Hyperion>nmake clean -f makefile-dllmod.msvc

Microsoft (R) Program Maintenance Utility Version 14.11.25547.0
Copyright (C) Microsoft Corporation.  All rights reserved.

Makefile presuming VS2017 (VS15 = _MSC_VER 1910 - 1912)
Target processor type is 32-bit i386
ZLIB support will not be generated
BZIP2 support will not be generated
PCRE support will not be generated
makefile-dllmod.msvc(28) : fatal error U1052: file 'win32.mak' not found
Stop.

F:\Hyperion>nmake clean -f makefile-dllmod.msvc
```

I have commented out WIN32.mak include but get further errors if I do that.

Am I missing something? My machine is x64 Windows 10 machine.

I do have the old version working but want to try this one for the enhanced recovery.

**Comment by TheBaronBradley** [comment]
Oh I do have VS 2017 installed but run with e VS 2008 redistributables as well.

**Comment by wrljet** [comment]
Go to these instructions:

`http://www.softdevlabs.com/hercules-vs2015-build.html`

Make sure you have "Windows XP Support for C++" optional feature of VS installed.

And make sure you have done the stuff in:

  **2. Define Environment Variables and Fix Property Sheets.**

This should let it find the `win32.mak`.

Bill

**Comment by TheBaronBradley** [comment]
Thank you
