### ISSUE TITLE
Windows update?

### ISSUE THREAD

**Issue by rvanspaa** [SDL-Hercules-390/hyperion#286]
Hi,

Is there a more recent Windows binary than this:- Hercules-4.2.1.9826-SDL-g9b5cbe3d-x64 ?

**Comment by Fish-Git** [comment]
Not yet, no.

But the latest and greatest 4.3 version (still under development) can always be built manually for yourself at any time by anyone.

**Comment by Fish-Git** [comment]
p.s. Such questions should normally be asked on the Hercules-390 support group (https://hercules-390.groups.io/g/group) and not here. GitHub Issues are for reporting "Issues" (problems), not for asking simple questions. In the future, please ask such questions there and not here.
