### ISSUE TITLE
OSA Adapter Layer 3 

### ISSUE THREAD

**Issue by thomasMainframe** [SDL-Hercules-390/hyperion#291]
Hi all,
i try to configure an OSA Adapter in my **z/OS 2.3** and Hercules Version **Linux-4.12.14-lp151.28.40-default x86_64.**

From my config :

`0400.3   QETH debug `

When TCPIP comes up see the following Messages 

`HHC03800I 0:0401 QETH: Adapter mode set to Layer 3 `                                                                                                        
`HHC00901I 0:0401 QETH: Interface tun0, type TUN opened`                                                                                                     
`HHC03997I 0:0401 QETH: tun0: using MAC address 02:00:5e:cc:fa:37             `                                                                              
`HHC03997I 0:0401 QETH: tun0: using MTU 1500  `                                                                                                              
`HHC03997I 0:0401 QETH: tun0: using drive MAC address da:4d:d5:f7:c6:f3 `                                                                                    
`HHC03997I 0:0401 QETH: tun0: using drive IP address fe80::da4d:d5ff:fef7:c6f3 `                                                                             
`HHC03805I 0:0401 QETH: tun0: Register guest IP address 192.168.178.200`                                                                                     
`HHC02499I Hercules utility hercifc - Hercules Network Interface Configuration Program - version 4.3.9999.0-SDL-ge004d298 `                                  
`HHC01415I Build date: Mar 23 2020 at 10:51:46`                                                                                                              
`HHC00166E hercifc: ioctl error doing SIOCSIFDSTADDR on tun0: 99 Cannot assign requested address                                                            `
`HHC00007I Previous message from function 'main' at hercifc.c(257) ` 

How can i fix that ?

Thanks, Thomas

**Comment by mcisho** [comment]
Hi Thomas,
From the information you have provided I'm afraid we do not know how you can fix that. Perhaps if you were to provide the complete config, the complete log, and a detailed description of the environment in which you are running Hercules, we might have enough information to be able to provide some suggestions.
Ian

**Comment by thomasMainframe** [comment]
Hi Ian
here are more details.

Driving System OpenSUse 15.1 with kernel 4.12.14-lp151.28.40-default
Guest System is z/OS 2.3 LPAR Mode
[hercules.log](https://github.com/SDL-Hercules-390/hyperion/files/4381421/hercules.log)
[zos.txt](https://github.com/SDL-Hercules-390/hyperion/files/4381428/zos.txt)

ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether d4:3d:7e:d8:23:bf brd ff:ff:ff:ff:ff:ff
    inet 192.168.178.43/24 brd 192.168.178.255 scope global eth0
       valid_lft forever preferred_lft forever

ip route
default via 192.168.178.1 dev eth0 proto dhcp 
192.168.178.0/24 dev eth0 proto kernel scope link src 192.168.178.43 

Thanks, Thomas

**Comment by mcisho** [comment]
The last time I used SUSE was more than 15 years ago, so I'm definitely no expert on SUSE, open or otherwise. Perhaps openSUSE is stricter than other distributions on the IP addresses used by interfaces? You would have two interfaces (eth0 and tun0) that are both using IP address in the 192.168.178.0/24 subnet. Try eth0 and tun0 on different subnets.
Ian

**Comment by thomasMainframe** [comment]
Hi Ian,

1. i run as root
2. ip addr add 192.168.178.200 dev tun0 
2a. results in HC03805I 0:0401 QETH: tun0: Register guest IP address 192.168.178.200 
3. ping 192.168.178.200 from my suse works
I will setup a package trace to see what happens

**Comment by thomasMainframe** [comment]
Later 
HC03805I 0:0401 QETH: tun0: Register guest IP address 192.168.178.200 
sniffer trace from z/os

wireshark trace from suse

![suse](https://user-images.githubusercontent.com/41484233/77566367-d5a20800-6ec5-11ea-83da-0342cd1a0e23.png)

![zos](https://user-images.githubusercontent.com/41484233/77566215-a4293c80-6ec5-11ea-8019-4ebd03d30b53.png)

What i did 
Suse
stop firewall
clear iptables
trace tun0 via Wireshark

z/OS

trace ct,wtrstart=wtrproc
trace ct,on,comp=systcpda,comp=(tcpip)
r xx,wtr=wtrproc,end
v tcpip,,pkttrace,on
`ping to and from z/OS`
trace ct,on,comp=systcpda,comp=(tcpip)
r xx,wtr=disconnect,end
trace ct,off,comp=systcpda,sub=(tcpip)
trace ct,wtrstop=wtrproc,flush
Convert Trace to sniffer format
//SYSPROG  JOB  (015424,OS390,TEST),'GRANZOW.4825',
//  MSGCLASS=X,NOTIFY=&SYSUID,MSGLEVEL=(1,1),REGION=0M
//*
// SET INDUMP=OEM.EXIGENCE.EXPORT
// SET SNIFFR=XFER.SYSPROG.SNIFFER
//*
//IPCSBTCH EXEC PGM=IKJEFT01,DYNAMNBR=30
//SYSPRINT DD SYSOUT=*
//SYSTSPRT DD SYSOUT=*
//IPCSDDIR DD DISP=SHR,DSN=&SYSUID..DDIR
//INDMP    DD DISP=SHR,DSN=&INDUMP
//*SNIFFER  DD DISP=SHR,DSN=&SNIFFR
//SNIFFER  DD DISP=(,CATLG),DSN=&SNIFFR,
//            DCB=(LRECL=1560,RECFM=FB,DSORG=PS),
//            SPACE=(CYL,(500,550))
//IPCSPRNT DD SYSOUT=*
//IPCSTOC  DD SYSOUT=*
//SYSTSIN  DD *
 PROFILE MSGID
 IPCS NOPARM
 SETD PRINT NOTERM LENGTH(160000) NOCONFIRM FILE(INDMP)
 DROPD
 CTRACE COMP(SYSTCPDA) SUB((TCPIP)) OPTIONS((SNIFFER(1500)))
 END

**Comment by thomasMainframe** [comment]
I see a icmp package from z/OS to suse ( tun0 )
But did not see the ping from suse to zos

**Comment by mcisho** [comment]
Can you please try eth0 and tun0 on different subnets, so that we can eliminate your original question?

> ip addr add 192.168.178.200 dev tun0

sets the IP address of the linux end of the tun0 to 192.168.178.200, hence ping 192.168.178.200 from your SUSE will always work. It's like pinging 192.168.178.43 or 127.0.0.1 from SUSE, always gaurenteed to work

Ian

**Comment by thomasMainframe** [comment]
Hi Ian,
i changed the z/OS address to 192.168.179.100, but still no luck
[hercules.log](https://github.com/SDL-Hercules-390/hyperion/files/4385573/hercules.log)

**Comment by mcisho** [comment]
Hmm... looks like an openSUSE problem to me.

You could try setting up and using a preconfigured tun interface. To set it up, and assuming your z/OS address is still 192.168.179.100, issue:

> ip tuntap add mode tun dev tun999
> ip -4 addr add dev tun999 192.168.179.43 peer 192.168.179.100/24
> ip link set dev tun999 mtu 1500
> ip link set dev tun999 up

and change you Hercules config to:

> 0400.3  QETH  ifname tun999  debug

Ian

**Comment by thomasMainframe** [comment]
Hi Ian,
it's working now. 

Thanks for your help, Thomas
