### ISSUE TITLE
MacOS build fails decNumber 

### ISSUE THREAD

**Issue by kikohnl** [SDL-Hercules-390/hyperion#292]
Aloha,

decNumber is shipped without source, and the lib directory only has static libraries, which cannot be used to build shared application/libraries.

**Comment by wably** [comment]
kikohnl,

It looks like you did not build the external packages as required by SDL Hyperion.  Please see the readme.extpkg write up in the readme directory of the code repository.  While the readme documentation is Windows focused, I have successfully followed it on both Windows and Raspbian (Raspberry PI Linux).   After this one-time special build, then proceed to build and compile SDL Hyperion.

Regards,
Bob

**Comment by Fish-Git** [comment]
kikohnl,

What Bob said is absolutely the correct resolution to your problem.

I would like to quickly add that this is also mentioned in our documentation regarding [how to build SDL Hyperion](https://sdl-hercules-390.github.io/html/hercinst.html#install), specifically step 5:

* **Download and build all External Packages if needed**

(which for MacOS is pretty much a hard requirement.)

I am going to close this issue as Invalid, Won't Fix.
