### ISSUE TITLE
Start hercifc during early stages of IMPL (to prevent Out Of Memory symptoms)

### ISSUE THREAD

**Issue by ivan-w** [SDL-Hercules-390/hyperion#297]
Under *nix systems, `hercifc` is used to pass privileged network interface control instructions when using Layer 3 networking interfaces. The `hercifc` utility is currently instantiated on demand whenever a Layer 3 (L3) network interface is activated.

The problem it generates is that since it is separate process (required because it has separate POSIX rights) it also inherits the entire resources of the parent process (including memory allocation), and the host system may deem there is not enough memory to host both processes causing the process for hercifc to not spawn.

My suggestion is that `hercifc` should be spawned early during initialization, before any amount of substantial memory is allocated, well before it is determined to actually be needed. Whether `hercifc` will actually be needed or not isn't really relevant (it's a very lightweight process), but if it is later determined that some L3 Network interface does need it, it will then already be available.

**Comment by Fish-Git** [comment]
Ivan: (@ivan-w)

Any progress? (Just asking!)

**Comment by Fish-Git** [comment]
Closing due to non-response.
