### ISSUE TITLE
Wish: Change HAO command string w/o knowing the slot number

### ISSUE THREAD

**Issue by pjfarleyiii** [SDL-Hercules-390/hyperion#302]
The context of this request is a chained series of scripts supporting automated MVS shutdown.  The chained scripts may in some cases need to reuse the HAO target string for the same OS message string (where the same message string can be issued multiple times by the OS) but a different command string to advance the shutdown process to the next step.

The chained scripts need a way to change the command string of an existing HAO target set by a prior script by using the same target expression as was used to originally set the target, without knowing the HAO slot number.  Example:

script1:
hao tgt HASP099
hao cmd scripts/script2
* do some MVS shutdown command here and then terminate this script
* where the result of the issued command will again cause HASP099 to be issued by the OS

script2:
hao del HASP099
hao tgt HASP099
hao cmd scripts/script3
* do another MVS shutdown command here and then terminate this script

Or alternatively an HAO "replace" operand that reuses the same HAO slot but can replace the associated command string.

script1:
hao tgt HASP099
hao cmd scripts/script2
* do some MVS shutdown command here and then terminate this script
* where the result of the issued command will again cause HASP099 to be issued by the OS

script2:
hao rpl HASP099
hao cmd scripts/script3
* do another MVS shutdown command here and then terminate this script

Peter

**Comment by Peter-J-Jansen** [comment]
Hello Peter,

I think that one would be able to write a scripts/scriptx in such a way that it would first invoke scripts/script2, and on a later invocation when appropriate invoke scripts/script3. I am not convinced that adding the extra HAO functionality to SDL-Hyperion would be the right way forward, as SDL-Hyperion is already quite large, and this functionality is easy to achieve outside SDL-Hyperion.

Cheers,

Peter

**Comment by Fish-Git** [comment]
I agree with Peter. This can be easily accomplished via creative use of various scripts containing Hercules HAO commands which, upon triggering, invoke yet other Hercules scripts, etc.

I have done this myself on several occasions in the past. It's not hard. It just requires some thought and careful planning. There's no need for any Hercules change.

**Comment by pjfarleyiii** [comment]
<Fish wrote:>

> I agree with Peter. This can be easily accomplished via creative use of various scripts containing Hercules HAO commands which, upon triggering, invoke yet other Hercules scripts, etc.
> 
> I have done this myself on several occasions in the past. It's not hard. It just requires some thought and careful planning. There's no need for any Hercules change.

Just a question: When the next and only target message ID string that will be seen is the same as the one that invoked script2, how does one accomplish that chaining without either deleting or replacing the first target and command?  We are in a series of shutdown scripts here and there isn't a lot left running in the system to generate messages other than JES.

The observed behavior of the current HAO implementation is that ONLY the first target for HASP099 and it's original command string remain active, and HAO goes into an infinite loop: 

1. script 2 is invoked, 
2. HAO to replace the target HASP099 command string fails, 
3. MVS command that causes the same message number to appear next is issued and 
4. causes script2 to be invoked again.

How does one break the infinite loop without another unique message string to set as an HAO target?

I won't argue your decision not to make such an enhancement, but how does one program around this issue?

<Peter Jansen wrote:>

> . . . this functionality is easy to achieve outside SDL-Hyperion.

Would you please expand on that thought?  How does one accomplish these tasks "outside of Hyperion"?

Peter

**Comment by Peter-J-Jansen** [comment]
An example of a script called "scriptx", which invokes "script1" the very first time and from then on "script2" in bash could be something like this : 
```
hercules@pjrpi4z1:~/hao_2_scripts_example$ ls -l
total 12
-rwxrwxr-x 1 hercules hercules  34 May 16 11:35 script1
-rwxrwxr-x 1 hercules hercules  88 May 16 11:36 script2
-rwxrwxr-x 1 hercules hercules 212 May 16 11:19 scriptx
hercules@pjrpi4z1:~/hao_2_scripts_example$ cat scriptx
#!/bin/bash
if [ "$SCRIPT1" == "" ]
then
   echo "About to call script1"
   export SCRIPT1="Has been called; next scriptx call will use script2."
   ./script1
else
   echo "About to call script2"
   ./script2
fi
hercules@pjrpi4z1:~/hao_2_scripts_example$ cat script1
#!/bin/bash
echo "I am script $0"
hercules@pjrpi4z1:~/hao_2_scripts_example$ cat script2
#!/bin/bash
echo "I am script $0 and will from now on be called when scriptx is called"
hercules@pjrpi4z1:~/hao_2_scripts_example$ 

hercules@pjrpi4z1:~/hao_2_scripts_example$ ./scriptx
About to call script1
I am script ./script1
hercules@pjrpi4z1:~/hao_2_scripts_example$ ./scriptx
About to call script1
I am script ./script1
hercules@pjrpi4z1:~/hao_2_scripts_example$ source scriptx
About to call script1
I am script ./script1
hercules@pjrpi4z1:~/hao_2_scripts_example$ source scriptx
About to call script2
I am script ./script2 and will from now on be called when scriptx is called
hercules@pjrpi4z1:~/hao_2_scripts_example$ source scriptx
About to call script2
I am script ./script2 and will from now on be called when scriptx is called
hercules@pjrpi4z1:~/hao_2_scripts_example$ 
```
HAO would only ever trigger "scriptx". No need to modify the HAO setup after "scriptx" gets triggered the first time.

In Windows something similar is possible.

Cheers,

Peter

**Comment by Fish-Git** [comment]
> When the next and only target message ID string that will be seen is the same as the one that invoked script2, how does one accomplish that chaining without either deleting or replacing the first target and command?

By replacing the entire rule with a new rule.

Example for 3-step shutdown, wherein after each shutdown step, the guest issues the same "HASP099" message again, but after each shutdown step, a _different_ command needs to be issued to the guest to trigger the next shutdown step:

script "begshut.txt":

    hao clear
    hao tgt HASP099
    hao cmd scripts/shut2.txt
    .foo    # guest command to acknowledge the end of shutdown step 1
            # and to trigger the start of shutdown step 2


script "shut2.txt":

    hao clear
    hao tgt HASP099
    hao cmd scripts/script3
    .bar    # completely different guest command to acknowledge the end of shutdown step 2
            # and to trigger the start of shutdown step 3

script "shut3.txt":

    .quiesce    # final guest shutdown command

_**NOTE:** The above was just thrown together off the top of my head and has **not** actually been tested, but does (I hope!) adequately illustrate how it **could** be easily accomplished (and how I myself accomplished something very similarly in the past)._

_**Please also notice** that no special host scripting is needed either! That is to say, you **don't** need to code any type of fancy Windows batch file or Linux bash script either. It is all accomplished via very simple **Hercules** command scripts._

**Comment by pjfarleyiii** [comment]
Thank you both for your replies.  I understand them both and appreciate the logic.

I somehow missed seeing the HAO CLEAR operation, and that makes things very simple for my needs.

Regards,

Peter
