### ISSUE TITLE
Current code does not build under macOS 10.14.6 "Mojave"

### ISSUE THREAD

**Issue by sstillwell** [SDL-Hercules-390/hyperion#306]
Checked out SDL Hyperion code as of today's date with git clone.  Using master branch.

Running Xcode 11.3.1

ran configure with 
`CC="gcc -arch x86_64" ./configure --enable-setuid-hercifc --host=x86_64-apple-darwin18.7.0`

ran make with 
`CC="gcc -arch x86_64" make`

received following errors (log excerpt beginning just above the errors):
```
  CC       logger.lo
  CC       logmsg.lo
  CC       memrchr.lo
  CC       parser.lo
  CC       pttrace.lo
  CC       version.lo
  CC       ltdl.lo
  CCLD     libhercu.la

*** Warning: Linking the shared library libhercu.la against the
*** static library ./crypto/lib/libcrypto64.a is not portable!

*** Warning: Linking the shared library libhercu.la against the
*** static library ./decNumber/lib/libdecNumber64.a is not portable!

*** Warning: Linking the shared library libhercu.la against the
*** static library ./SoftFloat/lib/libSoftFloat64.a is not portable!

*** Warning: Linking the shared library libhercu.la against the
*** static library ./telnet/lib/libtelnet64.a is not portable!
ld: warning: ignoring file ./crypto/lib/libcrypto64.a, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0A 0x2F 0x20 0x20 0x20 0x20 0x20 0x20 0x20 )
ld: warning: ignoring file ./decNumber/lib/libdecNumber64.a, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0A 0x2F 0x20 0x20 0x20 0x20 0x20 0x20 0x20 )
ld: warning: ignoring file ./SoftFloat/lib/libSoftFloat64.a, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0A 0x2F 0x20 0x20 0x20 0x20 0x20 0x20 0x20 )
ld: warning: ignoring file ./telnet/lib/libtelnet64.a, building for macOS-x86_64 but attempting to link with file built for unknown-unsupported file format ( 0x21 0x3C 0x61 0x72 0x63 0x68 0x3E 0x0A 0x2F 0x20 0x20 0x20 0x20 0x20 0x20 0x20 )
Undefined symbols for architecture x86_64:
  "_crypto_version", referenced from:
      _init_sysblk_version_str_arrays in version.o
  "_decnumber_version", referenced from:
      _init_sysblk_version_str_arrays in version.o
  "_softfloat_version", referenced from:
      _init_sysblk_version_str_arrays in version.o
  "_telnet_version", referenced from:
      _init_sysblk_version_str_arrays in version.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libhercu.la] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

running 'make clean' followed by 'make' again does not change the error.

Let me know if you need more info.

**Comment by Fish-Git** [comment]
You need to build the External Packages first, and then specify that directory as the `--enable-extpkgs=<dir>` option on your `./configure` command, as explained in the "**Building from source - Linux and Mac OS X**" section of our official "**[Installation and Operation](https://sdl-hercules-390.github.io/html/hercinst.html#instsource)**" web page:

1. Download the `extpkgs.sh` and `extpkgs.sh.ini` files from [**"gists" repository**](https://github.com/SDL-Hercules-390/gists).

2. `extpkgs.sh clone c d s t`

3. `./configure ... --enable-extpkgs=<dir> ...`

4. `make ...`

Refer to the following web pages for more information:

* https://sdl-hercules-390.github.io/html/hercinst.html#instsource
* https://github.com/sdl-hercules-390/hyperion/blob/master/readme/README.EXTPKG.md
* https://github.com/SDL-Hercules-390/gists

Closing as "Invalid (User Error)".

**Comment by sstillwell** [comment]
User error indeed.  It built fine this time.  I read BUILDING and didn't dig further.
