### ISSUE TITLE
IPL of z/OS causes WS 07b-20 missing function in the STFLE instruction 

### ISSUE THREAD

**Issue by colinpaicemq** [SDL-Hercules-390/hyperion#307]
z/OS ipl gets  WS 07b-20
WS 7b code 20 
One or more of the following required functions  required by z/OS V2R3, or later,  are not available:

    Decimal-floating-point zone-conversion facility
    Miscellaneous-instruction-extension facility
    Interlocked-access facility 2
    Floating point extension facility
    Distinct operands facility

if I use
archlvl enable bit37
archlvl enable bit48
archlvl enable bit45
it works.

The code is installed, but facility table is missing some stuff. I made some changes and it now works

diff --git a/archlvl.c b/archlvl.c
index 09d8baf0..947b8ce3 100644
--- a/archlvl.c
+++ b/archlvl.c
@@ -263,7 +263,12 @@ FACILITY(EXECUTE_EXTN,     Z390,         NONE,      Z390,          ALS2|ALS3)
 #if defined(_FEATURE_ENHANCED_MONITOR_FACILITY)
 FACILITY(ENH_MONITOR,      Z390,         NONE,      Z390,          ALS3)
 #endif
-//FACILITY(FP_EXTENSION,     ZARCH,        NONE,      ZARCH,         ALS3)
+#if defined(FEATURE_BASIC_FP_EXTENSIONS)
+FACILITY(FP_EXTENSION,     ZARCH,        NONE,      ZARCH,         ALS3)
+#endif
+
+
 #if defined(_FEATURE_LOAD_PROGRAM_PARAMETER_FACILITY)
 FACILITY(LOAD_PROG_PARAM,  Z390,         NONE,      Z390,          ALS3)
 #endif
@@ -277,6 +282,12 @@ FACILITY(DFP_HPERF,        Z390,         NONE,      Z390,          ALS2|ALS3)
 #if defined(_FEATURE_PFPO)
 FACILITY(PFPO,             Z390,         NONE,      Z390,          ALS2|ALS3)
 #endif
+
+#if defined(FEATURE_DFP_ZONED_CONVERSION_FACILITY)
+FACILITY(DFP_ZONED_CONVERSION, Z390,     NONE,      Z390,          ALS3) //912
+#endif
+
+
 #if defined(_FEATURE_FAST_BCR_SERIALIZATION_FACILITY)
 FACILITY(FAST_BCR_SERIAL,  Z390,         NONE,      Z390,          ALS3)
 #endif
_________________________________________________________________
diff --git a/esa390.h b/esa390.h
index 7f75f43a..7dca6b76 100644
--- a/esa390.h
+++ b/esa390.h
@@ -1423,6 +1423,8 @@ typedef struct _MBK {
 #define STFL_RESERVED_46          46    /* Reserved */
 #define STFL_CMPSC_ENH            47    /* CMPSC-enhancement        810
                                            Facility installed     810*/
+#define STFL_DFP_ZONED_CONVERSION 48    /* decimal-floating-point 
+                                           zoned-conversion facility 912 */ 
 #define STFL_MISC_INST_EXTN_1     49    /* Misc Instr Extension 
                                            Facility 1 installed   912
                                            Plus Load And Trap and
__________________________________________________

I found it very useful to extend the archlvl command to display the bit number for the STFLE instruction for example 

HHC00890I Facility( ENH_MONITOR          ) Enabled (bit 36)                                                                                                             
HHC00890I Facility( FP_EXTENSION         ) Enabled (bit 37)                                                                                                             
HHC00890I Facility( LOAD_PROG_PARAM      ) Enabled (bit 40)                                                                                                             
HHC00890I Facility( FPS_ENHANCEMENT      ) Enabled (bit 41)                                                                                                             
HHC00890I Facility( DECIMAL_FLOAT        ) Enabled (bit 42) 

I did this by using 

diff --git a/msgenu.h b/msgenu.h
index 5d955afa..ff0e4b45 100644
--- a/msgenu.h
+++ b/msgenu.h
@@ -644,7 +644,7 @@ Examples:
 #define HHC00885 "Channel Report queue:"
 #define HHC00886 "CRW 0x%8.8X: %s"
 
-#define HHC00890 "Facility( %-20s ) %sabled"
+#define HHC00890 "Facility( %-20s ) %sabled (bit %d)"
 #define HHC00891 "Facility name not found"
 #define HHC00892 "Facility name not specified"
 #define HHC00893 "Facility(%s) does not exist"

and archlvl.c

@@ -751,9 +762,9 @@ int archlvl_cmd(int argc, char *argv[], char *cmdline)
             if( argc < 3 || CMD(argv[2],all,3) || !strcasecmp( argv[2], tb->name ) )
             {
                 fcnt++;
-                WRMSG( HHC00890, "I", tb->name,
+                WRMSG( HHC00890 , "I", tb->name,
                        sysblk.facility_list[sysblk.arch_mode][fbyte] & fbit
-                        ? "En" : "Dis" );
+                        ? "En" : "Dis", tb->bitno );
             }
         }
 
@@ -773,7 +784,7 @@ int archlvl_cmd(int argc, char *argv[], char *cmdline)
                 fbit = 0x80 >> (bitno % 8);
                 WRMSG( HHC00890, "I", get_facname(bitno),
                        sysblk.facility_list[sysblk.arch_mode][fbyte] & fbit
-                        ? "En" : "Dis" );
+                        ? "En" : "Dis", tb->bitno  );
             }
             else
             {

**Comment by colinpaicemq** [comment]
I also noticed that some of the faciliy statements are out of order.  With my display it shows

HHC00890I Facility( MSA_EXTENSION_3      ) Enabled (bit 76)                                                                                                             
HHC00890I Facility( MSA_EXTENSION_4      ) Enabled (bit 77)                                                                                                             
                                                                                                            
HHC00890I Facility( MOVE_INVERSE         ) Enabled (bit 128)                                                                                                            
HHC00890I Facility( MSA_EXTENSION_1      ) Enabled (bit 129)   

so HHC00890I Facility( INTERLOCKED_ACCESS_2 ) Enabled (bit 52)                                                                                                             
HHC00890I Facility( MISC_INST_EXTN_1     ) Enabled (bit 49)
are out of order ... 

Not a problem, it just makes it a little harder when trying to determine what is enabled

**Comment by colinpaicemq** [comment]
sorry..closed by accident

**Comment by Fish-Git** [comment]
You are using the wrong Hercules.

Please try again using SDL Hyperion, no regular Hyperion. They're _NOT_ the same.

Regular Hyperion 4.0 is dead. No one is working on it.

The only actively maintained Hercules is SDL Hercules 4.x Hyperion:

* https://sdl-hercules-390.github.io/html/

Closing as "Invalid (user error)".
