### ISSUE TITLE
Ubuntu 20.04 LTS  s390x fails to boot.

### ISSUE THREAD

**Issue by spamsool** [SDL-Hercules-390/hyperion#308]
I cannot boot and run installer on ubuntu s390x 20.04 running under Hercules. 
Ubuntu 18.04 boots and install just fine, however 20.04 does not.  Could you please have a look on the issue?

**Comment by mcisho** [comment]
Speaking personally, no. You haven't provided even the most trivial information, such as host system, Hercules version, what makes you think you can't boot or run, anything.

**Comment by wrljet** [comment]
I just tried it myself and ran into trouble also. This was over top of a previously working Ubuntu 18.04.  SDL Hercules, locally built, on Debian 10.

The first thing I wasn't expecting:

`10:43:11 HHC00801I Processor CP00: Specification exception code 0006  ilc 4
10:43:11 HHC02324I CP00: PSW=0000000180000000 0000000000012A4C INST=83020308     DIAG  0,2,776(0)             diagnose
10:43:11 HHC02326I CP00: R:0000000000000308:K:06=7FFFFFFF FFFFFFFF D81087F3 9B6870DD`  

`10:43:17 HHC00653E Hardware loader file type 3 not not supported
10:43:17 HHC00007I Previous message from function 'z900_hwl_thread' at scescsi.c(330)`

I've attached the full log and Hercules config.

[s390x-ubuntu-20.04-err.zip](https://github.com/SDL-Hercules-390/hyperion/files/4774820/s390x-ubuntu-20.04-err.zip)

BIll

**Comment by mcisho** [comment]
The first thing you weren't expecting is to do with Linux running under z/VM. Search the Linux source for ```diag308```, to see its use. Presumably you were running Ubuntu natively under Hercules?

The second thing you weren't expecting has been appearing with Linux guests for a while now. I had started to investigate what it meant but got side-tracked. It appears to have no effect, good, bad or indifferent.

The several ```Operation exception INST=E70030000802``` are something in Ubuntu attempting to use the ```Vector Load Element (VLEG)``` instruction provided by the ```Vector Facility for z/Architecture```, a feature that has not been implemented in Hercules.

**Comment by mcisho** [comment]
Facilities that appeared with the z13 were:

```Decimal-floating-point packed-conversion facility
FCX-bidirectional-data-transfer facility
Load-and-zero-rightmost-byte facility
Load/store-on-condition facility 2
Message-security-assist extension 5
Multithreading facility
Vector facility for z/Architecture```

http://ubuntu-on-big-iron.blogspot.com/ says:

```Starting with Ubuntu Server 20.04 the architectural level set was changed to z13 (1836907). This has a significant impact: Ubuntu Server for s390x now benefits from improved and more instructions that got introduced with z13 hardware; at the same time support for zEC12/zBC12 got dropped and the minimum supported hardware is now IBM z13 and LinuxONE Rockhopper (I) and LinuxONE Emperor (I).```

**Comment by spamsool** [comment]
Thank you very much for your time and commitment. So basically we are out of luck now with running Ubuntu 20.04 on current version of Hercules.

**Comment by Fish-Git** [comment]
> So basically we are out of luck now with running Ubuntu 20.04 on current version of Hercules.

Unfortunately it would appear that is correct. IBM is able to make changes to their hardware and software faster than Hercules is able to keep up! &nbsp; `:(`

Am closing this issue as "Missing", "Won't Fix". &nbsp; **`(*)`**
___
**`(*)`** _PLEASE NOTE! "Won't Fix" does not mean we won't ever fix it! It just means it is unlikely to be fixed any time soon given the scope involved, i.e. the large amount of effort involved over a protracted period of time. We might be able to implement some of the required new facilities at some point in the future, but it is unlikely that we will ever be able to implement all of them. Sorry!_ &nbsp; `:(`
