### ISSUE TITLE
ABEND S0E0 RSN 018 related to TXF when running z/OS 2.4 second level under z/VM

### ISSUE THREAD

**Issue by Peter-J-Jansen** [SDL-Hercules-390/hyperion#309]
System ABENDs occur frequently when running z/OS 2.4 second level under z/VM 6.4. Example : 
```
ATR218I TAKEOVER PROCESS HAS FAILED DUE TO 868                   
INACCESSIBLE LOG DATA IN LOGSTREAM ATR.S0W1.DELAYED.UR.          
IXG063I LOGGER ABENDED AND REQUESTED AN SVC DUMP WHILE PROCESSING
LOGSTREAM: **UNKNOWN**                                           
STRUCTURE: **UNKNOWN**                                           
GROUP: **UNKNOWN**                                               
MODULE=IXGL2RTE,ABEND=S00E0,REASON=00000018                      
```
The System Codes manual for `S0E0 RSN 18` shows : 
```
0E0
Explanation: A program check occurred. The hexadecimal interruption code is as follows:
Code   Explanation
18     A transaction constraint exception occurred.
```
So far none of these has been encountered when running 1st level.

This occurs under the current SDL-Hyperion (under Ubuntu 18.04 but probably under any guest OS).

Cheers,

Peter

**Comment by ivan-w** [comment]
Odd.. It should be 218... And I thought that'd been fixed quit soe tie ago

**Comment by Fish-Git** [comment]
More than likely a TXF bug somewhere.

We _really_ need to start working on developing a comprehensive suite of tests for TXF.

**Comment by Fish-Git** [comment]
FYI: I have some info (courtesy of a former IBM employee) regarding TXF under SIE which I shall post to issue #263 as soon as I get a chance.

**Comment by Fish-Git** [comment]
I hope you don't mind, Peter, but I am going to close this issue and label it as "MOVED" because I believe it is actually related to our incomplete TXF implementation (issue #263), and I would rather have _ALL_ TXF related issues all reported in the same place (in the same GitHub Issue) rather than to have to deal with multiple GitHub Issues that more than likely are all being caused by the same thing.

**Comment by Fish-Git** [comment]
> Odd.. It should be 218... And I thought that'd been fixed quite some time ago.

It was, and no it is not odd at all. Since this is a z/OS error message I personally don't find it odd at all that it chooses to report the problem as 18 instead of 218. Program Interrupt code 18 is after all a Transaction Constraint Exception, and z/OS is free to format its error messages however it wants.

If _Hercules_ reports it as 18 instead of 218, then _that_ would be a problem!

**Comment by Fish-Git** [comment]
I have changed my mind!

In order to better track problems likely being caused by our current incomplete/buggy Transactional-Execution Facility implementation, I have decided to create a new GitHub Issue Label called "TXF" that should be assigned to issues such as this one where we believe the reported problem is likely being caused by our current incomplete (and still buggy) TXF implementation.

While we continue to work on addressing (fixing) various TXF related bugs, problems such as the one this one describes, are likely to occur more and more, and in order to better manage resolving such problems, it is probably better to report such problems individually rather than in our existing Issue #263 thread (which is already very, very long!).

I have therefore re-opened this issue and have assigned it the new "TXF" Label so that we can better track our progress trying to resolve each TXF issue.

My apologies to Peter for originally closing it!

**Comment by Peter-J-Jansen** [comment]
I have observed that every time this ABEND occurs, the Hercules log shows the following error : 
```
18:37:00 HHC01413I Hercules version 4.3.9999.0-SDL-gbca5d05c-modified (4.3.9999.0)
[...]
18:43:35 HHC97703D TXF: CP02: SIE: Failed Outermost Cons Transaction for TND 1 txfs=2 retry=1: TAC_INSTR (Restricted instruction), why = TXF_WHY_CONTRAN_INSTR
```
The HHC97703 message is my enhanced version of HHC07703 as described in Isuue #315. In the past, TBEGINC constrained instructions being aborted because of `Restricted instruction` were appearing in abundance. This is now no longer the case, so perhaps we have a genuine Hercules bug in that it has marked an instruction as such in error. I'll be trying to hunt down what that instruction is.

Cheers,

Peter

**Comment by Fish-Git** [comment]
> This is now no longer the case, so perhaps we have a genuine Hercules bug in that it has marked an instruction as such in error.

Sounds like it, doesn't it?

> I'll be trying to hunt down what that instruction is.

I have some upcoming TXF changes related to the `'txf'` tracing command that I haven't committed yet that, when the TDB option is specified (e.g. `txf c bad tdb`), will, if the verbose message option is enabled (`msglvl +verbose`), produce a formatted display of all TDB fields (rather than just a storage dump like it does today), including displaying the actual instruction that caused the transaction to fail (i..e a display of the instruction at the TDB `ATIA` (Aborted Transaction Instruction Address). This _should_ tell us exactly what instruction it was that program checked thereby causing the transaction to be aborted.

I'm still testing but hope to be done sometime today if things go well.

**Comment by Peter-J-Jansen** [comment]
That will be useful Fish.

The `txf ... bad ...` command is useful, but it also issues loggings for TXF aborts that are perfectly normal, i.e. in the case of fetch or store conflicts, or CSP(G) instructions, or even SIE intercepts, during unconstrained transactions, or even during the 1st retry of an unconstrained transaction. Hence that that thought of a `focussed` TXF abort logging as explained in Issue #315 which are really cases of TXF aborts not following the POP. I just hardcoded that.

Cheers,

Peter

**Comment by Peter-J-Jansen** [comment]
The constrained transaction restricted instruction causing this problem is an unconditional BC : 
```
14:58:48 HHC02324I SIE: CP02: PSW=0404000080000000 000000000136543E INST=47FA9000     BC    15,0(10,9)             branch_on_condition
14:58:48 HHC02326I SIE: CP02: V:0000000001365444:A:000000007F743444:K:06=A7F40022 A7F40638 A7F40E82 A7F40634  x4..x4..x4.bx4..
14:58:48 HHC02269I CP02: R0=000000001FFD5028 R1=000000001FFD5028
14:58:48 HHC02269I CP02: R2=000000001FFD502E R3=0000000000000200
14:58:48 HHC02269I CP02: R4=0000000001D91318 R5=000000001F9C1B58
14:58:48 HHC02269I CP02: R6=0000000000FD45B8 R7=00000000032A8100
14:58:48 HHC02269I CP02: R8=00000000032F9000 R9=0000000001365444
14:58:48 HHC02269I CP02: RA=0000000000000000 RB=00000000057A14C7
14:58:48 HHC02269I CP02: RC=00000000057A04C8 RD=000000001FFD5128
14:58:48 HHC02269I CP02: RE=00000000857A09C8 RF=1F9DB0001F9DB200
14:58:48 HHC02271I CP02: C0=00800002DF98EE20 C1=0000000111204007
14:58:48 HHC02271I CP02: C2=000000007CC21CC0 C3=0000000180400032
14:58:48 HHC02271I CP02: C4=0000000100010015 C5=000000007EEFC540
14:58:48 HHC02271I CP02: C6=00000000FE000000 C7=000000021BA10007
14:58:48 HHC02271I CP02: C8=0000000000000000 C9=0000000000000000
14:58:48 HHC02271I CP02: CA=0000000000000000 CB=0000000000000000
14:58:48 HHC02271I CP02: CC=00000000FA9CE413 CD=000000021BA10007
14:58:48 HHC02271I CP02: CE=00000000DF8FEEFB CF=000000007F0B85D8
14:58:48 HHC97703D TXF: CP02: SIE: Failed Outermost Cons Transaction for TND 1 txfs=1 retry=1: TAC_INSTR (Restricted instruction), why = TXF_WHY_CONTRAN_INSTR
```
This above was produced making this additional code addition : 
```diff
hercules@pjjs12:~/SDL-hyperion$ diff -u --color ~/Qsync/Source/Originals/SDL-hyperion/opcode.h   ~/SDL-hyperion/opcode.h 
--- /home/hercules/Qsync/Source/Originals/SDL-hyperion/opcode.h	2020-07-24 16:49:02.000000000 +0200
+++ /home/hercules/SDL-hyperion/opcode.h	2020-07-31 11:17:41.000000000 +0200
@@ -1370,6 +1370,7 @@
       if ((_regs)->txf_contran)                                                         \
       {                                                                                 \
         (_regs)->txf_why |= TXF_WHY_CONTRAN_INSTR;                                      \
+        ARCH_DEP( display_inst )( (_regs), inst);                         /* @PJJ */    \
         ARCH_DEP( abort_transaction )( (_regs), ABORT_RETRY_PGMCHK, TAC_INSTR );        \
       }                                                                                 \
     } while (0)
hercules@pjjs12:~/SDL-hyperion$ 

```
plus passing the `inst` variable as required.

According to the POP however this BC instruction _is_ indeed a restricted instruction. The `BC 15,0(10,9)` would effectively branch to `'1365444'X`, so just skipping the next instruction or so. The POP on pg 5-108 explains that _relative_ forward branches with nonzero branch masks are _not_ restricted. Is perhaps the POP out of touch with reality and does this also apply to _non-relative_ branches ? I think I'm going to try it out, although this appears very unlikely to be the reason we're having this problem.   

Cheers,

Peter

**Comment by Peter-J-Jansen** [comment]
The instruction environment where the problem occurs, around instruction address `7F74343E` is like this : 
```
16:24:29 HHC01603I u r7f743418
16:24:29 HHC02289I R:000000007F743418  AF070461     MC    1121(0),7              monitor_call
16:24:29 HHC02289I R:000000007F74341C  907A0950     STM   7,10,2384(0)           store_multiple
16:24:29 HHC02289I R:000000007F743420  58800210     L     8,528(0,0)             load
16:24:29 HHC02289I R:000000007F743424  587005B0     L     7,1456(0,0)            load
16:24:29 HHC02289I R:000000007F743428  91200228     TM    552(0),32              test_under_mask
16:24:29 HHC02289I R:000000007F74342C  A714114F     BRC   1,*+8862               branch_relative_on_condition
16:24:29 HHC02289I R:000000007F743430  94DF821F     NI    543(8),223             and_immediate
16:24:29 HHC02289I R:000000007F743434  C09000000008 LARL  9,*+16                 load_address_relative_long
16:24:29 HHC02289I R:000000007F74343A  48A0049E     LH    10,1182(0,0)           load_halfword
16:24:29 HHC02289I R:000000007F74343E  47FA9000     BC    15,0(10,9)             branch_on_condition
16:24:29 HHC02289I R:000000007F743442  0000         ????? ,                      ?
16:24:29 HHC02289I R:000000007F743444  A7F40022     BRC   15,*+68                branch_relative_on_condition
16:24:29 HHC02289I R:000000007F743448  A7F40638     BRC   15,*+3184              branch_relative_on_condition
16:24:29 HHC02289I R:000000007F74344C  A7F40E82     BRC   15,*+7428              branch_relative_on_condition
16:24:29 HHC02289I R:000000007F743450  A7F40634     BRC   15,*+3176              branch_relative_on_condition
16:24:29 HHC02289I R:000000007F743454  A7F41092     BRC   15,*+8484              branch_relative_on_condition
```
I doubt it very much that this would be within a constrained transaction, so I think we have an SIE -related TXF bug.

Cheers,

Peter

**Comment by Fish-Git** [comment]
> The `txf ... bad ...` command is useful, but it also issues loggings for TXF aborts that are perfectly normal, i.e. in the case of fetch or store conflicts, or CSP(G) instructions, or even SIE intercepts, during unconstrained transactions, or even during the 1st retry of an unconstrained transaction. Hence that that thought of a `focussed` TXF abort logging as explained in Issue #315 which are really cases of TXF aborts not following the POP.

Hmmm... Maybe I can add some additional finer grained options to the TXF tracing command, such as being able to specify only specific abort code(s) (or perhaps being able to specify abort codes that you are _not_ interested in seeing) and/or the ability to trace transactions only for a specific CPU?

I happened to notice that, at least for me, when z/OSMF is initializing (i.e. after starting `izusvr1`), most of the processing (CPU activity) seemed to be taking place on the zIIP processor, running for the most part at 100% (whereas the activity on the other CPUs, all being general purpose Central Processors, only bounced around 10-30% or so).

Maybe an ability to specify a retry count as well might be useful? I.e. only trace transactions that have failed more than 'n' times in a row?

I'll have to play around with that. Maybe I can come up with something a little bit more useful than what we currently have.

**Comment by Fish-Git** [comment]
> The POP on pg 5-108 explains that _relative_ forward branches with nonzero branch masks are _not_ restricted. Is perhaps the POP out of touch with reality and does this also apply to _non-relative_ branches?

I suppose it's certainly possible. To be honest I never did understand why non-relative branches should be restricted. As long as they were forward branches only whose target remained with the 256 byte limit, I don't see why they shouldn't be allowed. But hey, no matter how much we may personally dislike it, we _must_ remain true to the published architecture, and unless I'm misreading (misunderstanding) page 5-108, branches _other than_ forward branching relative branches (meaning all BC and similar type instructions) are indeed restricted (which is exactly how we currently have things coded).

**Comment by Fish-Git** [comment]
> The instruction environment where the problem occurs, around instruction address `7F74343E` is like this:
> _(snipped)_
> I doubt it very much that this would be within a constrained transaction, ...

Agreed!

> ... so I think we have an SIE-related TXF bug.

Looks that way. &nbsp; `:(`

What bothers me however is, I can't for the life of me see what the heck SIE has to do with it?! The only thing SIE (z/VM) cares about is: 1) intercepting the TXF instructions themselves (if the `SIE_ECTX` bit is on in the SIEBK), and 2) the filling in of the Interception TDB for program interrupt related transaction aborts (i.e. interception code 8 = `SIE_C_PGMINT`) at `sie_exit`.

But how and the heck can doing that confuse poor z/OS so much that it would try executing an obviously non-transactional instruction sequence as a constrained transaction?! It doesn't make any sense to me! How did z/OS get so incredibly confused?! &nbsp; `:(`

**Comment by Peter-J-Jansen** [comment]
Using the same HAO-triggered PTT debugging technique I used in Issue #315 on this problem, the result is this : 
```
14:13:05 HHC90021I 14:13:05.783362 00007fe6fbefe700 Processor CP02  sie.c:1180         run_sie !run      ffffffffffffffff 0000000000000000 0000000000000000
14:13:05 HHC90021I 14:13:05.783362 00007fe6fbefe700 Processor CP02  sie.c:1195         run_sie !run      ffffffffffffffff 0000000000000000 0000000000000000
14:13:05 HHC90021I 14:13:05.783362 00007fe6fbefe700 Processor CP02  sie.c:919          run_sie setjmp    0000000000000000 0000000000000000 0000000000000000
14:13:05 HHC90021I 14:13:05.783363 00007fe6fbefe700 Processor CP02  sie.c:923          run_sie run...    0000000000000000 0000000000000000 0000000000000000
14:13:05 HHC90021I 14:13:05.783371 00007fe6fbefe700 Processor CP02  sie.c:1180         run_sie !run      ffffffffffffffff 0000000000000000 0000000000000000
14:13:05 HHC90021I 14:13:05.783371 00007fe6fbefe700 Processor CP02  sie.c:1195         run_sie !run      ffffffffffffffff 0000000000000000 0000000000000000
14:13:05 HHC90021I 14:13:05.783371 00007fe6fbefe700 Processor CP02  sie.c:919          run_sie setjmp    0000000000000000 0000000000000000 0000000000000000
14:13:05 HHC90021I 14:13:05.783372 00007fe6fbefe700 Processor CP02  sie.c:923          run_sie run...    0000000000000000 0000000000000000 0000000000000000
14:13:05 HHC90021I 14:13:05.783375 00007fe6fbefe700 Processor CP02  sie.c:1180         run_sie !run      ffffffffffffffff 0000000000000000 0000000000000000
14:13:05 HHC90021I 14:13:05.783375 00007fe6fbefe700 Processor CP02  sie.c:1195         run_sie !run      ffffffffffffffff 0000000000000000 0000000000000000
14:13:05 HHC90021I 14:13:05.783376 00007fe6fbefe700 Processor CP02  sie.c:919          run_sie setjmp    0000000000000000 0000000000000000 0000000000000000
14:13:05 HHC90021I 14:13:05.783377 00007fe6fbefe700 Processor CP02  sie.c:923          run_sie run...    0000000000000000 0000000000000000 0000000000000000
14:13:05 HHC90021I 14:13:05.783526 00007fe6fbefe700 Processor CP02  transact.c:650     TXF_TBEGINC       0000000000000002 0000000000000000 0000000000000000
14:13:05 HHC90021I 14:13:05.783540 00007fe6fbefe700 Processor CP02  transact.c:679     TXF TBEGINC       0000000000000000 0000000000000000 0000000000000000
14:13:05 HHC90021I 14:13:05.783609 00007fe6fbefe700 Processor CP02  transact.c:2281    TXF maddr_l:      00007fe5d663b000 00007fe6e011f000 0000000000000001
14:13:05 HHC90021I 14:13:05.783610 00007fe6fbefe700 Processor CP02  transact.c:2337    TXF maddr_l       00007fe6e011f800 0000000000000001 0000000000000001
14:13:05 HHC90021I 14:13:05.783611 00007fe6fbefe700 Processor CP02  transact.c:920     TXF beg           0000000000000000 0000000000000001 0000000000000001
14:13:05 HHC90021I 14:13:05.783613 00007fe6fbefe700 Processor CP02  sie.c:1180         run_sie !run      0000000000000000 0000000000000000 0000000000000000
14:13:05 HHC90021I 14:13:05.783614 00007fe6fbefe700 Processor CP02  sie.c:1195         run_sie !run      0000000000000000 0000000000000000 0000000000000000
14:13:05 HHC90021I 14:13:05.783614 00007fe6fbefe700 Processor CP02  sie.c:919          run_sie setjmp    0000000000000000 0000000000000000 0000000000000000
14:13:05 HHC90021I 14:13:05.783614 00007fe6fbefe700 Processor CP02  sie.c:923          run_sie run...    0000000000000000 0000000000000000 0000000000000000
14:13:05 HHC90021I 14:13:05.783618 00007fe6fbefe700 Processor CP02  sie.c:1180         run_sie !run      ffffffffffffffff 0000000000000000 0000000000000000
14:13:05 HHC90021I 14:13:05.783618 00007fe6fbefe700 Processor CP02  sie.c:1195         run_sie !run      ffffffffffffffff 0000000000000000 0000000000000000
14:13:05 HHC90021I 14:13:05.783619 00007fe6fbefe700 Processor CP02  sie.c:919          run_sie setjmp    0000000000000000 0000000000000000 0000000000000000
14:13:05 HHC90021I 14:13:05.783619 00007fe6fbefe700 Processor CP02  sie.c:923          run_sie run...    0000000000000000 0000000000000000 0000000000000000
14:13:05 HHC90021I 14:13:05.783620 00007fe6fbefe700 Processor CP02  transact.c:1040    TXF abort         0000000000000000 0000000000000001 0000000000000001
14:13:05 HHC90021I 14:13:05.783655 00007fe6fbefe700 Processor CP02  transact.c:1436    *TXF abrtpgm      0000000000000000 0000000000000001 0000000000000001
14:13:05 HHC90021I 14:13:05.783656 00007fe6fbefe700 Processor CP02  cpu.c:493          *TXF 218!         0000000000000218 0000000000000000 0000000000000000
14:13:05 HHC90021I 14:13:05.783657 00007fe6fbefe700 Processor CP02  sie.c:1180         run_sie !run      ffffffffffffffff 0000000000000000 0000000000000000
14:13:05 HHC90021I 14:13:05.783657 00007fe6fbefe700 Processor CP02  sie.c:1195         run_sie !run      ffffffffffffffff 0000000000000000 0000000000000000
14:13:05 HHC90021I 14:13:05.783657 00007fe6fbefe700 Processor CP02  sie.c:919          run_sie setjmp    0000000000000000 0000000000000000 0000000000000000
14:13:05 HHC90021I 14:13:05.783658 00007fe6fbefe700 Processor CP02  sie.c:923          run_sie run...    0000000000000000 0000000000000000 0000000000000000
14:13:05 HHC90021I 14:13:05.783664 00007fe6fbefe700 Processor CP02  sie.c:1180         run_sie !run      ffffffffffffffff 0000000000000000 0000000000000000
14:13:05 HHC90021I 14:13:05.783664 00007fe6fbefe700 Processor CP02  sie.c:1195         run_sie !run      ffffffffffffffff 0000000000000000 0000000000000000
14:13:05 HHC90021I 14:13:05.783664 00007fe6fbefe700 Processor CP02  sie.c:919          run_sie setjmp    0000000000000000 0000000000000000 000000000000000
```
The mystery here is even bigger, as I cannot explain why there are PTT loggings from `sie.c` in between the `transact.c` loggings for the aborted transaction. Can anyone help me here please ?

By the way, the initial TBEGINC logging `TXF_TBEGINC       0000000000000002` is just from an extra PTT call I inserted to know for sure whether this was intercepted or not: the `0000000000000002` shows it wasn't. The same is true in my latest entry against Issue #315 

Cheers,

Peter

**Comment by Fish-Git** [comment]
> The mystery here is even bigger, as I cannot explain why there are PTT loggings from `sie.c` in between the `transact.c` loggings for the aborted transaction. Can anyone help me here please?

Because you're running as a z/VM guest. Duh.

Unless I'm missing something (which wouldn't be the first time) I'm surprised that you're so surprised.

> By the way, the initial TBEGINC logging `TXF_TBEGINC 0000000000000002` is just from an extra PTT call I inserted to know for sure whether this was intercepted or not: the `0000000000000002` shows it wasn't.

I've noticed that z/VM seems to only set that flag when a transaction _isn't_ currently active (so that the instruction gets intercepted so it can then know that you are about to start a transaction), but from then on, while the transaction is active, it seems to dispatch you _without_ that flag. _(Or maybe vice-versa? I forget!)_

Once it starts dispatching you without that flag however, how the heck it can then learn (discover) that you've reached the _end_ of your transaction (`TEND`) I don't know. It's weird. Both z/VM and Hercules SIE is still somewhat of a mystery to me.

**Comment by Peter-J-Jansen** [comment]
>  I'm surprised that you're so surprised.

My surprise was triggered by observing successful TBEGINC transactions not exhibiting such `sie.c` PTT loggings in between the `transact.c` PTT loggings. Such successful transactions complete without leaving the `do {...} while` loop around the `txf_slower_loop:`. I now understand that this failing transaction left that  `do {...} while` loop twice before the `transact.c:1040 TXF abort` took place. Dumb question, sorry.

> [...] Hercules SIE is still somewhat of a mystery to me.

From the frequency (once for each CPU) and timing (very early after the guest IPL) of intercepted TXF instructions, could it possibly be that VM just wants to know that the guest is using the TXF feature ? Honestly though, the SIE mysteries for me are probably even bigger.

Cheers,

Peter

**Comment by Fish-Git** [comment]
> From the frequency (once for each CPU) and timing (very early after the guest IPL) of intercepted TXF instructions, could it possibly be that VM just wants to know that the guest is using the TXF feature?

I don't know! &nbsp;But I suppose so, yeah. &nbsp;_&lt;shrug&gt;_

**Comment by Fish-Git** [comment]
> > From the frequency (once for each CPU) and timing (very early after the guest IPL) of intercepted TXF instructions, could it possibly be that VM just wants to know that the guest is using the TXF feature?

One thing that I seem to recall was that whenever a TBEGIN or TBEGINC instruction was intercepted, z/VM was careful to always dispatch that guest's "workload" on the same CPU until the end of the transaction was reached (at which point it was then free to dispatch is on another CPU should it choose to do so). That was one of the things that was killing us before I committed the SIE TXF interception logic: transactions were getting dispatched on a completely different CPU (i.e. were switching CPUs mid-transaction!) which needless to say was causing all kinds of trouble! Once the SIE TXF interception logic was added however, z/VM began dispatching transactions on the same CPU as before until the transaction ended. That one fix alone fixed a lot of problems.

But whether z/VM uses that flag for other purposes besides that, I have no freaking idea.

**Comment by Fish-Git** [comment]
Enhanced (finer grained) TXF tracing committed.

**Comment by Fish-Git** [comment]
This bug _MAY_ be the same one as already reported in #315. Let me try to fix #315 first and see whether it also fixes this one or not.

**Comment by Peter-J-Jansen** [comment]
Similar to my latest comments for Issue #315 , the specifics as detailed in this issue are no longer appropriate as a number of TXF corrections have been committed since the original opening of this issue. But I suspect TXF issue(s) still remain.

Cheers,

Peter

**Comment by Fish-Git** [comment]
> Similar to my latest comments for Issue #315 , the specifics as detailed in this issue are no longer appropriate as a number of TXF corrections have been committed since the original opening of this issue. But I suspect TXF issue(s) still remain.

Then maybe we should close this issue and open a new issue with a more accurate/appropriate description of the actual perceived problem? Yes? No?

Some of our existing still-open GitHub Issues have been open for quite some time, with things changing significantly since they were first opened, thereby rendering their original problem description as possibly being no longer accurate, so I'm just trying to "clean things up" a little bit so we can ensure that whatever problems actually do remain are accurately described.

That is to say, whenever I review an open issue to see what its current status is (i.e. to see whether there is anything that can be done to resolve it), I simply wish that the problem description to accurately reflect that the actual problem is. I don't wish the original problem description to be misleading. I want it to be, as much as possible, an accurate description of the actual problem without having to wade through comment after comment after comment.

Thus my suggestion in such situations is to consider possibly closing the original issue with an explanation that what was originally reported is no longer accurate, and referring the user to the new replacement issue# that describes the  still-unresolved problem a bit more accurately given the current situation (i.e. given the current state of Hercules).

Does that make sense?

**Comment by Peter-J-Jansen** [comment]
I agree that this does make sense, so lets close both Issues #309 and #315. I will do more testing, especially also since I've seen commit 89ca882. (This commit has also raised other questions in my mind which I need to be able to answer first, but that's another matter.)

Cheers,

Peter
