### ISSUE TITLE
DIAGNOSE instructions should be documented

### ISSUE THREAD

**Issue by Fish-Git** [SDL-Hercules-390/hyperion#31]
Hercules supports many Diagnose instructions (see `ARCH_DEP(diagnose_call)` in source file `diagnose.c`), some of which are Hercules-specific (`FEATURE_HERCULES_DIAGCALLS`).

I personally feel all such diagnose instructions (whether Hercules-specific or not) should be documented somewhere in our documentation.

This is just another possible "TO-DO" item.

**Comment by marXtevens** [comment]
Could you point in a general direction, or its equivalent to give me, or someone else a place to start looking?

**Comment by Fish-Git** [comment]
Hi Mark!

_LOVE_ your handle! "MarXtevens". Heh! Pretty cool.&nbsp;`:)`

If you clone the repository (or just download the .zip) and look in file [`diagnose.c`](https://github.com/Fish-Git/hyperion/blob/master/diagnose.c) you'll see Hercules's code for processing the `DIAG` instruction (which of course, _technically_, doesn't really have a mnemonic).

Starting on line 108, we do a `switch` on the operand-2 value (`effective_addr2`) (I'm presuming you know 'C' code?). It's each one of these diagnose codes that I'd like to see documented.

You might have to chase down the helper sub-function some of the `case:` statements call into to actually process that particular diagnose (e.g. DIAG X'224' for example calls the `ARCH_DEP(diag224_call)` helper function to perform the actual processing for that particular diagnose code), which might get kind of complicated (or might not! I don't know!), so be prepared to possibly dig through a lot of code.

What I'd like to see is something that identifies each of the diagnose codes that Hercules supports, what its name is, what it's overall purpose is (if the purpose can't be determined from the name itself), and what the register requirements are, if any. I'm talking minimal information. You _don't_ have to explain the nitty gritty details of the instruction (unless of course you feel they're important).

Don't bother formatting it fancy or anything. I'll do that myself when I put the information into a web page somewhere. Or you can take a crack at that if you want to. Whatever. I'm easy. I'm just looking to get the overall information right now. Formatting it into a readable format can come later.

Does that help?

Thanks!!

**Comment by marXtevens** [comment]
It's been a while. as recently  I spend most of my time dealing with IT audits. :-(

However, I was an [SA|SysProg|Programmer|...] in a movie once, so I can muddle through Git, C, and anything else I get thrown into. I will start simple and expand as I can manage.

Long ago and far away, as a SysProg, I had trouble getting into various VM Listserv groups. It was shortly after the CHRISTMA EXEC hit a number of VM sites, that some guy (me) was asking for access with a username of XMAS. Using marXtevens has had less repercussions.

**Comment by marXtevens** [comment]
I have created a rough version tonight of the documentation. See if the files I have created iare what you had in mind.
https://github.com/marXtevens/hyperion 
html/hercdiag.html
html/index.html

**Comment by Fish-Git** [comment]
Where are they?!  Your repository does not seem to have a `hercdiag.html` file, and its `index.html` file is identical to the existing one. I'm not seeing what you want me to see!

Did you maybe forget to commit your changes to your repository and/or forget to push your commit to GitHub?

**Comment by Fish-Git** [comment]
p.s. If you want (to make it easier for you), you can simply drag and drop the files into your reply. GitHub will automatically upload it to their server create a link to it.

**Comment by Fish-Git** [comment]
OR... You could create a GitHub "gist" too. Either way. Push your changes. Drag and drop. GitHub gist. I'm cool with all three.

**Comment by marXtevens** [comment]
Sorry for the delay, work and grandchildren visit got in the way. Sneaking time from them (grandkids) to try to get this updated on my repository. I "think" it is uploaded and commited on my respository. This is not RCS ;-)

**Comment by Fish-Git** [comment]
Found them!

But I'm not seeing any real documentation. Just fake "lorem ipsem" junk.

Reminder:
> What I'd like to see is something that identifies each of the diagnose codes that Hercules supports, what its name is, what it's overall purpose is (if the purpose can't be determined from the name itself), and what the register requirements are, if any. I'm talking minimal information.

> I'm just looking to get the overall information right now. **_Formatting it into a readable format can come later._**

**Comment by Fish-Git** [comment]
Oh. Okay. Sorry. That's fine then. Carry on.

**Comment by Fish-Git** [comment]
@marXtevens 

_Ping ..._

_(How's it going, Mark? I hope my previous comments didn't scare you off the project?)_

**Comment by marXtevens** [comment]
_... Ping_

Takes a lot more than that to scare me away ;-) I am done with the skeleton and have started reading the code to create the descriptions. I keep getting interrupted by real work and family events :-D

**Comment by Fish-Git** [comment]
Ah. Okay. We're cool then. I understand about interruptions. Take your time. No rush.&nbsp;`:)`

**Comment by Fish-Git** [comment]
@marXtevens 

_Ping?_

I'm not trying to rush you or anything! I know this is a "As I can find the time to work on it" type of project. I just like to check in on things every once in a while to see how things are going.

**Comment by marXtevens** [comment]
I have not given up. I have been busy with new home projects, and work. The good news, is I was able to understand most of the code for one of the calls, and had started documentation of it, in my "fork." I will make an effort to complete that one this weekend.

**Comment by Fish-Git** [comment]
@marXtevens 

_Ping?_

How's it going?&nbsp;`:)`

_(once again I am not trying to rush you and I don't mean to petster you either, but it's been over 4 months since my last ping so I thought I'd check with you to see how things were going)_

**Comment by Fish-Git** [comment]
Closing due to non-response/inactivity/apparent disinterest.
