### ISSUE TITLE
Build on aarch64 Ubuntu fails

### ISSUE THREAD

**Issue by rvjansen** [SDL-Hercules-390/hyperion#312]
Tried to build current Hyperion-SDL on Ubuntu 19.10 (GNU/Linux 5.3.0-1028-raspi2 aarch64). Verified the requirements. For completeness, whole build output:
```
➜  hyperion git:(master) ✗ make
make  all-recursive
make[1]: Entering directory '/home/rvjansen/apps/hyperion'
Making all in m4
make[2]: Entering directory '/home/rvjansen/apps/hyperion/m4'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/rvjansen/apps/hyperion/m4'
Making all in util
make[2]: Entering directory '/home/rvjansen/apps/hyperion/util'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/rvjansen/apps/hyperion/util'
Making all in html
make[2]: Entering directory '/home/rvjansen/apps/hyperion/html'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/rvjansen/apps/hyperion/html'
Making all in man
make[2]: Entering directory '/home/rvjansen/apps/hyperion/man'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/rvjansen/apps/hyperion/man'
Making all in .
make[2]: Entering directory '/home/rvjansen/apps/hyperion'
  CC       cckdcdsk.o
  CC       hsys.lo
  CCLD     libhercs.la
  CC       codepage.lo
  CC       hdl.lo
  CC       hexdumpe.lo
  CC       hostinfo.lo
In file included from hostinfo.c:21:
/usr/include/aarch64-linux-gnu/sys/sysctl.h:21:2: warning: #warning "The <sys/sysctl.h> header is deprecated and will be removed." [-Wcpp]
   21 | #warning "The <sys/sysctl.h> header is deprecated and will be removed."
      |  ^~~~~~~
  CC       hscutl.lo
hscutl.c: In function 'hgets':
hscutl.c:978:24: warning: comparison is always false due to limited range of data type [-Wtype-limits]
  978 |         if ((int)b[ix] == EOF) /* Corrected.                */
      |                        ^~
  CC       hsocket.lo
  CC       hthreads.lo
  CC       logger.lo
  CC       logmsg.lo
  CC       memrchr.lo
  CC       parser.lo
  CC       pttrace.lo
  CC       version.lo
  CC       ltdl.lo
  CCLD     libhercu.la

*** Warning: Linking the shared library libhercu.la against the
*** static library ./crypto/lib/aarch64/libcrypto64.a is not portable!

*** Warning: Linking the shared library libhercu.la against the
*** static library ./decNumber/lib/aarch64/libdecNumber64.a is not portable!

*** Warning: Linking the shared library libhercu.la against the
*** static library ./SoftFloat/lib/aarch64/libSoftFloat64.a is not portable!

*** Warning: Linking the shared library libhercu.la against the
*** static library ./telnet/lib/aarch64/libtelnet64.a is not portable!
gcc: error: ./crypto/lib/aarch64/libcrypto64.a: No such file or directory
gcc: error: ./decNumber/lib/aarch64/libdecNumber64.a: No such file or directory
gcc: error: ./SoftFloat/lib/aarch64/libSoftFloat64.a: No such file or directory
make[2]: *** [Makefile:2082: libhercu.la] Error 1
make[2]: Leaving directory '/home/rvjansen/apps/hyperion'
make[1]: *** [Makefile:2489: all-recursive] Error 1
make[1]: Leaving directory '/home/rvjansen/apps/hyperion'
make: *** [Makefile:1829: all] Error 2
```

**Comment by Fish-Git** [comment]
**http://www.sdl-hercules-390.org/** &nbsp; ==&gt;  &nbsp; https://sdl-hercules-390.github.io/html/

Scroll down to the "**Web documentation:**" section and click the "**Hercules Installation and Operation**" link.

Follow the instructions as documented in the "**Building from source - Linux and Mac OS X**" section, paying _particular attention_ to step 5: "**Download and build all External Packages if needed:**", where it mentions the **[README.EXTPKG](https://github.com/sdl-hercules-390/hyperion/blob/master/readme/README.EXTPKG.md)** document that explains how to build the  External Packages _(which is _required **before**_ building Hercules on any non-default _(non-Intel x86/x64)_ host architecture like aarch64).

You might also find the following blog post to be helpful as well:

* **[Hercules from source on RPi](https://geronimo370.nl/s370/hercules-installing/hercules-from-source/)**
_(the guy's [Command Center](https://geronimo370.nl/blog/2019/12/24/my-command-center/) looks pretty cool too!)_

&nbsp;
which explains in simple step-by-step detail how he personally builds SDL Hyperion for his Raspberry Pi.

It's actually pretty simple and straightforward IMO. &nbsp; _&lt;shrug&gt;_

Hope that helps!

Closing issue as "Invalid (user error)".

**Comment by wrljet** [comment]
I don't believe this is user error.
Rene is, IMHO, correct here.  The build process does not work correctly on Raspberry Pi running 64-bit Ubuntu.

gcc and configure know the 64-bit ARM architecture as `aarch64`, and the package libraries are expected to be found in a 
`extpkgs/lib/aarch64` directory.

`extpkgs.sh` puts them in `extpkgs/lib/aarch`, which is incorrect for the toolchain.

You can workaround this by renaming the output `lib/aarch` directory to `lib/aarch64` after the external packages are built.

The warning:
`hscutl.c:978:24: warning: comparison is always false due to limited range of data type [-Wtype-limits]`
`  978 |         if ((int)b[ix] == EOF) /* Corrected.                */`

That can be corrected by casting to (signed char) instead of (int).
`                 if ((signed char)b[ix] == EOF) /* Corrected.                */`

Bill

**Comment by Fish-Git** [comment]
@rvjansen

[...]
> gcc and configure know the 64-bit ARM architecture as `aarch64`, and the package libraries are expected to be found in a `extpkgs/lib/aarch64` directory.
> 
> `extpkgs.sh` puts them in `extpkgs/lib/aarch`, which is incorrect for the toolchain.

Hi Bill!

I'm a Windows person, not a Linux person, so when I wrote the `extpkgs.sh` script I did the best I could. I apologize that there are obviously still some bugs in it. I'll try to get them fixed for you.

In the mean time I will remove the erroneous "Invalid (user error)" label and re-open this issue with a bonafide "Bug" label.

My sincerest apologies to Rene!

> The warning:
> [...]
> can be corrected by casting to **`(signed char)`** instead of `(int)`:
> [...]

I'll get _that_ fixed for you right away too! Thank you for reporting it!

Thank you both, guys, for your patience with my Linux bumbling, and I again apologize most sincerely to Rene for my having mistakenly blamed him!

Re-opening issue...

**Comment by wrljet** [comment]
Actually, Fish, I think you did a great job on those scripts and build process.

If you like, I will try to fix up the 64-bit ARM for us.

Bill

**Comment by Fish-Git** [comment]
> If you like, I will try to fix up the 64-bit ARM for us.

That would be great! Thanks!

**Comment by Fish-Git** [comment]
> > If you like, I will try to fix up the 64-bit ARM for us.
> 
> That would be great! Thanks!

@wrljet How's it going? Need any help?

**Comment by wrljet** [comment]
Fish,

It works for me.  I've tried it on various Linux, and several Pi OSes, 32- and 64-bit.

You seemed like you had yours hands full with plenty of other things, so I didn't want to bother you.
But if you're ready I can send you something to look at.

Bill

**Comment by Fish-Git** [comment]
> But if you're ready I can send you something to look at.

Yes! Please! You can either post it here in this issue or send it directly to me if you wish. Either way. My email is on my web page: http://www.softdevlabs.com/about.html

Thanks!.

**Comment by Fish-Git** [comment]
@rvjansen

Fish wrote:
> Bill Lewis wrote:
> 
> > But if you're ready I can send you something to look at.
> 
> Yes! Please! You can either post it here in this issue or send it directly to me if you wish.



Got your email and committed your changes!

Thank you Bill!

René? Please try your build again using the latest version of the gists `extpkgs.sh` shell script to re-clone (or update) and build all External Packages. With Bill's fix it should work for you now. Please let us know if it doesn't.

I'm going to set the status of this bug to "Waiting to Close" until I hear positive confirmation from you that the bug is indeed fixed now. If I don't hear back from you within a couple of days I'll go ahead and close it anyway.

Thank you for your patience.

**Comment by Fish-Git** [comment]
I presume this is now fixed. Closing due to lack of response.

**Comment by slogoing** [comment]
I just tried to make install on Ubuntu 20.10, 64-bit, and got this exact screen.  Is there something I need to do prior to installing hercules to prevent me from getting these errors?

** Warning: Linking the shared library libhercu.la against the
*** static library ./crypto/lib/aarch64/libcrypto64.a is not portable!

*** Warning: Linking the shared library libhercu.la against the
*** static library ./decNumber/lib/aarch64/libdecNumber64.a is not portable!

*** Warning: Linking the shared library libhercu.la against the
*** static library ./SoftFloat/lib/aarch64/libSoftFloat64.a is not portable!

*** Warning: Linking the shared library libhercu.la against the
*** static library ./telnet/lib/aarch64/libtelnet64.a is not portable!
gcc: error: ./crypto/lib/aarch64/libcrypto64.a: No such file or directory
gcc: error: ./decNumber/lib/aarch64/libdecNumber64.a: No such file or directory
gcc: error: ./SoftFloat/lib/aarch64/libSoftFloat64.a: No such file or directory
gcc: error: ./telnet/lib/aarch64/libtelnet64.a: No such file or directory
make[1]: *** [Makefile:2082: libhercu.la] Error 1

**Comment by Fish-Git** [comment]
> Is there something I need to do prior to installing hercules to prevent me from getting these errors?

https://github.com/SDL-Hercules-390/hyperion/issues/312#issuecomment-654075843

**Comment by rvjansen** [comment]
Well maybe a bit late, but I checked it out and it works. You have to do a little something extra. It is almost completely documented at https://geronimo370.nl/s370/hercules-installing/hercules-from-source/ , but you have to specify aarch64 instead of arm. In short: (I am doing this in /home/rvjansen/apps)

mkdir extpkgs
 cd extpkgs
 git clone https://github.com/SDL-Hercules-390/gists
 cp ./gists/extpkgs.sh .
 cp ./gists/extpkgs.sh.ini .
 sudo chmod 777 .
 ./extpkgs.sh clone c d s t
 emacs extpkgs.sh.ini ---> change the CPU type here
 ./extpkgs.sh clone c d s t
 cd ..
 cd hyperion
 ./configure --enable-extpkgs=/home/rvjansen/apps/extpkgs/.
 make
 ./hercules ---> to see it run

So all is well, although it takes a few minutes extra.
