### ISSUE TITLE
Hercules Crash After Disk Errors

### ISSUE THREAD

**Issue by davekreiss** [SDL-Hercules-390/hyperion#313]
Enclosed is a split zip file.  For the crash.z0n.zip files remove the ".zip" making filenames crash,z0n and then you can open the split zip files using WinZip since the original zipped file exceeds the 10M size and github doesn't take the .z0n suffixed files.

crash.zip contains the hercules log and dmp.  There were a lot of disk errors so I shutdown the OS and when I did a quit a dump was produced.

There appear to be multiple disk errors - 
   trklen error for BCCHH = 011a0e0003 at  05:50:27 Jul 6
   invalid trk hdr trk 96642 buf 0000000006ACFB00:0100000001 at 01:36:00 Jul 8
With multiple occurrences to multiple devices.
I then shutdown the operating system and the crash occurred upon shutting down Hercules.

[crash.zip](https://github.com/SDL-Hercules-390/hyperion/files/4891290/crash.zip)
[crash.z01.zip](https://github.com/SDL-Hercules-390/hyperion/files/4891307/crash.z01.zip)
[crash.z02.zip](https://github.com/SDL-Hercules-390/hyperion/files/4891308/crash.z02.zip)
[crash.z03.zip](https://github.com/SDL-Hercules-390/hyperion/files/4891309/crash.z03.zip)

**Comment by davekreiss** [comment]
Ran a cckdcdsk against all disk files and none that showed errors in the hercules.log but a different disk did show errors.  The OS IPLed ok and seems to be ok but who knows,

The log of the cckdcdsk follows.

[hercules crash after dasd errors cckdcdsk.txt](https://github.com/SDL-Hercules-390/hyperion/files/4892606/hercules.crash.after.dasd.errors.cckdcdsk.txt)

**Comment by Fish-Git** [comment]
The compressed CKD dasd (CCKD/CCKD64) handler has always been sensitive to file corruption. Granted, _ideally_ it shouldn't be crashing, but there's not a lot that can be done when garbage data is fed to it. GIGO.

Closing as no action needed.
