### ISSUE TITLE
sysctl.h deprecated under Linux

### ISSUE THREAD

**Issue by s390guy** [SDL-Hercules-390/hyperion#314]
```
In file included from hostinfo.c:21:
/usr/include/x86_64-linux-gnu/sys/sysctl.h:21:2: warning: #warning "The <sys/sysctl.h> header is deprecated and will be removed." [-Wcpp]
   21 | #warning "The <sys/sysctl.h> header is deprecated and will be removed."
      |  ^~~~~~~
```

Needs to be replaced by access to `/proc` filesystem.

See: &nbsp; **https://lwn.net/Articles/795164/**

**Comment by s390guy** [comment]
sysctl.h is being deprecated on Linux.  Its access to data is to be replaced 
by access to the run-time file system via the /proc directory.

grep indicates Hercules references sysctl.h only from within hostinfo.c.
This module would appear to only be called during system initialization.

The explicit calls to sysctl seem to be only within an #if/#endif sequence
enabled for apple, FreeBSD or NetBSD, not Linux.

For Linux the call is to the uname() fucntion to build the hostinfo structure.
  The uname() function also is used in tuntap.c.226.

So while the deprecation message is generated during the compilation of the
Hercules modules, its absence does not appear to be an issue for Hercules on
Linux.  It is the inclusion of sysctl.h that triggers the message.  That
would suggest some adjustments to the build would eliminate this message
on Linux, but otherwise does not appear to be a cause for later concerns.

Confirmation from additional eyes would be appreciated before closing this issue.

**Comment by Fish-Git** [comment]
> Confirmation from additional eyes would be appreciated before closing this issue.

1. Your analysis appears to be spot on, IMHO.

2. I would appreciate someone _(you perhaps?)_ actually _**fixing**_ the problem _first,_ before closing the _[GitHub]_ issue! &nbsp; `;-)`

**Comment by Fish-Git** [comment]
Closing as no action needed.
