### ISSUE TITLE
Hyperion HERCULES-4.3.9999.10165-SDL-G876894D-X64 CPU 3 (of 8) in spin loop 

### ISSUE THREAD

**Issue by YossiReichman** [SDL-Hercules-390/hyperion#316]
From the hercules console I observed that CPU 3 was in spin loop.

This is from from memory (should of taken a screen shot ) it was trying to do ACR (z/os alternate cpu recovery) maybe it was a z/os console  message that went to the hercules console.

At the time I was debugging a program using TESTAUTH (what I am trying to say is I was doing very vanilla type stuff)

The dump it 179 mb zipped

I am running windows 10 I have i9-9980 2.4 gz 8 core lapatop 64 gb ram

I have noticed this happening when I get messages about the jes2 lock

this is just an FYI z/os provides a parmlib member about what to do if a CPU is spinning meaning from z/os point of view it is in 
a loop. You can let it spin or abend it. The parmlib member is EXSPAT     

will try to upload the file to your FTP site 

Thanks

**Comment by Fish-Git** [comment]
Version **4.3.9999.10165-SDL-g876894d-X64** does not correspond to any known version of Hercules.

Closing as Invalid.
