### ISSUE TITLE
HHC90013E 'obtain_lock(&sysblk.txf_lock2[  0])' failed: rc=11: deadlock; tid=000070000febf000, loc=transact.c:673

### ISSUE THREAD

**Issue by azarrafa** [SDL-Hercules-390/hyperion#317]
Hello,
I am getting this error below after starting a zosmf server STC I don't now if It is the cause or a consequence of my STC java Dump.
I attached the startup and config log. I am using z/os 2.4.

HHC90013E 'obtain_lock(&sysblk.txf_lock2[  0])' failed: rc=11: deadlock; tid=000070000febf000, loc=transact.c:673

[herc_startup.log](https://github.com/SDL-Hercules-390/hyperion/files/5095705/herc_startup.log)
[hercules_SYST_z14.cnf.txt](https://github.com/SDL-Hercules-390/hyperion/files/5095712/hercules_SYST_z14.cnf.txt)

**Comment by azarrafa** [comment]
I forget to add the javacore file : 

0SECTION       TITLE subcomponent dump routine                                  
NULL           ===============================                                  
1TICHARSET     IBM-1047                                                         
1TISIGINFO     Dump Event "gpf" (00002000) received                             
1TIDATETIME    Date: 2020/08/18 at 14:54:34:612                                 
1TINANOTIME    System nanotime: 1597762474616245000                             
1TIFILENAME    Javacore filename:    /SYSTEM/var/zosmf/data/logs/zosmfServer/jav
1TIREQFLAGS    Request Flags: 0x1 (exclusive)                                   
1TIPREPSTATE   Prep State: 0x100 (trace_disabled)                               
1TIPREPINFO    Exclusive VM access not taken: data may not be consistent across 
NULL           -----------------------------------------------------------------
0SECTION       GPINFO subcomponent dump routine                                 
NULL           ================================                                 
2XHOSLEVEL     OS Level         : z/OS 02.04.00                                 
2XHCPUS        Processors -                                                     
3XHCPUARCH       Architecture   : s390x                                         
3XHNUMCPUS       How Many       : 4                                        
3XHNUMASUP       NUMA is either not supported or has been disabled by user 
NULL                                                                       
1XHEXCPCODE    J9Generic_Signal_Number: 00000018                           
1XHEXCPCODE    Signal_Number: 0000000B                                     
1XHEXCPCODE    Error_Value: 00000000                                       
1XHEXCPCODE    Signal_Code: 000000FF                                       
1XHEXCPCODE    Handler1: 000000500871F5B0                                  
1XHEXCPCODE    Handler2: 00000050086F3BA0                                  
NULL                                                                       
NULL                                                                       
1XHREGISTERS   Registers:                                                  
2XHREGISTER      gpr0: 0000000000000016                                    
2XHREGISTER      gpr1: 000000000F0F9C00                                    
2XHREGISTER      gpr2: 00000000BF3E3210                                    
2XHREGISTER      gpr3: 000000000000000E                                    
2XHREGISTER      gpr4: 00000050082FB7C0

**Comment by Peter-J-Jansen** [comment]
azzarrafa,

This problem has been fixed in the mean time. If you re-build SDL-Hyperion it will no longer appear.

Cheers.

Peter

**Comment by azarrafa** [comment]
Hello Peter,
Thank you for your reply. I will rebuild the source and see if somethings come up.
regards,
Abdellah

**Comment by azarrafa** [comment]
Thank you it works with the last build.

**Comment by azarrafa** [comment]
My problem was solved with this config 👍  running a zos 2.4 :
HHC00100I Thread id 000000011c04fdc0, prio 5, name 'impl_thread' started
HHC00100I Thread id 000070000e395000, prio 4, name 'logger_thread' started
HHC01413I Hercules version 4.3.9999.0-SDL-g2c0d41ed (4.3.9999.0)
HHC01414I (C) Copyright 1999-2020 by Roger Bowler, Jan Jaeger, and others
HHC01417I ** The SoftDevLabs version of Hercules **
HHC01415I Build date: Aug 19 2020 at 16:23:27
HHC01417I Built with: Apple Clang 11.0.3 (clang-1103.0.32.62)
HHC01417I Build type: Mac OS X x86_64 host architecture build
HHC01417I Modes: S/370 ESA/390 z/Arch
HHC01417I Max CPU Engines: 128
HHC01417I Using   shared libraries
HHC01417I Using   setreuid() for setting privileges
HHC01417I Using   POSIX threads Threading Model
HHC01417I Using   Error-Checking Mutex Locking Model
HHC01417I With    Shared Devices support
HHC01417I With    Dynamic loading support
HHC01417I With    External GUI support
HHC01417I With    Partial TCP keepalive support
HHC01417I With    IPV6 support
HHC01417I With    HTTP Server support
HHC01417I With    sqrtl support
HHC01417I With    Signal handling
HHC01417I With    Watchdog monitoring
HHC01417I With    CCKD BZIP2 support
HHC01417I With    HET BZIP2 support
HHC01417I With    ZLIB support
HHC01417I With    Regular Expressions support
HHC01417I Without Object REXX support
HHC01417I Without Regina REXX support
HHC01417I With    Automatic Operator support
HHC01417I Without National Language Support
HHC01417I With    CCKD64 Support
HHC01417I With    Transactional-Execution Facility support
HHC01417I With    FISHTEST_TXF_STATS
HHC01417I Without OPTION_TXF_SINGLE_THREAD
HHC01417I Machine dependent assists: cmpxchg1 cmpxchg4 cmpxchg8 cmpxchg16 hatomics=C11
HHC01417I Running on: macbook-pro.dhcp.broadcom.net (Darwin-19.6.0 64-bit 64-bit x86_64) LP=16, Cores=8, CPUs=1
HHC01417I Built with crypto external package version 1.0.0.33-g02174c9-modified
HHC01417I Built with decNumber external package version 3.68.0.86-g963bd1f-modified
HHC01417I Built with SoftFloat external package version 3.5.0.89-g4bd642a-modified
HHC01417I Built with telnet external package version 1.0.0.50-g650fad2-modified
HHC00018I Hercules is running in elevated mode
