### ISSUE TITLE
CNSLPORT xxxx command in Hyperion console doesn't seem to work

### ISSUE THREAD

**Issue by moshix** [SDL-Hercules-390/hyperion#318]
When I IPL a guest with a config file saying, for example, `CNSLPORT  3270`, and if I then want to change that at runtime to 3280, I do from the Hyperion console:

```
cnslport 3280
```

It responds with:
```
HHC01603I cnslport 3280
```

It accepts the command fine, but it never changes the console port to the new value of 3280 (or whatever valid port number). 

Seems to be the same behavior also with Spinhawk (if that helps). 

thanks

M

**Comment by Peter-J-Jansen** [comment]
OK, but the CNSLPORT statement in the configuration .cnf file works, right ? At least for me it does.

Cheers,

Peter

**Comment by moshix** [comment]
Peter

yes, in the config file it takes the port parameter fine. 

The CNSLPORT command in the console seems to not do anything at all. I tried also combinations like:

CNSLPORT 192.168.1.100:3280 etc. 

Nothing works. 

The documentation on this command is not clear. Is it supposed to only report the current port, but not change it? Or is it supposed to change and it silently refuses to do that?

Unclear. 

I would of course love it if it actually did change the port.

thanks

M

**Comment by moshix** [comment]
After looking at the code in https://github.com/SDL-Hercules-390/hyperion/blob/master/console.c it's clear that there is no way to close down a previous socket and re-open with a new configuration of address and port. 

So, the cnslport command actually only reports the current configuration as loaded from the config file. It does not send any new address/port argument to console.c to close and re-open with the argument. 

So, what is the use case for this ? 

For me it' when I want to add a LUNAME to a console port to block others temporarily from connecting, or when I really need to change the port number without taking down the mainframe OS down for that small change. 

thanks

M
