### ISSUE TITLE
Differences between Hyperion and Hercules

### ISSUE THREAD

**Issue by PaulRaulerson** [SDL-Hercules-390/hyperion#320]
I wanted to move up to Hyperion because it is said to have reasonable support for QETH as a network device. I figured it would not be all that hard, and in fact, the source code for Hyperion compiled in a very short time under Debian. (Linux ZMF001 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux) 

Everything looked pretty good, so I made a copy of the DASD I was using, setup the .cnf file to point to them, and loaded hercules/hyperion and went to IPL. 

It didn't get very far, because it didn't handle the DASD well at all, even after making sure I compiled in ZLIB support. Long story made short, I wound up copying all the dasd (using the Hyperion utility) at which point, everything IPL'ed and seemed to work. 

Except for networking. The exact same config file (using a LCS device at address 0900) started, but failed to route packets to the network. (It could ping the local IP of the virtual adapter.)

MMM- I checked all the settings, restarted TCPIP, then even re-IPLed.  No joy.   Okay, I says, lets try the QETH interface. Happily, the interface appeared to have correctly started. But it did the same dang thing... could ping the interface but nothing at all beyond it.  

Did a make "uninstall" and then reinstalled Hercules 3.13. Loaded the LCS device and voila -it all worked. The QETH device reported it failed to start correctly. 

Yes, this sounds like a routing issue - however, where is this issue?  The Hercules / Hyperion code should run Hercifc and pick up the /dev/net/tun routing, no?  I tried adding a specific routing on my network switch, and checked the routing on the Linux host. 

What I don't understand is why it works on the same hardware with (essentially) the same configuration file with 3.13, but Hyperion doesn't want to play ball and behave. I like the idea of the fixes I can see in Hyperion, but I am really a bit frustrated that it doesn't work even when configured correctly by the documents, and that I could not not find any lear documentation on the DASD formats. (It may be there, but I didn't see it. Why would it not take cckd disk images from 3.13 and what did it do to them in the dasd copy that makes the copied files unusable in 3.13?  

Thanks 
-Paul 

```
ARCHLVL    z/ARCH
FACILITY   ENABLE 044_PFPO
PGMPRDOS   LICENSED
ECPSVM     NO
CPUVERID   00
LPARNAME   ZVM44TEST
LPARNUM    01
CPUIDFMT   1
MODEL      EMULATOR
PLANT      ZZ
MANUFACTURER IBM
CPUSERIAL 071060
CPUMODEL  2818
ENGINES   CP,CP,CP,IP
MAINSIZE  4G
CNSLPORT  3271
HTTPPORT  8082
NUMCPU    6
CPUPRIO   15
LOADPARM  0200

...
...
...

#Network devices
#CUU dev  driver          IP Address of S/390 Guest (Optional)
#0900-0901 LCS -n /dev/net/tun  10.10.50.48

#QETH Driver
A600.3   QETH chpid F1  iface /dev/net/tun  ipaddr 10.10.50.48  netmask 255.255.255.0 mtu 1492 
```

**Comment by Fish-Git** [comment]
@mcisho @s390guy 

Ian?  Harold? Can you maybe help this gentleman? You know me, I'm a Windows guy. Linux networking is a mystery to me! Thanks.

**Comment by s390guy** [comment]
@dasdman 

The first thing to understand is the age of Hercules 3.13.  Hyperion split from Hercules around 5 years ago.  Could have been more.  There have definitely been enhancements in networking.  QETH is one.

I personally have not done much work with Hercules DASD, old or new, so can not really explain why you had issues with the emulated DASD when you moved them to SDL Hyperion.  The fact that they worked after you used the Hyperion utility suggests some known and planned internal differences exist.  Beyond that I can not explain it.  Perhaps dasdman can answer that question.

With regards to networking, the usual reason that a networked device can not reach the guest OS (and vice versa) is that there needs to be a route in the networked device to the IP address of the guest via the LAN address of the Hyperion host.  You must have IP forwarding enabled for the Linux IP stack.  If you can not ping the network interface of the Hercules host from the guest or probably vice versa, that is usually an IP forwarding issue.  If you can not do the same with some other device outside of the Hyperion host, that is usually a missing route IN THE DEVICE back to the Hyperion guest.

Without more information it is difficult to tell.  This is mainly the SDL Hyperion developers around a dozen people and we tend to specialize, as you can see above.  Fish know Windows.  I have done some networking work.  I use Linux.  And dasdman specializes in I/O, DASD devices especially.

I would encourage you to raise your issues on the main Hercules list.  There are a lot more people there who have practical everyday experience with these matters.  They may have some ready answers from their experience.

If you would like to exchange some private emails with me on the networking, I am willing to try helping.  h.grovsteen@tx.rr.com

Harold

**Comment by s390guy** [comment]
After some discussion, I can provide an explanation related to your emulated DASD issues.  Over time small things have changed.  Some have been driven by external library changes (outside our control).  Some are issues found within the compressed DASD code itself.  The utilities try to manage some of the these small changes.  The easiest way to think of compressed DASD is that there is a layer of cached records sitting between the guest and the emulated DASD "hardware".  The utilities refresh this caching "layer".  Given enough time, even the utilities will not correct the problem.

To track down exactly what introduced the issues _you_  were experiencing is very difficult if not impossible.

That is the explanation for your DASD experiences I was able to determine.  You now have working DASD so it is largely academic.  Hope that helps.

**Comment by s390guy** [comment]
BTW, 3.13 is roughly a decade behind Hyperion.  Many changes now between the SDL version of Hyperion and Hercules 3.13.

**Comment by PaulRaulerson** [comment]
That was one reason to think of moving to Hyperion. On the other paw, I do not want to run under Windows, don’t want the cool looking but useless to me 360 graphical control panel, and it seems one has to buy three or four add ons to get Windows Guests to work on the network.  Noneof which is to say I won’t load up W10 on a machine if I have to. 

Network wise - why would one need to handcode a route? Shouldn’t Proxy ARP take care of publishing a route?

Typos courtesy of my iPhone and my fat fingers!

**Comment by Fish-Git** [comment]
> don’t want the cool looking but useless to me 360 graphical control panel

100% OPTIONAL. Hercules will run just fine using an ordinary elevated Command Prompt (i.e. "Terminal") window just like it does on Linux. You do _NOT_ need HercGUI.

> and it seems one has to buy three or four add ons to get Windows Guests to work on the network.

Um, no. Not three or four. _ONE_. You only need _one_ add-on: my [CTCI-WIN](http://www.softdevlabs.com/ctci-win.html) product. Nothing else.

> Network wise - why would one need to handcode a route? Shouldn’t Proxy ARP take care of publishing a route?

I don't know. Ask Harold. &nbsp; `:)`

**Comment by s390guy** [comment]
Proxy ARP is certainly an option provided network addresses work.  You provided no details, so I assumed nothing about the rest of your network.  What I suggested does not involve actual publishing of a route, in the sense that the remote devices learn about how to get to the Hyperion host.  It involves manually telling such a device how to get there.

Having said that and you know about proxy ARP, the question remains, why is it not working with your upgraded Linux system?
I cam away with that impression anyway.  That is, you upgraded Linux.

Unless of course you fixed that.

I generally try not to make assumptions about the environment or a poster's knowledge of networking.

**Comment by Fish-Git** [comment]
> > and it seems one has to buy three or four add ons to get Windows Guests to work on the network.
> 
> Um, no. Not three or four. _ONE_. You only need _one_ add-on: my [CTCI-WIN](http://www.softdevlabs.com/ctci-win.html) product. Nothing else.

_**And technically**_ you don't need to even "buy" _ANYTHING AT ALL!_ You can download and use the free "Trial" version of any of my products and use them for as long as you want, completely free of change. Zero dollars and zero cents. The trial versions are 100% identical in functionality to the paid version. The trial versions just have splash screens and/or "watermarks" that identify themselves as being an "Unpaid Trial Version" (to try and prod you into purchasing the paid version instead). Other than that they are, as I said, 100% identical in functionality.

So trying whatever you are trying to do on Windows will cost you _nothing._ Not a single dime. And all you need is CTCI-WIN and nothing else. Period.

Just wanted to make that clear.

**Comment by PaulRaulerson** [comment]
I seriously thank you for your politeness and consideration. It is appreciated very much. 

You can certainly feel free to ask any questions you like - I am the one asking assistance after all!🤠

This is actually a new machine with new hardware and SW. it certainly makes a lot of sense to try and use Hyperion vs Hercules on it - and the final goal is a standalone z/Linux system. I needed to load an old copy of z/VM to do some dasd transfers. At least I think I do. The older Linux images are on DDR backups with a 3590 physical tape system. Also ancient.  ;) 

The only things I noticed with Hyperion were the odd networking issues and better load management - the system ran smoother. 

Hope that helps. I am generally pretty good with networking, and Herc has always been trivial to get networking up on.  I may just be missing something simple (i.e. tunnel blindness, pun intended. :)

Typos courtesy of my iPhone and my fat fingers!

**Comment by PaulRaulerson** [comment]
I meant if I used it, I would need to pay for it eventually. So yes, there is an additional, if small, cost to run under Windows. I do not mind using or paying for it if it works. I admit, I am not a Windows fan, as something or another always seems to go haywire on Windows - for me at least. Linux seems far more stable. YMMV!

I do wish someone could put out Herc or Hyperion as a software service. That may be worth paying for. 

Typos courtesy of my iPhone and my fat fingers!

**Comment by mcisho** [comment]
Can I confirm, you have a Debian host, on which you are running Hercules SDL, under which you are running an unspecified guest? With this configuration neither LCS nor QETH work? You said **It could ping the local IP of the virtual adapter**, by which I assume that you meant that the guest could ping its local IP address, but nothing else?

Can you provide the output of the **ifconfig** and **route** commands issued on your host, and the output of equivalent commands issued on your guest? Can you issue a Hercules **debug ctc on 900** command, and then issue a ping command on your guest, and then on your host, so that we can see what traffic, if any, passes over the tap interface?

I use a Fedora host, and Hercules SDL's LCS and QETH both work without problems for me, though admittedly I generally use preconfigured interfaces, not hercifc configured interfaces.

Ian

**Comment by s390guy** [comment]
@mcisho 

All questions I would like answered as well.  In addition, I would like to know the IP addresses in use on all concerned devices, at least those expected to be involved in the communication path.

Thanks,
Harold

**Comment by mcisho** [comment]
Having read what I wrote, I realized I was ambiguous. What I should have said was:

Can you provide the output of **ifconfig* and **route** commands issued on your host, and the output of the equivalent commands issued on your guest, once you guest is running? Can you issue a Hercules **debug ctc on 900** command, and then issue a ping command on your guest to your host, and then on your host to your guest, so that we can see what traffic, if any, passes over the tap interface?

Ian

**Comment by Fish-Git** [comment]
Paul? (@PaulRaulerson)

Has this issue been resolved to your satisfaction yet? I would like to close this issue if possible but do not want to do so if you're still having problems. Is everything working okay for you now?

Thanks!

**Comment by PaulRaulerson** [comment]
Hi Fish - no, still not working but no need to hold it open either.  Thank you.  -Paul

**Comment by Fish-Git** [comment]
> Hi Fish - no, still not working but no need to hold it open either. Thank you. -Paul

As you wish!
