### ISSUE TITLE
Testing network implementation (tuntap.c)

### ISSUE THREAD

**Issue by Rhialto** [SDL-Hercules-390/hyperion#324]
Hi! I have been playing with Hercules a bit more recently, and I realised that in my previous packaging of Hercules in pkgsrc, I had simply disabled most of `tuntap.c` because it didn't compile.

I wanted to get a bit further this time. My strategy was to only disable those pieces of code that make no sense on NetBSD, and then see what problematic stuff is left. This was fairy easy: there were about 2 pieces of code that assumed Linux-like behaviour of tun/tap: that you always open the same device (/dev/net/tun or something), and then you switch it to either tun or tap mode.

After removal of these bits, it compiles! See commit https://github.com/Rhialto/hyperion/commit/f114bf9891746e8c64bb187880baa5b13a07bb7c . It's almost too easy.

But how do I test this? I've got the VM/370 sixpack beta 2 and 3, but I don't think those do anything with networking. Is there anything else I can try?

**Comment by mcisho** [comment]
The s390x version of one of the many Linux distos? Does NetBSD provide as s390(x) version?

**Comment by Rhialto** [comment]
I was actually thinking of something smaller than a whole operating system...

Alas, NetBSD has no s390 version. (There was an attempt to create a PDP-10 version, which is also an interesting old architecture, but that didn't come off the ground sufficiently, and was removed again).

I remember trying in the past to boot a Linux on Hercules, but I had difficulty finding an actual version. This time, I found at least https://wiki.ubuntu.com/S390X which led to https://cloud-images.ubuntu.com/releases/bionic/release/ . Unfortunately, whatever I found there was either in Qemu disk format, or in raw ext4 format. Not something I could IPL with Hercules.

For the rest there was "Access to the ISO and image download is provided via the following form " and some links to forms that mentioned paying "$19,500 per drawer per year," which doesn't appeal so much. Whatever a drawer is; probably not  a removable disk pack.

**Comment by mcisho** [comment]
https://alt.fedoraproject.org/alt/
https://cdimage.debian.org/debian-cd/current/s390x/iso-cd/?C=S;O=A

Do you have a public FTP server?

**Comment by Rhialto** [comment]
Thanks!

No, right now I don't have an ftp server set up.

Just now I found https://astr0baby.wordpress.com/2018/06/03/installing-ubuntu-18-04-server-s390x-in-hercules-mainframe-simulator/ which also looks promising.

**Comment by Rhialto** [comment]
So I played around with that Linux installer. The nice thing about it is that it supports several (but not all) networking options, so I could test a few. In the end I could make 2 out of 4 configurations working. I'm not sure if the failing ones simply could not work with this Linux installer, or if I messed something up.

I did notice in a few cases that Herculess seemed to be meddling with the host side of a TUN interface. Suddenly "my" side of the connection had the IP address that should be on the "other" (Hercules) side. That's easy enough to fix with an `ifconfig` command, but I wonder if I there put some IP address wrong, or if Hercules is making a mistake there.

Here are my attempts:

```
# Network. My host machine's address is 10.0.0.blah. 
# Hercules should be 10.0.1.2.
# The host side of the connection should be 10.0.1.1. 
# This is a routed approach.
#
# Works in Linux installer image:
0A00.2        CTCI -n /dev/tun0 -t 1500 10.0.1.2 10.0.1.1
# Create tun0 with
# sudo ifconfig tun0 create inet 10.0.1.1/24
# sudo route add 10.0.1.2 10.0.1.2

# Used in L3 mode (tun): didn't work
# 0A00.3        QETH ifname tun0 iface /dev/tun0   ipaddr 10.0.1.2
# sudo ifconfig tun0 create inet 10.0.1.1/24
# sudo route add 10.0.1.2 10.0.1.2

# Used in L3 mode (tap): worked:
0A00.3  QETH ifname tun0 iface /dev/tap0   ipaddr 10.0.1.2
#              prepare tap0: sudo ifconfig tap0 create inet 10.0.1.1/24
#                            sudo route add 10.0.1.2 10.0.1.2

# Not available in Linux intaller image
# 0A00.2       LCS     --dev /dev/tap0 --mac f2:0b:a4:2e:fd:5b 10.0.1.2
#              prepare tap0: sudo ifconfig tap0 create inet 10.0.1.1/24
#                            sudo route add 10.0.1.2 10.0.1.2
```
The way these similar devices take their arguments is confusingly irregular...

**Comment by mcisho** [comment]
> So I played around with that Linux installer.

By 'that' I assume you mean the Ubuntu installer?

> I'm not sure if the failing ones simply could not work with this Linux installer, or if I messed something up.

Debian, and presumably derivatives, doesn't support LCS. Well that's not entirely true, once you have an installed system running you can get LCS interfaces working. Hercules' QETH layer 3 (i.e. using tun) doesn't work too well when you want to communicate from the guest to the outside world.

> I did notice in a few cases that Hercules seemed to be meddling ...

Evidence please. No point bothering to tell anyone if you don't provide any supporting evidence. And is this a NetBSD issue, rather than a Hercules issue? Afaik, Hercules does not meddle on Linux or Windows hosts.

> The way these similar devices take their arguments is confusingly irregular...

The benefit of many peoples efforts over many years! There are now too many users happily using the confusingly irregular to change to something less confusingly regular.

**Comment by Rhialto** [comment]
To recap: I'm inspired by the instructions at https://astr0baby.wordpress.com/2018/06/03/installing-ubuntu-18-04-server-s390x-in-hercules-mainframe-simulator/ but the networking setup he's doing is way overdone, and NetBSD is different in implementation details anyway. So I ignored that part mostly.

The Installer ISO is a newer version by now; the URL I used is http://cdimage.ubuntu.com/releases/18.04/release/ubuntu-18.04.5-server-s390x.iso.

I'm using this as `ubuntu.conf`, copied from the blog, old config options and all:
```
ARCHMODE z/Arch
ALRF ENABLE
CCKD RA=2,RAQ=4,RAT=2,WR=2,GCINT=5,GCPARM=0,NOSTRESS=0,TRACE=0,FREEPEND=-1
CNSLPORT 3270
CONKPALV (3,1,10)
CPUMODEL 3090
CPUSERIAL 012345
DIAG8CMD ENABLE
ECPSVM YES
LOADPARM 0A95DB..
LPARNAME HERCULES
MAINSIZE 1024
MOUNTED_TAPE_REINIT DISALLOW
NUMCPU 4
OSTAILOR Z/OS
PANRATE 80
PGMPRDOS LICENSED
SHCMDOPT NODIAG8
SYSEPOCH 1900
TIMERINT 50
TZOFFSET +0200
YROFFSET 0

# Display Terminals

0700 3270
0701 3270

# dasd
0120 3390 ./dasd/ubuntu.disk

# Network. My host machine's address is 10.0.0.16.
# Used in L2 mode (tap):
  0A00.3       QETH ifname tun0 iface /dev/tap0   ipaddr 10.0.1.2
```
I'm preparing by setting up the `tap0` and the address of the host side, `10.0.1.1/24`
```
$ sudo ifconfig tap0 create inet 10.0.1.1/24

tap0: flags=0x8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 1500
        ec_capabilities=5<VLAN_MTU,JUMBO_MTU>
        ec_enabled=0
        address: f2:0b:a4:4b:89:0f
        media: Ethernet autoselect
        inet 10.0.1.1/24 broadcast 10.0.1.255 flags 0x0
        inet6 fe80::f00b:a4ff:fe4b:890f%tap0/64 flags 0x0 scopeid 0x6

$ route get 10.0.1.2
   route to: 10.0.1.2
destination: 10.0.1.0
       mask: 255.255.255.0
 local addr: 10.0.1.1
  interface: tap0
      flags: 0x141<UP,DONE,CONNECTED>
 recvpipe  sendpipe  ssthresh  rtt,msec    rttvar  hopcount      mtu     expire
       0         0         0         0         0         0         0       -15


$ sudo hercules -f ubuntu.conf

No messages about the network interface.
Network state unchanged.

herc =====> ipl /tmp/mktemp.GjxxV7Mp/ubuntu.ins

Configure the network device
----------------------------

Please choose the type of your primary network interface that you will need for
installing the Debian system (via NFS or HTTP). Only the listed devices are
supported.
Network device type:
  1: ctc: Channel to Channel (CTC) or ESCON connection,
  2: qeth: OSA-Express in QDIO mode / HiperSockets,
  3: iucv: Inter-User Communication Vehicle - available for VM guests only,
  4: virtio: KVM VirtIO,
Prompt: '?' for help>
HHC00160I SCP command: 2
2

Please select the OSA-Express QDIO / HiperSockets device.
Device:
  1: 0.0.0a00-0.0.0a01-0.0.0a02  *!,
Prompt: '?' for help, default=1>
HHC00160I SCP command: 1
1

By default OSA-Express cards use layer3 mode. In that mode LLC headers are
removed from incoming IPv4 packets. Using the card in layer2 mode will make it
keep the MAC addresses of IPv4 packets.
Use this device in layer2 mode?
  1: Yes  *!  2: No
Prompt: '?' for help, default=1>
HHC00160I SCP command: 1
1

HHC03800I 0:0A01 QETH: Adapter mode set to Layer 2
HHC00901I 0:0A01 QETH: Interface tap0, type TAP opened
HHC00136E Error in function TUNTAP_GetMACAddr: Unsupported
HHC00007I Previous message from function 'TUNTAP_GetMACAddr' at tuntap.c(702)
HHC02499I Hercules utility hercifc - Hercules Network Interface Configuration Pr
HHC01414I (C) Copyright 1999-2019 by Roger Bowler, Jan Jaeger, and others
HHC01417I ** The SoftDevLabs version of Hercules **
HHC01415I Build date: Sep 29 2020 at 14:21:49
HHC03997I 0:0A01 QETH: tap0: using MAC address 02:00:5E:A2:B3:70
HHC03997I 0:0A01 QETH: tap0: using MTU 1500
HHC03801I 0:0A01 QETH: tap0: Register guest MAC address 02:00:00:18:87:ba
Configure the network
---------------------

Networking can be configured either by entering all the information manually,
or by using DHCP (or a variety of IPv6-specific methods) to detect network
settings automatically. If you choose to use autoconfiguration and the
installer is unable to get a working configuration from the network, you will
be given the opportunity to configure the network manually.
Auto-configure networking?
  1: Yes  *!  2: No
Prompt: '?' for help, default=1>


tap0: flags=0x8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 1500
        ec_capabilities=5<VLAN_MTU,JUMBO_MTU>
        ec_enabled=0
        address: f2:0b:a4:4b:89:0f
        media: Ethernet autoselect
        inet 10.0.1.2/24 broadcast 10.0.1.255 flags 0x0
        inet6 fe80::f00b:a4ff:fe4b:890f%tap0/64 flags 0x0 scopeid 0x6
```
At this point you may notice that the address on the host-side of the tap0 has been changed from `10.0.1.1/24` to `10.0.1.2/24`. That address is supposed to the the Hercules instance on "the other side of the cable".

Looking at https://sdl-hercules-390.github.io/html/hercconf.html in the section under QETH I find that I could leave out the IP address on Unix (which will probably work around the issue), but it *is* supposed to be the guest address.
```
ipaddr  address
ipaddr  address/prefix

    Required on Windows
    Specifies the IPv4 address to be assigned to your virtual OSA Express card. This IP Address should match the IP address in your guest's TCPIP PROFILE, although this is not a requirement; during guest initialization your guest should automatically assign the proper IP address to your OSA device. 
```
If Hercules is using `TUNTAP_SetIPAddr()` (`SIOCSIFADDR`) to set a guest IP address, then this is a confusion on the part of Hercules, since it changes the host address. As we've seen.

Similarly, it should not be using `TUNTAP_GetMACAddr()` (about which an error is printed) since it is about the MAC address on the host side as well.

Guests have total control of their own MAC and IP addresses, simply by the values they write in those fields in the packets that they inject through their file descriptor side of the virtual cable.

I do have some experience with this sort of networking: I rewrote a lot of the network interfacing code in the klh10 PDP-10 emulator. See for example https://github.com/PDP-10/klh10/blob/bde5dcdc27d45bd69c69ac567beaf8b1674534e8/src/dpni20.c   or  https://github.com/PDP-10/klh10/blob/bde5dcdc27d45bd69c69ac567beaf8b1674534e8/src/osdnet.c#L1156 where setting an EA (ethernet address) is specifically not done on taps or VDE interfaces.

**Comment by mcisho** [comment]
> ... but it is supposed to be the guest address.

> If Hercules is using TUNTAP_SetIPAddr() (SIOCSIFADDR) to set a guest IP ...

Yep, Hercules shouldn't be using TUNTAP_SetIPAddr() where it is.

> Similarly, it should not be using TUNTAP_GetMACAddr() (about which an error is printed) since it is about the MAC address on the host side as well.

Hercules is using TUNTAP_GetMACAddr() to obtain the MAC address on the host side. What is the error that is printed?

**Comment by Rhialto** [comment]
`HHC00136E Error in function TUNTAP_GetMACAddr: Unsupported` is the error. I see in the code that it depends on the preprocessor variable `OPTION_TUNTAP_GETMACADDR`. This seems to be undefined for me. It depends in turn on `HAVE_DECL_SIOCGIFHWADDR`. That seems to depend on `#include <linux/sockios.h>` to find `SIOCGIFHWADDR` which indeed NetBSD doesn't have (certainly not `<linux/...>`). NetBSD does have `SIOCGIFADDR     Get interface address for protocol family.`.

But Hercules has no need to know the host-side MAC address. 

- In a routed setup (like I'm currently using, where the guest is located on a newly invented network): the guest OS will need to send packets to the host, but it will use ARP to find out the MAC address
- In a bridged setup (where the guest appears to be present on the existing LAN): the host-side of the tap interface is there only to be bridged to the LAN interface. It has no purpose of its own, other than to be invisible. It need not have any address at all, since no packet will ever be sent from it, so no packet will contain it.

**Comment by mcisho** [comment]
> Yep, Hercules shouldn't be using TUNTAP_SetIPAddr() where it is.

Having opened mouth before checking, I am of course wrong, and Hercules should be using TUNTAP_SetIPAddr() where it is. The description of the **ipaddr** parameter in the QETH code says **When using a routed configuration the tap device needs to have an IP address assigned in the same subnet as the guests virtual eth adapter.**, i.e. the IP address refers to the host end of the tunnel. When the guest activates its eth adapter the guest will inform the QETH code of the IP address(es) that the guest is using.

Another example of ** The way these similar devices take their arguments is confusingly irregular...**

**Comment by mcisho** [comment]
I should add that the guest will only inform the QETH code of the IP address(es) that it is using when the guest is using layer 3, i.e. Hercules creates a tun interface. When the guest is using layer 2, i.e. Hercules creates a tap interface, the guest will only inform the QETH code of the MAC address(es) that it is using. However, whether the guest is using layer 2 or 3 is irrelevant, the IP address specified on the ipaddr parameter refers to the host side of the tun or tap interface.

**Comment by Fish-Git** [comment]
@Rhialto
@mcisho

Rhialto, Ian,

Since this GitHub Issue wasn't created to report an actual problem/bug, but instead was created to just basically ask a question about Hercules networking, I have to now ask:

Has this issue been resolved yet? Can it be closed? Or is there more that needs to be done?

Just asking!

Thanks.
