### ISSUE TITLE
wsl2 ??

### ISSUE THREAD

**Issue by stevebovy** [SDL-Hercules-390/hyperion#343]
Han anyone been researching using herc on wsl2.   

I know their might be issues with tun/tap devices,  but supposedly  with wsl2 tun/tap is supported ???

**Comment by Fish-Git** [comment]
stevebovy (@stevebovy),

Please use the Hercules-390 support group on Groups.IO to ask such questions. GitHub Issues are supposed to be for reporting problems, not asking questions. I am closing this issue as Invalid.

**Comment by Peter-J-Jansen** [comment]
@stevebovy : This is indeed not a Hercules-390 _issue_, but rather WSL2 issue #4150.

WSL2 does support tun/tap, but by default the WSL2 NIC is in NAT mode with its Windows host. And dat hampers Hercules tun/tap functioning. However, at the bottom of this [WSL2 issue #4150 entry](https://github.com/microsoft/WSL/issues/4150#issuecomment-727197204) you may find a Bash script of mine which allows one to switch from NAT mode to Bridge mode and back. (The switch back requires a PC restart though.) Please give it a try.

Cheers,

Peter
