### ISSUE TITLE
zlib compression unsupported

### ISSUE THREAD

**Issue by sakect** [SDL-Hercules-390/hyperion#346]
Hi,

I just start hercules 4 and try to start the system it got the following issue when try to start ipl

Could you help me how to fixed it please?

```
0:D000 CCKD file[0] /etc/hercules/Z21RES.3390-9.comp-z: invalid trk hdr trk 0: zlib compression unsupported
```

Thank you

**Comment by Fish-Git** [comment]
**How to Ask for Help:** &nbsp; https://github.com/Fish-Git/AskForHelp

**Comment by Fish-Git** [comment]
I will wait another few days for more information before closing.

**Comment by Fish-Git** [comment]
Original user is unresponsive. Closing as Invalid (User error).
