### ISSUE TITLE
Locks on DASDs and external DASD utilities: relax read access locking.

### ISSUE THREAD

**Issue by marcoxa** [SDL-Hercules-390/hyperion#355]
Hi

Hercules locks the DASDs listed in its configuration file with both a write and a read lock.  The write lock is justified.  The read lock could (I am arguing "should") be relaxed.

In this way, some of the external utilities could still work while Hercules is running (e.g., DASDLS).

Thanks

Marco

**Comment by mcisho** [comment]
This is a Windows problem, dasdls works fine while Hercules is running on Fedora Linux.

Ian

**Comment by Fish-Git** [comment]
Fixed by commit cee323ba234487574ff2fc90e724181e3aa3b38b.

Closing.
