### ISSUE TITLE
IEA304W SYSTEM WAIT STATE CODE 80009064 DURING IEAVNPDC INITIALIZATION

### ISSUE THREAD

**Issue by noxysj** [SDL-Hercules-390/hyperion#361]
Hello, I'm getting this wait state when trying to load **z/OS 1.7**:

```
IEA196I CONSOL00 SYSCONS: MSCOPE IGNORED. REASON=4                    
IEA191I CONSOLE 0C60 SELECTED AS MASTER CONSOLE.                      
IEE712I SET CNGRP PROCESSING COMPLETE                                 
IEA549I SYSTEM CONSOLE FUNCTIONS AVAILABLE                            
        SYSTEM CONSOLE NAME ASSIGNED CS01                             
IEA304W SYSTEM WAIT STATE CODE 80009064 DURING IEAVNPDC INITIALIZATION
```

I'm using this new version for the first time today:
```
HHC01413I Hercules version 4.3.0.10296-SDL-ga4db8213 (4.3.0.10296) 
```

I was using this fine before on the older Hercules V3.

```
HHC00801I Processor CP00: Translation-specification exception code 0012 ilc 4
HHC02324I CP00: PSW=0704400080000000 00000000059482E2 INST=98EF9000     LM    14,15,0(9)             load_multiple
HHC02326I CP00: V:0000000000FD9760:K:06=7FF8D3E0 00000120 00000000 00000000  "8L\............
HHC02269I CP00: R0=000000007FFCEC0C R1=0000000000000000
HHC02269I CP00: R2=000000007FF845DC R3=000000007FFCE9E8
HHC02269I CP00: R4=00000000009FDD00 R5=0000000000F4E680
HHC02269I CP00: R6=000000007FFCF027 R7=0000000000FD9490
HHC02269I CP00: R6=000000007FFCF027 R7=0000000000FD9490
HHC02269I CP00: R8=0000000000FD9760 R9=0000000000FD9760
HHC02269I CP00: RA=0000000000FD2270 RB=000000000594C6B7
HHC02269I CP00: RC=000000000594B6B8 RD=000000007FFCE028
HHC02269I CP00: RE=00000000859425B0 RF=0000000000000000
HHC02271I CP00: C0=00000001DF00EE40 C1=000000007FF58003
HHC02271I CP00: C2=000000006981CE40 C3=000000018040000A
HHC02271I CP00: C4=000000000000000A C5=000000007FAEA280
HHC02271I CP00: C6=00000000FE000000 C7=000000007FF58003
HHC02271I CP00: C8=0000000000030000 C9=0000000000000000
HHC02271I CP00: CA=0000000000000000 CB=0000000000000000
HHC02271I CP00: CC=000000006CECA84F CD=000000007FF58003
HHC02271I CP00: CE=00000000DF8FC806 CF=000000007FFA6260
HHC02272I CP00: AR00=009FD0C8 AR01=00000000 AR02=00000000 AR03=00000000
HHC02272I CP00: AR04=00000000 AR05=00000000 AR06=00000000 AR07=00000000
HHC02272I CP00: AR08=00000000 AR09=01810036 AR10=00000000 AR11=00000000
HHC02272I CP00: AR12=00000000 AR13=00000000 AR14=00000000 AR15=00000C05
HHC00809I Processor CP00: disabled wait state 0002000080000000 0000000000009064
```

I've tried a number of things that I found on google. Changing the order of some of the config statements to no avail.

```
  PGMPRDOS  LICENSED		# Allow Hercules to run licensed code.
  ARCHLVL  z/Arch               # Architecture mode S/370, ESA/390 or z/Arch

#  ALRF      DISABLE             # ASN-and-LX-Reuse facility
  FACILITY DISABLE 006_ASN_LX_REUSE # Replaces line above thats depricated.
  FACILITY ENABLE 044_PFPO

  MAXCPU    4                   # Maximum number of CPUs
  NUMCPU    4                   # Number of CPUs

#  CPUSERIAL 143436              # CPU serial number
#  CPUMODEL  2064                # CPU model number
#  MODEL     109                 # STSI returned model
#  PLANT     ZZ                  # STSI returned plant
  MANUFACTURER IBM              # STSI returned manufacturer
  LPARNAME  CS01                # DIAG 204 returned lparname
#  CPUVERID  FD                  # CPU Version Identification
  MAINSIZE  2048                 # Main storage size in megabytes
  XPNDSIZE  0                   # Expanded storage size in megabytes

# NUMVEC    1                   # Number of Vector Processors
#  ECPSVM    NO                  # VM Assist : NO or Level (20 recommended)

#------------------------------------------------------------------------------
#       OS Tailoring
#------------------------------------------------------------------------------

  LOADPARM  278DC2M1            # IPL parameter
  OSTAILOR  z/OS                # OS tailoring
  SYSEPOCH  1900                # Base year for initial TOD clock
# TZOFFSET  0                   # Using UTC (GMT)
```

Hope you can get me going. Thanks in advance,

**Comment by Fish-Git** [comment]
Please upload your **configuration file** _AND_ your **complete logfile** for each of both a successful v3.13 run as well as for the 4.3 failed run (both of which should have a different configuration file and a different logfile obviously), and we'll try to look into the problem. Thank you.

To upload, please see the instructions at the bottom of the GitHub Issues text input box that you are typing into right now:

* https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests

**Comment by noxysj** [comment]
[noxyhercules3.log](https://github.com/SDL-Hercules-390/hyperion/files/5804315/noxyhercules3.log)
[noxyhercules4.log](https://github.com/SDL-Hercules-390/hyperion/files/5804316/noxyhercules4.log)

[hercules3.cnf.txt](https://github.com/SDL-Hercules-390/hyperion/files/5804330/hercules3.cnf.txt)
[hercules4.cnf.txt](https://github.com/SDL-Hercules-390/hyperion/files/5804331/hercules4.cnf.txt)

Hi again thanks very much for the comments. I've attached the logs and config files above. Hopefully you can see them.
Cheers,
Steve

**Comment by Fish-Git** [comment]
> I've attached the logs and config files above.

Thank you. I see nothing in any of your files that might explain the problem you are having.

There was a [recent fix made on Dec. 4th](https://github.com/SDL-Hercules-390/hyperion/commit/7e35ff11043afd16c546246e81aa86df202573c6) that resolved a [Translation-Specification Exception (PIC 12) issue that someone was having on z/VSE 6.2 with Hercules 4.3.0](https://github.com/SDL-Hercules-390/hyperion/issues/338) that might also resolve yours as well.

If you are setup to be able to build Hercules for yourself, you might want to try pulling/cloning current git to see whether that resolves your problem or not. Otherwise, since your problem sounds like it might be due to the problem with our original attempt to fix the issue that was first included in version 4.3, you might consider giving [version 4.2.1](https://github.com/SDL-Hercules-390/hyperion/releases/tag/Release_4.2.1) a try instead.

If [version 4.2.1](https://github.com/SDL-Hercules-390/hyperion/releases/tag/Release_4.2.1) works okay for you, then the bug is likely the same one and you _should_ consider building current git for yourself. Otherwise, if [4.2.1](https://github.com/SDL-Hercules-390/hyperion/releases/tag/Release_4.2.1) works okay for you, then I'm afraid you will have to stick with using it instead until such time as version 4.4 is eventually released (which will likely be a while yet).

Please let us know your results.

Thanks.

**Comment by noxysj** [comment]
Good evening. I have downloaded 4.2.1 and that is working absolutely fine so I can use that for the time being.
I would attempt a build but I'm not sure where to start with cmake and I dont know git either.
Perfect thanks for the support.

**Comment by Fish-Git** [comment]
> I have downloaded 4.2.1 and that is working absolutely fine ...

Fantastic! Thank you for the confirmation.

I am going to close this issue as having already been resolved by commit 7e35ff11043afd16c546246e81aa86df202573c6.

**Comment by ejjeamore** [comment]
Just trying to help those trying to get hyperion working.

I got hercules4.5.0 working with about any files by using old config file from 3.07 and letting 4.5.0 default. With 4.5.0 config was getting disabled wait state. Don't know what parameter specified was giving trouble but tried ASX_REUSE etc and still disabled wait state.
#
# System parameters
#

CPUSERIAL 07346F
CPUMODEL  2096
MAINSIZE  768
XPNDSIZE  0
CNSLPORT  3270
NUMCPU    2
ARCHMODE  ESA/390
ARCHLVL   ESA/390
LOADPARM  ....W1M1
TZOFFSET  +0000
OSTAILOR  ESA/390
PANRATE   1000
MAXDEVT   80
PGMPRDOS  LICENSED

# Card Readers

000C    3505	c:/zos/zzsacard.bin
000D    3525    c:/zos/punch00d.txt ascii

# Line Printers

000E    1403    c:/zos/print00e.txt crlf
#000F    1403    c:/zos/print00f.txt crlf

# TAPE Devices
#030E    3480    c:/zos/hardcopy.log 
02B0     3490     
1000     3490
#1A02    3490
#1A03	3490

# CTC Adapters

0E20    3088    CTCI 192.168.0.5 192.168.0.1

# Display Terminals
0100	3270
#0101    3270
#0102    3270
0108	3270 
010C    3270
0118    3270
0128    3270    


# DASD Devices

**Comment by Fish-Git** [comment]
If you are trying to run z/OS _(Yes?)_, then your config file is all wrong:

> `MAINSIZE  768`

> `ARCHMODE  ESA/390`
> `ARCHLVL   ESA/390`

> `LOADPARM  ....W1M1`

> `OSTAILOR  ESA/390`

> `# DASD Devices`

1. 768MB is likely not enough storage for z/OS. I would suggest at least 2GB (`MAINSIZE 2G` or `MAINSIZE 2048`).

2. z/OS is _not_ an ESA/390 operation system. It is a _z/Architecture_ operating system. Remove your `ARCHMODE` statement _(it is deprecated) and change your `ARCHLVL` statement to z/Arch instead (`ARCHLVL z/Arch`). 

3. Your failed to specify the address of your master catalog device on your `LOADPARM` statement. This is usually your "SYS1" volume. So if your "SYS1" volume is, for example, device 0A83, then you would use `LOADPARM 0A83W1M1` for your LOADPARM.

4. Again, this is z/OS, not OS/390. Your OSTAILOR should be set to Z/OS (`OSTAILOR Z/OS`).

5. Your config file doesn't have any DASD devices defined!

**Comment by ejjeamore** [comment]
Sorry for the confusion
Looks like it was the LOADPARM
LOADPARM 3006W1M1 - gave error and disabled wait state - 4.5.0 cfg had this 
 Processor CP00: Special-operation exception interruption code 0013 ilc 4  CP0
0: PSW=0008000080000612 INST=B2790000     SACF  0(0)                   set_address_space_control 

LOADPARM 3006....        gives vector error but continues to ipl - old 3.07 had this
Processor CP00: Specification exception interruption code 0006 ilc 4
HHC02324I CP00: PSW=0404000080000000 0000000000004B1A INST=B2650000     SVS   0,0                    set_vector_summary
