### ISSUE TITLE
"Crash" on aarch64 Ubuntu 20.04

### ISSUE THREAD

**Issue by rvjansen** [SDL-Hercules-390/hyperion#364]
➜  vm370 <b>./sixpack.sh</b>
<pre>
HHC00100I Thread id 0000ffff83a09430, prio 5, name 'impl_thread' started
HHC00100I Thread id 0000ffff82da51b0, prio 4, name 'logger_thread' started
HHC01413I Hercules version 4.4.9999.0-SDL-g135ac68c (4.4.9999.0)
HHC01414I (C) Copyright 1999-2020 by Roger Bowler, Jan Jaeger, and others
HHC01417I ** The SoftDevLabs version of Hercules **
HHC01415I Build date: Jan 16 2021 at 13:36:36
HHC01417I Built with: GCC 9.3.0
HHC01417I Build type: GNU/Linux aarch64 host architecture build
HHC01417I Modes: S/370 ESA/390 z/Arch
HHC01417I Max CPU Engines: 128
HHC01417I Using   shared libraries
HHC01417I Using   setresuid() for setting privileges
HHC01417I Using   POSIX threads Threading Model
HHC01417I Using   Error-Checking Mutex Locking Model
HHC01417I With    Shared Devices support
HHC01417I With    Dynamic loading support
HHC01417I With    External GUI support
HHC01417I With    IPV6 support
HHC01417I With    HTTP Server support
HHC01417I With    sqrtl support
HHC01417I With    Signal handling
HHC01417I With    Watchdog monitoring
HHC01417I Without CCKD BZIP2 support
HHC01417I Without HET BZIP2 support
HHC01417I With    ZLIB support
HHC01417I With    Regular Expressions support
HHC01417I With    Object REXX support
HHC01417I Without Regina REXX support
HHC01417I With    Automatic Operator support
HHC01417I Without National Language Support
HHC01417I With    CCKD64 Support
HHC01417I With    Transactional-Execution Facility support
HHC01417I With    "Optimized" instructions
HHC01417I Machine dependent assists: cmpxchg1 cmpxchg4 cmpxchg8 cmpxchg16 hatomics=C11
HHC01417I Running on: montague (Linux-5.4.0-1026-raspi aarch64) MP=4
HHC01417I Built with crypto external package version 1.0.0.49-g837705e
HHC01417I Built with decNumber external package version 3.68.0.99-gda66509
HHC01417I Built with SoftFloat external package version 3.5.0.102-g42f2f99
HHC01417I Built with telnet external package version 1.0.0.59-g2aca101
HHC00018I Hercules is running in elevated mode
HHC00150I Crypto module loaded (C) Copyright 2003-2016 by Bernard van der Helm
HHC00151I Activated facility: Message Security Assist
HHC00151I Activated facility: Message Security Assist Extension 1, 2, 3 and 4
<b><i>terminate called after throwing an instance of 'ActivityException'</i>
Aborted</b>
</pre>

This is with VM/370 sixpack on a freshly built Hyperion.

**Comment by Fish-Git** [comment]
This appears to be an issue related to **Object Rexx** (i.e. oorexx) and not Hercules per se:

* https://sourceforge.net/p/oorexx/mailman/oorexx-devel/thread/5d74c5721001241409j3052bf24meec52bcd635b1bcf%40mail.gmail.com/#msg24424766

I seem to remember reading something about the daemon somewhere in the rexx documentation. Are you ensuring the rexx daemon is always started _before_ attempting to start Hercules? That is to say, does the problem go away (not occur) if you, for example, enter the command `rexx -v` _before_ issuing your `./sixpack.sh` command?

I myself have the following in my `.bash_profile` (or whatever it's called in your distro):

```
# To prevent problems with Hercules Rexx loading/starting
# the first time Hercules is started, we need to start the
# rexx daemon first, which is started automatically the
# first time any rexx command is issued.

rexx -v > /dev/null
```

In this way I am sure the daemon is _always_ started whenever I logon. If you don't want to add it to your .bash_profile (.profile?), then maybe you can add it to your `sixpack.sh` script somewhere?

Please let me know whether the above helps you or not.

Thanks.

**Comment by rvjansen** [comment]
Thanks, interesting. Indeed ooRexx is on that system, but I am not aware I compiled Hercules with ooRexx support. The way we start that daemon changed a lot since that error report by Mark Miesfeld (rest in peace, Mark). I will try at the earliest opportunity.

**Comment by Fish-Git** [comment]
> ... but I am not aware I compiled Hercules with ooRexx support.

Refer to your startup messages:

<pre>
HHC01417I With    Object REXX support
HHC01417I Without Regina REXX support
</pre>

If ooRexx (or Regina Rexx) is installed on your system, Hercules will get built with support for it by default. If you _don't_ want to have Rexx support built into Hercules, then you need to tell it that in your `./configure` command:

```
./configure ... --disable-object-rexx  --disable-regina-rexx ...
```

Of course, if rexx is not installed on your system then, by default, Hercules support for it will obviously _not_ be included for it whenever you build Hercules.

**Comment by wrljet** [comment]
Is this on a Raspberry Pi 4B?

May I ask what version of ooRexx you have installed, and how it got there (package, or built from source)?

Bill

**Comment by rvjansen** [comment]
Hi Bill, yes it is. Built from source, version 5.0.0 (Beta). I made a package for someone. I also have Regina and BREXX on that same Raspi, on Ubuntu 20.04 so 64 bits, not all in standard locations. So I am going to build Hercules without Rexx support for the moment to see if the error goes away.

**Comment by wrljet** [comment]
René,

That *should* work.  At least it works for me.

Why don't you try my _under-construction_ Hercules Helper project to do the build and see if it helps you.

`https://github.com/wrljet/hercules-helper.git`

It will do a complete full build of SDL-Hercules-390, along with installing the required packages.

Since REXX is required for the tests after building, it also will build Regina Rexx, if it does not find
an existing Regina or ooRexx.   (Not sure how it will react to BREXX, etc)

I just installed a fresh Ubuntu 20.10 on the Pi 4, and ran through the entire process, first building
ooRexx 5.0 from source.  It all worked.  (well, I didn't actually IPL an OS under it though)

Instructions are in the README on the GitHub page.  And I'm here for support.

Bill

**Comment by rvjansen** [comment]
Hi Bill and Fish,
it works. For googlers, I still needed bzip, because some of my disks were not recognized:
sudo apt install libbz2-dev
and my .configure is now as follows:
./configure --enable-extpkgs=/home/rvjansen/apps/extpkgs/. --disable-object-rexx --disable-regina-rexx --enable-cckd-bzip2 --enable-het-bzip2

I saw it builds a hRexx.o now.

Bill, thanks for your offer, next I will do the 8M Raspi, which runs much more important stuff, after a week or so acceptance testing on the 4M Raspi, then I will try your helper!

best regards,

**Comment by wrljet** [comment]
Cool.  I look forward to your feedback to improve it.

BTW, it installs both zip file libraries. :-)
