### ISSUE TITLE
SUBMITTING PROBLEM REPORTS

### ISSUE THREAD

**Issue by Fish-Git** [SDL-Hercules-390/hyperion#373]
# How to Ask for Help
## Introduction

When filing a problem report it is never harmful to provide _more_ information than needed, but is _almost always harmful to not provide enough information_.

If your problem report does not provide enough information many people will not bother to even respond as they consider it a waste of time to ask for information which **_should_** have been provided in the original problem report.

Help others to help _you!_

_Try to provide as much information as possible when filing problem reports!_

----

## Details

_**[Before You Ask](http://www.catb.org/~esr/faqs/smart-questions.html#before):**_

1.  If your problem is networking related, and are using a third party product to provide needed Hercules functionality _(such as SDL's "[CTCI-WIN](http://www.softdevlabs.com/ctci-win)" product)_, have you consulted the provided "Help" file that comes with the product? For example, did you perform a multi-directional Ping Test as part of your troubleshooting? If you did, you should probably provide that output in your problem report.

_**[Be precise and informative about your problem](http://www.catb.org/~esr/faqs/smart-questions.html#beprecise):**_

2.  **The _specific_ version of Hercules you are using** (i.e. the output of the Hercules `version` command).</br></br>The reported version string should look like this:<pre>     <b>HHC01413I</b> Hercules version 4.3.0.10296-SDL-<b>ga4db8213</b> (4.3.0.10296)</pre>The **`ga4db8213`** portion of the version string is the most important. If your version string only displays a generic "4.3.0.0" version string, then your Hercules was built wrong and **[you should rebuild it](https://sdl-hercules-390.github.io/html/hercinst.html#install)**.

3.  Your _complete_ Hercules configuration file.

4.  **Your _complete_ Hercules log file, from beginning to end!** &nbsp; _(VERY important!)_

5.  What guest operating system and release level are you running under Hercules? VM? MVS? z/VM? z/OS? Other? Which version?

6. Your _complete_ `TCPIP.PROFILE` dataset if your problem is networking related, as well as any other dataset members associated with your guest's network configuration.

7. Which host operating system platform are you using? (Windows? Linux? Mac?) Which version is it? Windows 10? Windows 11? CentOS 6.8? Kubuntu 21.10? Is it 32-bit or 64-bit?

8.  **Is the problem consistent and repeatable? What procedure can others use to try and re-create your problem?**

9.  Is there anything else you can think of that might be related to your problem? Do you have any unusual or related software installed on your host, such as VPN software? If so, which product  and which version? And how do you have it configured? 

10. Have you made any recent configuration changes or installed any system updates recently on your host?
----

## Closing Remarks

If you provide a high quality problem report containing the information that others actually  _need_ in order to be _able_ to help you, you will stand a much better chance of actually obtaining the help you need!

_**Remember**: the people you are asking are not psychic. They don't know the details of your problem. Only you know that._

If you provide them with the information they actually _need_ to help you, they might actually be willing and _able_ to help you.

Otherwise you're just wasting their time.
___

**Comment by marXtevens** [comment]
VMFPLC2 documentation is unclear for a parameter in the control file.
in the Hercules_Operations_and_Utilities.pdf on Page 96.

[Hercules_Operations_and_Utilities.pdf](https://github.com/SDL-Hercules-390/hyperion/files/6572905/Hercules_Operations_and_Utilities.pdf)

5.23.4 Control File
Each line of the control file has the following format:

filename filetype filemode recfm lrecl type tapefile

and tapefile is defined as:

tapefile
The tape file is created or read as a HET (Hercules Emulated Tape) format. The
DUMP function creates a file, while SCAN and LOAD functions only read the file.

Actually, this field identifies the path to the file to be dumped such that:

[xmas@vm370dev src]$ cat ../src_list 
ASASSIGN MEMO A1 F 80 T ASASSIGN
...
[xmas@vm370dev src]$ vmfplc2 -u dump ../src_list `date +%F`.ASSIST.het
HHC02499I Hercules utility vmfplc2 - VM/CMS VMFPLC2/TAPE Utility - version 4.4.9999.0-SDL
HHC01414I (C) Copyright 1999-2021 by Roger Bowler, Jan Jaeger, and others
HHC01417I ** The SoftDevLabs version of Hercules **
HHC01415I Build date: Mar  5 2021 at 16:26:42
HHC02637I Output tape format set to VMFPLC2
HHC02625I DUMPING...
HHC02626I >>> ASASSIGN MEMO A1 F 80 T ASASSIGN
HHC02628W lrecl 80 less than 81; one or more records truncated
HHC00007I Previous message from function 'dump_text_file' at vmfplc2.c(1001)
...

resulting in a .het tape 
[xmas@vm370dev src]$ vmfplc2 scan ~/Hercules/VM370/CE.V1.R1.1/tapes/2021-05-31.ASSIST.het
HHC02499I Hercules utility vmfplc2 - VM/CMS VMFPLC2/TAPE Utility - version 4.4.9999.0-SDL
HHC01414I (C) Copyright 1999-2021 by Roger Bowler, Jan Jaeger, and others
HHC01417I ** The SoftDevLabs version of Hercules **
HHC01415I Build date: Mar  5 2021 at 16:26:42
HHC02637I Input tape format set to VMFPLC2
HHC02625I SCANNING...
HHC02626I >>> ASASSIGN MEMO     A1 F 80    2098-03-03 22:18:22 recs 13086 blks 1309
...

So, if you will allow:

filename filetype filemode recfm lrecl type inputfile

inputfile
The inputfile is the path to the file to be copied to the .het file identified as outputfile in the 5.23.2 Syntax.

Or something like that. Do you need additional information?

[vmfplc2_example.txt](https://github.com/SDL-Hercules-390/hyperion/files/6572881/vmfplc2_example.txt)
[Hercules_version.log](https://github.com/SDL-Hercules-390/hyperion/files/6572897/Hercules_version.log)

 ... Mark S.

**Comment by Fish-Git** [comment]
I can't remember whether closing this issue unpins it or not, but I guess since _technically_ it's not a bug/problem that needs to be resolved, it should probably be closed instead of left open. If closing it prevents it from being pinned however, I'll re-open it again. &nbsp; ... &nbsp; Here goes!
