### ISSUE TITLE
DASDLOAD Utility using compression option does not finish writing the output file

### ISSUE THREAD

**Issue by gcb4** [SDL-Hercules-390/hyperion#374]
Running on Windows 10 64-bit, the DASDLOAD utility from version 4.2.0 onwards does not appear to finish writing the output file. Writer and Garbage Collection threads are started, but have not completed by the time the DASDLOAD utility terminates.

Attached is a sample DASDLOAD configuration file and the DASDLOAD output from version 4.3.0.10296-SDL-ga4db8213. Also attached for comparison is the DASDLOAD output from version 4.1.0.9426-SDL-g42b533fa.

The command used to produce the output is as follows:
```
dasdload -z -lfs C:\Hercules\config\dasdload.cnf.txt C:\Hercules\devices\DASDXX.cckd 2
```

* [dasdload.cnf.txt](https://github.com/SDL-Hercules-390/hyperion/files/6064262/dasdload.cnf.txt)
* [Dasdload output - Herc 4.3.0.txt](https://github.com/SDL-Hercules-390/hyperion/files/6064265/Dasdload.output.-.Herc.4.3.0.txt)
* [Dasdload output - Herc 4.1.0.txt](https://github.com/SDL-Hercules-390/hyperion/files/6064266/Dasdload.output.-.Herc.4.1.0.txt)

Gordon

**Comment by gcb4** [comment]
Changing the %h to %u in the following line in cckddasd.c (line 5399) appears to resolve the issue?

 CCKD_TRACE( "gcperc move trk %d at pos 0x%16.16"PRIx64" len %h",
 
 Gordon

**Comment by Fish-Git** [comment]
Close by commit 785aef5435f5030b1d108bf0a593cf622ea3d2e5.

**Comment by Fish-Git** [comment]
THANK YOU, Gordon!!
