### ISSUE TITLE
Deadlock

### ISSUE THREAD

**Issue by edtgek** [SDL-Hercules-390/hyperion#383]
Hi.

I have an issue with deadlock between MVS systems.

In a virtual Linux system (running Debian) I have 2 Hercules system running MVS and then I have a third Hercules system that is owner of all disks shared by the MVS systems.

I am currently using Hercules version **ge520d262**.

Before currently running Hercules version, I was using Hercules version gae8babc9. In earlier versions of Hercules (including gae8babc9) I have not seen this deadlock, but in current version I have seen it a couple of times.

When the deadlock appear the Hercules owning all disks die completely. The Hercules system running MVS stop running but are still up.

I attach log files from all 3 Hercules systems and I also attach the configuration files from the 3 systems.

I also attach the syslog file from the host Debian system, as there are 2 kernel messages 1 second after the deadlock in disk owning Hercules system.

-- 
Goran
(goran@ekloef.se)

**warm.SDS.cnf** is configuration file of disk owning system.
**warm-G001.cnf** and **warm-G002.cnf** are configuration files of the MVS systems.

* [warm-SDS.cnf.txt](https://github.com/SDL-Hercules-390/hyperion/files/6212592/warm-SDS.cnf.txt)
* [warm-G001.cnf.txt](https://github.com/SDL-Hercules-390/hyperion/files/6212589/warm-G001.cnf.txt)
* [warm-G002.cnf.txt](https://github.com/SDL-Hercules-390/hyperion/files/6212591/warm-G002.cnf.txt)

**hercgek.txt** is log file from disk owning Hercules system.
**hercg1.txt** and **hercg2.txt** are log files from MVS Hercules systems.

* [hercgek.txt](https://github.com/SDL-Hercules-390/hyperion/files/6212582/hercgek.txt)
* [hercg1.txt](https://github.com/SDL-Hercules-390/hyperion/files/6212576/hercg1.txt)
* [hercg2.txt](https://github.com/SDL-Hercules-390/hyperion/files/6212580/hercg2.txt)

**syslog.txt** is the host Debian syslog file. 

* [syslog.txt](https://github.com/SDL-Hercules-390/hyperion/files/6212575/syslog.txt)

**Comment by Fish-Git** [comment]
Hi Goran!

I apologize for the problem you are having. The deadlock you describe is actually a false alarm.

The problem you are experiencing is being caused by a bug that was only just **[recently identified and fixed](https://github.com/SDL-Hercules-390/hyperion/issues/371)** two weeks ago on **March 12, 2021**:

* **[Fix false alarm bug in deadlock detection logic](https://github.com/SDL-Hercules-390/hyperion/commit/d83b36e138673dc864dfffe51983f8495b1ca159)**

Please do a `git pull` to refresh your local Hercules repository clone (or else delete it and then do a fresh `git clone` again) to pick up the fix, and then rebuild your Hercules.

**Comment by Fish-Git** [comment]
**P.S.** &nbsp;Your log files are incomplete. They are all missing important startup information. You are obviously not starting Hercules properly to ensure your logfiles are always complete.

Please see:

* [**Command line arguments**](https://sdl-hercules-390.github.io/html/hercinst.html#arguments)

for the description of the new Hercules `-o` _logfile_ &nbsp;(or `--output=` (or `--logfile=`)) command line argument that you should _always_ be using. This ensures your logfiles will always contain _all_ messages that Hercules issues, from the moment of startup _(which is when the critically important **version and startup messages** are issued)._

The logfiles you provided do not contain any version information in them, and thus, under normal circumstances, would be of limited use.
