### ISSUE TITLE
CMakeLists.txt missing

### ISSUE THREAD

**Issue by BerndHKG** [SDL-Hercules-390/hyperion#384]
Hello ladies and gentlemen,

After watching too many mainframe related videos on YouTube, I remembered that I have a Raspberry Pi 3 somewhere and thought that it'd be worth a try to install Hercules/Hyperion on it. So I followed the **"[QUICK START: Build Hercules Using CMake](https://hercules-390.github.io/html/CMake/index.html#quickstart)"** This is how far I got (you probably already guessed it from the thread topic):

```
[hercules@pi3 ~/source/hercules]$ git clone https://github.com/SDL-Hercules-390/hyperion.git .
Cloning into '.'...
remote: Enumerating objects: 219, done.
remote: Counting objects: 100% (219/219), done.
remote: Compressing objects: 100% (158/158), done.
remote: Total 54570 (delta 113), reused 131 (delta 61), pack-reused 54351
Receiving objects: 100% (54570/54570), 53.60 MiB | 3.78 MiB/s, done.
Resolving deltas: 100% (42757/42757), done.
Updating files: 100% (1146/1146), done.
[hercules@pi3 ~/source/hercules]$ git branch
* master
[hercules@pi3 ~/source/hercules]$ mkdir build
[hercules@pi3 ~/source/hercules]$ cd build
[hercules@pi3 ~/source/hercules/build]$ cmake -S .. -B .
CMake Error: The source directory "/home/hercules/source/hercules" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
```

I checked and I could not find the file anywhere. Any ideas where I can find it?

I am running FreeBSD 12.2 on the Pi3 but I think at this stage it doesn't look like a OS specific issue. 

Best regards
Bernd

**Comment by Fish-Git** [comment]
Hi Bernd!

You are either trying to build the wrong Hercules, or else you have posted your question/problem (GitHub Issue) in the wrong place.

I suspect it is probably the former: you're following the wrong build instructions.

Hyperion Hercules is not the same as SDL Hyperion Hercules. They are completely different products:

* [Hercules **4.0** (Hyperion)](https://hercules-390.github.io/html/)
* [_**SDL**_ Hercules **4.x** Hyperion](https://sdl-hercules-390.github.io/html/)

Notice the URLs of each of the above web pages:

<pre>
 https://hercules-390.github.io/html/
 https://<b>sdl-</b>hercules-390.github.io/html/
</pre>

The _original_ Hercules 4.0 Hyperion is pretty much a dead product. It is no longer being developed/maintained.

The _SoftDevLabs (**SDL**)_ version of _Hercules **4.x** Hyperion_ however, is currently the _only_ actively maintained version of the Hercules emulator known to be in existence (or so it seems anyway):

* https://github.com/SDL-Hercules-390/hyperion/blob/master/README.md

> This version of Hercules 4.x Hyperion is a SoftDevLabs maintained version of the Hercules emulator containing fixes made by myself and others for bugs that may still exist in the original hercules-390 version of Hercules 4.0 Hyperion, as well as enhancements and improvements to the overall functionality above and beyond what is provided by the original hercules-390 version of Hercules.

The build instructions for SDL Hyperion Hercules can be found by following the "[**Hercules Installation and Operation**](https://sdl-hercules-390.github.io/html/hercinst.html)" link on our main web page. It's build procedure is completely different. The building of Hercules itself does not use CMake at all.

The building of the _External Packages_ that Hercules itself _needs_ do use CMake _(refer to step <span>#</span>4 of the build instructions)_, but the actual building of Hercules itself still uses the old tried and true "autoconf" technique (i.e. ./configure and make).

Hope that helps!

**Comment by BerndHKG** [comment]
Hi Fish!

That helped a lot! Thank you for pointing me the right way :-)

Best regards
Bernd

**Comment by Fish-Git** [comment]
You're very welcome. &nbsp;`:)`

Closing issue.
