### ISSUE TITLE
Unclear VMFPLC2  control file parameter documentation

### ISSUE THREAD

**Issue by Fish-Git** [SDL-Hercules-390/hyperion#395]
_**EDIT:** This issue is being moved from its original location (which was in the wrong place) to here instead, where it properly belongs. It was originally posted by [**marXtevens**](https://github.com/marXtevens), not by me. (Fish)_
_________________________________________________________________________________________
VMFPLC2 documentation is unclear for a parameter in the control file.

On page 96 of the "[**Hercules - Operations and Utilities Guide**](http://hercdoc.glanzmann.org/V400/HerculesOperationsandUtilities.pdf)" PDF documentation manual _(https://sdl-hercules-390.github.io/html#docs)_ it says:
&nbsp;
### _5.23.4 Control File_

_Each line of the control file has the following format:_
<pre>
<i>filename  filetype  filemode  recfm  lrecl  type  tapefile</i>
</pre>
&nbsp;
and _`tapefile`_ is defined as:
&nbsp;
<dl>
<dt><b><i>tapefile</i></b>
<dd><i>The tape file is created or read as a HET (Hercules Emulated Tape) format. The
DUMP function creates a file, while SCAN and LOAD functions only read the file.</i>
</dl>

&nbsp;
This field actually identifies the _path_ to the file to be dumped such that:

<pre>
[xmas@vm370dev src]$ <b>cat ../src_list </b>
ASASSIGN MEMO A1 F 80 T ASASSIGN
...
[xmas@vm370dev src]$ <b>vmfplc2 -u dump ../src_list `date +%F`.ASSIST.het</b>
HHC02499I Hercules utility vmfplc2 - VM/CMS VMFPLC2/TAPE Utility - version 4.4.9999.0-SDL
HHC01414I (C) Copyright 1999-2021 by Roger Bowler, Jan Jaeger, and others
HHC01417I ** The SoftDevLabs version of Hercules **
HHC01415I Build date: Mar  5 2021 at 16:26:42
HHC02637I Output tape format set to VMFPLC2
HHC02625I DUMPING...
HHC02626I >>> ASASSIGN MEMO A1 F 80 T ASASSIGN
HHC02628W lrecl 80 less than 81; one or more records truncated
HHC00007I Previous message from function 'dump_text_file' at vmfplc2.c(1001)
...
</pre>

resulting in a .het tape:

<pre>
[xmas@vm370dev src]$ <b>vmfplc2 scan ~/Hercules/VM370/CE.V1.R1.1/tapes/2021-05-31.ASSIST.het</b>
HHC02499I Hercules utility vmfplc2 - VM/CMS VMFPLC2/TAPE Utility - version 4.4.9999.0-SDL
HHC01414I (C) Copyright 1999-2021 by Roger Bowler, Jan Jaeger, and others
HHC01417I ** The SoftDevLabs version of Hercules **
HHC01415I Build date: Mar  5 2021 at 16:26:42
HHC02637I Input tape format set to VMFPLC2
HHC02625I SCANNING...
HHC02626I >>> ASASSIGN MEMO     A1 F 80    2098-03-03 22:18:22 recs 13086 blks 1309
...
</pre>

So, if you will allow:

<pre>
<i>filename  filetype  filemode  recfm  lrecl  type  <b>inputfile</b></i>
</pre>

<dl>
<dt><b><i>inputfile</i></b>
<dd><i>The inputfile is the path to the file to be copied to the .het file identified as outputfile in the 5.23.2 Syntax.</i>
</dl>

Or something like that.

Do you need additional information?

* [vmfplc2_example.txt](https://github.com/SDL-Hercules-390/hyperion/files/6572881/vmfplc2_example.txt)
* [Hercules_version.log](https://github.com/SDL-Hercules-390/hyperion/files/6572897/Hercules_version.log)

 ... Mark S.

**Comment by Fish-Git** [comment]
In the [**PDF manuals**](https://sdl-hercules-390.github.io/html#docs) section of our main web page, it states:

* _"The below PDF manuals **are for the original 4.0 version of Hercules Hyperion, not for this SoftDevLabs version.** At the moment however they should still be reasonably accurate. Over time as more and more changes are made to the SDL version however, they might not be. The official web documentation however should always be accurate and considered as authoritative."_ &nbsp; (emphasis added)

</br>Additionally, on the cover page of the manual itself:

[**![Hercules - Operations and Utilities Guide (cover)](https://user-images.githubusercontent.com/1486786/120277728-46327a80-c269-11eb-80a3-c7b8023c635c.jpg)**](http://hercdoc.glanzmann.org/V400/HerculesOperationsandUtilities.pdf)

it identifies the manual as being a _**Draft**_ which was created on _November **2015**_ and is no longer being updated or maintained.  _(You should consider all of the PDF manuals to be largely historical in nature and **not** authoritative.)_

Hercules's current VMFPLC2 utility was greatly enhanced by myself in _February_ of _**2019**_, as noted in the "**[History](https://github.com/SDL-Hercules-390/hyperion/blob/master/readme/README.VMFPLC2.md#History)**" section of our [**VMFPLC2 README**](https://github.com/SDL-Hercules-390/hyperion/blob/master/readme/README.VMFPLC2.md) document **`(*)`**:

> _**History**_
>
> &nbsp; &nbsp; &nbsp; _**2019-02-29**  Program completely rewritten by "Fish" (David B. Trout) ..._

</br>What this means to you is, the PDF manual you are referring to is _not current_ and as a result, does _**not**_ accurately document how the utility behaves today. As our main web page says: "The official web documentation ... should be considered as authoritative."

I do however apologize for not having a hyperlink on our main web page pointing to our main README document which in retrospect may well have prevented this unfortunate unintended miscommunication leading to your reporting of this non-existent documentation error.

I'll try to remember to correct that as soon as I get a chance.

Will wait a day or three before closing this issue as resolved.

_______
**`(*)`** _Reachable from the link in the "**Features and Operation**" section of our [**primary README**](https://github.com/SDL-Hercules-390/hyperion/blob/master/README.md)._

**Comment by marXtevens** [comment]
Thank you, Fish. Please feel free to close at your convenience.

 ... Mark S.
"Read ALL the documentation, FIRST." ;-)

**Comment by Fish-Git** [comment]
Fixed! Closing.
