### ISSUE TITLE
Compile error on  Debian 4.19 x86_64 GNU/Linux

### ISSUE THREAD

**Issue by a323870** [SDL-Hercules-390/hyperion#410]
Compiling the latest version of hyperion I have an error on ltdl.c
gcc version 8.3.0.

Tanks.

  CC       pttrace.lo
  CC       version.lo
  CC       ltdl.lo
ltdl.c: In function ‘rpl_memcpy’:
ltdl.c:412:11: warning: dereferencing ‘void *’ pointer
       dest[i] = src[i];
           ^
ltdl.c:412:20: warning: dereferencing ‘void *’ pointer
       dest[i] = src[i];
                    ^
ltdl.c:412:15: error: invalid use of void expression
       dest[i] = src[i];
               ^
ltdl.c: In function ‘rpl_memmove’:
ltdl.c:437:9: warning: dereferencing ‘void *’ pointer
     dest[i] = src[i];
         ^
ltdl.c:437:18: warning: dereferencing ‘void *’ pointer
     dest[i] = src[i];
                  ^
**ltdl.c:437:13: error: invalid use of void expression
     dest[i] = src[i];**
             ^
ltdl.c:440:25: warning: comparison of unsigned expression >= 0 is always true [-Wtype-limits]
     for (i = size -1; i >= 0; --i)
                         ^~
ltdl.c:442:9: warning: dereferencing ‘void *’ pointer
     dest[i] = src[i];
         ^
ltdl.c:442:18: warning: dereferencing ‘void *’ pointer
     dest[i] = src[i];
                  ^
**ltdl.c:442:13: error: invalid use of void expression
     dest[i] = src[i];
             ^
ltdl.c: At top level:
ltdl.c:877:39: error: ‘LTDL_OBJDIR’ undeclared here (not in a function); did you mean ‘LT_OBJDIR’?
 static  const char  objdir[]        = LTDL_OBJDIR;
                                       ^~~~~~~~~~~
                                       LT_OBJDIR**
ltdl.c: In function ‘find_file_callback’:
ltdl.c:364:21: warning: initialization discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
#define strrchr rpl_strrchr
                     ^~~~~~~~~~~
ltdl.c:2761:22: note: in expansion of macro ‘strrchr’
       char *dirend = strrchr (filename, '/');
                      ^~~~~~~
ltdl.c: In function ‘try_dlopen’:
ltdl.c:3110:13: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   base_name = strrchr (canonical, '/');
             ^
ltdl.c:3163:13: warning: implicit declaration of function ‘isalnum’ [-Wimplicit-function-declaration]
         if (isalnum ((int)(base_name[i])))
             ^~~~~~~
ltdl.c:3305:28: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
           && (last_libname = strrchr (dlname, ' ')) != 0)
                            ^
ltdl.c: In function ‘lt_dlopenext’:
ltdl.c:3483:7: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   ext = strrchr (filename, '.');
       ^
At top level:
ltdl.c:422:19: warning: ‘rpl_memmove’ defined but not used [-Wunused-function]
#define memmove rpl_memmove
                   ^~~~~~~~~~~
ltdl.c:427:1: note: in expansion of macro ‘memmove’
 memmove (dest, src, size)
 ^~~~~~~
ltdl.c:398:20: warning: ‘rpl_memcpy’ defined but not used [-Wunused-function]
#define memcpy rpl_memcpy
                    ^~~~~~~~~~
ltdl.c:403:1: note: in expansion of macro ‘memcpy’
 memcpy (dest, src, size)
 ^~~~~~
make[2]: *** [Makefile:2518: ltdl.lo] Error 1

**Comment by wrljet** [comment]
You probably just need the `libtool` package.

I'm working on updating the build instructions and automated detection, to match the current code.

See this comment for the list of required packages:

https://github.com/SDL-Hercules-390/hyperion/issues/405#issuecomment-889951960

Bill

**Comment by a323870** [comment]
Tanks. 
Install package libtools resolve the problem.

**Comment by Fish-Git** [comment]
Bill (@wrljet),

Have you been able to determine the answer to my previous question/concern yet?

* https://github.com/SDL-Hercules-390/hyperion/issues/410#issuecomment-906653785

Just asking! I don't want you to feel pressured/rushed or anything! I'm just incredibly curious/interested/concerned is all.

Thanks.

**Comment by wrljet** [comment]
Fish,

Yes, I have.  The answer is yes, we don't need (or want) those files.
I have modifications here that I've been testing on various systems.  11 systems so far.

A bit more work is needed on the autoconf stuff, though.

Bill

**Comment by wrljet** [comment]
The libtool/libltdl changes are in commit https://github.com/SDL-Hercules-390/hyperion/commit/929c9008b4cb39e40a693f30fe705d755ada5518
