### ISSUE TITLE
Abend RUN003 on zVM 5.3 or older

### ISSUE THREAD

**Issue by Juergen-Git** [SDL-Hercules-390/hyperion#413]
Under z/VM 5.3 or older, CP throws a soft `RUN003`, when a VM tries to IPL CMS. The problem occurs regardless whether CMS is IPLed using a named saved system or from the 190 minidisk.

**Comment by Fish-Git** [comment]
This is a shot in the dark, but based on the description of `RUN003`:

> _**RUN003**_
> 
> _**Explanation**_
> (soft) An incorrect or unsupported interception code
> was found in the start interpretive execution state
> descriptor.
> 
> _**User response**_
> Examine the internal trace table and storage dump to
> determine why the interception event code
> (VMDICODE) is set with an incorrect code.

could you give the following patch a try to see whether it helps any or not?

```diff
--- old/sie.c
+++ new/sie.c
@@ -620,7 +620,7 @@
 
     if (0
         || (U64)fld > regs->mainlim /* (beyond end of main storage?)  */
-        || (fld & ~0x7ffffff8)      /* (above 2GB or not DW aligned?) */
+//        || (fld & ~0x7ffffff8)      /* (above 2GB or not DW aligned?) */
     )
     {
         /* ZZ: FIXME
@@ -630,7 +630,8 @@
         return;
     }
 
-    if (fld)
+//    if (fld)
+    if ((fld &= 0x7ffffff8))
     {
         GUESTREGS->sie_fld = true;
 
```

I would give it a try myself but I no longer have z/VM 5.3, and have lost the URL where I originally downloaded it from (directly from IBM as I recall).

The above reverts a change I made in the handling of the State Block `fld` field.

Previously, Jan was doing this:

```C
        if(fld > regs->mainlim)
        {
//          SIE_SET_VI(SIE_VI_WHO_CPU, SIE_VI_WHEN_SIENT,
// ZZ: FIXME           SIE_VI_WHY_??ADR, GUESTREGS);
            STATEBK->c = SIE_C_VALIDITY;
            return;
        }

        if(fld & 0x7ffffff8)
        {
            facility_mask = &(regs->mainstor[fld]);
```

which did not seem right to me. Why mask `fld` with `0x7ffffff8` in the `if` statement to check whether the field is (presumably) NULL/empty, but then go ahead and use the _unmasked_ value in the very next statement?

I'm guessing that that maybe the bits being masked are simply supposed to be _ignored_, not reserved, and my bad change of erroneously treating them as being reserved is what may have caused an invalid validity intercept value to get set (or more correctly, caused a _valid_ validity intercept code to _NOT_ be set!).

_(me: fingers crossed)_

**Comment by Juergen-Git** [comment]
I expected something in this direction too, at first sight. However, the problem is apparently elsewhere: Everything works fine up to commit "cosmetic: remove #include 10673a41699411bf79d225e534370b9488ef110e". The problem starts occuring from commit Fix "skey handling part 6 of 6 134e977f7d046eaf217074c88220722fc0a56a35" onward (I didn't test the part 1...5 of 6 commits, so in fact the culprit is one of this whole series).

That whole skey related series of commits is well after those two that are directly SIE related, which is why changing anything with those SIE commits will probably not solve the problem. Trying your patch didn't resolve the problem, which seems to confirm my conclusion. So, we probably have to dig into those skey commits.

Here a short VMDUMPTL session showing what's going on:

`z/VM Version 5 Release 3.0, service level 0801 (CP 64-BIT)
Generated at 04/28/08 19:27:44.000000, IPLd at 08/15/21 09:48:00.266374
Date 08/15/21 Time 09:48:11.199819

CPUID = FD110111 20970000

CPU address is 0001    Prefix register is 00902000   (failing)
CPU address is 0000    Prefix register is 00032000
2DFC17A0 09:48:11  RUN003 Soft Abend svc 04 at HCPRUN+B08 opsw 04040000_002E6118
                   svcilc 0002

Summary of CP exits
      0 Pre-defined exits found
      0 Dynamic exits found
      0 Diagnose exits found

RUN003 (soft) An incorrect or unsupported interception code was found in
       the start interpretive execution state descriptor.

>>> symptom
Symptom Record for Incident DA2A4972 2914BSYM

TOD Clock . . DA2A49722914B060         Date. . . . . 08/15/21
Time Zone . . 02.00.00                 Time. . . . . 09:48:11.199819
CPU model . . 2097                     Base SCP. . . 5741
CPU Serial. . 110111                   NodeID. . . . ZVM1
Dump Name . . PRB00000 DUMP0001 A1     Dump Type . . CPDUMP
Comp ID . . . 5741A05                  Ver/Rel/Mod . V05R03M0
Dump format . 64-BIT
------------------------------------------------------------
Primary Symptom Strings
              PIDS/5741A0502           (Component ID)
              AB/SRUN003               (Abend Code)
              RIDS/RUN                 (Failing Module)
              PRCS/00000000            (PRCS Info)
              REGS/0D6F2               (Register/PSW Info)
------------------------------------------------------------
Section 5 Data:
              USERID DUMPED: SYSTEM
              DUMP RECEIVER: OPERATNS
              SPOOLID: 0038
------------------------------------------------------------
Last trace entry on abending processor
2DFC17A0 09:48:11  RUN003 Soft Abend svc 04 at HCPRUN+B08 opsw 04040000_002E6118
                   svcilc 0002
------------------------------------------------------------
Abend  Description
RUN003 (soft) An incorrect or unsupported interception code was found in
       the start interpretive execution state descriptor.
>>> trace for 3
2DFC17A0 09:48:11  RUN003 Soft Abend svc 04 at HCPRUN+B08 opsw 04040000_002E6118
                   svcilc 0002
2DFC1760 09:48:11  Non-inst Intercept vmdbk 01B1D000 AUTOLOG1 vmdmmode 82
                   sieicode 20 guest-psw 00080000 00020030 sientvct 00
                   siestatc C0 siemodex 00 siemode A0
  Bits  defined in VMDMMODE         (82)
    80 VMDMRG32 Guest is using the small (32-bit) register mode.
    02 VMDMESA Guest is in ESA/390 mode. This bit is on for SET MACHINE
       ESA or XA.
  Codes defined in SIEICODE         (20)
    20 SIEICVAL VALIDITY INTERCEPTION
  Bits  defined in SIENTVCT         (00)
  Bits  defined in SIESTATC         (C0)
    80 SIERUNNING Indicates guest CPU is running
    40 SIERSCB SIE-state-retention retained- status control bit. When 1,
       an internal version of the contents of certain fields of the
       state description retained from a previous SIE instruction
       invocation may be used
  Bits  defined in SIEMODEX         (00)
2DFC1720 09:48:11  Run-User vmdbk 01B1D000 AUTOLOG1 vmdmmode 82
                   guest psw 00080000 00020030 00000000 00000000
                   sieintwd 008000A0 sienvtct 00 siestatc 80 siemodex 00
                   siemode A0
  Bits  defined in SIESTATC         (80)
    80 SIERUNNING Indicates guest CPU is running
  Bits  defined in SIEMODEX         (00)
  Bits  defined in SIEMODE          (A0)
    A0 (undefined)
`

**Comment by Juergen-Git** [comment]
Well, I'm just seeing that commit "Fix skey handling part 2 of 6 1538dc632d8f22476915d590fba6379c8b579a0f" has lots of SIE changes. So, I'd almost bet that this one is the culprit ;-).

**Comment by Juergen-Git** [comment]
The following patch makes it work again. It is a reversal of a specific change made by the above commit.

```C
--- a/sie.c	2021-08-15 16:03:48.262718996 +0200
+++ b/sie.c	2021-08-15 16:03:22.422677194 +0200
@@ -663,6 +663,7 @@
 
 #endif /* defined( FEATURE_VIRTUAL_ARCHITECTURE_LEVEL ) */
 
+#if !defined( FEATURE_001_ZARCH_INSTALLED_FACILITY )
    /* Reference and Change Preservation (RCP) Origin if high-order
       0x80 bit is off. Otherwise (high-order 0x80 bit is on, which
       it usually is for VM/ESA and z/VM), then the field ACTUALLY
@@ -677,6 +678,7 @@
         STATEBK->c = SIE_C_VALIDITY;
         return;
     }
+#endif
 
     /* Load the CPU timer */
     FETCH_DW( dreg, STATEBK->cputimer );
```
Well, go figure...

Can it be that this shouldn't be decided by a preprocessor directive but instead at execution time?

**Comment by Fish-Git** [comment]
> The following patch makes it work again.  [...]

Interesting.......

> Well, go figure...

Yeah. Go figure indeed. But then, upon further reflection, maybe the following is what I should have done instead? (which is a slight variation of your reversal patch above):

```diff
--- aaa/sie.c
+++ bbb/sie.c
@@ -671,12 +671,15 @@
    */
     FETCH_FW( GUESTREGS->sie_rcpo, STATEBK->rcpo );
 
+#if !defined( FEATURE_001_ZARCH_INSTALLED_FACILITY )
+
     if (!GUESTREGS->sie_rcpo && !GUESTREGS->sie_pref)
     {
         SIE_SET_VI( SIE_VI_WHO_CPU, SIE_VI_WHEN_SIENT, SIE_VI_WHY_RCZER, GUESTREGS );
         STATEBK->c = SIE_C_VALIDITY;
         return;
     }
+#endif
 
     /* Load the CPU timer */
     FETCH_DW( dreg, STATEBK->cputimer );
```

The idea here is, the `STATEBK->rcpo` field should _ALWAYS_ be fetched, _**regardless**_ of whether z/Architecture is installed or not (i.e. regardless of whether the host (i.e. z/VM) is running in z/Arch mode or not), since the bits in that field _ARE_ always used regardless of which architecture mode the z/VM host is running in.

If the z/VM host is not running in z/Arch mode (e.g. VM/ESA), then the `STATEBK->rcpo` field is indeed the Reference and Change Preservation Table Origin. If the z/VM host is running in z/Architecture mode however, then the bits in the `STATEBK->rcpo` field mean something else entirely: they're the flags that control SKA (Storage Key Assist) and other assists. But either way, the bits in that field _DO_ have meaning and _should_ always be fetched.

That having been said however, it makes sense that the field must _never_ be empty (null/zero) -- _but **only** when the field is being interpreted as a Reference and Change Preservation Table Origin field!_ (i.e. if the z/VM host is running in z/Arch mode and the field is thus being interpreted as just a set of assist flags, then is it completely valid for it to sometimes be zero and thus that shouldn't be considered to be an error).

Does that make sense?

> Can it be that this shouldn't be decided by a preprocessor directive but instead at execution time?

I suppose it _could_ be decided at runtime, sure. But why wait until then? The `FEATURE_001_ZARCH_INSTALLED_FACILITY` preprocessor directive and the way we're using it ends up accomplishing the same thing, but _without_ the extra overhead of a runtime test. Oh sure, the runtime test would only be a single instruction (an 'if' statement), but as I said, why do it when the exact same thing can be accomplished with our existing `FEATURE_001_ZARCH_INSTALLED_FACILITY` preprocessor directive?

**Comment by Juergen-Git** [comment]
Yes, that's it: (a) it works!! (b) no runtime decision is necessary :-)

**Comment by Fish-Git** [comment]
> Yes, that's it: (a) _it works!!_ (b) no runtime decision is necessary. `:-)`

Fantastic! Are you going to commit the fix? Or should I? (I don't want to cause another incident like I did with __clear_page!)

**Comment by Juergen-Git** [comment]
you had the key idea on how to get it fixed, I only found out were the bug was hiding... so, please, go ahead and commit it!

**Comment by Fish-Git** [comment]
> I only found out were the bug was hiding...

Which I am very grateful to you for!

> ... so, please, go ahead and commit it!

Done!
