### ISSUE TITLE
Some package manager suggestions are wrong in hercinst.html  

### ISSUE THREAD

**Issue by ghost** [SDL-Hercules-390/hyperion#421]
they should be

open suse ==> zypper
fedora ==> dnf
freebsd ==> pkg

enrico

**Comment by wrljet** [comment]
Enrico,

Thank you for discovering those embarrassing typos!
Corrections are pending...

Bill

**Comment by wrljet** [comment]
Enrico,

Thank you for discovering those embarrassing typos!
Corrections have been posted.

Bill

**Comment by Fish-Git** [comment]
Closing
