### ISSUE TITLE
Linking issues on ARM64 Mac OS X

### ISSUE THREAD

**Issue by HackerSmacker** [SDL-Hercules-390/hyperion#429]
Hello folks, I am encountering a strange issue trying to link Hyperion on an ARM64 Mac. I've compiled the external packages, and it seems to link against them, but it is failing to link against libtool properly. I have tried to use the included libtool, but it does not seem to work at all (getting some undefined symbol errors with it), so I tried to use the libtool that I've got installed on my system. I ran the configure script with `./configure --enable-extpkgs=/Users/user/source/hercextpkgs --with-ltdl-include=/usr/local/include --with-ltdl-lib=/usr/local/lib`. This presented a new issue, however:

```
  CCLD     libherc.la

*** Warning: Linking the shared library libherc.la against the
*** static library /Users/user/source/hercextpkgs/lib/aarch64/libcrypto64.a is not portable!

*** Warning: Linking the shared library libherc.la against the
*** static library /Users/user/source/hercextpkgs/lib/aarch64/libdecNumber64.a is not portable!

*** Warning: Linking the shared library libherc.la against the
*** static library /Users/user/source/hercextpkgs/lib/aarch64/libSoftFloat64.a is not portable!

*** Warning: Linking the shared library libherc.la against the
*** static library /Users/user/source/hercextpkgs/lib/aarch64/libtelnet64.a is not portable!
Undefined symbols for architecture arm64:
  "___emutls_v.softfloat_exceptionFlags", referenced from:
      _ieee_cond_trap in ieee.o
      _ieee_exception_test_oux in ieee.o
      _s370_add_bfp_ext_reg in ieee.o
      _s370_add_bfp_long_reg in ieee.o
      _s370_add_bfp_long in ieee.o
      _s370_add_bfp_short_reg in ieee.o
      _s370_add_bfp_short in ieee.o
      ...
  "___emutls_v.softfloat_roundingMode", referenced from:
      _s370_add_bfp_ext_reg in ieee.o
      _s370_add_bfp_long_reg in ieee.o
      _s370_add_bfp_long in ieee.o
      _s370_add_bfp_short_reg in ieee.o
      _s370_add_bfp_short in ieee.o
      _s370_convert_fix32_to_bfp_ext_reg in ieee.o
      _s370_convert_fix32_to_bfp_long_reg in ieee.o
      ...
ld: symbol(s) not found for architecture arm64
collect2: error: ld returned 1 exit status
make[2]: *** [libherc.la] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

I'm not sure what's going on here, `arm64` and `aarch64` both show up, maybe this is the issue. I symlinked `arm64` to point to the `aarch64` directory in the extpkgs build location, but that didn't make a difference.

**Comment by wrljet** [comment]
For Mac M1 silicon there are a number of things done differently, so I suggest you first use my Hercules-Helper project to do your build. It will run though everything, including installing the required packages.  It works with both Homebrew and MacPorts.

Rough instructions are in the readme on the repo.

https://github.com/wrljet/hercules-helper

A simple example of usage is:

```
cd ~
git clone https://github.com/wrljet/hercules-helper.git
mkdir herctest && cd herctest
~/hercules-helper/hyperion-buildall.sh --verbose --prompts --homebrew
```

For MacOS and Homebrew, be sure /opt/homebrew/bin appears at the front of your search PATH, so newer packages from Brew override older defaults from MacOS or the Xcode command line tools.

There will be LOTS of output, which will all also be logged.  And it will not overwrite existing logs.  They are all timestamped in the filenames.  Also a rough re-build script will be generated.

Bill

**Comment by HackerSmacker** [comment]
[hyperion-buildall-2021-10-10-4.log.gz](https://github.com/SDL-Hercules-390/hyperion/files/7317847/hyperion-buildall-2021-10-10-4.log.gz)

Okay, here's my log.

**Comment by wrljet** [comment]
OK, there may be a mismatch in the compiler(s) on your system.

One of the compiler warnings in your log refers to this include path:
```/opt/homebrew/Cellar/gcc/11.2.0/lib/gcc/11/gcc/aarch64-apple-darwin20/11.1.0/include-fixed/stdio.h```

Which looks like it's for gcc.

Can you rerun the process again, but stick `CC=clang` on the front.  Along the lines of:

```
CC=clang .../hercules-helper/hyperion-buildall.sh --verbose --prompts --homebrew
```

**Comment by HackerSmacker** [comment]
Okay, that got it! Works like a charm now!

**Comment by HackerSmacker** [comment]
[hyperion-buildall-2021-10-10-4.log.gz](https://github.com/SDL-Hercules-390/hyperion/files/7317958/hyperion-buildall-2021-10-10-4.log.gz)
[build-commands-2021-10-10-5.log.gz](https://github.com/SDL-Hercules-390/hyperion/files/7317960/build-commands-2021-10-10-5.log.gz)
Alright, here they are. I went ahead and re-compiled *with* REXX support and it works like a charm. Looks like the Homebrew GCC for some reason doesn't look in /usr/local/include by default.

**Comment by wrljet** [comment]
The one log you posted above appears to be a duplicate from earlier.

Now, one other tidbit...

The default config file in Hercules-Helper currently points to my fork of SDL-Hercules.  This is because of the in-flux nature of current on-going development efforts there, which are not always advertised or guaranteed to work.

If you want to build with the latest SDL-Hercules (or any other commit in that repo) you can edit `hercules-helper.conf`.

Scroll down a ways and reversing the commenting of the two lines:

```
# Git repo for SDL-Hercules Hyperion
# git_repo_hyperion=https://github.com/SDL-Hercules-390/hyperion.git
git_repo_hyperion=https://github.com/wrljet/hyperion.git
```

Bill

**Comment by HackerSmacker** [comment]
Ahh, I see the different log number now! Hmm, could be related to the gzipping of the "old" 4th log, and it never rolled over the number since there wasn't a filename conflict. Oh yeah, the latest compile straight off of the git repo here is also working great. Now, I'm not sure if I can test out the LCS driver since I cannot find any good ways to create a tap device on M1 OS X. The QETH emulation seems to work with a tun device, but it looks like there's no hope for tap on here.

**Comment by wrljet** [comment]
HackerSmacker, are you John, whom I've been emailing previously?

Bill

**Comment by wrljet** [comment]
I recognized your handle from Moshix Discord, but people don't seem to like to mention their names.

Bill

**Comment by HackerSmacker** [comment]
Yep, that's me! For the sake of privacy, I've always omitted my actual name from online discussions since having several people with the same name is never not confusing at times.

**Comment by HackerSmacker** [comment]
So, my ultimate goal is to get the QETH and LCS emulations to actually work with tap devices, but I fear that this might actually be impossible. Apple has done away with the tap extension, but I have not tested out Tunnelblick's tap extension. I am installing that right now, one reboot withstanding.

**Comment by wrljet** [comment]
The original complaint about linking issues on MacOS is explained, and what's left is now a mention about Apple not having a TAP extension.

I would suggest we can close this issue and create a new one if desired.

**Comment by wrljet** [comment]
Fish, looks like a "lost interest" here.  Close?
