### ISSUE TITLE
Missing dependency in installation doc for FreeBSD

### ISSUE THREAD

**Issue by cwjordan** [SDL-Hercules-390/hyperion#430]
The `_dynamic_version` script relies on bash, which isn't installed by default on FreeBSD.  

The FreeBSD section of the installation instructions at **https://sdl-hercules-390.github.io/html/hercinst.html** should be updated to list bash as a dependency, and ideally the `bldlvlck` script should check for it.

**Comment by wrljet** [comment]
The documentation page has been updated.  

`bldlvlck` to follow (I need to test those changes on about a dozen systems).

Bill

**Comment by wrljet** [comment]
This was addressed in commit https://github.com/SDL-Hercules-390/hyperion/commit/cc02569458c9299f5927677eb38e6807520f7a86 on 13 OCT 2021, and I forgot to update this issue.

Bill
