### ISSUE TITLE
devtype 3270 not recognized

### ISSUE THREAD

**Issue by trknz** [SDL-Hercules-390/hyperion#431]
I've tried compiling the sources under _**Ubuntu 20.04**_ and got the following error in the log:

<pre>
<b>HHC01462E 0:001F devtype 3270 not recognized
HHC00007I Previous message from function 'attach_device' at config.c(1299)
HHC01462E 0:0700 devtype 3270 not recognized
HHC00007I Previous message from function 'attach_device' at config.c(1299)</b>
</pre>

The same config is working fine under the Hercules 3.13. 

Here is the full log:

<pre>
HHC00100I Thread id 00007fb40694a540, prio 5, name 'impl_thread' started
HHC00100I Thread id 00007fb406847700, prio 4, name 'logger_thread' started
HHC01413I Hercules version 4.3.0.0-SDL-ga4db8213 (4.3.0.0)
HHC01414I (C) Copyright 1999-2020 by Roger Bowler, Jan Jaeger, and others
HHC01417I ** The SoftDevLabs version of Hercules **
HHC01415I Build date: Oct 12 2021 at 00:24:34
HHC01417I Built with: GCC 9.3.0
HHC01417I Build type: GNU/Linux x86_64 host architecture build
HHC01417I Modes: S/370 ESA/390 z/Arch
HHC01417I Max CPU Engines: 128
HHC01417I Using   shared libraries
HHC01417I Using   setresuid() for setting privileges
HHC01417I Using   POSIX threads Threading Model
HHC01417I Using   Error-Checking Mutex Locking Model
HHC01417I With    Shared Devices support
HHC01417I With    Dynamic loading support
HHC01417I With    External GUI support
HHC01417I With    IPV6 support
HHC01417I With    HTTP Server support
HHC01417I With    sqrtl support
HHC01417I With    Signal handling
HHC01417I With    Watchdog monitoring
HHC01417I With    CCKD BZIP2 support
HHC01417I With    HET BZIP2 support
HHC01417I With    ZLIB support
HHC01417I With    Regular Expressions support
HHC01417I Without Object REXX support
HHC01417I Without Regina REXX support
HHC01417I With    Automatic Operator support
HHC01417I Without National Language Support
HHC01417I With    CCKD64 Support
HHC01417I With    Transactional-Execution Facility support
HHC01417I With    "Optimized" instructions
HHC01417I Machine dependent assists: cmpxchg1 cmpxchg4 cmpxchg8 cmpxchg16 hatomics=C11
HHC01417I Running on: PC_ultra (Linux-5.10.16.3-microsoft-standard-WSL2 x86_64) MP=2
HHC01417I Built with crypto external package version 1.0.0.27-ga3e07b5
HHC01417I Built with decNumber external package version 3.68.0.80-gdb5c456
HHC01417I Built with SoftFloat external package version 3.5.0.83-g3da230f
HHC01417I Built with telnet external package version 1.0.0.45-g2d9f219-modified
HHC00018I Hercules is running in elevated mode
HHC00150I Crypto module loaded (C) Copyright 2003-2016 by Bernard van der Helm
HHC00151I Activated facility: Message Security Assist
HHC00151I Activated facility: Message Security Assist Extension 1, 2, 3 and 4
HHC00111I Thread CPU Time IS available (_POSIX_THREAD_CPUTIME=0)
HHC00100I Thread id 00007fb4062fd700, prio 7, name 'timer_thread' started
HHC00100I Thread id 00007fb4063fe700, prio 2, name 'Processor CP00' started
HHC00811I Processor CP00: architecture mode z/Arch
HHC00811I Processor CP00: architecture mode ESA/390
HHC02204I ARCHLVL        set to ESA/390
HHC02204I MAXCPU         set to 2
HHC00827I Processor CP00: engine 00 type 0 set: CP
HHC00827I Processor CP01: engine 01 type 0 set: CP
HHC00100I Thread id 00007fb4059fa700, prio 2, name 'Processor CP01' started
HHC00811I Processor CP01: architecture mode ESA/390
HHC02204I NUMCPU         set to 2
HHC02204I AUTO_SCSI_MOUNT set to NO
HHC02204I conkpalv       set to (3,1,10)
HHC01474I Using internal codepage conversion table default
HHC02204I CPUMODEL       set to 7490
HHC02204I CPUSERIAL      set to 012345
HHC02204I CPUVERID       set to 00
HHC02204I DIAG8CMD       set to DISABLE  NOECHO
HHC02204I ECPSVM         set to disabled

<b><i>HHC01508I HDL: loadable module directory is '/mnt/c/Users/roma/hercules'
HHC02204I MODPATH        set to /mnt/c/Users/roma/hercules</i></b>

HHC02204I LEGACYSENSEID  set to disabled
HHC02204I LPARNUM        set to 01
HHC02204I LPARNAME       set to HERCULES
HHC17003I MAIN     storage is 1G (mainsize); storage is not locked
HHC02204I MANUFACTURER   set to HRC
HHC02204I MODEL          set to hardware(EMULATOR) capacity(EMULATOR) perm() temp()
HHC02204I MOUNTED_TAPE_REINIT set to disabled
HHC02204I PANRATE        set to 50
HHC02204I PLANT          set to ZZ
HHC02204I SHCMDOPT       set to DISABLE  NODIAG8
HHC02204I TIMERINT       set to 50
HHC02204I TRACEOPT       set to TRADITIONAL
HHC02204I TZOFFSET       set to -0600
HHC17003I EXPANDED storage is 0 (xpndsize); storage is not locked
HHC02204I YROFFSET       set to 0
<b>HHC01462E 0:001F devtype 3270 not recognized
HHC00007I Previous message from function 'attach_device' at config.c(1299)</b>
<b>HHC01462E 0:0700 devtype 3270 not recognized
HHC00007I Previous message from function 'attach_device' at config.c(1299)</b>
HHC00414I 0:0123 CKD file 240RES.cckd: model 3390-3 cyls 3339 heads 15 tracks 50085 trklen 56832
HHC00414I 0:0124 CKD file 240W01.cckd: model 3390-3 cyls 3339 heads 15 tracks 50085 trklen 56832
HHC00414I 0:0125 CKD file 240W02.cckd: model 3390-3 cyls 3339 heads 15 tracks 50085 trklen 56832
HHC00414I 0:0126 CKD file 240W03.cckd: model 3390-3 cyls 3339 heads 15 tracks 50085 trklen 56832
HHC00414I 0:0128 CKD file 240SPL.cckd: model 3390 cyls 1113 heads 15 tracks 16695 trklen 56832
HHC02204I DIAG8CMD       set to DISABLE  NOECHO
HHC02204I ECPSVM         set to disabled
HHC01508I HDL: loadable module directory is '/mnt/c/Users/roma/hercules'
HHC02204I MODPATH        set to /mnt/c/Users/roma/hercules
HHC02204I LEGACYSENSEID  set to disabled
HHC02204I LPARNUM        set to 01
HHC02204I LPARNAME       set to HERCULES
HHC17003I MAIN     storage is 1G (mainsize); storage is not locked
HHC02204I MANUFACTURER   set to HRC
HHC02204I MODEL          set to hardware(EMULATOR) capacity(EMULATOR) perm() temp()
HHC02204I MOUNTED_TAPE_REINIT set to disabled
HHC02204I PANRATE        set to 50
HHC02204I PLANT          set to ZZ
HHC02204I SHCMDOPT       set to DISABLE  NODIAG8
HHC02204I TIMERINT       set to 50
HHC02204I TRACEOPT       set to TRADITIONAL
HHC02204I TZOFFSET       set to -0600
HHC17003I EXPANDED storage is 0 (xpndsize); storage is not locked
HHC02204I YROFFSET       set to 0
<b>HHC01462E 0:001F devtype 3270 not recognized
HHC00007I Previous message from function 'attach_device' at config.c(1299)</b>
<b>HHC01462E 0:0700 devtype 3270 not recognized
HHC00007I Previous message from function 'attach_device' at config.c(1299)</b>
HHC00414I 0:0123 CKD file 240RES.cckd: model 3390-3 cyls 3339 heads 15 tracks 50085 trklen 56832
HHC00414I 0:0124 CKD file 240W01.cckd: model 3390-3 cyls 3339 heads 15 tracks 50085 trklen 56832
HHC00414I 0:0125 CKD file 240W02.cckd: model 3390-3 cyls 3339 heads 15 tracks 50085 trklen 56832
HHC00414I 0:0126 CKD file 240W03.cckd: model 3390-3 cyls 3339 heads 15 tracks 50085 trklen 56832
HHC00414I 0:0128 CKD file 240SPL.cckd: model 3390 cyls 1113 heads 15 tracks 16695 trklen 56832
</pre>

**Comment by fsword7** [comment]
Yeah. I had the same problem but I already figured it out.  I removed MODPATH from hercules.cnf file and all problems went away.

**Comment by vlsinitsyn** [comment]
Thanks, that solved it.

**Comment by Fish-Git** [comment]
Closing.
