### ISSUE TITLE
Pls update configure with the recent version of the gnu-config

### ISSUE THREAD

**Issue by trknz** [SDL-Hercules-390/hyperion#438]
The existing configure is using an outdated version of the gnu-config and missing several architectures.

**Comment by Fish-Git** [comment]
Hi Bill! (@wrljet)

What's the status on this issue? And is there anything I can do to help?

Thanks!

**Comment by wrljet** [comment]
Fish,

That should be all taken care of, as part of the Elbrus e2k work.

Bill

**Comment by Fish-Git** [comment]
> > What's the status on this issue? And is there anything I can do to help?

> That should be all taken care of, as part of the Elbrus e2k work.

Which was done quite a while ago, yes?  So this GH has long since been closed/completed/resolved, yes?

**Comment by wrljet** [comment]
Yes, that has been in place for some months now.
