### ISSUE TITLE
DASDINIT mod-27 Volume in windows

### ISSUE THREAD

**Issue by perja11** [SDL-Hercules-390/hyperion#439]
Hello Friends,

What is the exact syntax to create a Mod-27 disk and attach to the hercules running on top of the windows 10.

Any pointers are much appreciated.

**Comment by Fish-Git** [comment]
GitHub Issues are meant for reporting bugs, _not_ for asking questions on product usage. If you need help using the product, ask your question in one of the appropriate support forums:

* https://sdl-hercules-390.github.io/html/hercsupp.html

Closing as Invalid (User Error).
