### ISSUE TITLE
Recent cckddump/cckdload changes have broken Linux build.

### ISSUE THREAD

**Issue by mcisho** [SDL-Hercules-390/hyperion#444]
Have just cloned the repository but the make does not work.

```
Making all in util
make[2]: Entering directory '/home/xxx/Hercules.SDL/hyperion/util'
make[2]: *** No rule to make target 'cckddump.hla', needed by 'all-am'.  Stop.
```

Ian

**Comment by Fish-Git** [comment]
(Oops!) I forgot to commit the results of my `autogen`. Sorry. &nbsp; `:(`

Give me a few minutes(?) and I'll get that committed for you.

In the mean time, if you do `autogen` first, before your `./configure`, then it _should_ build okay.

(But give me a few minutes(?) to commit the results of an `autogen` so you won't have to do that.)

Thanks.

**Comment by Fish-Git** [comment]
Fixed!

Please refresh your local repo (either via git pull or delete and re-clone) and try again.

Thanks. &nbsp; (and again, my apologies for the SNAFU)
