### ISSUE TITLE
Error 22 (EINVAL) writing to CTCI device

### ISSUE THREAD

**Issue by MartinTr2** [SDL-Hercules-390/hyperion#446]
The guest in Herc cannot connect via tun interface using CTCI definition

Attached is a logfile of a bad start and a good start:

* [logfile_bad.txt](https://github.com/SDL-Hercules-390/hyperion/files/7656002/logfile_bad.txt)
* [logfile_good.txt](https://github.com/SDL-Hercules-390/hyperion/files/7656003/logfile_good.txt)

And the information as required when problem with tun interface as per documentation for the bad and the good case:

* [doc_herc_bad.txt](https://github.com/SDL-Hercules-390/hyperion/files/7655985/doc_herc_bad.txt)
* [doc_herc_good.txt](https://github.com/SDL-Hercules-390/hyperion/files/7655986/doc_herc_good.txt)

The guest in both cases sees the ping coming in but cannot answer (in the bad case). Console of the guest when the ping is done is attached as .png file:

![Screenshot_2021-12-05_12-40-05](https://user-images.githubusercontent.com/95575836/144749771-1136b842-e6a4-4e10-8c6b-f33d745782ae.png)

The modification that makes it work is a return as coded in `ctc_ctci.c` around line 959 (handling of error HHC00911) but only for cases where the errno is not 22:

Instead of:
```
    return;
```
It is now:
```
    if (errno!=22) return;
```

Please inform if more documentation is required.

**Comment by Fish-Git** [comment]
I understand your modification _seems_ to "fix" the problem from your point of view, but from a Hercules developer's point of view your modification appears dangerous and very wrong. It is ignoring a serious error and pretending that nothing went wrong. It is presuming the data was successfully written (it is presuming the guest's ping reply was successfully sent), when in fact it was not!

I personally would _not_ recommend making your change. I would ask that you _**not**_ "fix" the code like you did.

Rather, a better approach IMHO would be to help us determine _**why**_ the error is occurring in the first place.

I'm not a Linux person and thus have ZERO skill/experience with tuntap, but just out of curiosity, do you have OpenVPN installed? I did some quick Google searches and found the following:

* [**OpenVPN: No connectivity, and "write to TUN/TAP : Invalid argument (code=22)" error.**](https://github.com/kylemanna/docker-openvpn/issues/551)
* [**OpenVPN: Connection errors / comp-lzo only working after reconnect**](https://community.openvpn.net/openvpn/ticket/128?__cf_chl_jschl_tk__=pm8SUvkYsMxj3_UdCAQT6lVtFbn2vG06VYw7GWcblWE-1638725017-0-gaNycGzNCJE)

Does the above make any sense to you or anyone else? Could the above possibly be what is causing your problem? Or maybe something _similar_ to the above? Like a misconfigured tuntap device maybe? Or a tuntap device configured with some unusual/unsupported options?

I am going to need to let someone else (or several someone elses!) on our team help you with this one Martin, as it is clearly out of my league! Sorry! &nbsp; `:(`

Can anyone else on the team help this gentleman?

**Comment by MartinTr2** [comment]
Openvpn is installed as part of the basic-installation, but not invoked (that i know of)from a nobile....may have typos!
-------- Ursprüngliche Nachricht --------Von: Fish-Git ***@***.***> Datum: 05.12.21  19:38  (GMT+01:00) An: SDL-Hercules-390/hyperion ***@***.***> Cc: MartinTr2 ***@***.***>, Author ***@***.***> Betreff: Re: [SDL-Hercules-390/hyperion] ctci not working (Issue #446) 

I understand your modification seems to "fix" the problem from your point of view, but from a Hercules developer's point of view your modification appears dangerous and very wrong. It is ignoring a serious error and pretending that nothing went wrong. It is presuming the data was successfully written (it is presuming the guest's ping reply was successfully sent), when in fact it was not!

I personally would not recommend making your change. I would ask that you not "fix" the code like you did.

Rather, a better approach IMHO would be to help us determine why the error is occurring in the first place.

I'm not a Linux person and thus have ZERO skill/experience with tuntap, but just out of curiosity, do you have OpenVPN installed? I did some quick Google searches and found the following:



OpenVPN: No connectivity, and "write to TUN/TAP : Invalid argument (code=22)" error.

OpenVPN: Connection errors / comp-lzo only working after reconnect



Does the above make any sense to you or anyone else? Could the above possibly be what is causing your problem? Or maybe something similar to the above? Like a misconfigured tuntap device maybe? Or a tuntap device configured with some unusual/unsupported options?

I am going to need to let someone else (or several someone elses!) on our team help you with this one Martin, as it is clearly out of my league! Sorry!   :(

Can anyone else on the team help this gentleman?

**Comment by Fish-Git** [comment]
> OpenVPN is installed as part of the basic-installation, but not invoked (that I know of!) from a mobile. But it may have typos!

Martin?

FYI:

I'd appreciate it _very much_ if you would _**not**_ respond/reply to GitHub Issues via email.

I'd greatly prefer that you instead login to GitHub and respond/reply _directly_ via the GitHub Issues web page:

* `https://github.com/SDL-Hercules-390/hyperion/issues/446`

When you reply _directly_ via the GitHub Issues web page, I can make minor edits to your reply so that it is more readable (prettier). I can change the font being used, etc. (just like I did with your original post).

When you reply via email however, I cannot edit your reply (GitHub doesn't let me), so oftentimes it is much more difficult for others to read.

It's up to you whether or not you want to take the time to reply via the web page or continue to reply via email, but I'd _rather_ that you reply directly via their _web page_.

Thanks!

**Comment by mcisho** [comment]
MartinTr2, you have two interfaces (tun0 and wlx000cf6b78dc0) both using the same IP address (192.168.0.19).

**Comment by Fish-Git** [comment]
Some additional **preliminary analysis** for the benefit of my fellow Hercules developers _(one or more of which I hope will choose to help Martin!)_:

Martin appears to be using a self-built version of Hyperion 4.2 _(which specific version is unknown as he failed to build it properly)_, as well as appears to be running non-elevated too _(which might be the problem?)_:

<pre>
12:37:22 HHC00109E <b>set_thread_priority( 5 ) failed: Operation not permitted</b>
12:37:22 HHC00007I Previous message from function 'impl' at impl.c(754)
12:37:22 HHC00110W Defaulting all threads to priority 1
12:37:22 HHC00007I Previous message from function 'impl' at impl.c(757)
12:37:22 HHC00100I Thread id 00007fe3a7026740, prio -1, name 'impl_thread' started
12:37:22 HHC00100I Thread id 00007fe3a4ee4700, prio -1, name 'logger_thread' started
12:37:22 HHC01413I <b><i>Hercules version 4.2.0.0-SDL (4.2.0.0)</i></b>
</pre>

Something else I noticed _(which is probably not a concern but I feel compelled to mention it anyway)_ which is weird, is while Hercules is indeed properly setting X'10' EQPCK in the sense byte for the device:

<pre>
12:39:51 HHC00911E 0:0E81 CTCI: Error writing to device tun0: 22 Invalid argument
12:39:51 HHC00007I Previous message from function 'CTCI_Write' at ctc_ctci.c(957)
12:39:51 HHC01315I 0:0E81 CHAN: ccw 01122330 24000028=>00123000 00123800 00105000 00105800 ..........&.....
12:39:51 HHC01302I 0:0E81 CHAN: idaw 00123000, len 028: =>00280026 C9E5E2C5 C3E3C3C1 F0F14BF0 ....IVSECTCA01.0
12:39:51 HHC01312I 0:0E81 CHAN: stat 0E00, count 0000
12:39:51 HHC01313I 0:0E81 CHAN: sense <b><i>10</i></b>000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
12:39:51 HHC01314I 0:0E81 CHAN: sense EQPCK 
</pre>

&nbsp;
...the guest _(VSE/ESA 5.1?)_ for some odd reason, appears to not be receiving that information:

![Fish](https://user-images.githubusercontent.com/1486786/144762479-84b38913-817e-408e-836a-d14200b049b5.png)

As I said, I doubt that's significant to the problem, but I thought I should mention it anyway.

Personally I suspect it's either the fact that he's not running elevated _(which AFAIK is required(*) in order for Hercules networking to work correctly)_, or else it's OpenVPN that's causing the problem. One or the other or both.

But I leave that to you guys to figure out. &nbsp; `:)`

____
(*) [_"**Note:** Hercules's networking support requires privileged access to your host's networking devices. If Hercules is not started with Administrative (root) privileges then initialization of your networking devices will fail and your guest's networking will not work."_](https://sdl-hercules-390.github.io/html/hercconf.html#CTCI)

**Comment by Fish-Git** [comment]
> MartinTr2, you have two interfaces (tun0 and wlx000cf6b78dc0) both using the same IP address (192.168.0.19).

WOW! That was quick, Ian! Thanks!

**Comment by MartinTr2** [comment]
Ian,

It could well be that this incorrect use of ip-addresses is the root cause (and I did that since I attempted the first steps into networking). I will report as soon as I did some testing.
Thank you

Martin

Fish, 

you state "as he failed to build it properly" ---- 

this should not be. I do "./autogen.sh" "./configure" "make" "sudo make install" from the version downloaded as .zip. I do this because linux-mint does carry a pretty old version. What should I change to build it proper?

Best

Martin

**Comment by Fish-Git** [comment]
MartinTr2 wrote:

> What should I change to build it proper?

Build from a clone of the repository, not from a download of the source, as recommended on our web page:

  https://sdl-hercules-390.github.io/html/hercinst.html#instsource

  "(Note: building from the source code .zip file is strongly discouraged.
   Instead, it is highly recommended that you clone the git repository
   and build from that instead.)"

When you build from the downloaded source, you get just a very unhelpful generic version string such as "4.4.9999" (which doesn't tell us much).

When you build from a git clone of the repository however, you get a much more precise version string such as "4.4.9999.10623-SDL-g3162d249", which tells us *exactly* what Hercules code you are using.

The 8 hex digits of the "g3162d249" string is the actual git hash of the most recent commit to the repository, and thus tells us *exactly* what Hercules code you are using.

Without that hash we cannot know for certain what code (fixes/commits) your Hercules has and what code (fixes) it doesn't have.

The recommended (preferred) build procedure is to first do a "git clone" of the repository, and then do your normal ./configure, make, etc.

ALSO NOTE that you should NOT be doing an ./autogen.sh either. That modifies files and makes it appear as if you made some private/custom changes to Hercules code, which introduces suspicion as well.

Instead, just start with ./configure.

We, the developers, do the autogen and then commit the result. You the user that just wishes to build Hercules, should just do the ./configure and make, etc. You should *never* do an autogen unless you fully understand when and why doing so is necessary.

So... git clone, configure, make (and sudo make install too if desired of course). That's it.

-- 
"Fish" (David B. Trout)
Software Development Laboratories
http://www.softdevlabs.com
mail: ***@***.***

**Comment by MartinTr2** [comment]
Ian,

changed the ip-address of the TUN device... It works without any messages (the 0911) ... code not fixed yet- but sure that my problem is identified and fixed and herc will work. 

Fish,

thank you- will do.

Martin

**Comment by MartinTr2** [comment]
>>  It works without any messages (the 0911) 

well-I have to correct that: Sometimes it does not show up.

I did git clone and  build from that. The problem is still there. I tried it with predefined TUN at rc.local too. same. Sometimes I do not get the 0911 message. 

After a day of tinkering I reapplyed the kludge.

**Comment by mcisho** [comment]
> Sometimes I do not get the 0911 message.

Can you be more specific? Your initial report suggested that sometimes Hercules/VSE worked, sometimes they failed, but you gave no indication of the frequency of either. Is the failure every other time you run Hercules? One time in ten? Nine times out of ten? Does it only work, or fail, after a host reboot?

Have you tried Hercules/VSE on a different subnet to the host adapter (or alternatively, the host adapter on a different subnet to  Hercules/VSE)? Have you tried with the hosts Ethernet adapter, rather than the hosts Wifi adapter?

And what is 'martin-desktop'? A role-your-own Linux? Based on what?

Ian

**Comment by mcisho** [comment]
p.s. Can you turn on CTCI debug, so we can see what leads up to the fail?

**Comment by MartinTr2** [comment]
>> .. sometimes they failed, but you gave no indication of the frequency of either. <<

Originally I had hercules running without guest connecting to anything at all. Mainly because I am a mainframe person and have little to no knowledge of win or .nix. At some point I activated the TUNTAP connection (still under windows). That worked flawless (early with cygcin or so-later native windows). 
When I converted away from win to Linux (or later when I changed the distro - not sure about exact time- more than 8 years ago) the problem (as still manifesting today) started occuring hard and every time. Because of the exact line-number I ventured into uncharted land (for me) and modified sourcecode in a language I do not know on an operating system I am not familiar with.

Sometimes (approx in 2015) the need for connection to a browser on the hosting PC from the guest (VSE) disappeared so I did not pursue this - In January 2021 I had again a need for it and applied the kludge (only return from CTC_CTCI after 0911 if not ERRNO = 22).

Two days ago I started migrating all my stuff to linux-mint 20. During that process I stumbled over that (old) problem again and opened a bug report (Fish suggested it).  

Now to the rest of you questions:

>> Is the failure every other time you run Hercules? 

Yes - every time.

>>  after a host reboot?

Host as in hosting PC I assume: It happens as long as I use the unpatched version of Hercules. 

>> Have you tried Hercules/VSE on a different subnet to the host adapter

I do not understand or know how to do that?

>> (or alternatively, the host adapter on a different subnet to Hercules/VSE)? 

I do not understand or know how to do that?

>> Have you tried with the hosts Ethernet adapter, rather than the hosts Wifi adapter?

How can I do that?

>> (1) And what is 'martin-desktop'? (2)A role-your-own Linux? (3)Based on what?

1 - That is my PC running linux mint 18. 

2 - various software installed - but the op-sys is the plain vanilla version

3 - I am a mainframe person and can help identify issues around a z-instruction - but not manipulate a distro to the extent that it can be called "my Linux based on xxx".

Martin

**Comment by MartinTr2** [comment]
>> p.s. Can you turn on CTCI debug, so we can see what leads up to the fail?

Sure. Is that an option at start of herc or at build?

With the kludge or without it (prefer with kludge and at start)?

**Comment by mcisho** [comment]
The -d option on the CTCI config statement. With or without the kludge.

**Comment by MartinTr2** [comment]
Here is the logfile of herc ( > name_of_logfile) --
[logfile_debug_ctci.txt](https://github.com/SDL-Hercules-390/hyperion/files/7668655/logfile_debug_ctci.txt)

 also attached is the documentation as with first posting
[docherc.txt](https://github.com/SDL-Hercules-390/hyperion/files/7668641/docherc.txt)

Best

Martin

**Comment by mcisho** [comment]
Your VSE system is writing:-

```
+0000  00280026 C9E5E2C5 C3E3C3C1 F0F14BF0   ....IVSECTCA01.0
+0010  F540C640 F0F261F2 F661F0F8 F1F84BF2   5 F 02/26/0818.2
+0020  F4404040 09010001                     4   ....
```

The first 2 bytes are the block header (see struct CTCIHDR), the next 6 bytes are the segment header (see struct CTCISEG), and the remaining 32 bytes are the data, which is what is written to the tun interface. The host Linux expects the data to be an IPv4 or an IPv6 packet, but as you can see it is neither, hence the 22 Invalid argument error.

Looking at the CTCI code the data the VSE system is writing appears to be what the section of code beginning at line 866 should be processing, except in this case the first 2 bytes (i.e. the CTCIHDR) do not contain zero. Is your VSE system modified in any way? Is it very modern? I don't understand why your VSE should be different to any other VSE!

**Comment by MartinTr2** [comment]
Ian,

I see the data and I understand what you are saying- I can not judge it- 

The VSE is from (judging by the install-tapes=AWS files) January 2013. The use of the TCP/IP in VSE is usually for FTP only. I have had a hard time convincing people that CICS can easy talk to browsers and not only to 3270 screens. And I have seen a lot of VSE installations while working as sysprog for hire that were surprised to see i.e. this from a VSE-directly:
![image](https://user-images.githubusercontent.com/95575836/145072914-30dedb6b-c7fe-4530-8a86-54138cd4a4dc.png)

>> Is your VSE system modified in any way? <<

Yes it is, but certainly not in this corner - 100% sure

>> Is it very modern? <<

Right now 5.1 is old- Current system is AFAIK 6.2

>> I don't understand why your VSE should be different to any other VSE!

see above- TCPIP is usualy not used for this but only for FTP -

I see there are names that I do recognise on GITHUB- I get in touch and see what I/we can do to have CTCI debug data from a more current system.  

The data you are looking at looks to me like "IVSE" and a string that appears to be a a module-header with a date (CTCA and version 01.05 F from 02/26/08 18:24 )....Just scanned the load-library and found module IPLNCTCA that has exactly that string in its belly at offset +A8 (including the trailing blanks)- No idea why.

Martin

**Comment by mcisho** [comment]
Martin, I have committed some changes to the SDL repo which will hopefully cure the problem. I say hopefully because I can't test them, I don't have a VSE to play with.

CTC connections are intended for stack to stack communication, so presumably the message VSE is sending is intended to identify itself to its remote partner stack. Hercules' CTCI is of course pretending to be that remote stack, but has obviously not been exposed to a 'modern' VSE since the CTCI code was written many years ago.

Ian

**Comment by MartinTr2** [comment]
Hercules version 4.4.9999.0-SDL-g19fdaf8 (4.4.9999.0

works!

Thank you

I leave this open till the trace with a more current VSE comes in- shall I extract a specific part of the trace (just the first - only with a certain length - , whatever) ?

**Comment by mcisho** [comment]
It would be nice to see the trace down to and including the HHC00907 message that should have been produced, just to check that works as expected.

Might as well close the issue after that, it can always be re-opened if necessary.

**Comment by MartinTr2** [comment]
11:35:34 HHC00979D CTCI: packet: +0060> 220D0A4D 583A2031 0D0A5354 3A207572  "..MX: 1..ST: ur ...(............
11:35:34 HHC00979D CTCI: packet: +0070> 6E3A6469 616C2D6D 756C7469 73637265  n:dial-multiscre >.../%._.%......
11:35:34 HHC00979D CTCI: packet: +0080> 656E2D6F 72673A73 65727669 63653A64  en-org:service:d .>.?............
11:35:34 HHC00979D CTCI: packet: +0090> 69616C3A 310D0A55 5345522D 4147454E  ial:1..USER-AGEN ./%............+
11:35:34 HHC00979D CTCI: packet: +00A0> 543A2043 68726F6D 69756D2F 39302E30  T: Chromium/90.0 ......?_.._.....
11:35:34 HHC00979D CTCI: packet: +00B0> 2E343433 302E3732 204C696E 75780D0A  .4430.72 Linux.. .........<.>....
11:35:34 HHC00979D CTCI: packet: +00C0> 0D0A                                 ..               ..              
11:35:35 HHC00913D 0:0E80 CTCI: Receive packet of size 194 bytes from device tun0
11:35:35 HHC00979D CTCI: packet: +0000> 450000C2 D5E34000 0111F240 C0A80064  E.....@....@...d ...BNT ...2 {y..
11:35:35 HHC00979D CTCI: packet: +0010> EFFFFFFA E7E9076C 00AEA0EA 4D2D5345  .......l....M-SE ....XZ.%....(...
11:35:35 HHC00979D CTCI: packet: +0020> 41524348 202A2048 5454502F 312E310D  ARCH * HTTP/1.1. ..........&.....
11:35:35 HHC00979D CTCI: packet: +0030> 0A484F53 543A2032 33392E32 35352E32  .HOST: 239.255.2 ..|.............
11:35:35 HHC00979D CTCI: packet: +0040> 35352E32 35303A31 3930300D 0A4D414E  55.250:1900..MAN .............(.+
11:35:35 HHC00979D CTCI: packet: +0050> 3A202273 7364703A 64697363 6F766572  : "ssdp:discover ............?...
11:35:35 HHC00979D CTCI: packet: +0060> 220D0A4D 583A2031 0D0A5354 3A207572  "..MX: 1..ST: ur ...(............
11:35:35 HHC00979D CTCI: packet: +0070> 6E3A6469 616C2D6D 756C7469 73637265  n:dial-multiscre >.../%._.%......
11:35:35 HHC00979D CTCI: packet: +0080> 656E2D6F 72673A73 65727669 63653A64  en-org:service:d .>.?............
11:35:35 HHC00979D CTCI: packet: +0090> 69616C3A 310D0A55 5345522D 4147454E  ial:1..USER-AGEN ./%............+
11:35:35 HHC00979D CTCI: packet: +00A0> 543A2043 68726F6D 69756D2F 39302E30  T: Chromium/90.0 ......?_.._.....
11:35:35 HHC00979D CTCI: packet: +00B0> 2E343433 302E3732 204C696E 75780D0A  .4430.72 Linux.. .........<.>....
11:35:35 HHC00979D CTCI: packet: +00C0> 0D0A                                 ..               ..              
11:35:37 HHC00981D 0:0E81 CTCI: Accept data of size 40 bytes from guest
11:35:37 HHC00979D CTCI: data: +0000< 00280026 C9E5E2C5 C3E3C3C1 F0F14BF0  .(.&..........K. ....IVSECTCA01.0
11:35:37 HHC00979D CTCI: data: +0010< F540C640 F0F261F2 F661F0F8 F1F84BF2  .@.@..a..a....K. 5 F 02/26/0818.2
11:35:37 HHC00979D CTCI: data: +0020< F4404040 09010001                    .@@@....         4   ....        
11:35:37 HHC00907I 0:0E81 CTC: interface command: IVSECTCA01.05 F 02/26/0818.24    09010001
11:35:37 HHC00982D 0:0E80 CTCI: Present data of size 802 bytes to guest
11:35:37 HHC00979D CTCI: data: +0000> 032200C8 08000000 450000C2 D38B4000  ."......E.....@. ...H.......BL. .
11:35:37 HHC00979D CTCI: data: +0010> 0111F498 C0A80064 EFFFFFFA E7E9076C  .......d.......l ..4q{y......XZ.%
11:35:37 HHC00979D CTCI: data: +0020> 00AEA0EA 4D2D5345 41524348 202A2048  ....M-SEARCH * H ....(...........
11:35:37 HHC00979D CTCI: data: +0030> 5454502F 312E310D 0A484F53 543A2032  TTP/1.1..HOST: 2 ..&.......|.....
11:35:37 HHC00979D CTCI: data: +0040> 33392E32 35352E32 35352E32 35303A31  39.255.255.250:1 ................
11:35:37 HHC00979D CTCI: data: +0050> 3930300D 0A4D414E 3A202273 7364703A  900..MAN: "ssdp: .....(.+........
11:35:37 HHC00979D CTCI: data: +0060> 64697363 6F766572 220D0A4D 583A2031  discover"..MX: 1 ....?......(....
11:35:37 HHC00979D CTCI: data: +0070> 0D0A5354 3A207572 6E3A6469 616C2D6D  ..ST: urn:dial-m ........>.../%._
11:35:37 HHC00979D CTCI: data: +0080> 756C7469 73637265 656E2D6F 72673A73  ultiscreen-org:s .%.......>.?....
11:35:37 HHC00979D CTCI: data: +0090> 65727669 63653A64 69616C3A 310D0A55  ervice:dial:1..U ........./%.....
