### ISSUE TITLE
Avoid the use of Perl in configure

### ISSUE THREAD

**Issue by Rhialto** [SDL-Hercules-390/hyperion#454]
In `configure.ac` there are these lines:
```
dnl Kludge to fix Debian/Ubuntu libtool
perl -pi -e 's/link_all_deplibs=no/link_all_deplibs=yes/' libtool
```
As far as I can see, this is the only use of Perl in the actual building process. It would be nice to remove it, since it is a pretty expensive dependency.

The same effect can be had with (`gnu`)`sed` which is already a dependency. I haven't checked yet if any gnu specific features of `gsed` are used, and can be removed, but here I will avoid those:
```
sed -e 's/^link_all_deplibs=no$/link_all_deplibs=yes/' <libtool >libtool.new
mv libtool.new libtool
```
(adding the `^` and `$` anchors while I'm there)

(There is some use of Perl in the git hooks, but those are only relevant when committing anything, so removing Perl for the build-only case is still worth it in my opinion)

**Comment by wrljet** [comment]
I will test this on all my build test systems.
Bill

**Comment by wrljet** [comment]
OK, I lied, I'm not going to test this on *all* my test systems, as there are just too many.
But I have tested this change on these:

- Arch Linux (updated to latest)
- Alma Linux 8.5
- Debian 10
- Fedora 34
- FreeBSD 12.2
- MacOS Big Sur 11.5
- MacOS Monterey 12.1

I think this is a decent representative sample of the different major distributions.
All of the above are x86_64 versions, but I seriously doubt the `sed` is affected by the CPU type.

So... I'm going to go ahead and commit this change tomorrow to the `develop` branch.

Bill

**Comment by wrljet** [comment]
Changed in commit https://github.com/SDL-Hercules-390/hyperion/commit/dabbf1918dfa934c68110b4b2eb3552cb6540bd2
