### ISSUE TITLE
make check fails for the develop branch 

### ISSUE THREAD

**Issue by ghost** [SDL-Hercules-390/hyperion#462]
Updated the repositories  20 minutes ago. No errors reported  for the master branch . The make check for the develop branch gives:

```
line 62692: Cr 14 compare mismatch.
                  Want: C2000000
                  Got:  00000000C2000000
line 62699: Cr 2 compare mismatch.
                  Want: 00000ABC
                  Got:  0000000000000ABC
Test "Initial control register values":  7 OK compares.  2 failures.

Did 208 tests.  1 failed; 207 OK.
```

enrico

**Comment by wrljet** [comment]
Hmm, it works for me on Debian 10, with ooRexx 5.0.

What system and Rexx are you using?

Bill

**Comment by Fish-Git** [comment]
Enrico,

Please run the "cr.tst" by itself and post the full/complete output.

Thanks.

**Comment by atncsj6h** [comment]
Hello Fish
sorry for the late reply
i run the single test and ( murphy's law ) no error shows up 

I will run more tests for the M1 and x86_64 with different compiler level and different systems 

it will take a bit of time but I want to get to the end of the tunnel
I am also setting up freeBSD13 and Fedora35 environment to carry on as much testing as I can 

the test strategy will be ...

on all systems :
optimization, NO optimization
bulk run of the tests ( make check)
run all the tests one by one ( the behavior seems different )

on fedora :
clang , gcc 

on apple :
the native apple compiler, the llvm.org  compiler  

please be patient 
syncing and keeping track of 28 test will be a nightmare

I will keep You posted on the progress 
enrico 

PS
the tests should also shed some light on the doubts about failures of the optimized builds

**Comment by Fish-Git** [comment]
encrio,  (@atncsj6h)

Any progress?  Should we close it?  Does the problem still occur?  Do you have any new information to report?

Thanks.

**Comment by atncsj6h** [comment]
Hi Fish
sorry for not following on, I had some urgencies to take care of
you can close it,  I will open a new issue if I get more crashes
e

**Comment by Fish-Git** [comment]
> you can close it, I will open a new issue if I get more crashes

Thanks. Closing.
