### ISSUE TITLE
--enable-optimization=yes does not work

### ISSUE THREAD

**Issue by ghost** [SDL-Hercules-390/hyperion#463]
file configure.ac  

bug 1
the test for hc_cv_builtin_alloca_broke at line 1818 
fails because the c snippet does not include <string.h>

as a consequence the AUTO-OPTIMIZE section at lines 2788/2793
does not set the -O3 flag  

adding '#include <string.h' at stmt 1835
fixes the problem

bug 2
the flag -fomit-frame-pointer
is set only for the x86 arch 

enrico

**Comment by wrljet** [comment]
Enrico,

For bug 1, on what OS and compiler?

Bill

**Comment by atncsj6h** [comment]
Hi Bill,

apple mac mini m1
Big Sur 11.6.1
xcode 13 
clang version 13

looks like I opened a can of worms
looking at the logs I just found that also the check for getopt-optreset 
doen not work aon the mac mini

adding the include does not hurt anyway 
a standalone compile of the original snippet gave the usual warning about impliciyt declarations of library functions

enrico

PS

I will have to investifgate more so let's just keep this issue pending/dormant 
until I post the results of my research

**Comment by wrljet** [comment]
For MacOS, add `--disable-getoptwrapper` to your `configure`.

The libtool from Xcode doesn't offer the option to show its capabilities.
So we skip that test with `disable-getoptwrapper`.
(assuming we're taking about the same check)

Of course I haven't dared to update my Mini to the latest Xcode, so I can't test exactly what you've got running.
But it does work with Monterey and Clang 13 on x86_64.

Bill

**Comment by atncsj6h** [comment]
already using it ...

the code should be fixed anyway ...
IMO all the c snippets used to run a test should pass a standalone compile without warnings 
the fact that in some circumstances the check is more forgiving is irrelevant 

enrico

**Comment by wrljet** [comment]
Please keep in mind many of these configure tests are ancient and obsolete.
And any changes have to be carefully tested on a large number of different OSes and compilers.

So it is a slow, ongoing, process.

**Comment by atncsj6h** [comment]
the can of worms gets bigger and bigger ...

let's consider the check for getopt optreset 

on the mac mini M1 and the macbook pro ( Big Sur clang 13 )  the config.log contains

configure:19929: checking whether 'optreset' needed for 'getopt' use
configure:19950: clang -o conftest -Wall  -W  -pthread  -D_GNU_SOURCE   -I/opt/local/include -I/opt/ooRexx/include -L/opt/local/lib -L/opt/ooRexx/lib conftest.c -lresolv -lm -ldl  >&5
conftest.c:179:21: error: implicit declaration of function 'getopt' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                    getopt(0,0,0);
                    ^
1 error generated.

while on the imac x86_64  clang 10  it contains

configure:19929: checking whether 'optreset' needed for 'getopt' use
configure:19950: clang -o conftest -Wall  -W  -pthread  -D_GNU_SOURCE   -I/opt/local/include -I/opt/ooRexx/include -L/opt/local/lib -L/opt/ooRexx/lib conftest.c -lresolv -lm -ldl  >&5
conftest.c:179:21: warning: implicit declaration of function 'getopt' is invalid in C99 [-Wimplicit-function-declaration]
                    getopt(0,0,0);
                    ^
1 warning generated.

can You please confirm it for x86_64 monterey 

thank you
enrico

**Comment by wrljet** [comment]
Here's what I get from Monterey 12.1, Clang 13, x86_64 VM.

```
configure:19929: checking whether 'optreset' needed for 'getopt' use
configure:19950: gcc -o conftest -Wall  -W  -pthread  -D_GNU_SOURCE   -I/usr/local/Cellar/libtool/2.4.6_4/include  -fsanitize=address -L/usr/local/Cellar/libtool/2.4.6_4/lib conftest.c -lresolv -lm -ldl  >&5
conftest.c:178:21: error: implicit declaration of function 'getopt' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                    getopt(0,0,0);
                    ^
1 error generated.
```

**Comment by atncsj6h** [comment]
Thank you  Bill,

so if you tried with --enable-optimization=yes --disable-debug you not get any optimization flags set  

things are getting more and more confusing

looks like the bugs  show up only to apple clang 13 
where test compilations seem to be done with the -Werror flag 

high sierra clang 10 works 
high sierra clang 13 downloaded from the llvm url works
freeBSD clang 13 works 
no -Werror flag used 

lets keep the issue open until I do more research 

synchronizing and keeping a diary of the tests  on five different environment is a bit distressing

since I opened the can of worms, I will try to close it

cheers 
enrico

**Comment by wrljet** [comment]
> synchronizing and keeping a diary of the tests on five different environment is a bit distressing

Tell me about it!  (See the list I posted in the other issue.)

And that long list is why I prefer to not make changes to anything in the autoconf stuff without being *very* careful.

Bill

**Comment by Fish-Git** [comment]
> And that long list is why I prefer to not make changes to anything in the autoconf stuff without being _very_ careful.

And that long list is why I "hate" Linux so much. The absolute PLETHORA of distributions/variants makes trying to support it a veritable nightmare.

_(I don't really "hate" Linux per se. I just find supporting it to be a royal PITA compared to Windows.)_

**Comment by wrljet** [comment]
> > And that long list is why I prefer to not make changes to anything in the autoconf stuff without being _very_ careful.
> 
> And that long list is why I "hate" Linux so much. The absolute PLETHORA of distributions/variants makes trying to support it a veritable nightmare.
> 
> _(I don't really "hate" Linux per se. I just find supporting it to be a royal PITA compared to Windows.)_

I agree with you completely.
