### ISSUE TITLE
Console not accessible

### ISSUE THREAD

**Issue by Rakeshreddy11** [SDL-Hercules-390/hyperion#467]
Hi,

Not sure if this is just for me. I am IPLing z1.0 on Windows machine. I connect my terminal to Console port, I get the NIP console initially and then I get zOS logon session. I never get Console messages. I always had to go to SYSLOG to check the console messages. I am using Hyperion 4. Please let me know if you need any additional details needed.

**Comment by Fish-Git** [comment]
Yes. Please see: "[SUBMITTING PROBLEM REPORTS](https://github.com/SDL-Hercules-390/hyperion/issues/373)".

**Comment by Rakeshreddy11** [comment]
Hi Fish,

Attaching config and log files. I am running Windows Server 2016. Same issue on Windows Server 2012. Never got it working on any Windows Server operating systems. But works fine on Windows Personal edition(all non server editions).
I am able to recreate the issue every time i IPL. NIP comes first then directly mainframe logon, not the console messages.

[hercules conf.txt](https://github.com/SDL-Hercules-390/hyperion/files/7844633/hercules.conf.txt)
[Hercules Logfile.002.txt](https://github.com/SDL-Hercules-390/hyperion/files/7844634/Hercules.Logfile.002.txt)

**Comment by Fish-Git** [comment]
_**THIS IS A GUEST OPERATING SYSTEM (i.e. z/OS) ISSUE AND NOT A HERCULES ISSUE**_

It appears you do not have a 3270 master console device defined at address 700. Unless you changed it (check your IODF?), the z/OS master console is usually always at address 700. Devices 701, 702, etc... are the TSO devices (which are enabled and brought online at some later point during the IPL, once TSO comes up).

You need to define a 3270 device at address 700, and connect to 700 before you IPL. Device 700 is where NIP messages appear, and then once NIP is complete, it switches over to become the master console where console messages then appear and where you can enter console commands from.

Change:

    #  Display Terminals
    0701.2  3270    * 127.0.0.1

to:

    #  Display Terminals
    0700.3  3270    * 127.0.0.1

Then when you connect your 3270 session to Hercules, it should connect at device address 700. Once connected, _then_ you can enter your `ipl` command, and everything should work as expected.

Closing as "Invalid" (User Error).

**Comment by Rakeshreddy11** [comment]
Thanks a lot Fish.

Changing display terminals as you suggested fixed the issue.
