### ISSUE TITLE
Unable to create zLinux VM for rhel7 (s390x) on redhat 8 host os

### ISSUE THREAD

**Issue by amitbatajoo** [SDL-Hercules-390/hyperion#476]
Hello team.

I am trying to create zLinux vm for rhel7(s390x) on Redhat 8 as host OS but unable to setup.
I am learning to user Hercules.  If anyone know the configuration / manual/ tutorial. Please help me.
Every time, setup ends with 
Entering emergency mode. Exit the shell 

#dracut:/
I cannot boot and run installer on Rehel7 s390x running under Hercules 4.4.1.
Anyone please share working Hercules config script to setup rhel7???

**Comment by wrljet** [comment]
This is probably better asked on one of the group lists.  Such as: https://hercules-390.groups.io/g/group

That said, here's the `.cnf` I used for Ubuntu zLinux two years ago:

```
ARCHLVL   z/Arch
FACILITY  ENABLE BIT37    # FPEXT   floating point extension
                          #  Needed to enable SUSE SLES 12 under
FACILITY  ENABLE BIT44    # PFPO    PFPO instruction
                          #  Hercules version 4.00 only
FACILITY  ENABLE BIT45    # FAST_BCR_SERIAL
                          #  Needed for Ubuntu 16.04.3
########################################################################
FACILITY  ENABLE BIT48    # DFPZC decimal-floating-point zoned-conversion
FACILITY  ENABLE BIT49    # MISC
                          #  Needed for Ubuntu 16.04.3 like BIT45
########################################################################
CNSLPORT  3270
CPUMODEL  3090            # 2066=z900, 2098=z10, 2818=z196, 2828=zEC12
CPUSERIAL 002623
NUMCPU    2
MAXCPU    2
DIAG8CMD ENABLE
ECPSVM   YES

LPARNAME  UBUNTU
LPARNUM   18                   # LPARNUM = SA number

MAINSIZE  2048
MOUNTED_TAPE_REINIT  DISALLOW
OSTAILOR  LINUX
PANRATE   SLOW
SHCMDOPT  ENABLE     NODIAG8

# Display Terminals
0700 3270
0701 3270

# dasd
0120 3390 ./dasd/ubuntu.120.cckd

# tape
0581    3420

# network                               s390     realbox
0A00,0A01  CTCI -n /dev/net/tun -t 1500 10.1.1.2 10.1.1.1
```

**Comment by amitbatajoo** [comment]
@wrljet Thanks for the suggestion and sample .cnf. Actually, I have already worked for Ubuntu and SUSE. But the problem is unable to setup rhel7 zLinux on redhat. I will try ask to the group as you suggested.

Thank you.

**Comment by wrljet** [comment]
For what it's worth, I was going to try to install zLinux RHEL7 to help you, but it wanted a login to download the ISO.
So I just grumbled and gave up. :-)

**Comment by amitbatajoo** [comment]
@wrljet Thanks again for your kind effort. You can just crate a login and access 60days trial ISO file. 
Thanks again.
