### ISSUE TITLE
manjaro package manager error in  hercinst.html 

### ISSUE THREAD

**Issue by ghost** [SDL-Hercules-390/hyperion#477]
the package manager for manjaro ( based on arch Linux ) is pacman, NOT apt
https://wiki.manjaro.org/index.php/Pacman_Overview#Overview
 e

**Comment by wrljet** [comment]
Sorry about that.

Fixed with commit https://github.com/SDL-Hercules-390/hyperion/commit/5d7ae599f31b61dc32b4fe61281edf2a51a4c4a1 .
