### ISSUE TITLE
Build problem on FreeBSD 13.1  (amd64) - linkage error

### ISSUE THREAD

**Issue by nutilius** [SDL-Hercules-390/hyperion#491]
I try to build current version of hercules on FreeBSD. Compilation passed but during link phase for cckdcdsk process finished with link error

```
  CCLD     cckdcdsk
ld: error: ./.libs/libhercu.so: undefined reference to lt_dlinit [--no-allow-shlib-undefined]
ld: error: ./.libs/libhercu.so: undefined reference to lt_dlsym [--no-allow-shlib-undefined]
ld: error: ./.libs/libhercu.so: undefined reference to lt_dlopen [--no-allow-shlib-undefined]
ld: error: ./.libs/libhercu.so: undefined reference to lt_dlerror [--no-allow-shlib-undefined]
ld: error: ./.libs/libhercu.so: undefined reference to lt_dlclose [--no-allow-shlib-undefined]
cc: error: linker command failed with exit code 1 (use -v to see invocation)
```

Before build I've made aliasses as was described in README.BSD

uname -a result:

```
FreeBSD lnv-comp 13.1-RELEASE FreeBSD 13.1-RELEASE releng/13.1-n250148-fc952ac2212 GENERIC amd64
```

**Comment by wrljet** [comment]
I will look into that for you.

**Comment by wrljet** [comment]
The information in `README.BSD` has not been updated in a long time, and is now obsolete/incomplete.
I will address that.

For current info on building, please see: [https://sdl-hercules-390.github.io/html/hercinst.html#instsource](https://sdl-hercules-390.github.io/html/hercinst.html#instsource)
Scroll down a ways and you'll see a list of required packages and environment variables for FreeBSD.

```
sudo pkg install -y bash git wget
sudo pkg install -y gmake autoconf automake cmake flex gawk m4 libltdl
sudo pkg install -y bzip2
```

Note: Bash is required by parts of the build apparatus.

Note: So configure/make will find ltdl.h and libltdl, which I believe is your issue:
```
export CFLAGS=-I/usr/local/include LDFLAGS=-L/usr/local/lib
```

I've just run through this myself on a FreeBSD 13.1 VM, (using Hercules-Helper) and it builds cleanly.

Bill

**Comment by ivan-w** [comment]
May I ask why anyone may need git, bash and wget to *build* hercules ? One should be able to build hercules using a standard bourne shell and without having any internet access !

**Comment by nutilius** [comment]
Your advice helped me to build executable and all so files, but after running hercules with device 3270 in configuration file, I see message:
```
HHC01462E 0:001F devtype 3270 not recognized
```
when I try to load module dynamically using ldmod, I see error message:
```
HHC01603I ldmod hdt3270
HHC01526I HDL: loading module hdt3270...
HHC01516E HDL: unable to open module hdt3270: /usr/local/lib/hercules/hdt3270.so: Undefined symbol "__errno_location"
HHC00007I Previous message from function 'hdl_loadmod' at hdl.c(281)
```
Searching binary points to four libraries with external symbol _errno_location:
```
Binary file telnet/lib/libtelnet32.a matches
Binary file telnet/lib/libtelnet32d.a matches
Binary file telnet/lib/libtelnet64.a matches
Binary file telnet/lib/libtelnet64d.a matches
```
so probably library is broken.
I see in the telnet/telnet.README.txt, that source code is:

- https://github.com/seanmiddleditch/libtelnet
- https://github.com/sdl-hercules-390/telnet

and I will try to build it myself, but building using cmake is terrific work.

**Comment by wrljet** [comment]
Hmm, it works for me.

I have set `LD_LIBRARY_PATH=/home/bill/herctest/herc4x/lib`

**Comment by wrljet** [comment]
Hi Ivan,

> May I ask why anyone may need git, bash and wget to _build_ hercules ? One should be able to build hercules from a source package using a standard bourne/posix shell and without having any internet access or having to resort to any source control program.

Yes, you may ask. :-)

The reason for `wget` is related to me copying my package list from my test system when I wrote up that documentation,
and it slipped in.  I will remove `wget` from the HTML doc page.

`git` is used by `_dynamic_version` during the build, if it is present.  And definitely recommended because it
allows us to know exactly what version of the source code was used during building, making debugging easier.

Similarly, `bash` is required by `_dynamic_version`.

Bill

**Comment by wrljet** [comment]
> Two addtonal things:
> 
>     * I use clang compiler, it is by default standard compiler in FreeBSD

Yes, same here.
 
>     * I noticed, that even I made `alias sed=gsed' I still receive error after running ./util/bldlvlck
> 
> 
> ```
> FreeBSD ==> custom version parsing!
>         sed: illegal option -- -
> HUH?    sed requires 3.02, found DUNNO
> ```

Just ignore that.  The sed on FreeBSD doesn't have a switch to report its version.

**Comment by wrljet** [comment]
I think we can close this one, Fish?

**Comment by nutilius** [comment]
I have working copy on my laptop. In free time I will repeat build in another FreeBSD environment. If the same problems appear I will open a new case. Now I think, that you can close this.
