### ISSUE TITLE
Question: Can I use VS2022 community to develop Hercules?

### ISSUE THREAD

**Issue by ssamayoa** [SDL-Hercules-390/hyperion#495]
Question: Can I use VS2022 community to develop Hercules?

**Comment by Fish-Git** [comment]
### FYI:

Such simple questions should not be asked via the GitHub Issues user interface. Instead, such questions should be directed to the main Hercules support group (forum) at:

  * https://hercules-390.groups.io/g/group

But to answer your question, yes, Hercules can be built using VS2022, but you'll need to perform a few minor housekeeping chores beforehand, as documented on my "Hercules Windows Build Instructions" web page at:

  * http://www.softdevlabs.com/hercules-vs2015-build.html

Then, just open the provided .sln Solution file and click Build or BuildAll. VOILA! Instant Hercules. &nbsp; `:)`

_**OR...**_ &nbsp; An even much _**easier**_ way to build Hercules on Windows is to use Bill Lewis's (wrljet) _most excellent_ "Hercules Helper" script, at:

  * https://github.com/wrljet/hercules-helper-windows

Bill's script completely automates everything thereby allowing you to quickly/easily build Hercules on Windows with just a simple command.

But again, _NEXT_ time we'd appreciate you asking such questions in our support forum and not here. Thanks for understanding.

Hope that helps!

**Comment by ssamayoa** [comment]
Thanks.

**Comment by wrljet** [comment]
FWIW I just tested Hercules-Helper on Win10 and let it install a fresh VS2022 and the required components/workloads.
It all worked.
