### ISSUE TITLE
Should CCKD Garbage Collector be disabled (and cckdcomp discouraged) by default?

### ISSUE THREAD

**Issue by Fish-Git** [SDL-Hercules-390/hyperion#504]
___
_**Note:** this issue is closely related to issue [\#490 "HHC00310E and HHC00342E on CCKD64 disk"](https://github.com/SDL-Hercules-390/hyperion/issues/490)._
___
After diligently trying (and failing) to determine the cause of (and fix for) issue #490 (and [related](https://github.com/SDL-Hercules-390/hyperion/issues/187) [issues](https://github.com/SDL-Hercules-390/hyperion/issues/194)), it has occurred to me that perhaps the idea of performing dynamic garbage collection on a "live" (in use) dasd image might not be such a good idea.

The very idea of doing in-place shuffling (relocation and updating) of various critical image-format structures (track images, L2 blocks, device header fields, etc) from one place to another while the image is still being used seems, well, inherently _dangerous_ to me.

It would be much safer (less risky IMO) to instead perform such things in a separate offline utility that only accesses the desired image read-only, creating a new output image as a result (which the user could then use to replace the original image with).

Additionally, while I have not performed any tests to either confirm or deny it, I can't help but wonder how well the garbage collector actually succeeds at helping to prevent a compressed dasd image from growing "unacceptably large".

Plus, when you add to all of this the already known bugs in the garbage collector itself (e.g. the [recently deprecated/neutered `cckd_gc_l2`/`cckd64_gc_l2` "Reposition level 2 tables" function](https://github.com/SDL-Hercules-390/hyperion/commit/6e4c52cda8c1354a658263beb2aac8b343b01252) (*)), I think it becomes clear _(at least it does to me!)_ that performing dynamic garbage collection (i.e. compression, essentially) on a "live" running system is simply too risky and can lead to damaged (potentially _seriously!_) dasd images, potentially leading to loss of user data.

Our existing CCKD logic that handles guest I/O appears to be sound and well designed (the idea of marking old track data as "pending" thereby preventing its immediate reuse in case anything goes wrong is a good one IMO), but the dynamic Garbage Collector idea? Not so much. &nbsp; `:(`

And finally, the nail in the coffin (hopefully), the very idea (design) that the preferred location of L2 tables should be at the very beginning of the image does not seem well thought out IMO. Level 2 (L2) tables should IMHO be kept near the track image data they are for. By preferring them (and indeed always relocating them) to be located at the beginning of the image (like both the garbage collector and `cckdcomp` utilities do) only serves to _increase_ the distance to a rather frequently accessed data structure from the very data it is for! (thereby making access to guest data _less_ efficient (slower) than it otherwise would be).

_**THEREFORE**_, I propose that we completely "neuter" (disable) our existing CCKD Garbage Collection logic altogether and instead simply report to the user when some predetermined free-space-to-used-space ratio is exceeded, so they can then deal with the situation manually themselves, in a much more controlled (and inherently _safer_) manner.

As far as `cckdcomp` (and `cckdcomp64` too of course) goes, it suffers from the same "in-place updating/modification" design flaw. Instead of _copying_ an uncompressed (fragmented) image to a new output image (thereby preventing the original image from being damaged should anything go wrong), it instead attempts the "shuffle things around" on the existing image, thereby increasing the change of catastrophic data loss should anything unfortunately go wrong during the effort.

Virtually _**all other**_ utilities on the other hand (such as `convto64` and `dasdcopy`, etc) always specify a separate _output_ file in addition to the required input file, thereby completely eliminating the likelihood of the original file ever being damaged.

So what do you think? Does what I've said above make sense? Yes? No?

I thank you for listening and I look forward to your thoughtful feedback and opinions regarding this proposed design change (enhancement).

Thanks.

________
(*) Which, ironically, I now have a fix for! I haven't tested it thoroughly enough to commit yet however, and besides, depending on the outcome of the above discussion, a fix for it may be moot anyway.

**Comment by Fish-Git** [comment]
Hello? Anyone there?

**Comment by wrljet** [comment]
Fish,

Can we add something that triggers the new announcement, but keep the original behavior for now.
And let people run that for a while.

Bill

**Comment by Fish-Git** [comment]
By "the new announcement" you mean the proposed change? Yes? Yeah, sure, we could do that. We could design some means of dynamically enabling/disabling the new proposed behavior (a command they could enter), thereby allowing the user to decide for themselves whether or not they wanted the new behavior or not.

[But we basically already have such a thing: **`cckd gcint=0`**](https://sdl-hercules-390.github.io/html/cckddasd.html#cckdcommand). That disables automatic garbage collection, converting it into a manual process instead. And of course if you never manually start the garbage collector (`cckd gcstart=1`), then it'll never run, thereby effectively "enabling" the new proposed behavior.

But I'd rather change the _default_ for gcint to 0 (thereby preventing it from automatically running) rather than keep its current default of 10. I'd rather do that and then monitor user reactions/feedback to that new behavior. I suggest this since I'm serious doubting very many people _(if any at all!)_ will likely add the needed `cckd` statement to their configuration files.

Instead, I'd rather change the default to the new behavior (effectively _disabling_ the garbage collector), while still allowing those few who _don't_ want the new behavior to easily obtain it via a simple `cckd gcint=10` statement/command.

I'm guessing most people wouldn't even KNOW (wouldn't even realize) the automatic garbage collector wasn't being automatically run.

The proposed change of issuing a new message whenever a dasd image's free-space-to-used-space ratio exceeded a certain limit is also something I recommend making a new default behavior as well, since it's a change that is technically completely unrelated to the other. That is to say, it's something that doesn't rely on whether the garbage collector is enabled or not. It's just a new completely benign message _MAY **eventually**_ be issued for some users, which they can easily react to whenever/_**IF-ever**_ it ever appears.

Does that make sense and is that agreeable? As I said, if we simply provide the ability to obtain the new behavior but requires users to specific ask for it, no one is ever going to. Instead, I'd rather do the opposite: enable the new behavior but provide a way for those who don't want it to be able to keep the old behavior.

**Comment by wrljet** [comment]
> 
> Does that make sense and is that agreeable? As I said, if we simply provide the ability to obtain the new behavior but require users to specifically request it, no one is ever going to. Instead, I'd rather do the opposite: enable the new behavior but provide a way for those who don't want it to be able to keep the old behavior.

Yes

**Comment by Fish-Git** [comment]
> Yes

Thanks, Bill.

I'm still slightly concerned no one else has commented yet on my proposal however.

Have I been (or am I being) "[ghosted](https://www.urbandictionary.com/define.php?term=Ghosting)"?

**Comment by ARandham** [comment]
Fish,
My 2 cents worth. I agree with your proposal to change the default behavior of garbage collection to gcint=0. 

Regarding cckdcomp, I would prefer that you left the "in place" operation as-is, or at least allow an option for "in place". Changing to new filenames for all the dasd devices would introduce file management problems with renaming,deleting, editing config files, disk space etc.

Andrew

**Comment by Fish-Git** [comment]
> My 2 cents worth. I agree with your proposal to change the default behavior of garbage collection to `gcint=0`.

Good! Thanks.

> Regarding `cckdcomp`, I would prefer that you left the "in place" operation as-is, or at least allow an option for "in place".

Huh? I must apologize if I have somehow mislead you into believing I was proposing to change the current behavior of `cckdcomp`, Andrew. I was not. I was simply pointing out that its current design/behavior, just like the garbage collector, is inherently dangerous (i.e. risky) IMO, that's all, The current behavior/design of `cckdcomp` is _not_ going to be changed! It is going to stay exactly the way it is. I was only suggesting that we should consider _discouraging_ its use, and to recommend our users to please use the `convto64` utility instead (which is much safer and faster too).

> Changing to new filenames for all the dasd devices would introduce file management problems with renaming, deleting, editing config files, disk space etc.

Again, huh? I'm not sure I understand what you're referring to. No editing of configuration files would be necessary. The procedure to compress a dasd image file under my proposal would involve just three simple commands instead of one, that's all (and those 3 commands could be placed into a simple script resulting in only _one_ simple command):

1. convto64 -q original-filename temp-filename
2. delete original-filename
3. rename temp-filename original-filename

You would simply run this script on demand whenever you wanted to (e.g. every few weeks? once a month?) as a matter of "routine system maintenance", after shutting down Hercules beforehand. No change to any existing configuration files would be necessary.

As far as disk space is concerned, [shadow files](https://sdl-hercules-390.github.io/html/cckddasd.html#shadowfiles) -- which IMHO _everyone_ should be using! -- are typically very small, the largest usually being only a few dozen megabytes in size. If your host disk space is so incredibly tight that you don't have room to make even one single copy of your largest shadow file, then I submit to you that you've got _much_ bigger problems to worry about than trying to compress your Hercules dasd images! &nbsp; `:)`

**Comment by Juergen-Git** [comment]
Sorry, I missed this thread, which is why I'm replying late.

1. I of course fully agree with Fish to neuter the garbage collector.

2. I'm not an active user of cckd, as I'm always running on not compressed DASD. Instead, I'm using ZFS with compression switched on on my Linux systems. That way, the task of efficiently and securely compressing data is done at the filesystem/storage level, where it logically belongs, imho. I'm of course aware that not every user will want to or is able to run on a compressing filesystem, which is why I refrain from proposing to remove CCKD support entirely ;-)

**Comment by Fish-Git** [comment]
Thanks, Jürgen. I appreciate the feedback. I'll get around to implementing my proposed changes eventually I'm sure. I'm just incredibly busy with other things right now,

I'm going to continue to keep this issue open to give others an opportunity to voice their own vote of confidence or objection. Thanks again and to all others who have replied so far too.

**Comment by Fish-Git** [comment]
Closed by commit 8111c37521c74cf968537754c0045777abaaa554.
