### ISSUE TITLE
Test "mainsize check storage size" fails on s390x CentOS 7

### ISSUE THREAD

**Issue by wrljet** [SDL-Hercules-390/hyperion#526]
Test "mainsize check storage size" fails on s390x CentOS 7

```
>>>>> line 19111: Informational message mismatch.
                  Want: HHC17006W MAINSIZE decreased to 2G architectural maximum
                  Got:  HHC02204I ARCHLVL        set to S/370
Test "mainsize check storage size":  25 OK compares.  One failure.
```

From `allTests.out`:

```
01:14:20 HHC01603I * Test 23
01:14:20 HHC01603I *If $ptrsize \= 4
01:14:20 HHC01603I archlvl z/Arch
01:14:20 HHC02204I ARCHLVL        set to z/Arch
01:14:20 HHC01603I mainsize 3g
01:14:20 HHC01430S Error in function configure_storage( 3G ): Cannot allocate memory
01:14:20 HHC00007I Previous message from function 'configure_storage' at config.c(338)
01:14:20 HHC02388E Configure storage error -1
01:14:20 HHC00007I Previous message from function 'mainsize_cmd' at hsccmd.c(3573)
01:14:20 HHC01603I archlvl s/370
01:14:20 HHC00811I Processor CP00: architecture mode S/370
01:14:20 HHC02204I ARCHLVL        set to S/370
01:14:20 HHC02204I LPARNUM        set to BASIC
01:14:20 HHC01603I *Info 1 HHC17006W MAINSIZE decreased to 2G architectural maximum
01:14:20 HHC01603I *Fi
```

**Comment by Fish-Git** [comment]
It looks like the test is expecting the `mainsize 3g` for z/Arch to succeed _(which would then trigger the expected `MAINSIZE decreased to 2G` message when archlvl 370 was set)_, but for some reason it's failing. That's very odd.

_**QUESTION:**_ &nbsp;Is the "s390x CentOS 7" host that this test is running on running under Hercules? I'm presuming so. Yes? _(Otherwise you'd have to have real 390x hardware which I'm doubting you have!)_

If so, then please check your (Hercules virtualized) host's Hercules configuration file to make sure your system has at least several gigabytes (3 or more) of MAINSIZE, and try again. That might be the problem right there.

Otherwise something else really weird is going on.

Let me know.

Thanks!

**Comment by wrljet** [comment]
> _**QUESTION:**_  Is the "s390x CentOS 7" host that this test is running on running under Hercules? I'm presuming so. Yes? _(Otherwise you'd have to have real 390x hardware which I'm doubting you have!)_

No, this is real IBM hardware, to which I have access.

**Comment by wrljet** [comment]
Also, keep in mind Linux handling of malloc() that it can't satisfy is not like on Windows.
(and is piss poor IMHO)

It'll say Yes, here you go.  And then if you actually try to use the memory, it crashes.

**Comment by wrljet** [comment]
Fish, just FYI, on some systems, like certain Raspberry Pi, I skip the 'mainsize' tests in Hercules-Helper,
because the systems have little RAM and Linux doesn't handle that well at all.

**Comment by Fish-Git** [comment]
> No, this is real IBM hardware, to which I have access.

Wow. Okay! I didn't realize that!

I'm no Linux expert _(but you knew that)_ but according to your free display, it looks to me like your system might not have enough memory?

> Also, keep in mind Linux handling of malloc() that it can't satisfy is not like on Windows. (and is piss poor IMHO)
> 
> It'll say Yes, here you go. And then if you actually try to use the memory, it crashes.

Well it's certainly not crashing in this case, just failing. One needs to keep in mind that in addition to the requested MAINSIZE amount, additional storage must be allocated for the storage-keys array as well. That is to say, even though `MAINSIZE 3g` is being requested, the amount actually requested via `calloc` is actually 3G + (3G/2048) bytes.

In any case, as I said, while I'm no Linux expert, it sure looks to me like you system doesn't have enough memory. Is it possible to incrase the size of your "LPAR"? (or whatever it is you're being given access to?)

**Comment by Fish-Git** [comment]
> Fish, just FYI, on some systems, like certain Raspberry Pi, I skip the 'mainsize' tests in Hercules-Helper,
> because the systems have little RAM and Linux doesn't handle that well at all.

Understood and makes perfect sense to me.

If you can't increase the size of your s390x LPAR (or whatever it is) then this might be another case where you'll just have to skip running this test.

Let me think about how we could maybe set a new rexx variable for maximum available mainsize or something. If we could set a new variable like that then the mainsize tests could check that new variable and skip their tests automatically.

I'm not sure it'll be possible, but let me think about it some.

**Comment by agadsby** [comment]
Looking at the output from your “free -h” it looks like you might need to increase the amount of swap. By the time you factor in the address space for Linux and other processes I think you might struggle to get the 3GBytes that your requesting. I’d up that swap area to 5GB and try again.

**Comment by wrljet** [comment]
I don't have that sort of admin authority to make a change like that. (And don't want to ask.)
For now I'll just up the cutoff point for what I deem a "low memory" system and skip the test.

**Comment by Fish-Git** [comment]
> Looking at the output from your “`free -h`” it looks like you might need to increase the amount of swap.

That looked suspect to me too. Thanks Andrew.

**Comment by Fish-Git** [comment]
> I don't have that sort of admin authority to make a change like that. (And don't want to ask.)

Oh well. It was a good thought while it lasted.

> For now I'll just up the cutoff point for what I deem a "low memory" system and skip the test.

Seems reasonable. Closing issue as "Invalid (User Error)".

**Comment by wrljet** [comment]
I think it would be a good enhancement to have to check the memory condition, like you mentioned above.

**Comment by Fish-Git** [comment]
> I may look into that when everything else settles down.

Myself as well. Remind me if I forget.
