### ISSUE TITLE
Tests "TRTE/TRTRE-01-basic" fail on s390x CentOS 7

### ISSUE THREAD

**Issue by wrljet** [SDL-Hercules-390/hyperion#528]
Tests "**TRTE**-01-basic" and "**TRTRE**-01-basic" fail on s390x CentOS 7.

<pre>
>>>>> line 23825: Received unexpected wait state:  0002000180000000 0000000000000BAD
Test "<b>TRTE-01-basic (Test TRTE instruction)</b>":  0 OK compares.  One failure.
>>>>> line 23936: Received unexpected wait state:  0002000180000000 0000000000000BAD
Test "<b>TRTRE-01-basic (Test TRTRE instruction)</b>":  0 OK compares.  One failure.
</pre>

<pre>
1:14:27 HHC01603I * Start of test file ../tests/<b>TRTE</b>-01-basic.tst date 2022-11-28 01:37:23.483148694 +0100 in /home/bill/herctest/hyperion/tests
01:14:27 HHC01603I *
01:14:27 HHC01603I *Testcase <b>TRTE</b>-01-basic (Test <b>TRTE</b> instruction)
01:14:27 HHC01603I mainsize    16
01:14:27 HHC17003I MAIN     storage is 16M (mainsize); storage is not locked
01:14:27 HHC01603I numcpu      1
01:14:27 HHC02204I NUMCPU         set to 1
01:14:27 HHC01603I sysclear
01:14:27 HHC02311I sysclear completed
01:14:27 HHC01603I archlvl     z/Arch
01:14:27 HHC00811I Processor CP00: architecture mode z/Arch
01:14:27 HHC02204I ARCHLVL        set to z/Arch
01:14:27 HHC01603I loadcore    "../tests/TRTE-01-basic.core" 0x0
01:14:27 HHC02250I Loading file ../tests/TRTE-01-basic.core to location 0
01:14:27 HHC02249I Operation complete
01:14:27 HHC02336I Script 1: test: test starting
01:14:27 HHC02339I Script 1: test: duration limit: 2.000000 seconds
01:14:27 HHC02228I restart key pressed
01:14:27 HHC02333I Script 1: test: running...
01:14:27 HHC00809I Processor CP00: disabled wait state 0002000180000000 0000000000000BAD
01:14:27 HHC02334I Script 1: test: test ended
01:14:27 HHC02338I Script 1: test: actual duration: 0.000000 seconds
01:14:27 HHC01603I *Done
01:14:27 HHC01603I * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
</pre>

<pre>
01:14:27 HHC01603I * Start of test file ../tests/<b>TRTRE</b>-01-basic.tst date 2022-11-28 01:37:23.493148694 +0100 in /home/bill/herctest/hyperion/tests
01:14:27 HHC01603I *
01:14:27 HHC01603I *Testcase <b>TRTRE<</b>-01-basic (Test <b>TRTRE</b> instruction)
01:14:27 HHC01603I mainsize    16
01:14:27 HHC17003I MAIN     storage is 16M (mainsize); storage is not locked
01:14:27 HHC01603I numcpu      1
01:14:27 HHC02204I NUMCPU         set to 1
01:14:27 HHC01603I sysclear
01:14:27 HHC00811I Processor CP00: architecture mode ESA/390
01:14:27 HHC02311I sysclear completed
01:14:27 HHC01603I archlvl     z/Arch
01:14:27 HHC00811I Processor CP00: architecture mode z/Arch
01:14:27 HHC02204I ARCHLVL        set to z/Arch
01:14:27 HHC01603I loadcore    "../tests/TRTRE-01-basic.core" 0x0
01:14:27 HHC02250I Loading file ../tests/TRTRE-01-basic.core to location 0
01:14:27 HHC02249I Operation complete
01:14:27 HHC02336I Script 1: test: test starting
01:14:27 HHC02339I Script 1: test: duration limit: 2.000000 seconds
01:14:27 HHC02228I restart key pressed
01:14:27 HHC00809I Processor CP00: disabled wait state 0002000180000000 0000000000000BAD
01:14:27 HHC02333I Script 1: test: running...
01:14:27 HHC02334I Script 1: test: test ended
01:14:27 HHC02338I Script 1: test: actual duration: 0.000000 seconds
01:14:27 HHC01603I *Done
01:14:27 HHC01603I * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
</pre>

**Comment by Fish-Git** [comment]
Hmmm... &nbsp;maybe yet another issue with endianness?? &nbsp; _(just a wild-assed guess!)_

_(Sigh!)_ &nbsp;Let me take a look at Jame's code, and I'll get back to you...

_**In the mean time...**_ &nbsp;It would be _tremendously_ helpful if you could run this one specific test by itself with instruction tracing turned on (`t+`) for me, and upload the results to here.

Based on the `HHC02338I` "actual duration" message, it looks like it's blowing up right away, so the resulting trace should hopefully be fairly smallish.

Thanks!

**Comment by wrljet** [comment]
OK

**Comment by wrljet** [comment]
Fish,

Here's the t+ output for TRTE-01-basic test on s390x.  Almost 13,000 lines.  That's "fairly smallish" I guess.

[TRTE-01-basic.zip](https://github.com/SDL-Hercules-390/hyperion/files/10124729/TRTE-01-basic.zip)

**Comment by Fish-Git** [comment]
> Here's the `t+` output for TRTE-01-basic test on s390x.

Got it. Thanks.

> Almost 13,000 lines. That's "fairly smallish" I guess.

Wow! I wasn't expecting that. Sounds like it may have mostly worked! I wonder what's going on? Oh well. Time to start digging into it. Thanks again, Bill. I'll get back to you.

**Comment by JamesWekel** [comment]
Sorry for joining this party a bit late. Thanks for the instruction trace for TRTE-01-basic test. 

Yes, there is an endianness issue. The failing test number is 'CB' which is testing a 128K Function code table and the 2 bytes function code crosses a page boundary. The TRTE/TRTRE code (general2.c about line 3284) is putting the 2 byte Function Code together as a little endian and then doing a CSWAP16... Wrong.    e.g
```
            if (f_bit)
            {
                fc_addr    = fct_addr + (arg_ch * 2);
                fc_page_no = fc_addr >> PAGEFRAME_PAGESHIFT;

                /* NOTE: The user *should* have specified a double-word
                         aligned FC table address, but since they might
                         not have, we still need to always perform the
                         below check. */

                /* Does FC cross page boundary? (last byte of page?) */
                if ((fc_addr & PAGEFRAME_BYTEMASK) == PAGEFRAME_BYTEMASK)
                {
                    /* Yes! Piece together the FC */
                    temp_l  =  *(fct_main_page_addr[ fc_page_no - fct_page_no + 0 ] + PAGEFRAME_BYTEMASK ); // (last byte of page)
                    temp_h  =  *(fct_main_page_addr[ fc_page_no - fct_page_no + 1 ] );                      // (first byte of next page)
                    fc      =   CSWAP16 ( (temp_h << 8) | temp_l ) ;
                }
                else
                    fc =  CSWAP16( *(U16*) (fct_main_page_addr[ fc_page_no - fct_page_no ] + (fc_addr & PAGEFRAME_BYTEMASK)));
            }
```
There is a similar problem getting a 2 byte argument character from operand 1 (about line 3255).

BUT, fixing the endianness leads to a 2nd problem. Either the test is wrong (the test would now fail on little endian machine) or there is an additional problem somewhere. 

Bill, is it possible to run the TRTE-01-basic test (with instruction tracing) on the Hercules 4.4.1 version just to make sure the test works? 

Fish, as I created the problem, I'm adding my 2 cents to fix it. 

Jim

**Comment by wrljet** [comment]
> Bill, is it possible to run the TRTE-01-basic test (with instruction tracing) on the Hercules 4.4.1 version just to make sure the test works?

Sure.  Here you go.

[TRTE-01-basic-4.4.1.zip](https://github.com/SDL-Hercules-390/hyperion/files/10126932/TRTE-01-basic-4.4.1.zip)

**Comment by JamesWekel** [comment]
Thanks Bill. The test works on both big-endian and little-endian machines before the change. 

The problem is that I was overthinking endianness on the page cross! I don't need the CSWAP16, just build a big endian function code or argument character.

Fish, I'll submit a pull request for your consideration later this afternoon. There is one other small change that I'll include to address a potential cross page issue getting the initial mainstore address for the argument.  

Jim

**Comment by JamesWekel** [comment]
Fish, pull request submitted. I hope that fixes the issue on s390x CentOS 7. I'm not sure how to start on the fails issue with "Sun Sparc64. But on there Hercules crashes outright". 

Jim

**Comment by wrljet** [comment]
I will give it a try on the s390x and if that works, then on the Sparc.

**Comment by wrljet** [comment]
Works now on the s390x.

```
Test "TRE-01-basic (Test TRE instructions)":  1 OK compares.  All pass.
Test "TRE-02-performance (Test TRE instructions)":  1 OK compares.  All pass.
Test "TRTE-01-basic (Test TRTE instruction)":  1 OK compares.  All pass.
Test "TRTE-02-performance (Test TRTE instruction)":  1 OK compares.  All pass.
Test "TRTR-01-basic (Test TRTR instruction)":  1 OK compares.  All pass.
Test "TRTR-02-performance (Test TRTR instruction)":  1 OK compares.  All pass.
Test "TRTRE-01-basic (Test TRTRE instruction)":  1 OK compares.  All pass.
Test "TRTRE-02-performance (Test TRTRE instruction)":  1 OK compares.  All pass.
```

**Comment by Fish-Git** [comment]
James Wekel wrote:
> Fish, pull request submitted. I hope that fixes the issue on s390x CentOS 7.

Bill Lewis wrote:
> Works now on the s390x.

Excellent work, James!

I will review your Pull Request, but I'm sure it's fine (given that it now works on s390x).

Bill? I presume you're going to verify for us that it now _(Hopefully!)_ also works on Sun Sparc64 too?

**Comment by wrljet** [comment]
Fish, James,

> Excellent work, James!

Yes, I was going to say that myself!


> Bill? I presume you're going to verify for us that it now _(Hopefully!)_ also works on Sun Sparc64 too?

Working on it.  I was running some MVS jobs to do more thorough testing overall.
And then wound up having to build Python from scratch to run the scans on the output.
(NetBSD isn't a lot of fun if you're not used to it, or one of its fanboys.)

But, it still crashes on the Sparc64.  I managed to get better info out of gdb, though.

```
Program terminated with signal SIGBUS, Bus error.
#0  z900_translate_and_test_xxx_extended (inst=<optimized out>, regs=0x412d9000) at ../general2.c:3262
3262                    arg_ch = CSWAP16( *(U16*) buf_main_addr );
```

Line 3262 is just after part of the new patch.

Bill

**Comment by Fish-Git** [comment]
> But, it still crashes on the Sparc64.

That's concerning. &nbsp; `:(`

> I managed to get better info out of gdb, though.
> 
> ```
> Program terminated with signal SIGBUS, Bus error.
> #0  z900_translate_and_test_xxx_extended (inst=<optimized out>, regs=0x412d9000) at ../general2.c:3262
> 3262                    arg_ch = CSWAP16( *(U16*) buf_main_addr );
> ```
> 
> Line 3262 is just after part of the new patch.

_(Doh!)_ &nbsp; Thanks! The bug is obvious now. It's the `CSWAP16` that's crashing because the pointer to the 16-bit value to be swapped _isn't aligned!_ Recall that Sparc requires its operands to be strictly aligned! Thus the reason for the special handling we have in our various `vfetch` functions in  `vstore.h`:

https://github.com/SDL-Hercules-390/hyperion/blob/b488236a9788efbba625f27bdf60c0c782d941dc/vstore.h#L675-L689

https://github.com/SDL-Hercules-390/hyperion/blob/b488236a9788efbba625f27bdf60c0c782d941dc/vstore.h#L386-L411

&nbsp;
James simply needs to change his `CSWAP16` functions to `ARCH_DEP( vfetch2 )` instead _(being careful to use the **virtual** address of the corresponding argument or function table and not the mainstore address (which would no longer be needed once the change is made)).

James? Does that make sense? Do you want to fix your Pull Request and resubmit it?

___
p.s. I also have an idea that might help speed things up even more too: pre-construct a local Function Code "lookaside" table (i.e. essentially a copy of the instruction's FC Table copied into a local work table) and use that instead in your code. That would eliminate a lot of the complexity in your existing code I would think and likely help speed things up considerable by virtue of the fact that the table would no longer be spread across multiple disparate real pages in storage, allowing virtually _ALL (more than likely!)_ FC table accesses to be resolved from host processor cache.

What do you think?

If you don't want to mess with it, I understand. But if you don't, I think I might give it a whirl myself. So let me know. I don't want to spend my time doing it if you're going to end up doing it! &nbsp; `:)`

**Comment by JamesWekel** [comment]
Fish,

I've updated the pull request with a different solution; just build the U16 FC and argument character. Your call as to which option to implement. 

I'm not going to work on a version that copies the FC Table. So, give it a whirl. :)

Jim

**Comment by wrljet** [comment]
Second patch applied to Spark64, fixes the issue.

```
Test "TRE-01-basic (Test TRE instructions)":  1 OK compares.  All pass.
Test "TRE-02-performance (Test TRE instructions)":  1 OK compares.  All pass.
Test "TRTE-01-basic (Test TRTE instruction)":  1 OK compares.  All pass.
Test "TRTE-02-performance (Test TRTE instruction)":  1 OK compares.  All pass.
Test "TRTR-01-basic (Test TRTR instruction)":  1 OK compares.  All pass.
Test "TRTR-02-performance (Test TRTR instruction)":  1 OK compares.  All pass.
Test "TRTRE-01-basic (Test TRTRE instruction)":  1 OK compares.  All pass.
Test "TRTRE-02-performance (Test TRTRE instruction)":  1 OK compares.  All pass.
```

**Comment by Fish-Git** [comment]
> I'm sorry to cause such a server error in your new 4.5 release.

Don't worry about it. These things happen.

> I am interested in your eventual solution to test Hercules on a big-endian system. Something that I should probably add to my environment for testing.

Me too. I'll let you know when I get something.

**Comment by wrljet** [comment]
We're working on the emulated s390x zLinux solution.

**Comment by wrljet** [comment]
Jim,

> I'm sorry to cause such a server error in your new 4.5 release.

That's nothing.

Really it's my fault, because I hadn't run a build and test on the s390x for quite a while.
And I only just got involved with "Sparky" when a friend mentioned the NetBSD pkgsrc for SDL-Hercules 4.4.1 didn't build.

Bill
