### ISSUE TITLE
Maybe a bug in 4.5 in hercifc

### ISSUE THREAD

**Issue by jdeckerus** [SDL-Hercules-390/hyperion#533]
___
_**Note:** this issue appears to be a duplicate of issue [\#525: "Crash in Hercules 4.5"](https://github.com/SDL-Hercules-390/hyperion/issues/525)._
___
```
HC02499I Hercules utility hercifc - Hercules Network Interface Configuration Program - version 4.5.0.0-SDL
HHC01414I (C) Copyright 1999-2022 by Roger Bowler, Jan Jaeger, and others
HHC01417I ** The SoftDevLabs version of Hercules **
HHC01415I Build date: Nov 27 2022 at 16:58:59
HHC01474I Using internal codepage conversion table default
HHC00166E hercifc: ioctl error doing SIOCSIFMTU on sion table defa: 19 No such device; ... ignoring and continuing
HHC00007I Previous message from function 'main' at hercifc.c(274)
HHC00166E hercifc: ioctl error doing SIOCSIFADDR on sion table defa: 19 No such device; ... ignoring and continuing
```

In my hercules.cnf I have

```
  0300.2  LCS     192.168.1.51
```

I reinstall 4.4.1 and the messages are not displayed and the LCS device works.

I'm running Fedora 37 (6.0.11-300.fc37.x86_64)

I install Hercules on Linux via

```
tar zxvf Hyperion-Release....
cd to directory created
./util/bldlvlck
./configure
make > Zmake.txt 2> Zmake.err
sudo make install
sudo chmod u+s /usr/local/bin/hercifc
sudo chmod u+s /usr/local/bin/hercules
```

I looked at Zmake.txt and Zmake.err and saw no errors.

It appears to be a 4.5 problem.

**Comment by wrljet** [comment]
John,

That is a known issue.  It has been debugged and a fixed coded.
I will be committing the changes as soon as I finish some testing on a few different OSes, etc.
(likely today)

Issue https://github.com/SDL-Hercules-390/hyperion/issues/525

Bill

**Comment by wrljet** [comment]
Corrected with commit https://github.com/SDL-Hercules-390/hyperion/commit/2e2e942fb38f43842e8a9e2800aa42c346bfb050
