### ISSUE TITLE
hetbsf.tst fails for BZIP2 on s390x

### ISSUE THREAD

**Issue by Fish-Git** [SDL-Hercules-390/hyperion#535]
The `hetbsf.tst` performs two identical tests: the first using a ZLIB compressed `.het` tape as input, the second using a BZIP2 compressed `.het` tape as input. On s390x systems/guests, the second BZIP2 test always fails:

```
   >>>>> line  8786: Received unexpected wait state:  000A0000 00EEEEEE
   >>>>> line  8800: Storage compare mismatch.
                     Want: R:00000500 E5D6D3F1  
                     Got:  R:00000500 FFFFFFFF
   >>>>> line  8805: Storage compare mismatch.
                     Want: R:00000510 0048  
                     Got:  R:00000510 FFFF
   >>>>> line  8810: Storage compare mismatch.
                     Want: R:00000510 E5D6D3F1  
                     Got:  R:00000510 FFFFFFFF
   Test "S/370 HET (BZIP2) tape BSF into Load Point":  1 OK compares.  4 failures.
```

Further research has revealed the failure is due to an incorrect API call to the `BZ2_bzBuffToBuffDecompress` libbz2 (bz2) function in source member `hetlib.c`'s  `het_read` function:

https://github.com/SDL-Hercules-390/hyperion/blob/58578601d7a34fc11f050b0ac4fd425a4c0422eb/hetlib.c#L964-L984

The problem stems from the fact that the bzip2 `BZ2_bzBuffToBuffDecompress` API is actually defined in header `bzlib.h` as:

```C
BZ_EXTERN int BZ_API(BZ2_bzBuffToBuffDecompress) (
      char*         dest,
      unsigned int* destLen,
      char*         source,
      unsigned int  sourceLen,
      int           small,
      int           verbosity
   );
```

but Hercules's `het_read` function in  `hetlib.c` is passing `unsigned long` values _(instead of `unsigned int` values)_ for the `destLen` (`slen`) and `sourceLen` (`tlen`) parameters:

https://github.com/SDL-Hercules-390/hyperion/blob/58578601d7a34fc11f050b0ac4fd425a4c0422eb/hetlib.c#L765-L772

&nbsp;
**Recall that s390x systems** _(just like most other non-Windows systems)_ **are [LP64](https://en.wikipedia.org/wiki/64-bit_computing#64-bit_data_models), not [LLP4](https://en.wikipedia.org/wiki/64-bit_computing#64-bit_data_models).** &nbsp;_(where 'long' is 64 bits, not 32 bits like an 'int' is)_

When the `slen` and `tlen` variables in the `het_read` function are properly declared as `unisgned int`, the test passes.

The same bug exists in the `het_write` function as well, where the `BZ2_bzBuffToBuffCompress` API call is being made.

This GitHub Issue is being created to simply document the bug and the resulting upcoming fix, which I will be making shortly.
&nbsp;

**Comment by Fish-Git** [comment]
Fixed by commit 7ab077ebf3ab71cfa5e4fd0eef15db677a652d2e.

Closing.

**Comment by wrljet** [comment]
You're closing before it's tested on the Spark64?

**Comment by Fish-Git** [comment]
> You're closing before it's tested on the Spark64?

Yes. Based on my analysis I am 99.999%+ confident the Sparc64 bug is identical and thus the fix just committed will also fix it too.

**Comment by Fish-Git** [comment]
> Yes. Based on my analysis I am 99.999%+ confident the Sparc64 bug is identical and thus the fix just committed will also fix it too.

_(SIGH!)_ &nbsp; Or at least it would if I had implemented it correctly! _(the way I actually tested it!)_

Sorry about that. &nbsp; `:(`

New commit d53fc0c897a6e7f3f644d794e2b97dd3afc8485d replaces previous commit.

**Comment by wrljet** [comment]
10-4

**Comment by wrljet** [comment]
OK, with commit https://github.com/SDL-Hercules-390/hyperion/commit/d53fc0c897a6e7f3f644d794e2b97dd3afc8485d the tests now pass on Hercules emulated s390x zLinux Ubuntu 18, real hardware s390x zLinux Centos 7, and Sun Sparc64 NetBSD 9.

(just mentioning for completeness, the original "fix", commit https://github.com/SDL-Hercules-390/hyperion/commit/7ab077ebf3ab71cfa5e4fd0eef15db677a652d2e resulted in compiler warnings related to the fix, failed ZLIB test on s390x, and a crash on the Sparc64.)

**Comment by Fish-Git** [comment]
> the original "fix", commit [7ab077e](https://github.com/SDL-Hercules-390/hyperion/commit/7ab077ebf3ab71cfa5e4fd0eef15db677a652d2e) resulted in compiler warnings related to the fix, failed ZLIB test on s390x, and a crash on the Sparc64.)

Yep. I saw the compiler warnings too, which is how I knew I f**ked up.

Glad to hear all is well now. I'm still having trouble testing it on my system though. I do a git pull and it says up to date, but after building it (make followed by make install), for some reason it's still saying it's at version g2e984f9a, which I don't understand! I must have done something wrong. I'm in the middle of doing everything all over again, but as you know it takes freaking forever.

**Comment by wrljet** [comment]
Using the same system under Windows 7 ( although God knows what you've done to it ), what I did in zLinux:

```
cd ~/herctest/hyperion
git fetch
git pull
cd build
make
make check
```

And yes, it took freakin' forever.

**Comment by Fish-Git** [comment]
I don't know what I was doing wrong or why it wasn't working, but I decided to just do a `hyperion-buildall.sh -v -p`, which, as expected, took forever, but eventually finished successfully, and now my Hercules properly reports version gd53fc0c8.

FWIW I was doing the exact same thing (except for the `git fetch` which I wasn't doing; is it important?), and each time, after the make (followed by a make install of course), it would still report the same version. I don't know why.

But the problem's moot. I did manage to get the system build using your hercules-helper script and all is fine now.

**Comment by wrljet** [comment]
Fish,

If you just run what I did, perhaps it'll skip the `_dynamic_version` so the informational display will be out of date?

As far as `git fetch` goes...  I hate git and don't get it.  So I don't know if it's needed or not.  Probably it isn't needed.

> I'm not sure what you mean by "(although God knows what you've done to it)". Except for a single alias command (cls=clear) and adding . (current directory) to the $PATH, it's exactly the same system you sent me.

I was being cute.

Having `.` in the PATH is considered by some to be a security risk.

Bill

**Comment by wrljet** [comment]
The fact that it runs forever, and everything actually works, is a pretty good thing, don't you think?

**Comment by Fish-Git** [comment]
> If you just run what I did, perhaps it'll skip the `_dynamic_version` so the informational display will be out of date?

Probably. My *nix skills are weak.

> > I'm not sure what you mean by "(although God knows what you've done to it)".
> 
> I was being cute.

Ah. My bad. Missed that. &nbsp;`:)`

> Having `.` in the PATH is considered by some to be a security risk.

I'm aware of that. Given how I use my system however it's not a real concern to me. It's more convenient to me to be able to enter the name of a command or script without having to always prefix it with `./`. If I want to run the script `foobar` in my current directory, I want to be able to enter just `foobar` to run it, not `./foobar`. It's just a personal preference of mine.

**Comment by Fish-Git** [comment]
> The fact that it runs forever, and everything actually works, is a pretty good thing, don't you think?

Absolutely! It works quite well! I'm quite proud of your hard work, and you should be too! &nbsp;`:))`
