### ISSUE TITLE
SDL Hercules : CTCI: Error writing to device tun0: 22 Invalid argument

### ISSUE THREAD

**Issue by zzd10h** [SDL-Hercules-390/hyperion#544]
Hi,

I just migrated from a Windows 10 PC to a new Windows 11 PC. 

Now when I try to use FTP or telnet to access to z/OS, CTCI crashes and a VTAM or TCPIP or telnet abend occurs on the z/OS side, and the CTC device recovers.

I used the same z/OS 2.4 files and the same SDL Hercules _(**4.5.0.10830-SDL-g58578601**)_ on both WIndows 10 & Windows 11.

The ping works fine, FTP and telnet connection seems to work but, crashes occurs as soon as I retrieve data from z/OS (`ls` command from FTP or when I enter my password after providing my userid during a telnet connection login).

_I just tested today with latest develop Hyperion under **Linux** with the same z/OS DASD/config, and **it works fine**._
&nbsp;

**Summary of attachments:**

Windows version = **Windows 11 Pro 22H2**
Hercules version = **4.5.0.10830-SDL-g58578601**
Hercules configuration = **zOS24_conf.txt**
Hercules log showing "CTCI: Error writing to device tun0: 22 Invalid argument" = **hercules.log**
Guest OS is **z/OS 2.4**.
Guest TCPIP Profile = **TCP_PROFILE.txt**
Guest TCPIP joblog showing CTC recovering = **TCPIP.log**
CTCI-WIN TTTest64U seems OK = **TTTest64U.txt**
Hercules `version` command output = **Version.txt**

Thank you for your help

Guillaume
___
(Attachments):

* [hercules.log.txt](https://github.com/SDL-Hercules-390/hyperion/files/10776592/hercules.log.txt)
* [TCP_PROFILE.txt](https://github.com/SDL-Hercules-390/hyperion/files/10776593/TCP_PROFILE.txt)
* [TCPIP.log.txt](https://github.com/SDL-Hercules-390/hyperion/files/10776594/TCPIP.log.txt)
* [Version.txt.txt](https://github.com/SDL-Hercules-390/hyperion/files/10776595/Version.txt.txt)
* [zOS24_conf.txt](https://github.com/SDL-Hercules-390/hyperion/files/10776596/zOS24_conf.txt)
* [TTTest64U.txt](https://github.com/SDL-Hercules-390/hyperion/files/10776604/TTTest64U.txt)

**Comment by zzd10h** [comment]
Just compiled and tried the latest SDL devel version (4.6.0.0-SDL-DEV) under Windows 11, same crashs

**Comment by zzd10h** [comment]
It seems that this problem could be related to the amount of data retrieved from z/OS. 
Tried FTP "ls" command for a user with few datas (few files on host to be returned), it works.
With another user with more datas (more files on host to be returned), it fails.


See FTP_OK_KO.png attached. GBO user at left works, IBMUSER at right failed.

Thanks

![Uploading FTP_OK_KO.png…]()

**Comment by zzd10h** [comment]
![FTP_OK_KO](https://user-images.githubusercontent.com/125796623/220198036-7a5523c1-f6c8-4d85-a799-ca71cf7e98be.png)

**Comment by Fish-Git** [comment]
> It seems that this problem could be related to the amount of data retrieved from z/OS.
> 
> I tried FTP `ls` command for a z/OS user with fewer files (smaller `ls` results amount to be returned), and it works.
> 
> With a different z/OS user with many more files, (much larger `ls` results amount to be returned), and it fails:

_**THANK YOU!**_ "zzd10h", for this important clue!

I'm current busy working on something else right now, so I unfortunately do not have time at the moment to investigate further into this issue (bug), but I assure you once I find the time, I _**will**_ look into this issue!

In the mean time, have you tried using a different FTP client? I myself use [**FileZilla**](https://filezilla-project.org/) on my Windows system, and it can list _ALL_ of `IBMUSER`'s files just fine. I notice you're using Windows's native FTP client. Many users have reported problems with Microsoft's command-line FTP client. As a workaround (until this bug can be located and fixed), I _**highly recommend**_ that you use a different FTP client such as [FileZilla](https://filezilla-project.org/).

_p.s. What is you name? Or do you prefer that we continue to refer to you as "zzd10h"?_

**Comment by zzd10h** [comment]
![FileZilla](https://user-images.githubusercontent.com/125796623/220323851-4e321165-f2e2-40d4-b9f6-91ffd8dfaaad.png)

**Comment by Fish-Git** [comment]
Well, one thing I noticed about your z/OS and Hercules configuration for your CTCI device is you are using (or trying to use) an IP address that is not in your Windows host's subnet. That is usually a huge no-no. The CTCI-WIN Help file mentions this (but probably not forcefully enough):

> _It is very important that whatever IP address you choose for your guest operating system, that it be in the same subnet as your Windows system!  This cannot be stressed enough.  Networking will not work correctly if it's not._
>
> _Basically your guest running under Hercules should be configured the same way you would configure any other real system that's physically connected to your local network. Same default gateway, same subnet, etc._
>
> _If you wish to isolate your guest by placing it into a separate subnet, then you can certainly do that.  But then you will of course need to use a bridge or define special routes to have the packets properly routed between the two subnets, which can be confusing to most people unskilled in networking._
>
> _Thus it is usually best (easiest) to keep things as simple as possible and always place your Hercules guest in the same subnet as your Windows host._

Your TTTest64U reports that the IP address of your Windows adapter is `192.168.1.41`:

```
11:21:54.293 Connection          = Ethernet
11:21:54.293 AdapterName         = NPF_{E624C55F-2C7B-4CBA-A74D-445B36658BDF}
11:21:54.293 Description         = Realtek Gaming 2.5GbE Family Controller
11:21:54.293 PhysAddr            = 74-56-3C-37-59-0A
11:21:54.293 LinkType            = NdisMedium802_3
11:21:54.293 Default Adapter?    = No
11:21:54.293 MediaConnected?     = Yes
11:21:54.293 PromiscuousMode?    = Yes
11:21:54.293 DHCP Enabled?       = Yes
11:21:54.293 LinkSpeed           = 1.0 Gbps
11:21:54.293 MaxPacketLen        = 1514
11:21:54.293 IPAddr              = 192.168.1.41
11:21:54.293 IPAddrMask          = 255.255.255.0
11:21:54.293 GatewayIPAddr       = 192.168.1.1
11:21:54.293 dwIndex             = 0x00000014
```

But your Hercules CTCI device statement is:
```
0A00.2  CTCI    10.1.10.190 10.1.10.90
```
and your z/OS TCPIP PROFILE specifies:
```
 HOME
   10.1.10.190   CTC1L

 BEGINRoutes
 ROUTE 10.1.10.0/24              =            CTC1L     MTU 1500
 ENDRoutes
```

This is wrong.

IP address 10.1.10.90 is your Loopback adapter, which you should not need. You should remove (delete) your unneeded Loopback adapter device, and use your existing "Realtek Gaming" adapter instead.

After deleting your unneeded Loopback device and rebooting, change your Hercules CTCI device statement to:
```
0A00.2  CTCI    192.168.1.xxx   192.168.1.41
```
where "xxx" is your chosen guest IP address.

Then change your z/OS TCPIP PROFILE to:
```
 HOME
   192.168.1.xxx   CTC1L

BEGINRoutes
;     Destination   SubnetMask      FirstHop     LinkName   MTU Size
ROUTE 192.168.1.0   255.255.255.0      =         CTC1L      MTU 1492
ROUTE DEFAULT                     192.168.1.1    CTC1L      MTU 1492
ENDRoutes
```

Once you have made the above changes, things should hopefully work better for you.

I suspect the reason you are getting your "tun0: 22 Invalid argument" error is because you are trying to use a Looback device, which CTCI-WIN apparently doesn't like. I don't know why it doesn't like it, but I'm guessing it is because WinPCap doesn't like it.

When you installed WinPcap, did you specify WinPcap or Npcap? Only WinPcap is supported by CTCI-WIN. Npcap is not supported. You should not use Npcap. You should use only WinPcap.

I hope that helps!

**Comment by zzd10h** [comment]
Wonderful, it works now. Many thanks.

But strangely, I used CTCI-WIN, Winpcap and MS Loopback adapter since years and it worked well even if I wasn't in the same subnet. Maybe that something changed in Windows 11 Pro.

_"Thus it is usually best (easiest) to keep things as simple as possible and always place your Hercules guest in the same subnet as your Windows host."_
I will follow your recommandation now.
Many thanks Fish ;)

Guillaume, new registered user of your tools ;)

**Comment by Fish-Git** [comment]
> Wonderful! It works now! Many thanks!

Fantastic! I am very happy for you. &nbsp; `:)`

> I will follow your recommendation from now on.

That's good to hear.

I would also recommend switching to using either LCS or OSA (QETH) devices too _(and not CTCI devices)_, but I didn't want to confuse you by rocking the boat too much.

It appears CTCI devices still work with z/OS. For now. How much longer that will remain true I don't know. I suspect IBM will eventually drop support for CTCI networking devices at some point in the future, so it's best (IMO) to become familiar with using QETH/OSA devices now.

But then, that's just me. That's just my personal feeling.

You of course can continue to do things your own way. &nbsp; `;-)`

I am closing this issue as Resolved.

**Comment by Fish-Git** [comment]
@zzd10h

Guillaume,

Have you tried [**FileZilla**](https://filezilla-project.org/) again? Now that your problem has been fixed, FileZilla _should_ work quite nicely for you.

**Comment by zzd10h** [comment]
Hi,
No, DOS FTP client still works fine but FileZilla is still blocked in "Connection established, waiting for welcome message...".
But as I tested too with FileZilla under Linux and as I have the same problem, it should be my z/OS.

**Comment by Fish-Git** [comment]
> No, FileZilla unfortunately still does not work. It still gets stuck in: "Connection established, waiting for welcome message...".

> I tested FileZilla under Linux too, and I have the same problem, so it could be my z/OS?

Maybe you don't have FileZilla configured properly? It works file for me:

Here is my FileZilla "**Site Manager**" entry for z/OS 2.5c:

&nbsp;
**"General" tab:**

_The "**Protocol**" is plain FTP, and the "**Encryption**" is also plain (insecure) FTP too:_
&nbsp;

![filezilla1](https://user-images.githubusercontent.com/1486786/221053902-c6aa87f2-cb9b-4996-8474-ffd845703b68.png)

&nbsp;
**"Advanced" tab:**

_The "**Server Type**" is z/OS, and the "**Default remote directory**" must be a valid z/OS format name (e.g. **`'ADCD.'`**. Make sure it is enclosed within single quotes (apostrophes), and ends with a dot:_
&nbsp;

![filezilla2](https://user-images.githubusercontent.com/1486786/221053924-43e92213-0534-4f9e-b8bb-112d310a2f86.png)

&nbsp;
_**And as you can see, it works just fine for me!**_
&nbsp;

![filezilla3](https://user-images.githubusercontent.com/1486786/221053990-10412353-da2e-43e4-8e12-a54fd7ee7f58.png)

&nbsp;
**I hope that helps!**
&nbsp;

**Comment by zzd10h** [comment]
Thank you, I don't know what I missed but now FileZilla works fine :)
