### ISSUE TITLE
Incorrect S/370 Floating Point functionality when FEATURE_370_EXTENSION is #defined

### ISSUE THREAD

**Issue by Fish-Git** [SDL-Hercules-390/hyperion#546]
___
_**Note:** this issue is closely related to issue [\#543: "FPR display command when CR0_AFP is off"](https://github.com/SDL-Hercules-390/hyperion/issues/543)._
___
_(CC: @ivan-w, @srorso, @s390guy)_

### THE PROBLEM

salva-rczero _(I don't know his real name)_ recently reported a problem with Hercules's display of floating point registers when the `CR0-AFP` bit is off. &nbsp; _(See GitHub Issue #543)_

I began looking into this problem and, much to my surprise, discovered that S/370 Floating Point functionality is currently _**totally borked!**_ &nbsp; `:(`

When I run the following quick test:
```
msglvl -debug
*
*
*
* BEGIN
*
*
*
*
mainsize  2
numcpu    1
sysclear
archlvl   370
*
r 000=0008000000000200
r 068=000A00000000DEAD
*
*
r 200=68000308   # LD    R0,FPR0
r 204=68200310   # LD    R2,FPR2
r 208=68400318   # LD    R4,FPR4
r 20c=68600320   # LD    R6,FPR6
*
*
r 210=2A20       # ADR   R2,R0
r 212=60200310   # STD   R2,FPR2
r 216=82000300   # LPSW  STOP
*
*
r 300=000A000000000000
r 308=3F393EE5EEDCC20D  # FPR 0 = dh'0.013976'
r 310=3FDD15F02C4D65E4  # FPR 2 = dh'0.053976'
r 318=4444444444444444  # FPR 4 = 4444444444444444
r 320=6666666666666666  # FPR 6 = 6666666666666666
*
*
u 200.12
*
*
fpr
*
*
r 308.20
*
*
restart
pause 0.1
*
*
r 308.20
*
*
fpr
*
*
* DONE
*
*
*
*
```

I get the following _**incorrect**_ results:

<pre>
10:55:11 HHC01603I *
10:55:11 HHC01603I *
10:55:11 HHC01603I *
10:55:11 HHC01603I * BEGIN
10:55:11 HHC01603I *
10:55:11 HHC01603I *
10:55:11 HHC01603I *
10:55:11 HHC01603I *
10:55:12 HHC01603I mainsize  2
10:55:12 HHC17003I MAIN     storage is 2M (mainsize); storage is not locked
10:55:12 HHC01603I numcpu    1
10:55:12 HHC02204I NUMCPU         set to 1
10:55:12 HHC01603I sysclear
10:55:12 HHC02311I sysclear completed
10:55:12 HHC01603I archlvl   370
10:55:12 HHC02204I ARCHLVL        set to S/370
10:55:12 HHC01603I *
10:55:13 HHC01603I r 000=0008000000000200
10:55:13 HHC02290I A:0000000000000000  K:00
10:55:13 HHC02290I R:00000000  00080000 00000200                    ........
10:55:13 HHC01603I r 068=000A00000000DEAD
10:55:13 HHC02290I A:0000000000000000  K:00
10:55:13 HHC02290I R:00000060                    000A0000 0000DEAD          ........
10:55:13 HHC01603I *
10:55:13 HHC01603I *
10:55:14 HHC01603I r 200=68000308   # LD    R0,FPR0
10:55:14 HHC02290I A:0000000000000000  K:00
10:55:14 HHC02290I R:00000200  68000308                             ....
10:55:14 HHC01603I r 204=68200310   # LD    R2,FPR2
10:55:14 HHC02290I A:0000000000000000  K:00
10:55:14 HHC02290I R:00000200           68200310                        ....
10:55:15 HHC01603I r 208=68400318   # LD    R4,FPR4
10:55:15 HHC02290I A:0000000000000000  K:00
10:55:15 HHC02290I R:00000200                    68400318                   . ..
10:55:15 HHC01603I r 20c=68600320   # LD    R6,FPR6
10:55:15 HHC02290I A:0000000000000000  K:00
10:55:15 HHC02290I R:00000200                             68600320              .-..
10:55:15 HHC01603I *
10:55:15 HHC01603I *
10:55:16 HHC01603I r 210=2A20       # ADR   R2,R0
10:55:16 HHC02290I A:0000000000000000  K:00
10:55:16 HHC02290I R:00000210  2A20                                 ..
10:55:16 HHC01603I r 212=60200310   # STD   R2,FPR2
10:55:16 HHC02290I A:0000000000000000  K:00
10:55:16 HHC02290I R:00000210      6020 0310                          -...
10:55:17 HHC01603I r 216=82000300   # LPSW  STOP
10:55:17 HHC02290I A:0000000000000000  K:00
10:55:17 HHC02290I R:00000210               8200 0300                     b...
10:55:17 HHC01603I *
10:55:17 HHC01603I *
10:55:17 HHC01603I r 300=000A000000000000
10:55:17 HHC02290I A:0000000000000000  K:00
10:55:17 HHC02290I R:00000300  000A0000 00000000                    ........
10:55:18 HHC01603I r 308=3F393EE5EEDCC20D  # FPR 0 = dh'0.013976'
10:55:18 HHC02290I A:0000000000000000  K:00
10:55:18 HHC02290I R:00000300                    3F393EE5 EEDCC20D          ...V..B.
10:55:18 HHC01603I r 310=3FDD15F02C4D65E4  # FPR 2 = dh'0.053976'
10:55:18 HHC02290I A:0000000000000000  K:00
10:55:18 HHC02290I R:00000310  3FDD15F0 2C4D65E4                    ...0.(.U
10:55:19 HHC01603I r 318=4444444444444444  # FPR 4 = 0
10:55:19 HHC02290I A:0000000000000000  K:00
10:55:19 HHC02290I R:00000310                    44444444 44444444          ........
10:55:19 HHC01603I r 320=6666666666666666  # FPR 6 = 0
10:55:19 HHC02290I A:0000000000000000  K:00
10:55:19 HHC02290I R:00000320  66666666 66666666                    ........
10:55:19 HHC01603I *
10:55:19 HHC01603I *
10:55:19 HHC01603I u 200.12
10:55:19 HHC02289I R:0000000000000200  68000308     LD    0,776(0,0)             load_float_long
10:55:19 HHC02289I R:0000000000000204  68200310     LD    2,784(0,0)             load_float_long
10:55:19 HHC02289I R:0000000000000208  68400318     LD    4,792(0,0)             load_float_long
10:55:19 HHC02289I R:000000000000020C  68600320     LD    6,800(0,0)             load_float_long
10:55:19 HHC02289I R:0000000000000210  2A20         ADR   2,0                    add_float_long_reg
10:55:20 HHC01603I *
10:55:20 HHC01603I *
10:55:20 HHC01603I fpr
10:55:20 HHC02270I Floating point registers
10:55:20 HHC02270I FPR0=0000000000000000 FPR2=0000000000000000
10:55:20 HHC02270I FPR4=0000000000000000 FPR6=0000000000000000
10:55:20 HHC01603I *
10:55:20 HHC01603I *
10:55:20 HHC01603I r 308.20
10:55:20 HHC02290I A:0000000000000000  K:00
10:55:20 HHC02290I R:00000300                    3F393EE5 EEDCC20D          ...V..B.
10:55:20 HHC02290I R:00000310  3FDD15F0 2C4D65E4 44444444 44444444  ...0.(.U........
10:55:20 HHC02290I R:00000320  66666666 66666666                    ........
10:55:20 HHC01603I *
10:55:20 HHC01603I *
10:55:20 HHC01603I restart
10:55:20 HHC02228I restart key pressed
10:55:20 HHC00809I Processor CP00: disabled wait state 000A0000 00000000
10:55:20 HHC01603I pause 0.1
10:55:20 HHC01600E Unknown command pause, enter 'help' for a list of valid commands
10:55:20 HHC01603I *
10:55:20 HHC01603I *
10:55:21 HHC01603I r 308.20
10:55:21 HHC02290I A:0000000000000000  K:06
10:55:21 HHC02290I R:00000300                    3F393EE5 EEDCC20D          ...V..B.
10:55:21 HHC02290I R:00000310  4011654D 61B2A27F 44444444 44444444   ..(/.s"........
10:55:21 HHC02290I R:00000320  66666666 66666666                    ........
10:55:21 HHC01603I *
10:55:21 HHC01603I *
10:55:21 HHC01603I fpr
<b>10:55:21 HHC02270I Floating point registers
10:55:21 HHC02270I FPR0=3F393EE5EEDCC20D FPR2=0000000000000000
10:55:21 HHC02270I FPR4=4011654D61B2A27F FPR6=0000000000000000</b>
10:55:21 HHC01603I *
10:55:21 HHC01603I *
10:55:21 HHC01603I * DONE
10:55:21 HHC01603I *
10:55:21 HHC01603I *
10:55:21 HHC01603I *
10:55:21 HHC01603I *
</pre>

_**HOWEVER**_, if I #undef _(comment out)_ the #define for `FEATURE_370_EXTENSION` in header `feat370.h`, I get the following _**correct**_ results:

<pre>
10:44:59 HHC01603I *
10:44:59 HHC01603I *
10:44:59 HHC01603I *
10:44:59 HHC01603I * BEGIN
10:44:59 HHC01603I *
10:44:59 HHC01603I *
10:44:59 HHC01603I *
10:44:59 HHC01603I *
10:44:59 HHC01603I mainsize  2
10:44:59 HHC17003I MAIN     storage is 2M (mainsize); storage is not locked
10:45:00 HHC01603I numcpu    1
10:45:00 HHC02204I NUMCPU         set to 1
10:45:00 HHC01603I sysclear
10:45:00 HHC02311I sysclear completed
10:45:00 HHC01603I archlvl   370
10:45:00 HHC02204I ARCHLVL        set to S/370
10:45:00 HHC01603I *
10:45:01 HHC01603I r 000=0008000000000200
10:45:01 HHC02290I A:0000000000000000  K:00
10:45:01 HHC02290I R:00000000  00080000 00000200                    ........
10:45:01 HHC01603I r 068=000A00000000DEAD
10:45:01 HHC02290I A:0000000000000000  K:00
10:45:01 HHC02290I R:00000060                    000A0000 0000DEAD          ........
10:45:01 HHC01603I *
10:45:01 HHC01603I *
10:45:02 HHC01603I r 200=68000308   # LD    R0,FPR0
10:45:02 HHC02290I A:0000000000000000  K:00
10:45:02 HHC02290I R:00000200  68000308                             ....
10:45:02 HHC01603I r 204=68200310   # LD    R2,FPR2
10:45:02 HHC02290I A:0000000000000000  K:00
10:45:02 HHC02290I R:00000200           68200310                        ....
10:45:03 HHC01603I r 208=68400318   # LD    R4,FPR4
10:45:03 HHC02290I A:0000000000000000  K:00
10:45:03 HHC02290I R:00000200                    68400318                   . ..
10:45:03 HHC01603I r 20c=68600320   # LD    R6,FPR6
10:45:03 HHC02290I A:0000000000000000  K:00
10:45:03 HHC02290I R:00000200                             68600320              .-..
10:45:03 HHC01603I *
10:45:03 HHC01603I *
10:45:04 HHC01603I r 210=2A20       # ADR   R2,R0
10:45:04 HHC02290I A:0000000000000000  K:00
10:45:04 HHC02290I R:00000210  2A20                                 ..
10:45:05 HHC01603I r 212=60200310   # STD   R2,FPR2
10:45:05 HHC02290I A:0000000000000000  K:00
10:45:05 HHC02290I R:00000210      6020 0310                          -...
10:45:05 HHC01603I r 216=82000300   # LPSW  STOP
10:45:05 HHC02290I A:0000000000000000  K:00
10:45:05 HHC02290I R:00000210               8200 0300                     b...
10:45:05 HHC01603I *
10:45:05 HHC01603I *
10:45:06 HHC01603I r 300=000A000000000000
10:45:06 HHC02290I A:0000000000000000  K:00
10:45:06 HHC02290I R:00000300  000A0000 00000000                    ........
10:45:06 HHC01603I r 308=3F393EE5EEDCC20D  # FPR 0 = dh'0.013976'
10:45:06 HHC02290I A:0000000000000000  K:00
10:45:06 HHC02290I R:00000300                    3F393EE5 EEDCC20D          ...V..B.
10:45:07 HHC01603I r 310=3FDD15F02C4D65E4  # FPR 2 = dh'0.053976'
10:45:07 HHC02290I A:0000000000000000  K:00
10:45:07 HHC02290I R:00000310  3FDD15F0 2C4D65E4                    ...0.(.U
10:45:08 HHC01603I r 318=4444444444444444  # FPR 4 = 0
10:45:08 HHC02290I A:0000000000000000  K:00
10:45:08 HHC02290I R:00000310                    44444444 44444444          ........
10:45:08 HHC01603I r 320=6666666666666666  # FPR 6 = 0
10:45:08 HHC02290I A:0000000000000000  K:00
10:45:08 HHC02290I R:00000320  66666666 66666666                    ........
10:45:08 HHC01603I *
10:45:08 HHC01603I *
10:45:08 HHC01603I u 200.12
10:45:08 HHC02289I R:0000000000000200  68000308     LD    0,776(0,0)             load_float_long
10:45:08 HHC02289I R:0000000000000204  68200310     LD    2,784(0,0)             load_float_long
10:45:08 HHC02289I R:0000000000000208  68400318     LD    4,792(0,0)             load_float_long
10:45:08 HHC02289I R:000000000000020C  68600320     LD    6,800(0,0)             load_float_long
10:45:08 HHC02289I R:0000000000000210  2A20         ADR   2,0                    add_float_long_reg
10:45:08 HHC01603I *
10:45:08 HHC01603I *
10:45:08 HHC01603I fpr
10:45:08 HHC02270I Floating point registers
10:45:08 HHC02270I FPR0=0000000000000000 FPR2=0000000000000000
10:45:08 HHC02270I FPR4=0000000000000000 FPR6=0000000000000000
10:45:08 HHC01603I *
10:45:08 HHC01603I *
10:45:09 HHC01603I r 308.20
10:45:09 HHC02290I A:0000000000000000  K:00
10:45:09 HHC02290I R:00000300                    3F393EE5 EEDCC20D          ...V..B.
10:45:09 HHC02290I R:00000310  3FDD15F0 2C4D65E4 44444444 44444444  ...0.(.U........
10:45:09 HHC02290I R:00000320  66666666 66666666                    ........
10:45:09 HHC01603I *
10:45:09 HHC01603I *
10:45:09 HHC01603I restart
10:45:09 HHC02228I restart key pressed
10:45:09 HHC00809I Processor CP00: disabled wait state 000A0000 00000000
10:45:09 HHC01603I pause 0.1
10:45:09 HHC01600E Unknown command pause, enter 'help' for a list of valid commands
10:45:09 HHC01603I *
10:45:09 HHC01603I *
10:45:09 HHC01603I r 308.20
10:45:09 HHC02290I A:0000000000000000  K:06
10:45:09 HHC02290I R:00000300                    3F393EE5 EEDCC20D          ...V..B.
10:45:09 HHC02290I R:00000310  4011654D 61B2A27F 44444444 44444444   ..(/.s"........
10:45:09 HHC02290I R:00000320  66666666 66666666                    ........
10:45:09 HHC01603I *
10:45:09 HHC01603I *
10:45:09 HHC01603I fpr
<b>10:45:09 HHC02270I Floating point registers
10:45:09 HHC02270I FPR0=3F393EE5EEDCC20D FPR2=4011654D61B2A27F
10:45:09 HHC02270I FPR4=4444444444444444 FPR6=6666666666666666</b>
10:45:10 HHC01603I *
10:45:10 HHC01603I *
10:45:10 HHC01603I * DONE
10:45:10 HHC01603I *
10:45:10 HHC01603I *
10:45:10 HHC01603I *
10:45:10 HHC01603I *
</pre>

Notice the display of the resulting floating point registers display after the test has run. In the first test, they're wrong. In the second test (just above), they're right.

The root cause of the incorrect functionality is the result of how the `FPR2I` and `FPREX` macros end up being #defined depending on the setting of the `FEATURE_BASIC_FP_EXTENSIONS` build option.

It is normally _not_ defined for 370 builds, whereas for 390 and 900 (z/Arch) builds it is normally #defined. The code that #defines the `FPR2I` and `FPREX` macros is in header `opcode.h`, and #defines them differently depending on whether `FEATURE_BASIC_FP_EXTENSIONS` is #defined or not:

https://github.com/SDL-Hercules-390/hyperion/blob/7eef88715c7e7370a4fdc8aa181ab8651d8afa45/opcode.h#L1631-L1896

As you can see, if `FEATURE_BASIC_FP_EXTENSIONS` is #defined, they get #defined to:
```C
  #define FPR2I(_r)     ((_r) << 1)     /* Convert fpr to index */
  #define FPREX              4          /* Offset of extended register */
```
whereas if if `FEATURE_BASIC_FP_EXTENSIONS` is _**not**_ #defined, they instead get #defined to:
```C
  #define FPR2I(_r)         (_r)        /* Convert fpr to index */
  #define FPREX               2         /* Offset of extended register */
```

This is the source _(cause)_ of Hercules's incorrect S/370 floating point behavior (functionality), _which includes not only the display of the floating point registers but also the **incorrect execution** of the instructions themselves too!_

Luckily(?) however, it appears only S/370 is impacted by this bug. Neither ESA/390 nor z/Architecture is impacted, since they both always have `FEATURE_BASIC_FP_EXTENSIONS` #defined in their feat390/feat900 headers. The bug currently only impacts 370 builds of Hercules, and as I said, it's all because `FEATURE_370_EXTENSION` is always being #defined even for 370 builds:

* https://github.com/SDL-Hercules-390/hyperion/blob/develop/feat370.h

Notice that `FEATURE_370_EXTENSION` is always being #defined, which ends up causing `FEATURE_BASIC_FP_EXTENSIONS` to also get #defined too _(since the ESA/390 and z/Architecture instructions being enabled by `FEATURE_370_EXTENSION` requires it)_, thereby triggering the incorrect 370 floating point functionality _(due to the resulting different #definition of the `FPR2I` and `FPREX` macros in header `opcode.h`)_.

### POSSIBLE RESOLUTION?

I have tested the following `opcode.h` change **`(*)`**:

```diff
--- hyperion-git/opcode.h	2023-02-20 13:50:19.697645400 -0800
+++ hyperion-1/opcode.h	2023-02-20 14:48:50.287027700 -0800
@@ -1630,13 +1630,11 @@
 
 /*-------------------------------------------------------------------*/
 /*                 Floating-point helper macros                      */
-/*-------------------------------------------------------------------*/
+/*                                                                   */
 #undef HFPREG_CHECK
 #undef HFPREG2_CHECK
 #undef HFPODD_CHECK
 #undef HFPODD2_CHECK
-#undef FPR2I
-#undef FPREX
 
 #if defined( FEATURE_BASIC_FP_EXTENSIONS )
 
@@ -1844,10 +1842,6 @@
   #endif /* !defined( _FEATURE_SIE ) */
 
 
-  #define FPR2I(_r)     ((_r) << 1)     /* Convert fpr to index */
-  #define FPREX              4          /* Offset of extended register */
-
-
 #else /* !defined( FEATURE_BASIC_FP_EXTENSIONS ) */
 
 
@@ -1885,18 +1879,62 @@
         (_regs)->program_interrupt( (_regs), PGM_SPECIFICATION_EXCEPTION )
 
 
-  #define FPR2I(_r)         (_r)        /* Convert fpr to index */
-  #define FPREX               2         /* Offset of extended register */
+#endif /* !defined( FEATURE_BASIC_FP_EXTENSIONS ) */
+/*                                                                   */
+/*               (end floating-point helper macros)                  */
+/*-------------------------------------------------------------------*/
+
 
 
-#endif /* !defined( FEATURE_BASIC_FP_EXTENSIONS ) */
 
 /*-------------------------------------------------------------------*/
-/*               (end floating-point helper macros)                  */
+/*            SPECIAL HANDLING for HERC_370_EXTENSION                */
+/*                                                                   */
+#undef FPR2I
+#undef FPREX
+#if defined( FEATURE_BASIC_FP_EXTENSIONS )
+
+  // 390 or zArch -OR- 370 with the "FEATURE_370_EXTENSION" BUILD
+  // option #defined, which causes the "FEATURE_BASIC_FP_EXTENSIONS"
+  // BUILD to necessarily ALSO be #defined, forcing us to check if
+  // the "HERC_370_EXTENSION" facility is enabled or not.
+  //
+  // PLEASE NOTE that enabling the "HERC_370_EXTENSION" facility
+  // causes nonconformant/incorrect S/370 floating point behavior!
+
+  #define FPR2I(_r)     /* Convert fpr to index */                    \
+  ((0                                                                 \
+      || ARCH_370_IDX != sysblk.arch_mode                             \
+      || FACILITY_ENABLED_ARCH( HERC_370_EXTENSION, ARCH_370_IDX )    \
+  )                                                                   \
+  ? ((_r) << 1) : (_r))
+
+  #define FPREX         /* Offset of extended register */             \
+  ((0                                                                 \
+      || ARCH_370_IDX != sysblk.arch_mode                             \
+      || FACILITY_ENABLED_ARCH( HERC_370_EXTENSION, ARCH_370_IDX )    \
+  )                                                                   \
+  ? 4 : 2 )
+
+#else // !defined( FEATURE_BASIC_FP_EXTENSIONS )
+
+  // S/370 without the "FEATURE_370_EXTENSION" BUILD option defined,
+  // which causes the "FEATURE_BASIC_FP_EXTENSIONS" BUILD option to
+  // NOT be #defined, which provides normal S/370 behavior.
+    
+  #define FPR2I(_r)     (_r)        /* Convert fpr to index */
+  #define FPREX           2         /* Offset of extended register */
+
+#endif // defined( FEATURE_BASIC_FP_EXTENSIONS)
+/*                                                                   */
+/*         (end special handling for herc_370_extension)             */
 /*-------------------------------------------------------------------*/
```

and it does indeed fix the incorrect 370 floating point functionality.

_**BUT**..._

The problem is, as soon as the `HERC_370_EXTENSION` facility is enabled, we're right back to incorrect 370 floating point behavior again!

To be honest I'm not sure what to do about that or whether anything _can_ be done about it. Unless someone can come up with some bright idea that hasn't occurred to me, I think we're stuck, I think we'll just have to document the fact that enabling the `HERC_370_EXTENSION` facility will necessarily cause incorrect floating point behavior as a result _(for 370 mode)_.

I've created this GitHub Issue solely to get your feedback on this issue, i.e. whether you agree with my analysis, your thoughts regarding my proposed fix, _AND_ whether you agree that this is just one of those things that cannot be fixed _(with respect to the enabling of the `HERC_370_EXTENSION` facility)_.

Thank you for reading this far.

I look forward to your feedback.

_____
**`(*)`** _Note that all(?) of the other Floating Point helper macros probably need to be fixed too. I didn't bother doing that yet. I was only interested in doing a quick test to validate my analysis and potential fix. Please let me know if you agree that they also need to be changed with the same archmode and FACILITY_ENABLED test too._

____
p.s. to @ivan-w: &nbsp; [57262a5e795ca619cfbbf6b97029731299eb636d](https://github.com/SDL-Hercules-390/hyperion/commit/57262a5e795ca619cfbbf6b97029731299eb636d#diff-4dcaa06fc7584a4c6ff7db3b79a2f00ed64bfa4cc4d6e5b48111eec02b39ac90)

**Comment by s390guy** [comment]
Enabling of the HERC_370_EXTENSION facility during build creates behavior in 370 that differs from that expected for 370 and is described above as "incorrect".   My question about this behavior is "Is this behavior also incorrect for the HERC_370_EXTENSION facility when enabled?"  I do not have a good definition in my head about exactly what is being enabled by this facility during the build process.  I know that sounds like a stupid question.  Of course it is correct when it is enabled.  Then it becomes a matter of documenting the new behavior.

At the root of my question is this: was HERC_370_EXTENSION intended to be a run-time option enabled via ARCHLVL and not enabled just by the build?  Rather the build #define was intended to ALLOW HERC_370_EXTENSION to be enabled by ARCHLVL.  This would have in all likelihood require changes to floating point instructions in S/370 during their execution, not just when built.  And clearly, if this was the intention, did not work.

As I understand the committed changes, HERC_370_EXTENSION is strictly a build change that changes S/370 floating point operations when Hercules is built with it enabled.  A user then would have to have two builds of Hercules, one with the #define enabled and one without it enabled, if the user would want to use the facility in some situations and not in others.

Other than suggesting some documentation outside of the code itself for the facility, I am really just trying to validate my own understanding and if possible, the original intent of the facility.

**Comment by Fish-Git** [comment]
> Enabling of the HERC_370_EXTENSION facility during build creates behavior in 370 that differs from that expected for 370 and is described above as "incorrect".

Correct. That _**WAS**_ indeed true, but it has since been fixed.

> My question about this behavior is "Is this behavior also incorrect for the HERC_370_EXTENSION facility when enabled?

It _**WAS**_, yes, but as just stated, it's since been fixed.

Well... _ACTUALLY_, that's not strictly true. Floating point has been working fine all along, even with the "bug" that I found. As it actually turns out, salva-rczero (see GitHub Issue #543) was actually spot on in that it was simply the _display_ of the floating point registers that was buggy, which was causing no end to confusion on both his and my part.

As it turns out, _**regardless**_ of whether the `FEATURE_370_EXTENSION` build option is #defined or not, and _**regardless**_ of whether the `HERC_370_EXTENSION` facility is enabled or not, Hexadecimal Floating Point (HFP) was working just fine across the board (for all build architectures).

Whenever the `FEATURE_370_EXTENSION` build option is #defined, the floating point macros in `opcode.h` are indeed #defined differently, but it ends up not causing any harm. The HFP floating point instructions still work correctly. They do work _differently_ internally, yes, but it all comes out in the wash so to speak. The end result is, from the guest's point of view, everything is fine. Yes, Hercules ends up modifying a different set of `fpr` array entries, but as long as all of Hercules's internal logic always accesses those `fpr` array entries the same way, the end result ends up being correct. The guest's view of its HFP floating point registers ends up being the same.

It was only due to the incorrect way that the `display_fregs` was access those `fpr` array entries that ended misleading us _(me!)_ into believing we had a serious bug in our HFP floating point handling. But as it turn out, that was not true. HFP floating point was working just fine _(albeit **differently**)_. It was only the _**displaying**_ of the registers that was fucked.

Clear as mud now, right? &nbsp; `:)`

> I do not have a good definition in my head about exactly what is being enabled by this facility during the build process. I know that sounds like a stupid question.

Not a stupid question at all! The `FEATURE_370_EXTENSION` build option ultimately defines a bunch of new instructions to 370 that mever originally existed. Most of the new instructions are actually z/Architecture instructions that are actually architecture agnostic _(such as the `LHI` (Load Halfword Immediate) instruction and the Branch Relative (i.e. "Jump") instructions, etc.)_ For the complete list of instructions included in the Hercules 370 Extension Facility, please see `BEG_DIS_FAC_INS_FUNC( herc37X )` in `facility.c`.

For more information about the facility, refer to the "S/370 Backport of select ESA/390 and z/Architecture instructions" entry in the "Features and Operation" section of our primary ["SDL Hercules 4.x Hyperion" README](https://github.com/SDL-Hercules-390/hyperion/blob/develop/README.md).

> was HERC_370_EXTENSION intended to be a run-time option enabled via ARCHLVL and not enabled just by the build?

I guess we'd have to ask Ivan (@ivan-w) about that. I believe it was _originally_ a build option only. But some people objected to introducing new instructions into the original 370 architecture. So I changed it into a Hercules facility that could be dynamically enabled for those who wanted it, while leaving it disabled by default, thereby not "polluting" the original 370 architecture with new instructions that never existed "back in the day".

The bottom line is, nothing was actually broken at any time except for how our registers were being displayed. The alarm I sounded ended up being a false alarm. It only _looked_ like things were broken due to our buggy floating point registers display function. _THAT_ was ultimately the only thing that was actually broken. The latest version of my "float" test proves this fact conclusively. If Hercules's HFP functionality was broken, then my test should have detected that and failed. But it never did. It always succeeded. And that because as I said, the _guest's_ view of its registers was always correct. And it was always correct because Hercules was always accessing (fetching, updating and storing. etc) the registers in a consistent _(but different!)_ manner, depending on the build option and the facility.

> A user then would have to have two builds of Hercules, one with the #define enabled and one without it enabled, if the user would want to use the facility in some situations and not in others.

As I said, that _was_ how it was originally design _(I think)_. But due to blowback, it was converted into a dynamic runtime option.

> Other than suggesting some documentation outside of the code itself for the facility, I am really just trying to validate my own understanding and if possible, the original intent of the facility.

The original intent was to simply allow our users running 370 operating systems to make use of some of the very handy and useful instructions that were introduced to z/Architecture. The Branch Relative (Jump) instructions alone are worth providing the option to our users! How many times in years past have you wished you didn't need to waste programming time and effort dealing with base registers?! Imagine how much simpler it would be _(and how much faster (more efficient) your programs would be!)_ if you didn't have to "waste" several extremely valuable General Purpose Registers just to provide addressability to your program data! Or how more efficnet it would be to be able to load a halfword into a register _without_ addressing any storage?! (because the value you want to load is already a part of the intruction itself?!).

Having such instructions available to the 370 programmer is invaluable!

But as I said, there are unfortunately some "purists" out there that mistakenly feel providing such new instructions that didn't originally exist "back then" is somehow an "architecural violation". It somehow _(in their mind)_ "breaks the architecture". &nbsp; _(SIGH!)_

Well, I've rambled on too much for one day now, so I guess I'll post this and get back to trying to locate our MVT bug.

I hope that helps you _(and others!)_ to understand things a bit better. If you have any further questions or concerns, feel free to post them here and I'll try to answer them.

See ya! &nbsp; `:)`

**Comment by s390guy** [comment]
A most wonderfully complete explanation.  Clears things up for me.  Very happy too that it was not a functional problem with hexadecimal floating point, but rather a display issue of the registers.  That was good news I did not grasp until now.

Thank you!

Harold
