### ISSUE TITLE
I'm getting devtype 3270 not recognized 

### ISSUE THREAD

**Issue by z-fanboy** [SDL-Hercules-390/hyperion#552]
___
_**NOTE:** &nbsp; This issue appears to be a **duplicate** of issue [**431**](https://github.com/SDL-Hercules-390/hyperion/issues/431)._
___
Hi all, first of all thank you for your work.

I've build Hercules from _**BSD 12.3**_ and when I started hercules I get these msgs:

<img width="742" alt="devtype BSD error" src="https://user-images.githubusercontent.com/128638616/227018015-af5e4028-26d6-4494-81ee-88214c0e764d.png">

Here you have log and cnf:

* [hercules.log](https://github.com/SDL-Hercules-390/hyperion/files/11044311/hercules.log)
* [hercules01.txt](https://github.com/SDL-Hercules-390/hyperion/files/11044322/hercules01.txt)

Thank you.

Regards.

**Comment by wrljet** [comment]
Probably Hercules cannot find its loadable modules.

Can you share the exact commands you used to build and install Hercules?

Bill

**Comment by z-fanboy** [comment]
Sure:
<img width="648" alt="history" src="https://user-images.githubusercontent.com/128638616/227035103-e63a0033-cece-45e5-a392-f4e72499ea72.png">

Thank you.

Regards.

**Comment by wrljet** [comment]
What SDL-Hercules-390 commit are you working with, exactly?

**Comment by z-fanboy** [comment]
I think it's the last, I did `git clone https://github.com/SDL-Hercules-390/hyperion.git`.

Thank you.

Regards.

**Comment by wrljet** [comment]
For FreeBSD, you will have an easier time with the `develop` branch.

And even easier, I recommend you give my [Hercules-Helper](https://github.com/wrljet/hercules-helper#readme) a try.
It will handle the SDL-Hercules build process for you.  I just tested it all yesterday on FreeBSD 12.3 after you created this issue.

Bill

**Comment by Fish-Git** [comment]
> I think it's the last, I did `git clone https://github.com/SDL-Hercules-390/hyperion.git`.

"Thinking" is not good enough. We must _know_ with certainty.

If Hercules was built correctly, it _should_ report its **exact version** whenever it first starts:

<pre>
HHC00100I Thread id 000014c0, prio 5, name 'impl_thread' started
HHC00100I Thread id 00001c64, prio 4, name 'logger_thread' started
<b>HHC01413I Hercules version 4.5.0.10830-SDL-g58578601</b>
HHC01414I (C) Copyright 1999-2022 by Roger Bowler, Jan Jaeger, and others
HHC01417I ** The SoftDevLabs version of Hercules **
HHC01415I Build date: Nov 26 2022 at 16:25:41
</pre>

According to the Hercules log you provided, the version is not being reported at all:

<pre>
<b>HHC01413I Hercules version</b>
HHC01414I (C) Copyright 1999-2022 by Roger Bowler, Jan Jaeger, and others
HHC01417I ** The SoftDevLabs version of Hercules **
</pre>

Notice message `HHC01413I`: it just says "Hercules version", but it does not report _what_ (which) version is being executed.

This tells us that you did not build Hercules correctly.

To further confirm, start Hercules and enter the Hercules `version` command. It _should_ then report its **exact version**:

<pre>
<b>HHC01603I version
HHC01413I Hercules version 4.5.0.10830-SDL-g58578601</b>
HHC01414I (C) Copyright 1999-2022 by Roger Bowler, Jan Jaeger, and others
HHC01417I ** The SoftDevLabs version of Hercules **
HHC01415I Build date: Nov 26 2022 at 16:25:41
HHC01417I Built with: Microsoft Visual Studio 2008 (MSVC 150030729 1)
HHC01417I Build type: Windows MSVC AMD64 host architecture build
HHC01417I Modes: S/370 ESA/390 z/Arch
HHC01417I Max CPU Engines: 64
HHC01417I Using   shared libraries
HHC01417I Using   Fish threads Threading Model
HHC01417I Using   Error-Checking Mutex Locking Model
HHC01417I With    Shared Devices support
HHC01417I With    Dynamic loading support
HHC01417I With    External GUI support
HHC01417I With    Partial TCP keepalive support
HHC01417I With    IPV6 support
HHC01417I With    HTTP Server support
HHC01417I With    sqrtl support
HHC01417I With    Signal handling
HHC01417I With    Watchdog monitoring
HHC01417I With    CCKD BZIP2 support
HHC01417I With    HET BZIP2 support
HHC01417I With    ZLIB support
HHC01417I With    Regular Expressions support
HHC01417I With    Object REXX support
HHC01417I Without Regina REXX support
HHC01417I With    Automatic Operator support
HHC01417I Without National Language Support
HHC01417I With    CCKD64 Support
HHC01417I With    Transactional-Execution Facility support
HHC01417I With    "Optimized" instructions
HHC01417I With    OPTION_USE_SKAIP_AS_LOCK
HHC01417I With    OPTION_SIE2BK_FLD_COPY
HHC01417I Machine dependent assists: cmpxchg1 cmpxchg4 cmpxchg8 cmpxchg16 hatomics=msvcIntrinsics
HHC01417I Running on: WIN7 (Windows-6.1.7601 Intel(R) x64) LP=8, Cores=8, CPUs=2
HHC01417I Built with crypto external package version 1.0.0.52-ga5096e5
HHC01417I Built with decNumber external package version 3.68.0.102-g3aa2f45
HHC01417I Built with SoftFloat external package version 3.5.0.105-g4b0c326
HHC01417I Built with telnet external package version 1.0.0.62-ge0e2a91
</pre>

If it does not report its exact version like above, then you did not build it correctly.

I strongly suggest that you use Bill's "[**Hercules Helper**](https://github.com/wrljet/hercules-helper#readme)" script to build SDL Hercules with. It will ensure that Hercules is always built correctly.

**Comment by z-fanboy** [comment]
Hi @wrljet, yes, your "[Hercules Helper](https://github.com/wrljet/hercules-helper#readme)" works fine:

<img width="711" alt="evidence" src="https://user-images.githubusercontent.com/128638616/227363612-c0e28520-d05c-47f9-8bf6-3b6095077ddd.png">
 
Hi @Fish-Git, yes, you're right, I'm sure that I did something wrong. I'll try to do it again in the next days.

Thank you both very much for your time and work.

Regards.

**Comment by wrljet** [comment]
Glad it worked! 

Don't be bashful about any questions or issues.  We're here to help.

Bill

**Comment by Fish-Git** [comment]
Closing issue?
