### ISSUE TITLE
small glitch in cardpch socket support

### ISSUE THREAD

**Issue by ghost** [SDL-Hercules-390/hyperion#555]
Hi Fish 

`sockdev.c` is missing in
`hdt3525_la_SOURCES  = cardpch.c`

enrico

**Comment by Fish-Git** [comment]
Oops! Thanks for reporting this, Enrico!

When I first did my Windows build, Hercules wouldn't even _build_ without adding sockdev to hdt3525.dll (link error). After adding it, it built fine and worked fine, but I forgot to do the same thing for Linux.

What threw me off though, was when I build Hercules on Linux, it built just fine! No link error!

But of course I failed to actually do any type of quick test on Linux. That's where I went wrong. I erroneously presumed if it built clean, it would run clean too.

Nope! "Device type 3525 not recognized". _(Oops!)_

As soon as I added the missing `sockdev.c` to the `hdt3525_la_SOURCES`  line of `Makefile.am` and did my full rebuild (autogen.sh && configure && ...), VOILA! Defining a 3525 punch device started working just fine.

To be safe and to be absolutely certain of things, this time I also did a quick `script tests/punch.txt` test on Linux and of course, as expected, it worked just fine this time too.

So THANK YOU again for reporting this, Enrico. I really appreciate it.

Closed by commit ef1cf386cb274ea2081b92d6f49dd8d0318bab83.
