### ISSUE TITLE
Trouble building Hercules (clone from git) on Apple M1

### ISSUE THREAD

**Issue by trigger2k20** [SDL-Hercules-390/hyperion#557]
Hello, 
please help, i cannot compile SDL Hercules (git clone) with make accorrding the installation instructions (install was w/o error) . It produces the following output:

<pre>
~/hyperion> make master
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in m4
make[2]: Nothing to be done for `all'.
Making all in util
make[2]: Nothing to be done for `all'.
Making all in html
make[2]: Nothing to be done for `all'.
Making all in man
make[2]: Nothing to be done for `all'.
Making all in .
  CCLD     libhercs.la
./libtool: line 7472: cd: ./crypto/lib/aarch64: No such file or directory
<b>libtool:   error: cannot determine absolute directory name of './crypto/lib/aarch64'</b>
make[2]: *** [libhercs.la] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
~/hyperion>
</pre>

Thanks for help,
Trigger2k23

**Comment by wrljet** [comment]
For macOS and M1 silicon, I recommend you use [Hercules-Helper](https://github.com/wrljet/hercules-helper#readme).
It will handle the SDL-Hercules build process for you.

Be sure to read the instructions fully.  (They aren't that great, though)

And any questions, please do not hesitate to ask here.

Bill

**Comment by Fish-Git** [comment]
> i cannot compile SDL Hercules (git clone) with make accorrding the installation instructions ...

What instructions did you follow? The official build procedure is documented here:

  * [_**Building and Installing**_](https://sdl-hercules-390.github.io/html/hercinst.html#install)<br>_**Building from source - Mac OS X**_<br>_**Building from source - Linux and macOS (High Sierra and newer)**_<br>_**Important: Please read everything before doing anything. Don't be bashful about asking for help.**_

Did you follow those instructions? Did you e.g. build the **External Packages** before attempting to build Hercules? _(and then specify the proper `--extpkgs=` option (or define your `LIBRARY_PATH` and `CPATH` variables) before issuing your `./configure` command?)_

SDL Hercules Hyperion will not build correctly unless you follow the build instructions _exactly_.

My suggestion is to use Bill's _**[Hercules-Helper](https://github.com/wrljet/hercules-helper#readme)**_ script to build Hercules with. It's specifically designed to make correctly building Hercules on Linux or Mac both fast and easy.

**Comment by trigger2k20** [comment]
Hello Fish & Bill,
thanks for the suggestion with Hercules- Helper, that worked ! Would it be not useful to include a link to Hercules Helper in the Building and Installing section (https://sdl-hercules-390.github.io/html/hercinst.html#install) ? Especially since it did not worked despite following those instructions.

Thanks for help,
Trigger2k23
