### ISSUE TITLE
Any suggestion for a good 3270 emulator for the Mac platform?

### ISSUE THREAD

**Issue by trigger2k20** [SDL-Hercules-390/hyperion#559]
Hi all,

Any suggestion for a good 3270 Emulation on the mac platform?

Thanks,

Trigger2k23

**Comment by Fish-Git** [comment]
Hi @trigger2k20!

The GitHub Issues interface should only be used for reporting bugs. It should not be used to simply ask questions or ask for advice.

If you have a question about Hercules or need some help or advice using it, you should post your message to our primary Hercules-390 Support Forum on Groups.IO:

  * https://hercules-390.groups.io/g/group

Hercules also has many other Support Forums that are more focused on running specific guest operating systems under Hercules, such as MVS and z/OS, DOSVS and z/VSE, VM370 and z/VM, etc.

For a completely list of available Hercules Support Forums, please refer to our "Technical Support" web page:

  * https://sdl-hercules-390.github.io/html/hercsupp.html

**Comment by trigger2k20** [comment]
Hi Fish,

thanks i will post my questions in those groups !
