### ISSUE TITLE
dasdcopy -0 (no compression on output) is not  "uncompressing"

### ISSUE THREAD

**Issue by mstram** [SDL-Hercules-390/hyperion#561]
As the title says.

This goes back to  Hercules 3.13

I guess not a lot of people ever use  dasdcopy -0 ..... ?

**Comment by Fish-Git** [comment]
Seriously, Mike? &nbsp; You call that a Problem Report?

Please read [**"SUBMITTING PROBLEM REPORTS"**](https://github.com/SDL-Hercules-390/hyperion/issues/373) and try again.

For _real_ this time.

Closing issue with not further action.
