### ISSUE TITLE
Hyperion complains MAC is invalid.

### ISSUE THREAD

**Issue by Rakeshreddy11** [SDL-Hercules-390/hyperion#562]
Hi,
I am running Hyperion **4.0** on a Windows machine with:

`0E20.2  LCS     -n xxx.xxx.xxx.xxx -m 00-15-5D-25-E1-A3`   &nbsp; &nbsp;    masking the IP here

And I get this:

```
07:46:42.329 00001254 HHC04100I TunTap64.dll version 3.6.2.4906 initiated
07:46:42.693 00001254 HHC00901I 0:0E20 LCS: Interface tap0, type TAP opened
```

At the same time, I am trying to start another instance of Hyperion **4.5** with same device:

<pre>0E20.2  LCS     -n xxx.xxx.xxx.xxx -m <b>00</b>-15-5D-25-E1-A3</pre>

But i get this:

<pre>
23:45:15.792 00001E68 HHC04100I TunTap64.dll version 3.6.2.4906 initiated
<b>23:45:15.915 00001E68 HHC00916E 0:0E20 LCS: Option MAC address value 00-15-5D-25-E1-A3 invalid</b>
23:45:15.915 00001E68 HHC00007I Previous message from function 'ParseArgs' at ctc_lcs.c(3406)
</pre>

Can't I start two instances of Hyperion at same time? Could someone help me what am I missing?

Thank you

**Comment by mcisho** [comment]
When a MAC address is specified in more recent versions of Hercules, Hercules requires that the locally assigned MAC address bit is on (0x02), and that the broadcast bit is off (0x01). Both bits are in the first byte of the MAC address. In your example you need to specify the locally assigned bit, i.e. 02-15-5D-25-E1-A3.

**Comment by Fish-Git** [comment]
**Ian is correct.**

Please see:

* https://sdl-hercules-390.github.io/html/hercconf.html#LCS

> _**Note:** The MAC address you specify for this option MUST have the 02 locally assigned MAC bit on in the first byte, must NOT have the 01 broadcast bit on in the first byte, and MUST be unique as seen by all other devices on your network segment. It should never, for example, be the same as the host adapter MAC address specified on the -n parameter._

_**HOWEVER...**_ &nbsp;I suspect the MAC address you are trying to assign to your virtual adapter might actually be the MAC address of your Windows host's real network adapter. Yes?

* https://maclookup.app/search/result?mac=00-15-5D

This is a common mistake.

To confirm, please post the output from `ipconfig -all`. I suspect `00-15-5D-25-E1-A3` is actually the hardware (MAC) address of your Windows adapter.

More than likely you probably meant to use the `-n` option, not the `-m` option. The meaning of the two options are _very different_ from each other. The first (`-n`) tells CTCI-WIN which _host_ network adapter you want it to use to access your local network with, whereas the second (`-m`) tells it what MAC address you want CTCI-WIN to _assign_ to your _guest's **virtual** adapter_.

Please try again using _**`-n`**_ instead.

**Comment by Rakeshreddy11** [comment]
Hi,

00-15-5D-25-E1-A3 is the hardware (MAC) address of your Windows adapter.

I changed the option from -m to -n which fixed the issue.

Thanks a lot.

**Comment by Fish-Git** [comment]
Closing issue.

**Comment by Rakeshreddy11** [comment]
Sorry for reopening the thread.
I tried both these options, i am able to access to my zos with in the host environment. But I can't access the IP outside of the HOST. Masking the Host IP.
0E20.2  LCS     -n xxx.xxx.xxx.xxx -n 00-15-5D-25-E1-A3
0E20.2  LCS     -n xxx.xxx.xxx.xxx -m 02-15-5D-25-E1-A3

I have Hyperion 4.0 where i use below parm and i am able to use the IP outside of the Host.
0E20.2  LCS     -n xxx.xxx.xxx.xxx -m 00-15-5D-25-E1-A3

Could you help me fixing this issue. Because of this, i am not able to upgrade to newer versions of Hyperion.

Thanks in advance.
