### ISSUE TITLE
HHC00324E 0:0270 CCKD file[1] shadow_dasd/pub001_1.270: shadow file not merged: file[0] cannot be opened read-write

### ISSUE THREAD

**Issue by oldbuzzard54** [SDL-Hercules-390/hyperion#565]
This problem started a couple of days ago.  I am trying to merge all my shadow files into the base file but all the shadows get this message `HHC00324E 0:0270 CCKD file[1] shadow_dasd/pub001_1.270: shadow file not merged: file[0] cannot be opened read-write`.

I can start and run MVS with no problems.  When I start hercules without MVS IPL, I usually merge the shadow files.  I have attached the log of one of the sessions.  The interesting stuff begins around 13:14:50 time.

* [3033.log](https://github.com/SDL-Hercules-390/hyperion/files/11413104/3033.log)

**Comment by Fish-Git** [comment]
> This problem started a couple of days ago.

Then you must have experienced a "senior moment" a couple of days ago that has lasted until today. &nbsp; `:)`

> I am trying to merge all my shadow files into the base file but all the shadows get this message `HHC00324E 0:0270 CCKD file[1] shadow_dasd/pub001_1.270: shadow file not merged: file[0] cannot be opened read-write`.

Which is absolutely correct. The shadow file you are trying to merge _into_ is indeed read-only:

<pre>
13:13:11 HHC01603I <b>sf-270</b>
13:13:11 HHC00324E 0:0270 CCKD file[1] shadow_dasd/pub001_1.270: shadow file not merged: file[0] cannot be opened read-write
13:13:11 HHC00007I Previous message from function 'cckd_sf_remove' at cckddasd.c(4337)
13:13:11 HHC00333I 0:0270   32/64       size free  nbr <b>st</b>   reads  writes l2reads    hits switches
13:13:11 HHC00335I 0:0270 ------------------------------------------------------------------------
13:13:11 HHC00336I 0:0270 [*] 32 00003737911 000% 0000    0000000 0000000 0000000 0000000  0000000
13:13:11 HHC00338I 0:0270 dasd/pub001.270
13:13:11 HHC00339I 0:0270 <b>[0]</b> 32 00003734049 000% 0000 <b>ro</b> 0000000 0000000 0000000
13:13:11 HHC00340I 0:0270 shadow_dasd/pub001_*.270
13:13:11 HHC00341I 0:0270 <b>[1]</b> 32 00000003862 000% 0000 <b>rw</b> 0000000 0000000 0000000
</pre>

Notice the "status" (`st`) column: `ro` means "read-only". `rw` means "read/write".

You currently have a base image [*] with two shadow files. The first [0] is read-only (`ro`), and the second [1] is read/write (`rw`).

You are trying to merge your second [1] read/write shadow file into your first [0] read-only shadow file.

Hercules correctly reports that it cannot do that.

Check your configuration file and/or your Windows file properties (attributes) for your first shadow file. I'm 100% certain you will see that the file is indeed marked read-only in either your Hercules configuration file and/or in Windows.

You need to mark your first shadow file -- the one you want to merge _into_ --as read/write _(i.e. you need to remove the read-only attribute from the file)_ before you can merge anything into it.

I see no bug here. All I see is an obvious user error.

Closing issue as PEBKAC.
