### ISSUE TITLE
Trying to build 4.6 with Visual Studio 2022 says not supported version 

### ISSUE THREAD

**Issue by YossiReichman** [SDL-Hercules-390/hyperion#569]
![hercules 4 6 buid](https://github.com/SDL-Hercules-390/hyperion/assets/39558335/0ff6f787-aa26-4032-b8a0-fb91eeb59106)
Severity	Code	Description	Project	File	Line	Suppression State
Error		No supported version of Visual Studio is installed	Hercules	C:\hyperion-Release_4.6\vstools.cmd	1

	
Microsoft Visual Studio Professional 2022
Version 17.4.3
VisualStudio.17.Release/17.4.3+33205.214
Microsoft .NET Framework
Version 4.8.09032

Installed Version: Professional

Visual C++ 2022   00476-80000-00000-AA906
Microsoft Visual C++ 2022

ASP.NET and Web Tools   17.4.326.54890
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.4.326.54890
Azure App Service Tools v3.0.0

C# Tools   4.4.0-6.22580.4+d7a61210a88b584ca0827585ec6e871c6b1c5a14
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

NuGet Package Manager   6.4.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   17.0.10921.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.4.0-6.22580.4+d7a61210a88b584ca0827585ec6e871c6b1c5a14
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

**Comment by wrljet** [comment]
Joseph,

The build rigging needs to find certain environment variables.

You can get those by using one of the VS command prompts.

Off the Start menu, expand VS2022, and then Visual Studio Tools.  Select x64 Native Tools Command Prompt.

Run your build in there.

Instructions for building on Windows are [here](http://www.softdevlabs.com/hercules-vs2015-build.html)

![Capture](https://github.com/SDL-Hercules-390/hyperion/assets/3638124/0a88af7c-4818-4036-aa2c-c3cd2526ed81)

I can help you through the process.  But if you have not done this before, you might find it easier to use [Hercules-Helper-Windows](https://github.com/wrljet/hercules-helper-windows)

It will automate getting all the required optional bits of Visual Studio installed, etc. and get Hercules built.

Bill

**Comment by YossiReichman** [comment]
defined VS170CMNTOOLS Thank you

**Comment by YossiReichman** [comment]
Just defined VSCMN170TOOLS and build let me close thanks

**Comment by wrljet** [comment]
> For 4.5 I had no issues building had VS pro 2020 Let me look thanks 

There's really little to no difference in the Windows build between 4.5 to 4.6.
