### ISSUE TITLE
Misuse of the getrusage() function

### ISSUE THREAD

**Issue by Rhialto** [SDL-Hercules-390/hyperion#573]
In my quest to make Hercules compile cleanly, I came across this compiler warning from gcc 10 on NetBSD:
```
hsccmd.c: In function 'qproc_cmd':
hsccmd.c:9409:28: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
 9409 |             if (getrusage( (int) sysblk.cputid[i], &rusage ) == 0)
      |                            ^
```
According to my manual, the first argument to `getrusage()` should be an integer value, either `RUSAGE_SELF` or `RUSAGE_CHILDREN`. The specified value is of type `TID`, apparently a "CPU thread id". That can't work.

The linux manual page at https://linux.die.net/man/2/getrusage shows a third possible value: `RUSAGE_THREAD (since Linux 2.6.26)` which indicates the current thread, not some random specified thread.

This isn't fixable with a simple patch. The whole context (looping over threads and trying to obtain each of their resource usages) is inapplicable here. https://github.com/SDL-Hercules-390/hyperion/blob/65c97fd6c4dcecd9ad64b89e65432e1bda9f7515/hsccmd.c#L9402-L9409

Whatever this function (which handles the qproc command) tries to do can't be done with `getrusage()`, if at all (within POSIX), and probably needs to be re-thought. Hence no patch, sorry about that.

**Comment by Fish-Git** [comment]
### FYI:

This is a _very old_ issue, and was _discussed to death **many**_ times in _many_ different GitHub Issues over the years, in both the old Hercules repository as well as in SDL's repository too:

* https://github.com/hercules-390/hyperion/issues/217
* https://github.com/SDL-Hercules-390/hyperion/issues/10
* https://github.com/SDL-Hercules-390/hyperion/pull/79
* https://github.com/SDL-Hercules-390/hyperion/pull/83
* https://github.com/SDL-Hercules-390/hyperion/commit/2ef9d79793df3ec6a392dc6720a87499d2411d54

I personally am _**not**_ the least bit interested in dredging up this long standing known issue just so we can once again beat a dead horse that has already been resting peacefully in its tomb for years now.

I am closing this issue.

**Comment by wrljet** [comment]
I've been meaning to bring this up for a year or so, but haven't gotten around to it. :)

**Comment by Fish-Git** [comment]
Well, if you read that first issue (\#217), you'll see Mark's comment where he says it _did_ work at one point in time, but then changed things.

It's kind of frustrating that, _apparently_, neither Linux not POSIX seems to support/provide any way to do what we ultimately need to do:  obtain resource usage for another thread in our own damn process! &nbsp; `:(`

It's trivially easy to do so on Windows, but it seems Linux/POSIX either doesn't provide that ability, or else they're hiding it.

Isn't there some tool on Linux that allows you to see (display) CPU and memory usage, etc, for all/ANY processes in the system? Do those tools allow you to drill down and see such information for each thread in a process? If they do, then there's _obviously_ a way to do it! We just need to learn _HOW_.

In any case, it's not my problem, so I'm not going to worry about it. I don't know Linux. I'm not a Linux developer. I leave such things up to the other developers on our team who _are_ experienced at Linux. That's _their_ job. I deal with the Windows side of things.
