### ISSUE TITLE
z/OS ADCD 1.13f  ipl fails

### ISSUE THREAD

**Issue by student501** [SDL-Hercules-390/hyperion#586]
Hyperion version:  **4.6.0.1-SDL-g65c97fd** built unter Debian Bookworm.

Trying to IPL [z/OS 1.13 ADCD 2013.10](https://archive.org/details/zOS.113.f.2013.10) published last year on [archive.org](https://archive.org).

The log is very short:

<pre>
HHC01603I ipl a80
HHC00811I Processor CP00: architecture mode ESA/390
HHC00811I Processor CP01: architecture mode ESA/390
HHC00814I Processor CP00: SIGP Set architecture mode            (12) CP00, PARM 00000001: CC 0
HHC00811I Processor CP00: architecture mode z/Arch
HHC00107I Starting thread cckd_ra(), active=0, started=0, max=2
HHC00100I Thread id 00007f77177fd6c0, prio 0, name 'cckd_ra thread 1' started
HHC00107I Starting thread cckd_ra() from cckd_ra(), active=1, started=1, max=2
HHC00100I Thread id 00007f77176fc6c0, prio 0, name 'cckd_ra thread 2' started
HHC00801I Processor CP00: Operand exception interruption code 0015 ilc 4
HHC02324I CP00: PSW=0400200080000000 0000000020000178 INST=B2342000     STSCH 0(2)                   store_subchannel
HHC02326I CP00: V:0000000020012C58:R:000000007FFF3C58:K:06=00000000 00000000 00000000 00000000  ................
HHC02269I CP00: R0=0000000020012C94 R1=0000000000050000
HHC02269I CP00: R2=0000000020012C58 R3=0000000000000030
HHC02269I CP00: R4=0000000020012C58 R5=0000000000000000
HHC02269I CP00: R6=000000002000F250 R7=0000000000000002
HHC02269I CP00: R8=00000000FFFFFFF9 R9=0000000020012000
HHC02269I CP00: RA=0000000000000005 RB=000000002000079C
HHC02269I CP00: RC=00000000A0000000 RD=00000000200006E4
HHC02269I CP00: RE=00000000A0000172 RF=00000000FFFFFFF8
HHC02271I CP00: C0=0000000000000200 C1=0000000000004003
HHC02271I CP00: C2=0000000000000000 C3=0000000000000000
HHC02271I CP00: C4=0000000000000000 C5=0000000000000000
HHC02271I CP00: C6=00000000FE000000 C7=0000000000000000
HHC02271I CP00: C8=0000000000000000 C9=0000000000000000
HHC02271I CP00: CA=0000000000000000 CB=0000000000000000
HHC02271I CP00: CC=0000000000000000 CD=0000000000000000
HHC02271I CP00: CE=00000000C2000000 CF=0000000000000000
<b>HHC00809I Processor CP00: disabled wait state 0002000000000000 00000000003000B1</b>
</pre>

**Comment by Tirocinante** [comment]
Hi all!

Student501, did you manage to convert the volumes from bin to cckd, I mean,
all of them? I got some errors after trying uncompressing them. In
particular, FDBBN1 seems to be corrupted, although I don't think it is
needed for IPLing.

Thanks.


Il mar 18 lug 2023, 10:35 student501 ***@***.***> ha scritto:

**Comment by student501** [comment]
Converted all but FDBBN1, but since IPL fails this early, it can not be the reason.

**Comment by Fish-Git** [comment]
> The log is very short:

Why?

> <pre>
> <b>HHC00809I Processor CP00: disabled wait state 0002000000000000 00000000003000B1</b>
> </pre>

Have you looked up this disabled wait code in the IBM manual? What does it mean?

**Comment by student501** [comment]
> > The log is very short:
> 
> Why?
> 
> > HHC00809I Processor CP00: disabled wait state 0002000000000000 00000000003000B1
> 
> Have you looked up this disabled wait code in the IBM manual? What does it mean?

Thanks for the hint.  How do I split it? In https://www.ibm.com/docs/en/zos/2.2.0?topic=codes-system-completion-code-module-table I see

0B1 |   | SSI | IEFJACTL IEFJCNTL IEFJJCLS IEFJJOBS IEFJWTOM

Or should it be a complete match to 3000B1 ?

**Comment by Fish-Git** [comment]
Google for "ibm zos disabled wait codes":

* https://www.google.com/search?q=ibm+zos+disabled+wait+codes

Very first hit at top of page:

* https://www.ibm.com/docs/en/zos/2.3.0?topic=codes-wait-state

Scroll down and click link for "0B1"

* https://www.ibm.com/docs/en/zos/2.3.0?topic=codes-0b1

**Comment by Fish-Git** [comment]
> The log is very short:

You did not answer this question.

**Comment by Fish-Git** [comment]
Did you read this before asking for help?

* [SUBMITTING PROBLEM REPORTS](https://github.com/SDL-Hercules-390/hyperion/issues/373)

There is a link to it at the very top of our GitHub Issues page:

* https://github.com/SDL-Hercules-390/hyperion/issues
*

**Comment by student501** [comment]
Fish, thank you very much for your answers, and sorry for misinterpreting submission rules. Attached the complete log.
[zos113f-ipl.log](https://github.com/SDL-Hercules-390/hyperion/files/12082200/zos113f-ipl.log)

So b1 is "A required device is not defined.", which means that the problem most likey lies in my config, not in hyperion.

**Comment by Fish-Git** [comment]
PEBKAC. Closing.
