### ISSUE TITLE
Continuation for #562. Issue with IP Address.

### ISSUE THREAD

**Issue by Rakeshreddy11** [SDL-Hercules-390/hyperion#587]
Hi,
I am using Hyperion 4.5
I tried both these options, i am able to access to my zos with in the host environment. But I can't access the Gust IP outside of the HOST. Masking the Host IP.
0E20.2 LCS -n xxx.xxx.xxx.xxx -n 00-15-5D-25-E1-A3
0E20.2 LCS -n xxx.xxx.xxx.xxx -m 02-15-5D-25-E1-A3

I have Hyperion 4.0 on the same host where i use below parm and i am able to use the Guest IP outside of the Host.
0E20.2 LCS -n xxx.xxx.xxx.xxx -m 00-15-5D-25-E1-A3

Could you help me fixing this issue. Because of this, i am not able to upgrade to newer versions of Hyperion.

Thanks in advance.

**Comment by Fish-Git** [comment]
This is not a problem with Hercules. It is a user configuration problem or networking problem.

**Comment by Fish-Git** [comment]
* https://hercules-390.groups.io/g/group
* https://github.com/SDL-Hercules-390/hyperion/issues/373
