### ISSUE TITLE
Include the HTML directory with the executables when a new release is created.

### ISSUE THREAD

**Issue by LaddieHanus1** [SDL-Hercules-390/hyperion#598]
This is to have the documentation match the current code thats runnning - Laddie

**Comment by Fish-Git** [comment]
It already is, in the separate source code download. When you download the executables for the new release, just download the source code to go along with it, and copy the `html` directory to wherever you want and delete the rest if you're not interested in it.

Besides, other users may _not_ want the `html` directory "polluting" their binaries-only download, preferring instead to simply refer to the always available online documentation.

Request rejected.
