### ISSUE TITLE
Double messages on startup

### ISSUE THREAD

**Issue by joemonk64** [SDL-Hercules-390/hyperion#606]
when starting hercules 4.6 on Windows 11, I get the following in the log:

<pre>
HHC00100I Thread id 00002890, prio 5, name 'impl_thread' started
HHC00100I Thread id 00002f60, prio 4, name 'logger_thread' started
<b>HHC01413I Hercules version 4.6.0.10941-SDL-g65c97fd6
HHC01414I (C) Copyright 1999-2023 by Roger Bowler, Jan Jaeger, and others
HHC01417I ** The SDL 4.x Hyperion version of Hercules **
HHC01415I Build date: Jun  8 2023 at 15:48:12</b>
<i>HHC01413I Hercules version 4.6.0.10941-SDL-g65c97fd6
HHC01414I (C) Copyright 1999-2023 by Roger Bowler, Jan Jaeger, and others
HHC01417I ** The SDL 4.x Hyperion version of Hercules **
HHC01415I Build date: Jun  8 2023 at 15:48:12</i>
HHC01417I Built with: Microsoft Visual Studio 2008 (MSVC 150030729 1)
HHC01417I Build type: Windows MSVC AMD64 host architecture build
HHC01417I Modes: S/370 ESA/390 z/Arch
</pre>

As you can see, it looks like it is looping thru the startup code twice...

**Comment by wrljet** [comment]
Joe,

I'm not seeing that behavior.
Can you post your config file?

Bill

**Comment by joemonk64** [comment]
[hercules.txt.txt](https://github.com/SDL-Hercules-390/hyperion/files/13193460/hercules.txt.txt)
[hercules.log](https://github.com/SDL-Hercules-390/hyperion/files/13193464/hercules.log)

Config and log files attached. 

Note: I was running this as a test...

**Comment by atncsj6h** [comment]
same on apple big sur

```
20:14:26 HHC01413I Hercules version 4.7.0.11015-SDL-DEV-g040abe0f
20:14:26 HHC01414I (C) Copyright 1999-2023 by Roger Bowler, Jan Jaeger, and others
20:14:26 HHC01417I Built using Hercules-Helper (version: v0.9.8-5-gc2450a8-dirty)
20:14:26 HHC01415I Build date: Aug 15 2023 at 16:20:01

20:14:26 HHC01413I Hercules version 4.7.0.11015-SDL-DEV-g040abe0f
20:14:26 HHC01414I (C) Copyright 1999-2023 by Roger Bowler, Jan Jaeger, and others
20:14:26 HHC01417I Built using Hercules-Helper (version: v0.9.8-5-gc2450a8-dirty)
20:14:26 HHC01415I Build date: Aug 15 2023 at 16:20:01

20:14:26 HHC01417I Built with: Apple Clang 13.0.0 (clang-1300.0.29.30)
20:14:26 HHC01417I Build type: Mac OS X aarch64 host architecture build

```

enrico

**Comment by wrljet** [comment]
OK, I see it myself now, on macOS Ventura.

Bill

**Comment by wrljet** [comment]
OK, I've found the problem, I think.

**Comment by wrljet** [comment]
Joe, this should be addressed as part of commit https://github.com/SDL-Hercules-390/hyperion/commit/a9c14be18ecbed64e33cef1421f4fda881dbec50.

Bill

**Comment by Fish-Git** [comment]
No response. Closing.
