### ISSUE TITLE
dasdseq enhancement request

### ISSUE THREAD

**Issue by GregoryTwin** [SDL-Hercules-390/hyperion#614]
At the moment, `dasdseq` is able to extract data from a z/OS sequential dataset using either ASCII or binary mode. However, binary mode can only be used for a very limited number and type of datasets, like TSO TRANSMIT results for example, since record boundaries would otherwise be lost if ASCII mode were to be used.

I propose implementing a third `dasdseq` mode, called e.g. "RECORD" or "BLOCK' mode. This would be the same type of mode that FTP currently uses when `'quote mode b'` is specified when uploading or downloading a file, where each data block is simply prefixed with x'80' followed by a 2-byte block length.

Using this new `dasdseq` extraction mode, the ease and speed at which transferring datasets between Hercules and a real mainframe could be _dramatically_ improved:

- On z/OS under Hercules, we could use `ADRDSSU` to dump any data to a sequential dataset.
- With the improved `dasdseq`, we could then extract that sequential dataset to a host system file.
- On the host system, we could then use _**FTP**_ "quote mode b" (i.e. binary transfer mode) to _directly_ upload that file to the real mainframe.
- And then of course on the real mainframe, we would then restore the original dataset via `ADRDSSU`.

We can of course currently accomplish the thing today, but it unfortunately takes _two separate FTPs_ in order to do so:

- On z/OS under Hercules, we use `ADRDSSU` to dump any data to a sequential dataset.
- Using _**FTP**_ "quote mode b" (binary transfer) on our host system, we then _download_ this sequential dataset _from_ z/OS (running under Hercules) to our host system.
- Then, using _**FTP**_ "quote mode b" (binary transfer) on our host system _again_, we then _upload_ this file to the real mainframe.
- And finally, on the real mainframe we then restore the original dataset via `ADRDSSU`.

Given how slow FTP is compared to `dasdseq` _(especially for large datasets)_, this new `dasdseq` extraction mode would thus allow datasets to be uploaded or downloaded to/from real mainframes _much_ more quickly and easily than without it.

**Comment by Fish-Git** [comment]
Hi Gregory!

That sounds like a really good idea! I will try to get started on making that change for you right away! Thank you for suggesting it! &nbsp;`:)`

_(Note: it might take me a little while to complete, as I am currently busy with other things at the same time, but I will let you know when I am done so you can test it.)_

**Comment by Fish-Git** [comment]
Gregory (@GregoryTwin),

SOME QUESTIONS:

1. I notice that `dasdseq` currently writes its output one logical record at a time. That is to say, currently it reads one "block" of data from the input dataset, and then writes multiple "lrecl" records to the output file (i.e. fixed-block mode). Am I to presume you are requesting that "record" mode would prefix each _logical record_ with X'80' + XL2'reclen' + record, whereas "block" mode would do the same thing but for the entire block only? Yes?

2. `dasdseq` does not currently write any file output when the `-ascii` option is specified. Instead, it simply displays each translated logical record to the console/terminal (i.e. to stdout) as a regular Hercules message:
```
dasdseq -ascii "Q:/111111.cckd" LARGE2.DATASET
03:08:15.778 dasdseq 111111.cckd LARGE2.DATASET started; process-id = 1544 (0x00000608)
03:08:15.816 HHC02499I Hercules utility DASDSEQ - Sequential DSN unload - version 4.7.0.11062-SDL-DEV-gfd3a6a77
03:08:15.816 HHC01414I (C) Copyright 1999-2023 by Roger Bowler, Jan Jaeger, and others
03:08:15.816 HHC01417I ** The SDL 4.x Hyperion version of Hercules **
03:08:15.816 HHC01415I Build date: Feb  8 2024 at 03:06:54
03:08:15.841 HHC00476I 0:0000 CCKD64 file 'Q:/111111.cckd': opened r/o
03:08:15.841 HHC00470I 0:0000 CCKD64 file 'Q:/111111.cckd': model 3390-27 cyls 32760 heads 15 tracks 491400 trklen 56832
03:08:15.932 HHC02691I ascii> '000000000000001'
03:08:15.932 HHC02691I ascii> '000000000000002'
03:08:15.932 HHC02691I ascii> '000000000000003'
03:08:15.932 HHC02691I ascii> '000000000000004'
```

3. Should the new "record" mode also apply (be valid) when the `-ascii` option is specified, and cause `dasdseq` to write its translated records to the _output file_ instead? (i.e. _not_ to the console/terminal?) Yes? Or should the `-ascii`, `-block` and `-record` options all be considered to be mutually exclusive to one another?

Thanks.

**Comment by GregoryTwin** [comment]
Thank you very much for your attention to the request!
Please see my thoughts below...

1. I suppose, dasdseq "block" mode should write data exactly the same way as "ftp get" does when "quote mode block" is in effect. For a member of partitioned data set with RECFM=FB LRECL=80 BLKSIZE=27920 ftp get writes logical records prefixed with X'800050'. z/OS ftp does not have "quote mode record", there is just "quote mode block", but IBM documentation sometimes call this "record mode" as well as "block mode", probably because it functionality.

2. I guess, write translated records (-ascii) could be subject of another enhancement.

3. "_should the new "record" mode also apply (be valid) when the -ascii option is specified_"
definitely NO. -ascii and -block should be mutually exclusive. -block assumes binary mode. 

Let me try to explain once more. RECFM=F and RECFM=V data sets could be used when thansferred in binary mode, because in both cases we able split data stream to restore original record (when F just split by LRECL, when V - split using record length kept on record descriptor  BDW & RDW. So, -block mode is not really necessary for RECFM F or V data set. However, without -block mode RECFM=U data sets cannot be processed at all, because block boundary are lost and these is no way to split data stream correctly. This is especially useful for ADRDSSU DUMP data set (RECFM=U). 
mode is

**Comment by GregoryTwin** [comment]
ha-ha) I'm completely wrong with point 2. above, sorry for that! I've just tried ftp:

`ftp mf
logon
password
ascii
quote mode b
get aaa
`

it works for ascii mode too! I got translated records prefixed with x'800050'. So, probably would be better to allow -block mode with -ascii, to provide the same beheviour as ftp.

**Comment by GregoryTwin** [comment]
I've also noticed that the last block of data transferred in "block mode" prefixed with x'40llll' rather than x'80llll'... had a look at RFC959 https://www.w3.org/Protocols/rfc959/3_DataTransfer.html 

in detail:
Block Header

            +----------------+----------------+----------------+
            | Descriptor     |    Byte Count                   |
            |         8 bits |                      16 bits    |
            +----------------+----------------+----------------+
            

         The descriptor codes are indicated by bit flags in the
         descriptor byte.  Four codes have been assigned, where each
         code number is the decimal value of the corresponding bit in
         the byte.

            Code     Meaning
            
             128     End of data block is EOR
              64     End of data block is EOF
              32     Suspected errors in data block
              16     Data block is a restart marker

I suppose, descriptors 32 and 16 (x'20' and x'10') not applicable in our particular case.

**Comment by Fish-Git** [comment]
> 1. I suppose, dasdseq "block" mode should write data exactly the same way as "ftp get" does when "quote mode block" is in effect. For a member of partitioned data set with RECFM=FB LRECL=80 BLKSIZE=27920 ftp get writes logical records prefixed with X'800050'. z/OS ftp does not have "quote mode record", there is just "quote mode block", but IBM documentation sometimes call this "record mode" as well as "block mode", probably because it functionality.

Thank you for the clarification!

> _(Oops!)_  I'm completely wrong with point 3 above!

> It works for ascii mode too! I got translated records prefixed with x'800050'. So, probably would be better to allow -block mode with -ascii, to provide the same beheaviour as ftp.

Nope. We're both wrong.

After reviewing (looking closely at) dasdseq's code (logic), it appears the "-ascii" option does not write any data whatsoever to the output file! Rather, it simply _displays_ the records _on the Hercules console!_ (as a Hercules message). The output file is never written to.

No I suppose we could change that behavior, but I would rather not. It appears the original author purposely designed dasdseq that way. They just didn't document it that well.

**Comment by Fish-Git** [comment]
> I've also noticed that the last block of data transferred in "block mode" is prefixed with x'40....' rather than x'80....'.
> 
> So I had a look at section 3.4.2 on page 21-22 of [RFC959 (File Transfer Protocol)](https://www.rfc-editor.org/info/rfc959):

Thank you! &nbsp;But I am still confused about the X'40' EOF flag. &nbsp;`:-(`

The way `dasdseq` works is, it reads the dataset one block at a time, and then processes each block one record at a time, until there are no more blocks remaining.

Should the EOF flag be used on the last record of each block? Or only on the last record of the very last block?

**Comment by GregoryTwin** [comment]
According to RFC959 just very last block should have flag EOF X'40', all other blocks have EOR X'80'. I've downloaded data set LRECL=80 BLKSIZE=27920 to PC using "quote mode b", as expected, only last record  marked with x'40'. I'm interested how principal is this EOF flag, so I update last record on the downloaded file replacing x'40' to x'80' and tried to upload this file back to MF using "quote mode b" - successfully. So, I believe, this EOF flag just formal requirement of RFC959, ftp normally process file having x'80' anywhere, including last record.

**Comment by Fish-Git** [comment]
> So, I believe, this EOF flag is just an _informal_ requirement of [RFC959](https://www.rfc-editor.org/info/rfc959). FTP apparently processes a file normally having x'80' anywhere in its data, including in the very last record.

Good! Because supporting it (the X'40' EOF flag) would complicate the existing logic in `dasdseq`. Supporting just the X'80' EOR flag on the other hand should be easy-peasy.

I will make the change right away.

Thanks for all your help, Gregory!

**Comment by Fish-Git** [comment]
Implemented in commit 179ba63797f9e1cfd820e04f2eee4e9f1ed96e68.

Feel free to give it a try!

Closing.

**Comment by GregoryTwin** [comment]
Thank you very much! Also thank you for correcting my English, this is useful for me)

**Comment by Fish-Git** [comment]
> Also thank you for correcting my English, this is useful for me.

You're very welcome! &nbsp;Please keep in mind however, that my own English is not perfect! &nbsp;`:)`
