### ISSUE TITLE
runnig z/osmf IZUSVR1 procedure failed in z/OS 2.5

### ISSUE THREAD

**Issue by syspmk** [SDL-Hercules-390/hyperion#619]
1. During java -version failed return a dump
2. Is this error related to  enable facility 129 where during start of hercules it return the following :
     `13:51:42 HHC00898W Facility( 129_ZVECTOR ) *Enabled for z/Arch`
     `13:51:42 HHC00007I Previous message from function 'facility_enable_disable' at facility.c(4611)`
3. it is important now because i need to simulate the installation of z/os 3.1 where ibm announced the server pack is running only under z/osmf

**Comment by Fish-Git** [comment]
> 1. During java -version failed return a dump

java is not Hercules.

> 2. Is this error related to  enable facility 129 where during start of hercules it return the following :
>     `13:51:42 HHC00898W Facility( 129_ZVECTOR ) *Enabled for z/Arch`
>     `13:51:42 HHC00007I Previous message from function 'facility_enable_disable' at facility.c(4611)`

I have no idea whatsoever. You are essentially asking whether and how a given Hercules configuration setting impacts  your guest operating system. We do not provide help with guest operating systems. We provide help with Hercules. All guest operating system questions are your responsibility, not ours.

> 3. it is important now because i need to simulate the installation of z/os 3.1 where ibm announced the server pack is running only under z/osmf

That's your problem, not ours.

Closing issue as Invalid.
