### ISSUE TITLE
gmake check fails

### ISSUE THREAD

**Issue by ghost** [SDL-Hercules-390/hyperion#630]
environment apple sonoma macbook-pro m3 

at version
enrico@enrico-mbp build % ./hercules --version
HHC01413I Hercules version 4.7.0.11088-SDL-DEV-gfffc1f57
HHC01414I (C) Copyright 1999-2024 by Roger Bowler, Jan Jaeger, and others
HHC01417I Built using Hercules-Helper (version: v0.9.8-5-gc2450a8-dirty)
HHC01415I Build date: Feb 20 2024 at 15:06:37

gmake check fails
...
>>>>> line  1786: Received unexpected wait state:  0002000180000000 000000000BAD0001
Test "Various CKD dasd I/O tests":  0 OK compares.  One failure.
...

works at version

enrico@enrico-mbp build % ./hercules --version
HHC01413I Hercules version 4.7.0.11078-SDL-DEV-g79a14889
HHC01414I (C) Copyright 1999-2024 by Roger Bowler, Jan Jaeger, and others
HHC01417I Built using Hercules-Helper (version: v0.9.8-5-gc2450a8-dirty)
HHC01415I Build date: Feb 20 2024 at 15:16:39

e

**Comment by wrljet** [comment]
Yup, that's a known issue -- being worked on.

**Comment by atncsj6h** [comment]
thank You Bill

**Comment by Fish-Git** [comment]
Should be fixed now. Closing.
