### ISSUE TITLE
some dasd tests pollute the repository with the shadow files

### ISSUE THREAD

**Issue by ghost** [SDL-Hercules-390/hyperion#638]
the title tells ... 

while it might be acceptable to run the build in a subdirectory of the repository 
it is just wrong to have collateral damages to the repository when running make check 
even if the shadow files are listed in the .gitignore file  

solution ...

change the string  **sf="$(testpath)/**  to **sf="./**

tested and working ... the shadow files are created in the build(current)  path

**Comment by Fish-Git** [comment]
Should be fixed now by commit 3b3cd7ce3c9921e7dd37c28fb2c7a0ef0c3ee9b7.

Closing.

**Comment by atncsj6h** [comment]
thank you Fish !
