### ISSUE TITLE
Possible run zPDT CNF on Hercules?

### ISSUE THREAD

**Issue by andysilva86** [SDL-Hercules-390/hyperion#644]
Hi, have a question is possible to run disks from zPDT on Hyperion?

 #devmap file for stock z/OS image
[system]
processors	1
memory	4096m
3270port	3270
system_name	VS01

#IPL
ipl DE27 DE28K2M

[manager]
name    aws3274 0002    #define a few 3270 terminals 
device  0060    3279    3274    mstcon
device  0061    3279    3274    tso1

[manager]
name	awsosa	0009	--path=A0	--pathtype=OSD	--tunnel_intf=y
device	1500	osa  osa	--unitadd=0
device	1501	osa	osa	--unitadd=1
device	1502	osa	osa	--unitadd=2
device	1503	osa	osa	--unitadd=3

[manager]
name awstape 000A
device 580 3490 3490

#zOS v2.5
[manager] 
name	awsckd	0001
device	DE24 	3390	3390  /volumes/ZFSVS1.CKD
device	DE26 	3390	3390  /volumes/Z25VS1.CKD
device	DE27	3390	3390  /volumes/D25VS1.CKD
device	DE28 	3390	3390  /volumes/OPEVS1.CKD
device	DE29	3390	3390  /volumes/STGVS1.CKD
device	DE2A	3390	3390  /volumes/JSPVS1.CKD
device	DE2B	3390	3390  /volumes/PRDVS1.CKD
device	DE2C	3390	3390  /volumes/JCKVS1.CKD
device	DE00	3390	3390  /volumes/USRVS1.CKD	
device	DE01	3390	3390  /volumes/DEVVS1.CKD

**Comment by Fish-Git** [comment]
> Hi, have a question ...

Then please ask it in our [support forum](https://hercules-390.groups.io/g/group), not here.

GitHub Issues are for reporting bugs, not for asking questions.
