### ISSUE TITLE
IPL Wait State 05D in base SYSPLEX 

### ISSUE THREAD

**Issue by itailleur** [SDL-Hercules-390/hyperion#663]
I have a base **SYSPLEX** with 2 z/OS systems. They communicate each other via **CTCE**.

System 1 is the dasd server, and System 2 is the dasd client.

The wait state occurs on the system 2.

The problem is repeatable.

* The Hercules version is: **Hercules version 4.7.0.11119-SDL-gf7d2360a**
* The host OS is **Opensuse 15.2**
* The guest OS is **z/OS 2.4 PUT2402 applied**

The same problem occurs with Hercules 4.8 dev, but everything works fine with Hercules 4.6, 4.5, and 4.4. The problem only occurs With Hercules 4.7 and 4.8.

Hercules conf and log files:

* System 1:<br>[herczos24-1ctce2.conf.txt](https://github.com/SDL-Hercules-390/hyperion/files/15369798/herczos24-1ctce2.conf.txt)<br>[herczos241.log](https://github.com/SDL-Hercules-390/hyperion/files/15369800/herczos241.log)

* Systems2:<br>[herczos24-2ctce2.conf.txt](https://github.com/SDL-Hercules-390/hyperion/files/15369803/herczos24-2ctce2.conf.txt)<br>[herczos242.log](https://github.com/SDL-Hercules-390/hyperion/files/15369804/herczos242.log)

**Comment by Fish-Git** [comment]
Change BOTH of your configuration files to use **`cu=3990-6`** _(not `3990-3`)_.

**Comment by itailleur** [comment]
It works fine with `cu=3990-6`
Thanks a lot
