### ISSUE TITLE
Issue Closed

### ISSUE THREAD

**Issue by tomwill1701** [SDL-Hercules-390/hyperion#664]

**Comment by Fish-Git** [comment]
Need more information:

* [_**SUBMITTING PROBLEM REPORTS**_](https://github.com/SDL-Hercules-390/hyperion/issues/373)

**Comment by tomwill1701** [comment]
Here is the log

20:04:17.567 ******** Power-On Date and Time  = 2024/05/19 at 20:04:17 PM
20:04:17.568 ******** Working directory to be = F:/Hercules-Volumes/
20:04:17.568 ******** Command line to execute = F:/Hercules-4.7.0/Hercules.exe -f F:/Hercules-Volumes/zvm53.cnf EXTERNALGUI
20:04:17.569 ******** Current active log file = "C:/Users/tom.DTS/Documents/HercGUI/Log Files/Hercules Logfile.000.txt"
20:04:17.569 ******** HHC046I Acceptance of PGMPRDOS LICENSED setting verified
20:04:17.577 Hercules started; process-id = 11160 (0x00002B98)
20:04:17.729 0x00002B98 HHC01413I Hercules version 4.7.0.11119-SDL-gf7d2360a
20:04:17.729 0x00002B98 HHC01414I (C) Copyright 1999-2024 by Roger Bowler, Jan Jaeger, and others
20:04:17.729 0x00002B98 HHC01417I ** The SDL 4.x Hyperion version of Hercules **
20:04:17.729 0x00002B98 HHC01415I Build date: Mar  9 2024 at 20:27:46
20:04:17.729 0x00002B98 HHC01417I Built with: Microsoft Visual Studio 2008 (MSVC 150030729 1)
20:04:17.729 0x00002B98 HHC01417I Build type: Windows MSVC AMD64 host architecture build
20:04:17.729 0x00002B98 HHC01417I Modes: S/370 ESA/390 z/Arch
20:04:17.729 0x00002B98 HHC01417I Max CPU Engines: 64
20:04:17.729 0x00002B98 HHC01417I Using   shared libraries
20:04:17.729 0x00002B98 HHC01417I Using   Fish threads Threading Model
20:04:17.729 0x00002B98 HHC01417I Using   Error-Checking Mutex Locking Model
20:04:17.729 0x00002B98 HHC01417I With    Shared Devices support
20:04:17.729 0x00002B98 HHC01417I With    Dynamic loading support
20:04:17.729 0x00002B98 HHC01417I With    External GUI support
20:04:17.729 0x00002B98 HHC01417I With    Partial TCP keepalive support
20:04:17.729 0x00002B98 HHC01417I With    IPV6 support
20:04:17.729 0x00002B98 HHC01417I With    HTTP Server support
20:04:17.729 0x00002B98 HHC01417I With    sqrtl support
20:04:17.729 0x00002B98 HHC01417I With    Signal handling
20:04:17.729 0x00002B98 HHC01417I With    Watchdog monitoring
20:04:17.729 0x00002B98 HHC01417I With    CCKD BZIP2 support
20:04:17.729 0x00002B98 HHC01417I With    HET BZIP2 support
20:04:17.729 0x00002B98 HHC01417I With    ZLIB support
20:04:17.730 0x00002B98 HHC01417I With    Regular Expressions support
20:04:17.730 0x00002B98 HHC01417I With    Object REXX support
20:04:17.730 0x00002B98 HHC01417I Without Regina REXX support
20:04:17.730 0x00002B98 HHC01417I With    Automatic Operator support
20:04:17.730 0x00002B98 HHC01417I Without National Language Support
20:04:17.730 0x00002B98 HHC01417I With    CCKD64 Support
20:04:17.730 0x00002B98 HHC01417I With    Transactional-Execution Facility support
20:04:17.730 0x00002B98 HHC01417I With    "Optimized" instructions
20:04:17.730 0x00002B98 HHC01417I With    OPTION_USE_SKAIP_AS_LOCK
20:04:17.730 0x00002B98 HHC01417I With    OPTION_SIE2BK_FLD_COPY
20:04:17.730 0x00002B98 HHC01417I With    OPTION_IODELAY_KLUDGE
20:04:17.730 0x00002B98 HHC01417I With    OPTION_MVS_TELNET_WORKAROUND
20:04:17.730 0x00002B98 HHC01417I With    OPTION_SIE_PURGE_DAT_ALWAYS
20:04:17.730 0x00002B98 HHC01417I With    OPTION_NOASYNC_SF_CMDS
20:04:17.730 0x00002B98 HHC01417I Machine dependent assists: cmpxchg1 cmpxchg4 cmpxchg8 cmpxchg16 hatomics=msvcIntrinsics
20:04:17.730 0x00002B98 HHC01417I Running on: W10TOM (Windows 11 Pro 23H2-10.0.22631 Intel(R) x64) LP=12, Cores=6, CPUs=1
20:04:17.730 0x00002B98 HHC01417I Built with crypto external package version 1.0.0.52-ga5096e5
20:04:17.730 0x00002B98 HHC01417I Built with decNumber external package version 3.68.0.102-g3aa2f45
20:04:17.730 0x00002B98 HHC01417I Built with SoftFloat external package version 3.5.0.105-g4b0c326
20:04:17.730 0x00002B98 HHC01417I Built with telnet external package version 1.0.0.63-g729f0b6
20:04:17.730 0x00002B98 HHC00100I Thread id 00010cb0, prio 5, name 'impl_thread' started
20:04:17.730 0x00002B98 HHC00100I Thread id 000103b4, prio 4, name 'logger_thread' started
20:04:17.730 0x00002B98 HHC00018I Hercules is running in elevated mode
20:04:17.730 0x00002B98 HHC02323W This build of Hercules has only partial TCP keepalive support
20:04:17.730 0x00002B98 HHC00007I Previous message from function 'impl' at impl.c(1313)
20:04:17.731 0x00002B98 HHC00150I Crypto module loaded (C) Copyright 2003-2016 by Bernard van der Helm
20:04:17.731 0x00002B98 HHC00151I Activated facility: Message Security Assist
20:04:17.731 0x00002B98 HHC00151I Activated facility: Message Security Assist Extension 1, 2, 3 and 4
20:04:17.739 0x00002B98 HHC17531W REXX(OORexx) dlopen 'rexx.dll' failed: The specified module could not be found.
20:04:17.739 0x00002B98 HHC00007I Previous message from function 'OORexxLoad' at hRexxapi.c(1340)
20:04:17.739 0x00002B98 HHC17511E REXX() Could not enable either Rexx package
20:04:17.739 0x00002B98 HHC00007I Previous message from function 'Enable' at hRexx.c(515)
20:04:17.739 0x00002B98 HHC17511E REXX() Could not enable default Rexx package
20:04:17.739 0x00002B98 HHC00007I Previous message from function 'InitializeRexx' at hRexx.c(262)
20:04:17.739 0x00002B98 HHC17500I REXX() Mode            : Command
20:04:17.739 0x00002B98 HHC17500I REXX() MsgLevel        : Off
20:04:17.739 0x00002B98 HHC17500I REXX() MsgPrefix       : Off
20:04:17.739 0x00002B98 HHC17500I REXX() ErrPrefix       : Off
20:04:17.739 0x00002B98 HHC17500I REXX() Resolver        : On
20:04:17.739 0x00002B98 HHC17500I REXX() SysPath    (58) : On
20:04:17.739 0x00002B98 HHC17500I REXX() RexxPath   ( 0) :
20:04:17.739 0x00002B98 HHC17500I REXX() Extensions ( 8) : .REXX;.rexx;.REX;.rex;.CMD;.cmd;.RX;.rx
20:04:17.740 0x00002B98 HHC02204I ARCHLVL        set to z/Arch
20:04:17.740 0x00002B98 HHC02204I LPARNAME       set to FLEXES
20:04:17.740 0x00002B98 HHC02204I LOADPARM       set to 0700
20:04:17.740 0x00002B98 HHC02204I LPARNUM        set to 00
20:04:17.740 0x00002B98 HHC02204I CPUMODEL       set to 1090
20:04:17.740 0x00002B98 HHC02204I CPUSERIAL      set to 01105B
20:04:17.740 0x00002B98 HHC02204I CPUVERID       set to 00
20:04:17.740 0x00002B98 HHC02204I DIAG8CMD       set to DISABLE  NOECHO
20:04:17.740 0x00002B98 HHC02204I ECPSVM         set to enabled, trap support enabled
20:04:17.740 0x00002B98 HHC02204I MAXCPU         set to 4
20:04:17.740 0x00002B98 HHC00111I Thread CPU Time IS available (_POSIX_THREAD_CPUTIME=1)
20:04:17.740 0x00002B98 HHC00100I Thread id 00012630, prio 2, name 'Processor CP00' started
20:04:17.740 0x00002B98 HHC00100I Thread id 000119d8, prio 7, name 'timer_thread' started
20:04:17.740 0x00002B98 HHC00811I Processor CP00: architecture mode z/Arch
20:04:17.740 0x00002B98 HHC00100I Thread id 000091e0, prio 2, name 'Processor CP01' started
20:04:17.740 0x00002B98 HHC00811I Processor CP01: architecture mode z/Arch
20:04:17.741 0x00002B98 HHC00100I Thread id 0000247c, prio 2, name 'Processor CP02' started
20:04:17.741 0x00002B98 HHC00811I Processor CP02: architecture mode z/Arch
20:04:17.741 0x00002B98 HHC00100I Thread id 00010700, prio 2, name 'Processor CP03' started
20:04:17.741 0x00002B98 HHC00811I Processor CP03: architecture mode z/Arch
20:04:17.741 0x00002B98 HHC02204I NUMCPU         set to 4
20:04:17.741 0x00002B98 HHC17003I MAIN     storage is 4G (mainsize); storage is not locked
20:04:17.742 0x00002B98 HHC00100I Thread id 000120bc, prio 4, name 'console_connect' started
20:04:17.747 0x00002B98 HHC05063I 0:0500 CTCE: Awaiting inbound connection :30882 <- 0:0000=127.0.0.1:30880/*
20:04:17.747 0x00002B98 HHC00414I 0:0123 CCKD file F:/Hercules-Volumes/zvm73/M01RES: model 3390-27 cyls 12250 heads 15 tracks 183750 trklen 56832
20:04:17.748 0x00002B98 HHC01024I Waiting for console connections on port 3270
20:04:17.788 0x00002B98 HHC00414I 0:0124 CCKD file F:/Hercules-Volumes/zvm73/VMCOM1: model 3390-27 cyls 12250 heads 15 tracks 183750 trklen 56832
20:04:18.079 0x00002B98 HHC02915I client 0 COMM: Connection received
20:04:18.080 0x00002B98 HHC02914I 0:0700 COMM: client 0 negotiations complete; ttype = 'IBM-3278-2-E'
20:04:18.080 0x00002B98 HHC01018I 0:0700 COMM: client 127.0.0.1 devtype 3270: connected
20:04:18.112 0x00002B98 HHC02915I client 1 COMM: Connection received
20:04:18.114 0x00002B98 HHC02914I 0:0701 COMM: client 1 negotiations complete; ttype = 'IBM-3278-2-E'
20:04:18.114 0x00002B98 HHC01018I 0:0701 COMM: client 127.0.0.1 devtype 3270: connected
20:04:19.557 0x00002B98 HHC00414I 0:0125 CCKD file F:/Hercules-Volumes/zvm73/730RL1: model 3390-27 cyls 12250 heads 15 tracks 183750 trklen 56832
20:04:20.237 0x00002B98 HHC00414I 0:0126 CCKD file F:/Hercules-Volumes/zvm73/M01S01: model 3390-27 cyls 12250 heads 15 tracks 183750 trklen 56832
20:04:20.277 0x00002B98 HHC00414I 0:0127 CCKD file F:/Hercules-Volumes/zvm73/M01P01: model 3390-27 cyls 12250 heads 15 tracks 183750 trklen 56832
20:04:20.280 0x00002B98 HHC05065I 0:0500 CTCE: Attempt outbound connection :30882 -> 0:0000=127.0.0.1:30880
20:04:20.313 0x00002B98 HHC17736W TXF: TIMERINT 50 is too small; using default of 400 instead
20:04:20.313 0x00002B98 HHC00007I Previous message from function 'txf_set_timerint' at transact.c(2587)
20:04:20.313 0x00002B98 HHC01541I HDL: dyngui.dll initiated
20:04:20.313 0x00002B98 HHC00100I Thread id 000059c8, prio 2, name 'rubato_thread' started
20:04:20.386 0x00002B98 HHC01603I herc ipl 0123
20:04:20.386 0x00002B98 HHC01600E Unknown command herc, enter 'help' for a list of valid commands
20:04:20.386 0x00002B98 HHC00007I Previous message from function 'DoCallHercCmdLine' at cmdtab.c(444)
20:04:42.217 0x00002B98 HHC01603I ipl 0123
20:04:42.228 0x00002B98 HHC00811I Processor CP00: architecture mode ESA/390
20:04:42.228 0x00002B98 HHC00811I Processor CP03: architecture mode ESA/390
20:04:42.228 0x00002B98 HHC00811I Processor CP01: architecture mode ESA/390
20:04:42.228 0x00002B98 HHC00811I Processor CP02: architecture mode ESA/390
20:04:42.240 0x00002B98 HHC00814I Processor CP00: SIGP Set architecture mode            (12) CP00, PARM 00000001: CC 0
20:04:42.240 0x00002B98 HHC00811I Processor CP00: architecture mode z/Arch
20:04:49.378 0x00002B98 HHC00107I Starting thread cckd_ra(), active=0, started=0, max=2
20:04:49.378 0x00002B98 HHC00100I Thread id 0000540c, prio 4, name 'cckd_ra thread 1' started
20:04:49.378 0x00002B98 HHC00107I Starting thread cckd_ra() from cckd_ra(), active=1, started=1, max=2
20:04:49.379 0x00002B98 HHC00100I Thread id 00012570, prio 4, name 'cckd_ra thread 2' started
20:04:49.516 0x00002B98 HHC00814I Processor CP00: SIGP Set architecture mode            (12) CP00, PARM 0000000000000000: CC 0
20:04:49.516 0x00002B98 HHC00811I Processor CP00: architecture mode ESA/390
20:04:49.516 0x00002B98 HHC00814I Processor CP00: SIGP Set architecture mode            (12) CP00, PARM 00000001: CC 0
20:04:49.516 0x00002B98 HHC00811I Processor CP00: architecture mode z/Arch
20:04:49.643 0x00002B98 HHC00814I Processor CP00: SIGP Set architecture mode            (12) CP00, PARM 0000000000000000: CC 0
20:04:49.643 0x00002B98 HHC00811I Processor CP00: architecture mode ESA/390
20:04:49.643 0x00002B98 HHC00814I Processor CP00: SIGP Set architecture mode            (12) CP00, PARM 00000001: CC 0
20:04:49.643 0x00002B98 HHC00811I Processor CP00: architecture mode z/Arch
20:04:52.457 0x00002B98 20:04:52 z/VM  V7 R3.0  SERVICE LEVEL 2201 (64-BIT)
20:04:52.457 0x00002B98 20:04:52 SYSTEM NUCLEUS CREATED ON 2024-02-19 AT 13:04:41, LOADED FROM M01RES
20:04:52.458 0x00002B98 20:04:52
20:04:52.458 0x00002B98 20:04:52 ****************************************************************
20:04:52.458 0x00002B98 20:04:52 * LICENSED MATERIALS - PROPERTY OF IBM*                        *
20:04:52.459 0x00002B98 20:04:52 *                                                              *
20:04:52.459 0x00002B98 20:04:52 * 5741-A09 (C) COPYRIGHT IBM CORP. 1983, 2022. ALL RIGHTS      *
20:04:52.459 0x00002B98 20:04:52 * RESERVED. US GOVERNMENT USERS RESTRICTED RIGHTS - USE,       *
20:04:52.460 0x00002B98 20:04:52 * DUPLICATION OR DISCLOSURE RESTRICTED BY GSA ADP SCHEDULE     *
20:04:52.460 0x00002B98 20:04:52 * CONTRACT WITH IBM CORP.                                      *
20:04:52.460 0x00002B98 20:04:52 *                                                              *
20:04:52.461 0x00002B98 20:04:52 * * TRADEMARK OF INTERNATIONAL BUSINESS MACHINES.              *
20:04:52.461 0x00002B98 20:04:52 ****************************************************************
20:04:52.462 0x00002B98 20:04:52
20:04:52.462 0x00002B98 20:04:52 HCPZCO6718I Using parm disk 1 on volume VMCOM1 (device 0124).
20:04:52.462 0x00002B98 20:04:52 HCPZCO6718I Parm disk resides on cylinders 1 through 120.
20:04:52.488 0x00002B98 20:04:52 HCPERP500I  DASD  0123 AN OPERATION WAS TERMINATED BECAUSE A
20:04:52.489 0x00002B98 20:04:52 HCPERP500I  COMMAND REJECT ERROR OCCURRED
20:04:52.489 0x00002B98 20:04:52 HCPERP6300I SENSE DATA FORMAT = 00       MSG CODE = 01
20:04:52.489 0x00002B98 20:04:52 HCPERP6301I CHANNEL COMMAND WORD COMMAND CODE = E7
20:04:52.489 0x00002B98 20:04:52 HCPERP6302I SEEK ADDRESS =   000000000000
20:04:52.490 0x00002B98 20:04:52 HCPERP6303I SENSE = 80000000 00FFFF01 00000000 00000000 00000000
20:04:52.490 0x00002B98 20:04:52 HCPERP6303I 00000000 00000080 00000000
20:04:52.490 0x00002B98 20:04:52 HCPERP6304I IRB = 00C24017 3FD2F008 0E000000 00800000
20:04:52.490 0x00002B98 20:04:52 HCPERP6305I USERID = SYSTEM
20:04:52.491 0x00002B98 20:04:52 HCPERP2216I CHANNEL PATH ID = 01
20:04:52.491 0x00002B98 20:04:52 HCPUDS1777E The directory on volume M01RES could not be initialized.
20:04:52.491 0x00002B98 20:04:52 HCPUDS1752E No directory could be initialized.
20:04:52.491 0x00002B98 20:04:52 HCPERP500I  DASD  0123 AN OPERATION WAS TERMINATED BECAUSE A
20:04:52.492 0x00002B98 20:04:52 HCPERP500I  COMMAND REJECT ERROR OCCURRED
20:04:52.492 0x00002B98 20:04:52 HCPERP6300I SENSE DATA FORMAT = 00       MSG CODE = 01
20:04:52.492 0x00002B98 20:04:52 HCPERP6301I CHANNEL COMMAND WORD COMMAND CODE = E7
20:04:52.492 0x00002B98 20:04:52 HCPERP6302I SEEK ADDRESS =   000000000000
20:04:52.493 0x00002B98 20:04:52 HCPERP6303I SENSE = 80000000 00FFFF01 00000000 00000000 00000000
20:04:52.493 0x00002B98 20:04:52 HCPERP6303I 00000000 00000080 00000000
20:04:52.493 0x00002B98 20:04:52 HCPERP6304I IRB = 00C24017 3FD2C008 0E000000 00800000
20:04:52.493 0x00002B98 20:04:52 HCPERP6305I USERID = SYSTEM
20:04:52.493 0x00002B98 20:04:52 HCPERP2216I CHANNEL PATH ID = 01
20:04:52.494 0x00002B98 20:04:52 HCPWRM902W System recovery failure; fatal I/O error
20:04:57.445 0x00002B98 20:04:57 HCPPCC2582I Storage reconfiguration by SYSTEM is complete. Permanent = 4G Reconfigurable = 0
20:04:57.495 0x00002B98 20:04:57 HCPWRP959I VM4PDT   SYSTEM TERMINATION IN PROGRESS ON 2024-05-19
20:04:57.496 0x00002B98 20:04:57 HCPWRP9025W SYSTEM TERMINATION COMPLETE, ENTERING WAIT STATE 0902
20:05:01.580 0x00002B98 HHC00809I Processor CP00: disabled wait state 0002000000000000 0000000000000902
20:05:01.580 0x00002B98 HHC00826W Processor CP00: processor auto-stopped due to disabled wait
20:05:01.580 0x00002B98 HHC00007I Previous message from function 'z900_process_interrupt' at cpu.c(1876)

Config:

#
# Hercules Emulator Control file...
#
# Description:       z/vm 7.3
# MaxShutdownSecs:   15
# LoadUnit:          0123
#

ARCHLVL              z/Arch
PGMPRDOS             LICENSED

LPARNAME             FLEXES
OSTAILOR             QUIET
LOADPARM             0700
LPARNUM              00
CPUMODEL             1090
CPUSERIAL            01105B
CPUVERID             00

DIAG8CMD        DISABLE
ECPSVM          YES

MAXCPU               4
NUMCPU               4
MAINSIZE             4096

#000C    3505    io/card.txt ascii eof trunc
#000D    3525    io/punch.txt ascii
#000E    1403    io/print1.listing
#000F    1403    io/print2.listing

# You can access the operator's console through the Hercules window, or you
# can launch a 3270 emulator and have the operator use it.  For the former,
# ensure the next line is not commented.
# 0009    3215-C  NOPROMPT
# For the latter, comment the above line and un-comment this line:
# 0010    3270  MOD4

# Display Terminals... these are defined in DMKRIO as 3277s.
0700.8  3270
3270    3270

# Tape Drives
0480    3420    *
0481    3420    *
0580    3420    *
0581    3420    *

# XNET CTCA
0500 CTCE 30882 127.0.0.1 30880


#0123    3390    zvm73/M01RES.bin  
#0124    3390    zvm73/VMCOM1.bin 
#0125    3390    zvm73/730RL1.bin 
#0126    3390    zvm73/M01S01.bin 
#0127    3390    zvm73/M01P01.bin   

0123    3390    F:/Hercules-Volumes/zvm73/M01RES sf=F:/Hercules-Volumes/zvm73/shadows/M01RES_*
0124    3390    F:/Hercules-Volumes/zvm73/VMCOM1 sf=F:/Hercules-Volumes/zvm73/shadows/VMCOM1_*
0125    3390    F:/Hercules-Volumes/zvm73/730RL1 sf=F:/Hercules-Volumes/zvm73/shadows/730RL1_*
0126    3390    F:/Hercules-Volumes/zvm73/M01S01 sf=F:/Hercules-Volumes/zvm73/shadows/M01S01_*
0127    3390    F:/Hercules-Volumes/zvm73/M01P01 sf=F:/Hercules-Volumes/zvm73/shadows/M01P01_*

**Comment by Fish-Git** [comment]
I would rather that you had _attached_ them to your comment instead!

&nbsp;
_**FYI:** &nbsp; See the web page text that appears just below GitHub's "Add a comment" input box? There's a link labeled "Paste, drop or click to add files". Click that, and select the file(s) on your system. That will ATTACH the file to your comment.  You can also use your mouse to just drag and drop the desired files directly from your desktop into the GitHub comment box too._

_Manually copying & pasting large amounts of text into a comment box runs the risk of making an error. Attaching the actual file(s) instead eliminates this risk and makes it easier on yourself and others too._

_Just trying to help!_
