### ISSUE TITLE
Hercules hyperion ($(CUU) is case sensitive

### ISSUE THREAD

**Issue by swhobbit** [SDL-Hercules-390/hyperion#669]
Configration lines like

```
0140	3380	dasd/SYSRES-3380-3	RO sf=shadow/SYSRES_$(cuu)_*.shadow
```
Correctly expanded under ~2022 Spinhawk but are case-sensitive under current Hyperion.

[hercules-lcml4381-2024-06-24_20.35.29.log (last log running under Hercules Version 3.13)](https://github.com/user-attachments/files/16046274/hercules-lcml4381-2024-06-24_20.35.29.log)

[Log under Hercules Version 3.13 (faailing log under Hyperion)](https://github.com/user-attachments/files/16046284/hercules-lcml4381.log)

[lcml4381.conf.txt](https://github.com/user-attachments/files/16046287/lcml4381.conf.txt)
[lcml4381-dasd-io.conf.txt](https://github.com/user-attachments/files/16046289/lcml4381-dasd-io.conf.txt)

**Comment by Fish-Git** [comment]
Your appear to be running on a Linux host. On Windows, enhanced symbols are case insensitive, whereas on Linux they are case sensitive:

  * https://sdl-hercules-390.github.io/html/hercconf.html#subs

Hercules 3.13 Spinhawk is documented as behaving identically, so this is actually a bug in Hercules 3.13 Spinhawk.

You _should_ be using _uppercase_ `${CUU}`.

Closing as User Error.

**Comment by swhobbit** [comment]
At least neither of us demonstrated we're insane because seeing different behavior.  :-)

Thanks
-ahd-
