### ISSUE TITLE
Possible issue with large (4GB) compressed FBA dasd under z/VM

### ISSUE THREAD

**Issue by wpappas** [SDL-Hercules-390/hyperion#676]
Host platform: **Windows 10**
Hercules version: **4.7.0.11119-SDL-gf7d2360a**
Guest OS: **z/VM 6.1 (FBA)**

I am seeing a Hercules issue under z/VM when trying to use large compressed FBA dasd volumes. The specific error being thrown is: `HHC00511E 0:0126 FBA file ./dasd/610W01.cfba: invalid file mask 48` and it is duplicated for every volume being formatted. The volumes in question were all created with the command: `dasdinit64 -bz2 610xxx.cfba 9336 610xx 8389200`.  I've tried this with zlib compression and as legacy non-64 dasdinit volumes and it still happens.

This is in the context of trying to get a FBA install of z/VM 6.1 (found at the usual archive site) up and running to play with. The installation fails when trying to write to one of these newly formatted volumes while the INSTDVD script is running.  Attached are my Hercules config and log files.

* [console.log](https://github.com/user-attachments/files/16365850/console.log)
* [zvm610_config.txt](https://github.com/user-attachments/files/16365874/zvm610_config.txt)

I am more or less following the procedure in the IBM installation guide (attached for reference) and using a CMS formatted minidisk to house the files on the installation DVD (see the section on second level installs from disk), although I am not doing this as a second level install but I doubt that would make a difference given the errors encountered.

* [zvm 6.1 install guide.pdf](https://github.com/user-attachments/files/16365899/zvm.6.1.install.guide.pdf)

This is easily reproducible and I can provide the CMS disk with the install files preloaded if there is a way to transfer a ~2GB file to whoever wants to look into this.

**Comment by Fish-Git** [comment]
Bill,

Your `dasdinit64` does not look right to me. 9336 dasds can have either 920,115 blocks (for a model -10) or 1,672,881 blocks (for a model -10 or -20/25), not  8389,200 blocks as you specified:

* [Dasd Geometry Chart.txt](https://github.com/user-attachments/files/16366497/Dasd.Geometry.Chart.txt)

I would try your `dasdinit64` again, but this time specifying the _exact_ 9336 model you wish to create. This will ensure your dasd is the correct size:

`dasdinit64  -bz2  610xxx.cfba  9336-10  610xx` &nbsp; (or)
`dasdinit64  -bz2  610xxx.cfba  9336-20  610xx`

If that does not resolve your issue, we will have to dig deeper.

**Comment by wpappas** [comment]
> Bill,
> 
> Your `dasdinit64` does not look right to me. 9336 dasds can have either 920,115 blocks (for a model -10) or 1,672,881 blocks (for a model -10 or -20/25), not 8389,200 blocks as you specified:
> 
>     * [Dasd Geometry Chart.txt](https://github.com/user-attachments/files/16366497/Dasd.Geometry.Chart.txt)
> 
> 
> I would try your `dasdinit64` again, but this time specifying the _exact_ 9336 model you wish to create. This will ensure your dasd is the correct size:
> 
> `dasdinit64 -bz2 610xxx.cfba 9336-10 610xx`   (or) `dasdinit64 -bz2 610xxx.cfba 9336-20 610xx`
> 
> If that does not resolve your issue, we will have to dig deeper.

Hi Fish,
Thanks for the quick reply.  The install requires very large FBA disks and was originally meant to be used on a SCSI attached FBA storage solution.  VM defines the disks as generic FBA-512 devices and I was hoping that hercules could emulate these (sans the SCSI piece) by creating a FBA disk with an unusually large number of blocks. It sounds like this might now be more of an enhancement vs. a bug given your comment.

--Bill

**Comment by Fish-Git** [comment]
> I was hoping that Hercules could emulate these (sans the SCSI piece) by creating a FBA disk with an unusually large number of blocks.

It can! Just do your `dasdinit64` just like you did before, but specifying a number of blocks _larger_ than what you originally specified. You originally only specified ... (Oops!) My bad! &nbsp;`:(`

You _did_ specify a large size! My eyes were fooling me. I thought you only specified 838200 (838,200) blocks, but I can see now that you _actually_ specified 8389200 (8,389,200) blocks! Sorry about that.

Hmmmm.... so something else is going on somewhere. Please try your same test again, but this time with CCW tracing enabled on your dasd device ("t+xxx"), and then post the resulting Hercules log file. Thanks.

**Comment by wpappas** [comment]
> > I was hoping that Hercules could emulate these (sans the SCSI piece) by creating a FBA disk with an unusually large number of blocks.
> 
> It can! Just do your `dasdinit64` just like you did before, but specifying a number of blocks _larger_ than what you originally specified. You originally only specified ... (Oops!) My bad!  `:(`
> 
> You _did_ specify a large size! My eyes were fooling me. I thought you only specified 838200 (838,200) blocks, but I can see now that you _actually_ specified 8389200 (8,389,200) blocks! Sorry about that.
> 
> Hmmmm.... so something else is going on somewhere. Please try your same test again, but this time with CCW tracing enabled on your dasd device ("t+xxx"), and then post the resulting Hercules log file. Thanks.

Attached is the console log with tracing enabled for the devices in question. I had to zip it as it was too large as an uncompressed text file. As an FYI, I've tried this under Linux as well (using a current git pull) with the save results so it is not platform specific.  I only reverted to Windows because I am told you are not really a Linux guy :-)

--Bill
[console.zip](https://github.com/user-attachments/files/16367055/console.zip)

**Comment by wpappas** [comment]
> > > I was hoping that Hercules could emulate these (sans the SCSI piece) by creating a FBA disk with an unusually large number of blocks.
> > 
> > 
> > It can! Just do your `dasdinit64` just like you did before, but specifying a number of blocks _larger_ than what you originally specified. You originally only specified ... (Oops!) My bad!  `:(`
> > You _did_ specify a large size! My eyes were fooling me. I thought you only specified 838200 (838,200) blocks, but I can see now that you _actually_ specified 8389200 (8,389,200) blocks! Sorry about that.
> > Hmmmm.... so something else is going on somewhere. Please try your same test again, but this time with CCW tracing enabled on your dasd device ("t+xxx"), and then post the resulting Hercules log file. Thanks.
> 
> Attached is the console log with tracing enabled for the devices in question:
> 
>     * [console.zip](https://github.com/user-attachments/files/16367055/console.zip)
> 
> 
> I had to zip it as it was too large as an uncompressed text file. As an FYI, I've tried this under Linux as well (using a current git pull) with the same results, so it is not platform specific. I only reverted to Windows because I am told you are not really a Linux guy.  `:-)`
> 
> --Bill

New update. Although Hercules is still throwing this error, I was able to get the install completed and IPLed successfully so it may just be cosmetic.  Had to do some install script editing to work around my somewhat unique configuration to be able to get this running under Hercules.  I haven't done a ton of testing yet, but it isn't falling over in any obvious ways.

--Bill

**Comment by Fish-Git** [comment]
### FYI:

I am seeing a possible problem in the code, Am researching and will get back to you.

Is there any chance of you sending me either the INSTDVD you're using or the URL where you downloaded it from? My email address is _fish_ `@` "infidels" organization.

**Comment by Fish-Git** [comment]
> ### New update:
> Although Hercules is still throwing this error, I was able to get the install completed ...

That's good to hear! Nevertheless, I'd still like to try and fix the problem so it doesn't occur in the first place, so I'd still like either the INSTDVD or the URL. Thanks.

**Comment by wpappas** [comment]
> > ### New update:
> > Although Hercules is still throwing this error, I was able to get the install completed ...
> 
> That's good to hear! Nevertheless, I'd still like to try and fix the problem so it doesn't occur in the first place, so I'd still like either the INSTDVD or the URL. Thanks.

Sent you an email as I'd rather keep this part of the discussion offline,

**Comment by Fish-Git** [comment]
### FYI:

Doing a normal install directly from the DVD (i.e. after mounting the DVD .iso image in my host and IPLing from the DVD's .ins file (e.g. `ipl G:\610VM.ins`)) and I did not see any filemask errors at all. Nevertheless, after reviewing Hercule's FBA dasd code (in `fbadasd.c`), I am seeing questionable day-one code that attempts to validate the DX's (Define Extent's) mask byte. Apparently some unknown older Reference Manual was used, because the bits that are being tested do not match the documented mask byte bits in any of the reference manuals that I have.`(*)`

So... I have committed a fix that also contains some _very temporary_ code that should report if/when your reported bug _would have_ (but _will not_) occur. (That is to say, the fix is in place to correct the problem so your problem _WILL NOT_ occur, but it _WILL_ be reported if it _WOULD HAVE_ occurred.)

The commit is 49168e8d8b9f3ae5524be354459b6ddcd3733e55. Please do a rebuild of the current 'develop' branch and give it a try and let me know (please confirm for me) whether or not the problem has now been fixed. Once I'm sure it's been fixed, I will do another commit to remove the small bit of temporary code.

Thanks!

(I'm too lazy to try your method for myself. I feel it would be easier/faster for you to simply try your own method for yourself.)

_____
`(*)` Specifically:

*  _GA32-0274-05 "3990/9390 Storage Control Reference"_ &nbsp; (October 1996)
* _SA22-1025-00 "System/390 Internal Disk Subsystem - Reference Guide (Multiprise 3000 Enterprise Server)"_ &nbsp; (November 1999)
* _SC26-7298-01 "Enterprise Storage Server - System/390 Command Reference - 2105 Models E10, E20, F10, and F20" &nbsp; (June 2000)

**Comment by wpappas** [comment]
> ### FYI:
> 
> Doing a normal install directly from the DVD (i.e. after mounting the DVD .iso image in my host and IPLing from the DVD's .ins file (e.g. `ipl G:\610VM.ins`)) and I did not see any filemask errors at all. Nevertheless, after reviewing Hercule's FBA dasd code (in `fbadasd.c`), I am seeing questionable day-one code that attempts to validate the DX's (Define Extent's) mask byte. Apparently some unknown older Reference Manual was used, because the bits that are being tested do not match the documented mask byte bits in any of the reference manuals that I have.`(*)`
> 
> So... I have committed a fix that also contains some _very temporary_ code that should report if/when your reported bug _would have_ (but _will not_) occur. (That is to say, the fix is in place to correct the problem so your problem _WILL NOT_ occur, but it _WILL_ be reported if it _WOULD HAVE_ occurred.)
> 
> The commit is [49168e8](https://github.com/SDL-Hercules-390/hyperion/commit/49168e8d8b9f3ae5524be354459b6ddcd3733e55). Please do a rebuild of the current 'develop' branch and give it a try and let me know (please confirm for me) whether or not the problem has now been fixed. Once I'm sure it's been fixed, I will do another commit to remove the small bit of temporary code.
> 
> Thanks!
> 
> (I'm too lazy to try your method for myself. I feel it would be easier/faster for you to simply try your own method for yourself.)
> 
> `(*)` Specifically:
> 
>     * _GA32-0274-05 "3990/9390 Storage Control Reference"_   (October 1996)
> 
>     * _SA22-1025-00 "System/390 Internal Disk Subsystem - Reference Guide (Multiprise 3000 Enterprise Server)"_   (November 1999)
> 
>     * _SC26-7298-01 "Enterprise Storage Server - System/390 Command Reference - 2105 Models E10, E20, F10, and F20"_   (June 2000)

Hi Fish,
I will try to test your fix later today and will report back what I find.  Thanks!

**Comment by wpappas** [comment]
Hi Fish -- that seems to have done the trick. Now seeing " +++ OLD WAY: HHC00511E 0:0126 FBA file /home/wapappas/source/hercules/hyperion-develop/hyperion/zz_zvm610/dasd/610W01.cfba: invalid file mask 0x48" in the console log.

--Bill

**Comment by Fish-Git** [comment]
> Hi Fish -- that seems to have done the trick. Now seeing "`+++ OLD WAY: HHC00511E 0:0126 FBA file /home/wapappas/source/hercules/hyperion-develop/hyperion/zz_zvm610/dasd/610W01.cfba: invalid file mask 0x48`" in the console log.

But no I/O error is actually logged by Hercules, and z/VM's formatting proceeds normally and eventually finishes successfully, correct?

I'm going to presume your answer is yes, so I'll go ahead and remove that temporary confirmation test code now, and close this issue as resolved.

Thanks for testing it for me, Bill. Much appreciated.

**Comment by Fish-Git** [comment]
Fixed by commit b328ab73cda6b2f76aa88a7506caaede12412191; closing.

**Comment by wpappas** [comment]
Yes -- no actual I/O error is logged by Hercules and the install completed successfully and seems to be running fine.  Thanks!
