### ISSUE TITLE
PRNO Instruction Issued Without Message Security Assist Extension 5 Being Available

### ISSUE THREAD

**Issue by Juergen-Git** [SDL-Hercules-390/hyperion#684]
Message-Security-Assist Extensions 5 and 7 provide a cryptographically secure deterministic random number generator (DRNG) and a true random number generator (TRNG) through the PRNO instruction. On real hardware, entropy for the TRNG is obtained using sources external to the CP. Data obtained from the TRNG is intended to be used to seed the DRNG. Neither facility is currently provided by Hercules.

There are, however, applications that ignore the facility bit assigned to MSA 5 by using the PRNO instruction even if the facility bit is not set. So far, we've seen that those applications use the PRNO QUERY function only (i.e., they don't actually use either of the DRNG or TRNG functions).

To allow such applications to run nonetheless, a version of the PRNO instruction has been implemented that supports only the QUERY function. Temporarily, this instruction has been added to Message-Security-Assist Extension 4, thus making it available without facility 057_MSA_EXTENSION_5 being enabled. Once a fully functional PRNO instruction has been developed, the dummy instruction will be removed from MSA 4 and the full one will be added to MSA 5 instead.

**Comment by Fish-Git** [comment]
Thank you for this, Jürgen!

**Comment by Juergen-Git** [comment]
Message Security Assists 5 and 7 are now fully available: https://github.com/SDL-Hercules-390/hyperion/commit/c67b47ff6e51cf014c3f974ea32fa0efbc0636aa
