### ISSUE TITLE
EAV Volumes

### ISSUE THREAD

**Issue by zOSdino** [SDL-Hercules-390/hyperion#686]
___
_**Note:** this issue is closely related to issue [\#648: "Enhancement of 3390-108 Support"](https://github.com/SDL-Hercules-390/hyperion/issues/648)._
___
Hello developers,

I am not shure, if this is the correct place for my request, but do you plan to implement use of EAVs with max cylinders above 65520 cyls?

That would be great, because I am supporting some tools/pgms on `cbttape.org` which support EAVs. I don't have access to real IBM z machines and want to test these programs with Hyperion.

Thanks.
Andreas

**Comment by Fish-Git** [comment]
Please see:

* https://github.com/SDL-Hercules-390/hyperion/issues/648#issuecomment-2035119725

Closing as "WON'T FIX".

(Sorry!) &nbsp;`:(`

**Comment by ThomasCothmann** [comment]
It's a shame that hyperion does not support EAV volumes and is not planned. I also like using EAV.

**Comment by Fish-Git** [comment]
_**FYI:** See also the question posed in issue https://github.com/SDL-Hercules-390/hyperion/issues/648#issuecomment-2457329316._

**Comment by Fish-Git** [comment]
> It's a shame that hyperion does not support EAV volumes and is not planned.

I understand completely. Unfortunately however, [providing such support in Hercules is extremely unlikely to ever occur](https://github.com/SDL-Hercules-390/hyperion/issues/648#issuecomment-2035119725) given its current design.

Sorry! &nbsp;`:(`
