### ISSUE TITLE
Hercules 4.8-Dev + z/VM 7.3 & z/OS 3.1 - Wait State 7B / 22 when z/OS is IPLed as a z/VM guest

### ISSUE THREAD

**Issue by prenard** [SDL-Hercules-390/hyperion#694]
Hello.

I use Hercules 4.8-Dev and z/VM 7.3 & z/OS 3.10. 

I have implemented recommended parameters in my conf files (Facility / CPUVERID):

```
FACILITY ENABLE 054                   # entropy-encoding-compression facility
FACILITY ENABLE 080_DFP_PACK_CONV     # decimal-floating-point packed-conversion facility
FACILITY ENABLE 058_MISC_INSTR_EXT_2  # miscellaneous instruction extension 2 facility
FACILITY ENABLE 129                   # vector facility for z/Architecture
FACILITY ENABLE 130                   # instruction execution protection facility
FACILITY ENABLE 134                   # vector Packed Decimal Facility
FACILITY ENABLE 135                   # vector enhancements facility 1
FACILITY ENABLE 148                   # vector enhancements facility 2
FACILITY ENABLE 152                   # vector-packed-Decimal-enhancement facility
FACILITY ENABLE 192                   # vector-packed-Decimal-enhancement facility 2
```
```
CPUMODEL   3931          # 3916 = z16
CPUVERID   00
CPUSERIAL  000611
```

I am able to IPL z/OS 3.1 natively under Hercules with these parameters.

But when I try to IPL z/OS 3.1 as a z/VM guest, I get wait state 7B / 22:

```
z/VM Version 7 Release 3.0, Service Level 2201 (64-bit),                     
built on IBM Virtualization Technology                                       
There is no logmsg data                                                      
FILES:   NO RDR,   NO PRT,   NO PUN                                          
LOGON AT 15:32:49 EST  THURSDAY 11/28/24                                     
term conmode 3270                                                            
ipl 0ab7 loadparm 0ab9ws                                                     
HCPGIR450W CP entered; disabled wait PSW 00020000 80000000 00000000 0022007B 
```

In IBM documentation: Wait State 7B - 22:

> _One or more of the following required functions required by z/OS V2R5 are not available:_
> * _The load/store-on-condition facility 2_
> * _The load-and-zero-rightmost-byte facility_
> * _The decimal-floating-point packed-conversion facility_
> * _The vector facility for z/Architecture®_

Thanks for your help.

**Comment by Fish-Git** [comment]
Please see:

* https://github.com/SDL-Hercules-390/hyperion/issues/93#issuecomment-2515817048

**Comment by Fish-Git** [comment]
@prenard

I apologize for providing incorrect information!

I do _**not**_ keep the three mentioned helper EXECs (cputypes, iplziip and stflefix) on my system's C disk!

_**I keep them on my system's S/Y disk!**_

* https://github.com/SDL-Hercules-390/hyperion/issues/93#issuecomment-2515817048
* https://github.com/SDL-Hercules-390/hyperion/issues/93#issuecomment-2518914213

I sincerely apologize for the confusion. &nbsp; `:(`
